### ISSUE TITLE
Does not add marker to map

### ISSUE THREAD

**Issue by mikekay01** [tombatossals/angular-leaflet-directive#100]
Inside my controller I have a function that grabs data from my factory and calls addMarker.  Here's my problem:

If I call addMarker inside this function the map displays with no marker, and I get this error:
[AngularJS - Leaflet] 'center' is undefined in the current scope, did you forget to initialize it? 

If I call addMarker outside of this I get a null data error because the data has not loaded yet.

myFactory.getDarta().then(function(data) {
       $scope.myData = data;
       $scope.addMarker($scope.myData);
    });

```
$scope.addMarker = function (item) {
    angular.extend($scope, {
        center: {
            lat: item.latitude,
            lng: item.longitude,
            zoom: 13
        },
        markers: {
            store: {
                lat: item.latitude,
                lng: item.longitude,
                message: "Drag me to your position",
                focus: true,
            }
        }
    });

};
```

**Comment by bobur554396** [comment]
a

**Comment by timur-gilauri** [comment]
@mikekay01 , can you please tell me how did you solve that problem. Beacause if i try to add markers in the way you did, not via function but in the beginning, leaflet doesnt add them. they ARE in map, but not displayed
