### ISSUE TITLE
Open Graphic Chart D3.js in Popup Map

### ISSUE THREAD

**Issue by ivanssa** [tombatossals/angular-leaflet-directive#1001]
Hello I am trying to include statistics in a popup a map, I'm using a D3.js approach to angular http://krispo.github.io/angular-nvd3/ to create graphics, drawing svg is activated by calling html <nvd3 options = "options" data = "date"> </ nvd3> however this only works outside the popup when I add the contents of the Leaflet popup it does not compile the graph, so I wonder if anyone can me to help? below is my attempt I commented the code map.js the chart works only when the popup is longer need to open it to activate dynamically only when you open the popup http://plnkr.co/edit/DXvTuieicvmyrlnaSRls?p=preview

**Comment by nmccready** [comment]
Looks like a popup compilation bug .

The code to this is [here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletMarkersHelpers.js#L150-L195) . This is kinda fragile code as it seems every-time someone mods it something else breaks. IE needs more specs.

**Comment by nmccready** [comment]
Possibly related #953 #866

**Comment by ivanssa** [comment]
I want to thank the collaboration, I tried to follow my approach to creating a more objective different way to solve the problem, because it really is not a bug, just the chart at d3 did not generate elements that were not in the Sun so it took envocar the $ compile because only the <d3 in the popup content not envocava the builder Graphical having already shot once, I had tried before with $ compile but had not noticed the [0] end in .setContent ($ compile (template) ($ scope) [0]);, after breaking his head finally managed to make it all work perfectly, follows the final code for those who need it, or check if everything is okay hugs ...

http://plnkr.co/edit/DXvTuieicvmyrlnaSRls?p=preview
