### ISSUE TITLE
Smooth panning map

### ISSUE THREAD

**Issue by that1guy** [tombatossals/angular-leaflet-directive#1002]
As my users click items within my app the leaflet map pans to that item's center point by using: 

````
     //zoom map on corresponding marker
      $scope.map.center = {
                lat: selectedProperty.geo.lat,
                lng: selectedProperty.geo.lon,
                zoom: 16
       };
````

If this re-centering of the map is panning over to a lat/long far enough outside the viewport, the map doesn't smoothly pan.  Instead the map tiles go blank and new tiles are dropped in, which is kinda ugly.

Is there anyway nifty way to smoothly pan from one point to another?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#136

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
