### ISSUE TITLE
Request for custom control: L.HistoryControl

### ISSUE THREAD

**Issue by milovanderlinden** [tombatossals/angular-leaflet-directive#1004]
I would like to have the directive extended to support L.HistoryControl. I will first try to implement this myself and send a pull request when finished.

https://github.com/cscott530/leaflet-history

**Comment by nmccready** [comment]
Sounds good as long as it is pluggable.

**Comment by nmccready** [comment]
Please include specs as well.

**Comment by milovanderlinden** [comment]
I discovered that L.HistoryControl had some dependencies on jQuery, so I rewrote it to fit angular. Pullrequest is pending: https://github.com/cscott530/leaflet-history/pull/5/files

**Comment by nmccready** [comment]
Nice way to use the leaflet utils.

**Comment by milovanderlinden** [comment]
Yes, the less external dependencies, the better.

**Comment by milovanderlinden** [comment]
Step one taken; my issue has been merged!
https://github.com/cscott530/leaflet-history/pull/5#event-448454741

**Comment by nmccready** [comment]
:+1:

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#137

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
