### ISSUE TITLE
[Question] Why leafletData.getMap() doesn't fire

### ISSUE THREAD

**Issue by milovanderlinden** [tombatossals/angular-leaflet-directive#1006]
Hi there,

I am trying to implement a custom control that needs the map to be rendered before it becomes useful. Since I am new to this, I tried to copy from examples. Beware; I am using Leaflet 0.7.7

I hacked together this piece of javascript. It works, but for some odd reason, the console.log statement never fires.

Am I doing something wrong?

```javascript
var myModule = angular.module('myModule', ['leaflet-directive']);
myModule.controller('myFirstController', ['$scope', 'leafletData', 
  function($scope, leafletData) {
    angular.extend($scope, {
      defaults: {
        zoomControl: false
      },
      controls: {},
      center: {
        lat: 43.88,
        lng: 7.57,
        zoom: 4
      }
    }
  );

  // Wait for center to be established
  leafletData.getMap().then(function(map) {
    console.log('Map loaded, getting exitingly extended!');
    angular.extend($scope.controls, {
      myController:{
        type: 'needs-to-be-created'
      }
    });
  });
```

**Comment by nmccready** [comment]
Your missing another dependency angular-simple-logger . It is stated in the Readme. 

>Include angular-simple-logger before Angular-Leaflet js files. Logger gets installed as a requirement >of Angular-Leaflet with bower install or npm install. Note if your using the browser to load it without >CommonJS (browserify, webpack) please use angular-simple-logger.js (not index.js) .

>Include the leaflet-directive dependency on your Angular module:

>var app = angular.module('demoapp', ['nemLogging','leaflet-directive']);

**Comment by nmccready** [comment]
https://github.com/tombatossals/angular-leaflet-directive/blob/master/README.md

**Comment by milovanderlinden** [comment]
Thanks for the responses! It was not in the nemLogging, I have that running, but in passing a DOM element ID to the getMap function.

**Comment by nmccready** [comment]
ahh cool

**Comment by milovanderlinden** [comment]
Final, working version:

```javascript
var myModule = angular.module('myModule', ['leaflet-directive']);
myModule.controller('myFirstController', ['$scope', 'leafletData', 
  function($scope, leafletData) {
    angular.extend($scope, {
      defaults: {
        zoomControl: false
      },
      controls: {},
      center: {
        lat: 43.88,
        lng: 7.57,
        zoom: 4
      }
    }
  );

  // Wait for center to be established
  leafletData.getMap('myMapElementID').then(function(map) {
    console.log('Map loaded, getting exitingly extended!');
    angular.extend($scope.controls, {
      myController:{
        type: 'needs-to-be-created'
      }
    });
  });
```
