### ISSUE TITLE
Marker Events example is out-of-date

### ISSUE THREAD

**Issue by EricWVGG** [tombatossals/angular-leaflet-directive#1009]
http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/events-example

It makes reference to a LeafletEvents module; that module is now called LeafletEventsHelper, and anyway doesn't appear to be necessary to initiate events.

**Comment by nmccready** [comment]
I think the github pages are out of date.  The example in the src examples directory appears correct
.  https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0115-basic-events-example.html

@tombatossals ls am not sure how the whole get pages are being handled. Are then generated from the src/examples here.  Anyway someone needs to PR the work or update the site.

**Comment by thulioph** [comment]
I have the same problem here ;~

![screen shot 2015-10-28 at 4 00 16 pm](https://cloud.githubusercontent.com/assets/2343288/10799726/14509906-7d8d-11e5-99a6-d8aa5ed2329d.png)

**Comment by tombatossals** [comment]
Finally solved! Some of the latest added examples broke the examples generation page, nothing related with the example. The script generator needs that the controller name of each example was different.

Working again. Thanks for reporting guys.
