### ISSUE TITLE
How can I access a control?

### ISSUE THREAD

**Issue by milovanderlinden** [tombatossals/angular-leaflet-directive#1011]
I have a custom button, somewhere in my angular bootstrap-ui page. From this button, I want to show or hide the minimap.

I know that leaflet has no way of telling which controls are loaded in the map, but does your wonderful directive offers this option?

For the history control I ended up declaring it in my controller and then accessing it's functions.

![screenshot from 2015-10-28 20-59-52](https://cloud.githubusercontent.com/assets/106038/10801320/20055abe-7db7-11e5-9892-4adbc770b778.png)

**Comment by nmccready** [comment]
I'd have to dig into this as I actually wanted to do the same thing. However, currently I am hiding it with css.

**Comment by milovanderlinden** [comment]
That is indeed a fine solution for now! I will use that too. Thank you!

2015-10-28 21:19 GMT+01:00 nmccready <notifications@github.com>:

> I'd have to dig into this as I actually wanted to do the same thing.
> However, currently I am hiding it with css.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tombatossals/angular-leaflet-directive/issues/1011#issuecomment-151978098>
> .
>



-- 
[image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#6

**Comment by nmccready** [comment]
Actually besides being migrated this was resolved as well.
