### ISSUE TITLE
gh-pages is broken

### ISSUE THREAD

**Issue by lavahot** [tombatossals/angular-leaflet-directive#1012]
The exact err is: Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=mainPage&p1=Error%3…leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js%3A19%3A463)

The page with start to render at the top, then go to a white page.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#141

**Comment by tombatossals** [comment]
Working again, I had to revert the angular-leaflet-directive version to an old one until I can investigate which is the cause of the conflict.

**Comment by tombatossals** [comment]
Finally solved, we missed the angular-simple-logger dependency of the core directive.

Closing.

**Comment by tombatossals** [comment]
Thanks @lavahot

**Comment by lavahot** [comment]
NP, my pleasure. Thank *you* for fixing it.
