### ISSUE TITLE
leafletdata's geoJson not updated

### ISSUE THREAD

**Issue by c0defre4k** [tombatossals/angular-leaflet-directive#1013]
Hi,

I'm using angular-leaflet-directive with leaflet.draw and I'm trying to add leaflat.snap for editing. For data I use geojson. When I update the geojson source the map is updated correctly, but when trying to update the leaflet.snap guidelayers i found a problem.

I made a plunkr demo showing the problem: http://run.plnkr.co/K19hDDYOuMzckycE/ (open your dev console!). After upating geoJson the layers of the geoJson object should get new ids but it doesn't. 
This seems to be the code which is responsible for this behaviour:
```javascript
if(!_hasSetLeafletData){//only do this once and play with the same ref forever
    _hasSetLeafletData = true;
    leafletData.setGeoJSON(leafletGeoJSON, attrs.id);
}
```

Also the ``attrs.id`` seems to be undefined!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#142

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
