### ISSUE TITLE
error when adding custom controls because of "for in" usage to iterate over array

### ISSUE THREAD

**Issue by uygardonduran** [tombatossals/angular-leaflet-directive#1014]
Hi, 
similar to https://github.com/tombatossals/angular-leaflet-directive/issues/899
and https://github.com/tombatossals/angular-leaflet-directive/pull/884
extending Array.prototype, breaks the code when adding custom controls array.

```javascript
if (isArray(customControlValue)) {
    for (var i in customControlValue) {
```
It's better not to use "for in" to iterate over arrays.
```javascript
for (var i = 0; i < customControlValue.length; i++) {
```

**Comment by uygardonduran** [comment]
Same error also occurs in angular-simple-logger.js

_fns = ['debug', 'info', 'warn', 'error', 'log'];

and iterating over _fns 
for (key in _fns)

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
