### ISSUE TITLE
Examples page broken

### ISSUE THREAD

**Issue by prognose** [tombatossals/angular-leaflet-directive#1015]
Hi

It seems http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html is broken after the latest update.

Unexpected end of line in: http://tombatossals.github.io/angular-leaflet-directive/dist/angular-leaflet-directive.min.js

Thank you for your great directive!

Best regards,

Pål

**Comment by tombatossals** [comment]
Thanks for reporting @prognose, I'm reworking a lot of things and the last compilation broke the directive. Solved now.
