### ISSUE TITLE
How to stop logging on console?

### ISSUE THREAD

**Issue by endigo** [tombatossals/angular-leaflet-directive#1026]
Lots of logs prints on browser console. How to stop them in production?
![capture](https://cloud.githubusercontent.com/assets/1501644/11205267/5473a0a0-8d41-11e5-9996-6c22d1cc5892.JPG)

**Comment by srthurman** [comment]
The logging is due to a angular $log.debug set in leafletMapEvents.js. You can turn it off by using $logProvider.debugEnabled(false);

Example:

``` javascript
var module = angular.module('demoapp', []);

module.config(function($logProvider){
  $logProvider.debugEnabled(false);
});
```

**Comment by marsmith** [comment]
I don't understand this, shouldn't the default be OFF and you can optionally turn on the logging?

I fixed by commenting out some of the debug statement:
ie:

```
//$log.debug('LeafletEventsHelpersFactory: lObjectType: ' + lObjectType + 'rootBroadcastName: ' + rootBroadcastName);
```

**Comment by endigo** [comment]
@srthurman thank you.

**Comment by bjaraujo** [comment]
+1

**Comment by ivanssa** [comment]
to update the angle for new version began this annoying console, which should be off by default, I decided to @srthurman solution by adding the code in config my app.js thank you for the help ...
