### ISSUE TITLE
Overlay layers are checked for url and failing

### ISSUE THREAD

**Issue by lavahot** [tombatossals/angular-leaflet-directive#1030]
Every time I put in an overlay layer I get `[AngularJS - Leaflet] A base layer must have an url`. I am running the latest commit and adding exactly the buildings layer from https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0603-mixed-layers-overlays-geojson-example.html , which has a url. I'm also adding some AJAX geoJSON overlays. I get three of the above message, one for each overlay, which do not have urls.

**Comment by srthurman** [comment]
Look at this example for how to include geoJSON loaded from an AJAX call as an overlay:
http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/overlay-geojson-example
