### ISSUE TITLE
Setting Leaflet errorTileUrl 

### ISSUE THREAD

**Issue by zachatrocity** [tombatossals/angular-leaflet-directive#1036]
```
angular.extend($scope, {
            center: {
                lat: 32.5259,
                lng: -92.1588,
                zoom: 8
            },
            tiles: {
                errorTileUrl: "http://myfallbackserver.com/{z}/{x}/{y}.png",
                url: "http://mymainserver.com/{z}/{x}/{y}.png",
                maxZoom: 18
            }
        });
```

I was wondering if there was easy way to provide a Tile Layer errorTileUrl, perhaps something like in the example above?

**Comment by Tazaf** [comment]
Hi !
If you still need to know how to achieve that, I can provide you with the answer.
Actually, you just have to define an `options` property to your `tiles` object, that will itself have a `errorTileUrl` property containing the url to your image:

``` javascript
angular.extend($scope, {
            center: {
                lat: 32.5259,
                lng: -92.1588,
                zoom: 8
            },
            tiles: {
                url: "http://mymainserver.com/{z}/{x}/{y}.png",
                maxZoom: 18,
                options: {
                    errorTileUrl: "http://myfallbackserver.com/{z}/{x}/{y}.png",
                }
            }
        });
```

**Comment by zachatrocity** [comment]
Awesome! Thanks for the tip. I've moved on to other things and for this I ended up using my own REST API middleware so that I could use locally cached tiles. This it great to know though thank you.
