### ISSUE TITLE
How to create a simple button that changes the layer between map and satellite?

### ISSUE THREAD

**Issue by ivanssa** [tombatossals/angular-leaflet-directive#1058]
Hello the days I'm looking for a solution to create a button to toggle between map and satellite layers all I want is a style toggle button that switches between the map layers and satelite I found an example as http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/dynamic-addition-example but it deletes the layer map and all I want is just to change as it is made by the leaflet-control-layer selector someone could help create that switch style?

![map_change](https://cloud.githubusercontent.com/assets/3166174/12810490/50c3c8fc-cb05-11e5-8601-20c5e6ce4465.jpg)

**Comment by IvanSanchez** [comment]
Duplicate of Leaflet/Leaflet#4195

**Comment by ivanssa** [comment]
I could settle with the function found here https://github.com/angular-ui/ui-leaflet/issues/22 was all he needed to create my custom layer switch following code

Function 

```
// Toggle Layer
$ Scope.layer = true;
$ Scope.change baselayer = function (key) {$ scope.layer = $ scope.layer!; leafletData.getMap () then (function (map) {leafletData.getLayers () then (function (layers) {_.each (layers.baselayers, function (layer) {map.removeLayer (layer);..}); map .addLayer (layers.baselayers [key]);});});
};

```

Html

```
<a ng-if="layer" ng-click="change BaseLayer('google Hybrid')" class="leaflet-control-layers-toggle radar" href="#" title="Layers"> </a>
<a ng-if="!layer" ng-click="changeBaseLayer('googleRoadmap')" class="leaflet-control-layers-toggle mapa" href="#" title="Layers"> </a>
```

Result: :-)

![result](https://cloud.githubusercontent.com/assets/3166174/12998515/411c9770-d123-11e5-80c5-416c59369615.jpg)

**Comment by hpandelo** [comment]
has possibility to do it without andgular?

**Comment by ivanssa** [comment]
hello @neomacedo yes you can do with simple javascript, creates a variable to control the corresponding button action display state through jquery style and use the onclick to define the action to change the google map layer.
