### ISSUE TITLE
Several console messages.

### ISSUE THREAD

**Issue by bjaraujo** [tombatossals/angular-leaflet-directive#1065]
I had this issue before but I don't recall how it was fixed. 
I have several  leafletDirectiveMap.mousemove messages in console. How can this be turned off?

**Comment by beccannlittle** [comment]
Looks like its enabled by default, see fix [here](https://github.com/tombatossals/angular-leaflet-directive/issues/1026).

**Comment by bjaraujo** [comment]
@beccannlittle 
Thanks. +1
