### ISSUE TITLE
FloorPlan is showing multiple

### ISSUE THREAD

**Issue by mudin3i** [tombatossals/angular-leaflet-directive#1086]
Hello!
Thanks for the great work!
I am trying to upload floor plan as baselayer.
Now it is showing multiple:
![screen shot 2016-04-04 at 12 00 27 pm](https://cloud.githubusercontent.com/assets/15241252/14237347/62eb9e74-fa5d-11e5-8aed-fd5bf5ec8b7d.png)

My code:
**app.js**
`$scope.layers = {
         baselayers: {
             myMap:{
               name: "Floor Plan",
               url:'images/0-0-0.png',
                 type: 'xyz'
             },
}`

**index.html**
`<leaflet id="myMap" layout="column" center="center" layers="layers" markers="markers"></leaflet>`

I cannot find any solution because I am beginner.
That would be great if I get any help.
Thank you very much.

Mudin

**Comment by lungare** [comment]
I think your type is incorrect. Try using   **type: 'imageOverlay'** since you want to your a floorplan as baselayer and not a tile layer.
Hope that helps.

**Comment by mudin3i** [comment]
Thanks, it works with this:

$scope.layers ={ baselayers: { myMap:{name: "myMap", type: "imageOverlay", url:"floor.jpg",
bounds:[[-1024, -180], [1024, 180]]}}}
