### ISSUE TITLE
Remove Marker by Name or Group

### ISSUE THREAD

**Issue by ivanssa** [tombatossals/angular-leaflet-directive#1093]
Hello there is a simpler way to remove a specific Marker of a map through its name, or remove all of which are part of a group marker? I am currently using this code but it only works for the first marker with name = point.

```
leafletData.getMarkers().then(function (markers) {
     for (var k in markers) {
          console.log(markers[k].options.name);
          if(markers[k].options.name=='point'){           
              leafletData.getMap().then(function (map) {
                map.removeLayer(markers[k]);
              });             
          }
     }  
});
```

**Comment by Vallenain** [comment]
I'm not working with markers but something looks strange to me.
What's the type of `k` ? Cause you're using it as an index but, from your `for` loop, I'd say it's not an integer = it's the marker itself.

**Comment by ivanssa** [comment]
Hi @Vallenain the function returns an Markers vector where k is the vector position to be traveled and moved through is I check the name you want to remove and then if you find the item I remove the item in position by leafletData.getMap () .then (function (map) {and map.removeLayer (markers [k]);

what I want is if it is possible to remove a marker by name or group without having to scan all the marker ..

RemoveMarker [ 'name'];
or RemoveAllMarkerGroup [ 'group'];

**Comment by ivanssa** [comment]
Hello after so long I managed to find a solution below the code that removes all markers with a specific name eg "special"

$scope.removep = function(){	
	leafletData.getMarkers().then(function (markers) {		
	var markerem = new Array();	
	leafletData.getMap().then(function (map) {		
	for(var k in markers) {
	if(markers[k].options.name=='especial'){
    map.removeLayer(markers[k]);
	}
    }  
});
});
