### ISSUE TITLE
The Promise leafletData.getLayers is never resolved or rejected

### ISSUE THREAD

**Issue by RaederDev** [tombatossals/angular-leaflet-directive#1108]
Hi!

I'm running Angular 1.4.3 with the angular-leaflet directive and I'm trying to get all available Layers
for my map. I'm calling it like this:

`leafletData.getLayers().then(() => console.log('success')).catch(() => console.log('error'));`

Neither "success" nor "error" is being printed.
I also tried passing the scope ID:

`leafletData.getLayers($scope.$id).then(() => console.log('success')).catch(() => console.log('error'));`

Am I doing something wrong here?
Thanks for your help!

**Comment by wangsha** [comment]
@N0ps32 try delaying this call or invoking it after layer initialization.

``` javascript
$timeout(function() {
  leafletData.getLayers().then(function(layers) {
     console.log(layers);
  });
}, 100);
```

**Comment by RaederDev** [comment]
The call is issued on user interaction, about 30 seconds after the layers are initialized.

**Comment by RaederDev** [comment]
Okay I solved the problem.
If you have the same problem make sure to give your map an ID in the DOM.
The problem is that if you have an ajax site, even if old map instances are already removed from the DOM, the service doesn't recognize that and doesn't reinitialize all map data when loading a different map.
