### ISSUE TITLE
How to make full size

### ISSUE THREAD

**Issue by insonifi** [tombatossals/angular-leaflet-directive#113]
Hello,
  how can I make map appear at 100% width/height. I need make it full window size (like Google Maps).
  At the moment, I define arbitrary name to the directive and then use a script that modifies style width/height in window.onresize event. The bad thing about that seems like part of map is not loading properly. Also I have to use non-angular JS to achieve that.

**Comment by rhalf** [comment]
Hi everyone, I have problem on setting height to 100% inside the tab (angular ui bootstrap).

```
<uib-tabset active="active">
    <uib-tab index="0" heading="Map">
        <div panel-map></div>
    </uib-tab>
    <uib-tab index="1" heading="Sample">
        Sample
    </uib-tab>
</uib-tabset>
```

and this is my template

```
<div ng-controller="panelMapController">
    <leaflet width="100%" height="100%"></leaflet>
</div>
```

**Comment by rhalf** [comment]
Luckily, i was able to make it, here's my fixed.

```
<div ng-controller="panelMapController">
    <div class="mapContainer">
        <leaflet width="100%" height="100%" lf-center="qatar" defaults="defaults"></leaflet>
    </div>
</div>
<style>
    .mapContainer {
        position: fixed;
        height: 100%;
        width: 100%;
    }
</style>
```

**Comment by pleasezoomout** [comment]
Thanks @rhalf your solution works like a charm. !

**Comment by bugdanov** [comment]
Thanks @rhalf. 

I use something like:

```
<div style="postiion: absolute;">
  <div style="position: relative;">
     <div class="mapContainer">
        <leaflet width="100%" height="100%"></leaflet>
```

**Comment by chander** [comment]
So my solution is a bit different - but I stick content above the map - so I really want my map to be "the rest of the page".  If there's no content above it, then it's 100% of the page size.  Though it's more complicated than the 100% all the time solution, it works pretty well. In this case I assume that the ID of the leaflet tag is "gismap".

/**
         \* We want the leaflet map to be 100% of the page size, so we
         \* have this nifty function to resize it.  However, in some cases
         \* the user might resize the window - and we want the map to resize as
         \* well.  This handles that by auto-updating the style.
         _/
        var updateWindowHeight=function () {
            // Get the top of the GISmap div - we'll make that where the map
            // starts, since that'll ensure that it uses the entire div.  
            var el=angular.element(document.querySelector('#gismap'));
            // Get the absolute position of the top of the element.
            var top_padding=el[0].getBoundingClientRect().top;
            // Get the height of the window.
            ctrl.doc_height=$window.innerHeight ;
            // Subtract that top padding - since other content is there.
            ctrl.map_height=ctrl.doc_height-top_padding;
            // Set the height of the map to be the remainder of the page. 
            // we need to have a height, otherwise it'll assume 0 height, 
            // which means no map.
            ctrl.mapStyle={'height': ctrl.map_height + 'px'};
            // Tell leaflet that it needs to reset the mapsize since
            // a window resize event or something similar happened.
            leafletData.getMap('gismap').then(function(map) {
                $timeout(function() {
                  map.invalidateSize();
                }, 300);
            });
        }
        /_*
         \* Window resize event handling - this ensures we properly adjust the 
         \* leaflet map size whenever someone resizes the window.  Essentially
         \* making it always take up 100% of the map.
         */
        angular.element($window).bind('resize', function () {
            updateWindowHeight();
        });
