### ISSUE TITLE
maxNativeZoom

### ISSUE THREAD

**Issue by lurkas34** [tombatossals/angular-leaflet-directive#1150]
Hi,

I need an offline map with tiles up to zoom level 10. Usually you can just add maxNativeZoom to prevent loading tiles in a higher zoom level. Apparently his is beeing ignored: 

 $scope.map = {
          bounds: bounds,
          defaults: {
            tileLayer: layer,
            maxZoom: 17,
            maxNativeZoom: 10,
            minZoom: 6,
            zoomControlPosition: 'bottomleft',

This does not work, leaflet allows zooming over 10. Is there a solution for that issue?

**Comment by mairsbw** [comment]
I'm also looking for this feature. Is this an easy change to enable it? I might be able to put together a patch if someone can point me in the right direction.

**Comment by lurkas34** [comment]
This is the way to do it: (couldn't find it in the docs)
        defaults: {
          tileLayer: layer,
          dragging: false,
          zoomControlPosition: 'bottomleft',
          tap: false,
          detectRetina: true,
          scrollWheelZoom: false,
          tileLayerOptions: {
            maxZoom: 18,
            maxNativeZoom: 10,
            minZoom: 2,
          },
...
maxNativeZoom has to be an item of tileLayerOptions in the defaults object.

**Comment by mairsbw** [comment]
Thanks, @lurkas34! I'll give that a go.

**Comment by webdeveloperneeraj** [comment]
> I am using this directive
> https://github.com/tombatossals/angular-leaflet-directive


```
> 
> var app = angular.module('demoapp', ['leaflet-directive']);
> 
> app.controller('DemoController', ['$scope', '$timeout', 'leafletData', function($scope, $timeout, leafletData) {
>   angular.extend($scope, {
>     center: {
>       lat: 51.505,
>       lng: -0.09,
>       zoom: 15
>     },
>    
>     defaults: {
>       dragging: false,
>       scrollWheelZoom: false,
>         minZoom : 14,
>         maxZoom :16
>     }
>   });
> }]);

```
in html file use this directive 
<body ng-controller="DemoController">
  <leaflet  lf-center="center" markers="markers" defaults="defaults"></leaflet>
</body>
Add minZoom and maxZoom param in below added  fiddle.

http://jsfiddle.net/adrd80vb/
