### ISSUE TITLE
Tiles error on load in Electron

### ISSUE THREAD

**Issue by jlanio** [tombatossals/angular-leaflet-directive#1175]
Something strange is happening when using the electron directive.
For some reason the electron tries to load the tiles in local file.

![as](https://cloud.githubusercontent.com/assets/10765588/25498223/c6cc2f96-2b4c-11e7-9fcc-1e5ac9f3143d.png)
`c.tile.openstreetmap.org/1/1/1.png:1 GET file://c.tile.openstreetmap.org/1/1/1.png net::ERR_FILE_NOT_FOUND`

HTML
>     <leaflet style="height: 200px;"></leaflet>
Controller

> angular.extend($scope, {
    center: {
        lat: 51.505,
        lng: -0.09,
        zoom: 8
    }
});

**Comment by sofivsofi** [comment]
Did you manage to find a solution about this ?
