### ISSUE TITLE
Hide Layer Control Element

### ISSUE THREAD

**Issue by ghost** [tombatossals/angular-leaflet-directive#130]
I played a bit with the development branch, especially with the baselayer/overlay feature. Is it possible to hide the layers control? I want to hide it and use my own controls.

Greetings

**Comment by gianvi** [comment]
Hi Guys, I was looking for a solution to hide the layer control.
Thanks to your solution @skalb I can hidden it from the css....
I just want to know if there is some improvements to disable it from the defaults properties: 
I mean something like 
defaults{
...
zoomControl: false,
layerControl: false
}

Thanks in advance

**Comment by jimmygeorgethomas** [comment]
Any updates on disabling layerControl?

**Comment by nmccready** [comment]
@gianvi @jimmygeorgethomas can you make a new issue since this is closed. Also an example via plnkr or jsfiddle would help showing your problem.
