### ISSUE TITLE
Update path while marker is being dragged

### ISSUE THREAD

**Issue by vincentdyleung** [tombatossals/angular-leaflet-directive#134]
In the path-example I can drag the markers to update the path, but paths are only updated when drag is finished. Is there a way to update the path when drag is still going on, i.e., sticking the path to the marker at all times? Thank you!

**Comment by patricknazar** [comment]
I've been trying to get this to work myself and the path won't update until I'm finished dragging. Can anyone provide a code example of this? Would be super appreciated.
