### ISSUE TITLE
Event management attribute in the directive

### ISSUE THREAD

**Issue by JaumeFigueras** [tombatossals/angular-leaflet-directive#137]
## Proposal

Add a events attribute in the directive to manage which Leaflet events are exposed to Angular

## Concern

I'm trying to perform move animation to markers when their position is updated and when they are clustered. This leads Leaflet to fire, at least, one event per marker. The directive 'send' the events to Angular consuming some CPU time (profiling in my computer tells me about 100ms). When dealing with thousands of markers the map update makes the application unusable.

## Usage example

Add an event attribute to select which events are forwarded to Angular. Something like:
```html
<leaflet events="none">
<leaflet events="all">
<leaflet events="map.click;map.popupopen;map.popupclose;marker.mouseover">
```
or possibly a model binding
```javascript
events = {
  map: {},
  markers: {}
}

events = {
  map: {
    click: true,
    popupopen: true,
    popupclose: true
  },
  markers: {
    mouseover: true
  }
}
```
```html
<leaflet events="events">
```
What do you think?

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
