### ISSUE TITLE
German election map using angular-leaflet-directive and twitter live data

### ISSUE THREAD

**Issue by datalyze-solutions** [tombatossals/angular-leaflet-directive#141]
Today the german twitter election map www.wahlodata.org started. It combines the angular-leaflet-directive with live data broadcasting from twitter. It's still in Beta mode but seams to work very good.

Thanks for this project!!!

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
