### ISSUE TITLE
BUG - Object icons (DivIcon, AwesomeIcon, LeafletIcon) are always different although they don't change

### ISSUE THREAD

**Issue by JaumeFigueras** [tombatossals/angular-leaflet-directive#148]
Hi,

for some reason I don't understand, the old value in the marker watch function looses the type of the icon, so to test if the old and new icon type can't be compared with instanceof in the helper functions.

Again, will try to solve it during the weekend.

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
