### ISSUE TITLE
A way to set map.attributionControl.setPrefix()

### ISSUE THREAD

**Issue by elmarburke** [tombatossals/angular-leaflet-directive#152]
I haven't found a way to add a prefex in the buttom right control bar.
It would be great to add a way in the directive like
```html
<leaflet controls="controls"></leaflet>
```
and
```javascript
$scope.controls = {
  attribution: {
    prefix: 'Leaflet and Me'
  }
}

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
