### ISSUE TITLE
Add custom Control

### ISSUE THREAD

**Issue by Diolor** [tombatossals/angular-leaflet-directive#160]
If I see correctly the .js main file I declare custom controls like that:

    ...,
    customControls : [
                    L.mapbox.geocoderControl('foursquare.map-ikj05elx'),
                    L.control.locate({
                                        setView: true, 
                                        locateOptions: {maxZoom: 10}
                    })
    ],...

Which I would traditionally declare like:

     map.addControl( L.mapbox.geocoderControl('foursquare.map-ikj05elx') )
           .addControl( L.control.locate({
                                        setView: true, 
                                        locateOptions: {maxZoom: 10} })
            )

However it doesn't work. Do I do something wrong?

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.

**Comment by vko-online** [comment]
This should be reopened
https://github.com/tombatossals/angular-leaflet-directive/issues/929

**Comment by itskashi** [comment]
I worked this out by commenting the following lines. 
if (!isValidControlType(controlType)) {
                            $log.error(errorHeader + ' Invalid control type: ' + controlType + '.');
                            return;
                        }

OR may be just add "custom" in controlTypes array around line 284.
