### ISSUE TITLE
Pushing markers do not update unless a hover event happens.

### ISSUE THREAD

**Issue by Diolor** [tombatossals/angular-leaflet-directive#164]
I have a strange glitch caused by a lot of asynchronous code.
Let's say we add a $watch event or a $scope.events. The code:

    $scope.$watch( "bounds" , function(n,o){
        // makes are call to server and the returned data are manipulated in populate()
        Dajaxice.async.hello(populate, {
                            'west' : $scope.bounds.southWest.lng,
                            'east': $scope.bounds.northEast.lng,
                            'north' : $scope.bounds.northEast.lat,
                            'south': $scope.bounds.southWest.lat,
        });
        //adds a dummy marker
        $scope.markers['test'] ={
            lat : 52.3,
            lng : 4.8
        }
    }

    function populate(data) {
        //dummy marker no2
        $scope.markers['test2'] ={
              lat : 53.3,
              lng : 5
        }

        //manipulates the returned data
        markers_length = data.markers.length;
        for (var i = 0; i < markers_length; i++) {
            temp_marker = data.markers[i]
            $scope.markers[temp_marker.foursquare_id] = {
                lat: temp_marker.latitude,
                lng: temp_marker.longitude
            }
        }

        alert('alert !' );

    };

Pretty simply, when the bounds change, it calls the function `populate` based on the bounds and also adds a marker called `test`.

Now, the `test` marker appears first since the `Dajaxice.async.hello` is async and takes some moments for the server to reply. That's fine. However the markers of the the `populate` will never appear on the map unless the map "senses" a user event. In my occasion just move the mouse over the map.

The alert executes well but none of the markers are displayed on the map unless I move a bit my mouse over the map. Marker 'test' is fine.

I thought that `Dajaxice` was the problem but why is the "hover" thing fixes the markers?

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
