### ISSUE TITLE
Projection support for map and geojson

### ISSUE THREAD

**Issue by wouterst** [tombatossals/angular-leaflet-directive#166]
I did some tests working with Angular Leaflet and it works good. However I am someone that has to work with a different projection (EPSG:28992) then Leaflet supports out of the box.

I have to use the EPSG:28992 projection because my datasets are in that projection. I have found a way to support this projection for WMS sources but when I plot a marker it is off by a hundred miles. For instance, if I want the marker to show at [53.22, 6.55] in latitude/longitude coordinates it shows them at the equivalent [53.53, 5.64] coordinates. If I modify the Angular Leaflet directive to use the EPSG:28992 projection for the map then it shows the marker at the right position on the map.

This should be relatively easy to fix by allowing the map projection to be set through the defaults attribute. Using the Proj4leaflet plugin for Leaflet would make this a whole lot easier to support in Angular Leaflet.

The second problem I ran into was that the GeoJSON class in Leaflet does not support the EPSG:28992 projection. Using the Proj4leaflet plugin also makes it possible for GeoJSON to use the EPSG:28992 projection. But that would also mean that the code in Angular Leaflet would have to use the L.Proj.GeoJSON class (class made available through the Proj4leaflet plugin).

This will hopefully add support for more projections.

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
