### ISSUE TITLE
Tiles not loading correct

### ISSUE THREAD

**Issue by sebastianzillessen** [tombatossals/angular-leaflet-directive#168]
I use your directive with angularJS 1.2.

If I include it with the defaults I just get one single tile loaded...

My Controller just includes:
`
$scope.center = {
      lat: 52,
      lng: 12,
      zoom: 14
    };
`
In my view I have

`<leaflet defaults="defaults" center="center" height="480px" width="640px"></leaflet>`

But I only get this view:
![screenshot 2013-11-05 12 53 51](https://f.cloud.github.com/assets/300879/1473061/fa7c4468-4610-11e3-81e9-b881fa0166ce.png)

I see that only one single tile is loaded from the web:
![screenshot 2013-11-05 12 54 52](https://f.cloud.github.com/assets/300879/1473066/2135eae6-4611-11e3-9f51-fdf43c907d19.png)

If I resize the window, all tiles come up and are displayed correct!

I use the following additional requirements:

`
'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngRoute',
    'ajoslin.mobile-navigate',
    'ngTouch',
    'leaflet-directive'
`

Can anyone reproduce this issue?

Thanks!

**Comment by bruha** [comment]
I have the same problem. Even [your example](http://tombatossals.github.io/angular-leaflet-directive/examples/hide-show-map.html) doesn't work properly, see [screencast](https://youtu.be/vNzA4gfHDac).

**Comment by chk1** [comment]
I upgraded one of my websites from AngularJS 1.2 to 1.3 today and found that `map.invalidateSize()` actually causes this behaviour in some cases, I removed it and use `map.setView();` by itself now which works fine.

**Comment by chromeo** [comment]
Same problem - I have a map in the 2nd tab with an id of "location", not the active one, that only shows one tile. I fixed it with the following:
```javascript
		jQuery('.nav-tabs a, #my-links a').click(function (e) {
			e.preventDefault();
			jQuery(this).tab('show');

			// a bug in Leaflet causes map tiles to stop loading in tabs that are initially hidden
			jQuery("a[href='#location']").on("shown.bs.tab", function() {
			    L.Util.requestAnimFrame(map.invalidateSize,map,!1,map._container);
			});
		});
```

**Comment by sebastialonso** [comment]
@tombatossals your example did not help me at all, I continue to have the same issue when showing the map after being hidden. @chromeo yours didn't help either.

what @bruha is showing in his video is exactly the issue I'm experiencing

**Comment by chromeo** [comment]
I recently had to switch my map codebase to Google Maps, but had the same issue. I fixed it by moving the map init into a custom initialize function, then calling that function after the bootstrap tab is clicked. Replace the Google Maps init stuff with Leaflet init:

		var map;
		var building = new google.maps.LatLng(<?php echo $latlng; ?>);
		var marker = new google.maps.Marker({
		    position:building
		});
		function initialize() {

		  	var mapOptions = {
			    zoom: 14,
			    center: building
			};
			map = new google.maps.Map(document.getElementById('loc-map'), mapOptions);
			marker.setMap(map);
			google.maps.event.addListener(marker, 'click', function() {

				infowindow.setContent(contentString);
				infowindow.open(map, marker);

			});
		}

		jQuery('.nav-tabs a, #useful-links a').click(function (e) {
			e.preventDefault();
			jQuery(this).tab('show');

			jQuery("a[href='#location']").on("shown.bs.tab", function() {
            // this was the magic - initialize when the tab is clicked
			    initialize();
			});
		});

**Comment by prasht63** [comment]
![image](https://cloud.githubusercontent.com/assets/2105062/8023078/0ab5f8d6-0d18-11e5-9f42-7f3bafd471ad.png)
In my case the map is loading like this.I dont kow why the tiles are haphazrdly placed and why one quarter of area is left blank.

**Comment by nmccready** [comment]
Any time this happens you need to tell the base map instance to resize. It happens with google maps easily if you use ng-show. ng-if will completley destroy and rebuild the element. However when you hide something it mucks up the map instance and it no longer knows its size. So you must tell it to resize on reshowing.

**Comment by sebastialonso** [comment]
This is disappointing, being such an awesome library. None of the above hacks works for every case, it's a process of trial and error, which is extremely costly in time.

**Comment by nmccready** [comment]
Well this library has possibly saved you time already. Digging down and providing people a better solution will possibly be a better long term fix. It is impossible to know every use case and issue which causes the problem. If you can't figure it out; providing a plunkr or jsfiddle is a starting point.
