### ISSUE TITLE
Map events not broadcasting by default since project overhaul

### ISSUE THREAD

**Issue by grantlucas** [tombatossals/angular-leaflet-directive#174]
So I've had time to get back into my Leaflet/Angular project and pretty much have everything working with the latest version of this directive. The one issue though is that map events aren't broadcasting by default like before. I've messed with it a bit but haven't been able to get it working. I tried adding `event-broadcast="events"` to my `<leaflet>` tag but it didn't make a difference.

When the map event limiting was added originally, all map events were being broadcast by default. Can someone with better knowledge of how this was refactored let me know if there's something I'm doing wrong?

If I just had `<leaflet center="center" width="640px" height="400px"></leaflet>` with the current code, would all the map events fire by default?

Marker events are still behaving properly.

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
