### ISSUE TITLE
Postpone actual map creation until the parent div is visible

### ISSUE THREAD

**Issue by rejoc** [tombatossals/angular-leaflet-directive#191]
When a leaflet tag is included in a div that is not visible when the page is loaded, the map is not initialized correctly and sometime, even a map.invalidateSize() is not enough to redraw the map correctly.

So isn't a way to postpone the actuel map creation (new L.map... ) until a specific signal or the changed value of an attribute ?

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
