### ISSUE TITLE
multiple geojson layer..

### ISSUE THREAD

**Issue by goldalworming** [tombatossals/angular-leaflet-directive#193]
how should I handle multiple geojson layer..

Should I group all data to one geojson layer or I can make multiple geojson layer??

**Comment by stev-0** [comment]
Has anyone done this for normal GeoJSON layers - not vector tiles?

**Comment by nmccready** [comment]
I'm having a hard time at figuring out the context of who has what issues. As far as the original concern of handling multiple geojson that are not vector tiles; use geojson nested

https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0125-basic-geojson-nested-example.html

Running here:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/geojson-nested-example

As far as other issues please start a new ticket.
