### ISSUE TITLE
Angular Error

### ISSUE THREAD

**Issue by bzmwillemsen** [tombatossals/angular-leaflet-directive#200]
I'm getting the following error with the current master build:

http://docs.angularjs.org/error/$compile:multidir?p0=leaflet&p1=leaflet&p2=new%2Fisolated%20scope&p3=%3Cdiv%20class%3D%22angular-leaflet-map%22%20ng-transclude%3D%22%22%20id%3D%22leaflet-map%22%20defaults%3D%22defaults%22%20center%3D%22center%22%20geojson%3D%22geojson%22%20event-broadcast%3D%22events%22%20bounds%3D%22bounds%22%20leaflet%3D%22leaflet%22%3E

I've tracked it down to this commit:
https://github.com/tombatossals/angular-leaflet-directive/commit/080fa82b7fc339b18fd9ec6f70eaa0cc22f02960

If I change
restrict from "EA" to "E" the error disappears.

I'm not sure what the reason is for this change, so I didn't make a change and pull request.

**Comment by tombatossals** [comment]
Old issue, code has changed a lot since this, closing. Please reply if you think this should be reopened. Thanks.
