### ISSUE TITLE
Map is divided in parts all over the page

### ISSUE THREAD

**Issue by figalex** [tombatossals/angular-leaflet-directive#204]
Any one know why is this happening? I just followed the "get started" guide and this is the result
![screen shot 2013-11-24 at 7 18 55 pm](https://f.cloud.github.com/assets/2828718/1610484/a1b68bde-5580-11e3-9778-20415c8009de.png)

**Comment by nmccready** [comment]
This is a css issue, and or ng-hide/ng-show. The show/hide usually requires resizing the map element.
