### ISSUE TITLE
Center is undefined but still working but markers won't show at all

### ISSUE THREAD

**Issue by kschio** [tombatossals/angular-leaflet-directive#208]
Hi there,

currently I set the center position without extending the scope and it actual works since the map is centered correctly and the zoom is also working but I still get the following warning:

[AngularJS - Leaflet] 'center' is undefined in the current scope, did you forget to initialize it? 

Next strange thing is that I can't get the markers to show, there is no other warning/error but they still won't show.

If I use the exact source from one of the examples with extend, nothing happens at all.

I can't post a demo of it at this time since there are many things going on in the controller and around it.

Maybe someone has an idea? If there is really no chance for help without an example I try to provide one.

Thanks

**Comment by nmccready** [comment]
No reply and this is dated; closing.
