### ISSUE TITLE
featureGroups or some other way to fit groups of markers on the map

### ISSUE THREAD

**Issue by ranmacar** [tombatossals/angular-leaflet-directive#215]
Hello!

I am trying to get started with the directive. One of the features I need is fitting groups of markers. This can be accomplished by adding relevant markers to a featureGroup and getting the bounds in Leaflet, and it is rather hard to work with markers as they are created by the directive.
This interface seems to be missing from the directive. Is there another way to achieve this kind of functionality?

What would be awesome, is a optional parameter on the Marker object, groups (string or array of strings), which when entered adds the marker to relevant featureGroups (and creates new ones when needed).

Anyone else thinks this is needed/useful?
Thanks,
Ranmacar

**Comment by nmccready** [comment]
Closing since this is dated. Please comment to re-open.
