### ISSUE TITLE
custom options ignored

### ISSUE THREAD

**Issue by jerroydmoore** [tombatossals/angular-leaflet-directive#221]
Hi tombatossal,

Great stuff. Working on switching my existing app to use the angular leaflet-directive.

I believe the correct way to add plugins to maps and have them be on by default, is the following code:
```
L.Map.mergeOptions({
    positionControl: true
});

L.Map.addInitHook(function () {
    if (this.options.positionControl) {
        this.positionControl = new L.Control.MousePosition();
        this.addControl(this.positionControl);
    }
});
```

However, the angular-leaflet-directive doesn't copy over custom options, when I examine `leafletMapDefault.setDefaults`. Is there another recommended way to install leaflet plugins when using angular-leaflet-directive?

**Comment by nmccready** [comment]
controls directive exists now so this seems to be closable.

**Comment by tvincent86** [comment]
Hello,

Excuse me for my English.

I added the plugin on the page HTML.
`<link rel="stylesheet" href="../Leaflet.MousePosition/L.Control.MousePosition.css" />`
`<script src="../Leaflet.MousePosition/L.Control.MousePosition.js"></script>`

Then, i added this code in the file angular-leaflet-directive.js (ligne 314), under ligne **var controlTypes = {**
`mousePosition: {
isPluginLoaded: function() {
        if (!angular.isDefined(L.Control.MousePosition)) {
          $log.error(errorHeader + ' MousePosition plugin is not loaded.');
          return false;
        }
        return true;
      },
      checkValidParams: function(/* params */) {
        return true;
      },
      createControl: function(params) {
        return new L.Control.MousePosition(params);
      },
    },`

And to finish, in the controller : 
`controls: {
        mousePosition: {}
}`

cordially

Tony
