### ISSUE TITLE
origin coordinates changed

### ISSUE THREAD

**Issue by jerroydmoore** [tombatossals/angular-leaflet-directive#222]
Hi tombatossals,

Before I started using angular-leaflet-directive, the origin was in the top left corner of my map. Now that I'm using angular-leaflet-directive, the origin is in the center.

I've always wondered why the origin was in the top left corner, making all latitude values negative. Perhaps a center origin is better than a top left origin, but now all of my markers are at the wrong coordinates!

If you could perhaps, explain this behavior, I might save myself a lot of trouble so I don't have to remap all of my markers

**Comment by nmccready** [comment]
Closing since this is dated. Please comment to re-open.
