### ISSUE TITLE
Some of the leaflet options are NOT handled via defaults-object

### ISSUE THREAD

**Issue by miemo** [tombatossals/angular-leaflet-directive#226]
Looks like there are some leaflet options that are NOT transmitted to leaflet.js from the defaults-object by angular-leaflet-directive. 

E.g. I was trying to disable touchZoom by adding ```touchZoom: false``` to the defaults-object, but zooming with two fingers was still possible. I took a quick look at the code, and it seems that the options that are transmitted are hardcoded in setDefaults-function - and e.g. touchZoom is not there.

I was able to disable it in the end by calling ```map.touchZoom.disable();``` but it took some time to figure out that was necessary.

**Comment by nmccready** [comment]
Closing since this is dated. Please comment to re-open.
