### ISSUE TITLE
Bounds atrribute not working for a array of lat and lng

### ISSUE THREAD

**Issue by lukasz-zak** [tombatossals/angular-leaflet-directive#228]
Since in leaflet maps we have possibility to set map centered on bounds points like here:

```
map.fitBounds([
    [40.712, -74.227],
    [40.774, -74.125]
]);
```

is it possible to use array of lat and lng like above in `bounds` attribute?

I noticed that in `bounds.js` you check if bounds have properties like `southWest` and `northEast` and if not you don't fire `fitBounds()`.

[Documentation](http://leafletjs.com/reference.html#latlngbounds)

**Comment by mihneasim** [comment]
http://leafletjs.com/reference.html#latlngbounds factory accepts any length Array of coordinates. I wonder if we can do the same, it just means calculating maximums and minimums lats/longs of points in list. Suggestions on preferred/already in use functional library for min/max calculations? I'm new to the project.
