### ISSUE TITLE
show hide geojson layer

### ISSUE THREAD

**Issue by goldalworming** [tombatossals/angular-leaflet-directive#231]
is it possible to show and hide geojson object...

I see at this example http://tombatossals.github.io/angular-leaflet-directive/examples/marker-groups-example.html has attribute visible..

is it possible in geojson object??

**Comment by huevosabio** [comment]
Hey @Grsmto , do you mind explaining further how you ended up doing it? By 

``` javascript
filterFilter($scope.data, $scope.search)
```

do you mean

``` javascript
$filter('filter')($scope.data, $scope.search)
```

and did you pass the `randomFilterFunction` to the `$filter` function?
