### ISSUE TITLE
getBounds method for zooming the map

### ISSUE THREAD

**Issue by littlebeeper** [tombatossals/angular-leaflet-directive#233]
Below is the usage example from leaflet documentation.

// create a red polyline from an arrays of LatLng points
var polyline = L.polyline(latlngs, {color: 'red'}).addTo(map);

// zoom the map to the polyline
map.fitBounds(polyline.getBounds());

There is no way for creating bounds from given Latlngs or from a path array

**Comment by nmccready** [comment]
Did you ever figure this out?

**Comment by tombatossals** [comment]
I'm going to close this as old issue, there are some examples of how to use the bounds facilities here:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/bounds-example
