### ISSUE TITLE
Dynamic bounds on geojson update

### ISSUE THREAD

**Issue by couclock** [tombatossals/angular-leaflet-directive#237]
I'm trying to get adaptative bounds depending on displayed geojson data. 

Here is my HTML fragment 
```
<leaflet center="center" bounds="map.bounds" geojson="map.geojson"></leaflet>

I succeeded using such code 
leafletData.getMap().then(function(map) {
            leafletData.getGeoJSON().then(function(geoJSON) {
                // Update my geoJSON data
                ...
                map.fitBounds(geoJSON.getBounds());
           });
});
```
I don't think this is the better way, I would prefer to use my $scope vars : 
`$scope.map.geojson = <NewGeoJSONData>;`
But using that manner, I can't get bounds corresponding to my new geojson data, so I can't update my map.bounds var ...

The only workaround I found is to update geojson directive so that map bounds are updated every time $watch is fired. I added those 2 lines at the end :
```
var geoJsonBounds = leafletGeoJSON.getBounds();
map.fitBounds(geoJsonBounds);
```
Would you any better idea ? Would it be possible to add a new attribute to the directive so that fitBounds would be fired automatically ?

Thank you

**Comment by tthew** [comment]
What's the current status of this?  The linked example is 404ing.  How would I go about fitting the map to the bounds of geojson FeatureCollection passed via the `geojson` attribute?

**Comment by nmccready** [comment]
@edrex you can get a hold of the layer. `leafletData.getGeoJson().then`
