### ISSUE TITLE
How can we process a form in a popup?

### ISSUE THREAD

**Issue by littlebeeper** [tombatossals/angular-leaflet-directive#238]
I'd like to accomplish something similar at http://users.leafletjs.com/ --> Add Me to the map (big blue button)

Basically it displays a form within a popup when a point on a map is clicked.

I tried to embed a code in "message" property It did not work. E.g.
```
angular.extend($scope, {
         center: {
            autoDiscover: true,
            zoom: 13
         },
         markers: {
            mrk1: {
               lat: 40.989,
               lng: 28.819,
               message: 'mrk1' +
                       '<br/> <span ng-click="messageClick()"> Click Me!</span>'
            }
```

**Comment by nmccready** [comment]
Closing as the hack seem sufficient for now. I'll re-open if people feel otherwise.
