### ISSUE TITLE
Markers disappear when I add one

### ISSUE THREAD

**Issue by thetom88** [tombatossals/angular-leaflet-directive#241]
Hello everyone and thank you for your great work.
I've just updated the directive to the latest stable version. I have a problem when I add a new marker on the map, they're unvisible until I move the map.
In addition the map doesn't always fit the bounds specified.
Here's my html and controller code: http://pastebin.com/Pft78J0e

**Comment by tombatossals** [comment]
Closed, please reopen if needed.
