### ISSUE TITLE
Expose TileLayer events.

### ISSUE THREAD

**Issue by MichielDeMey** [tombatossals/angular-leaflet-directive#242]
It would be nice if there was a way that we could hook onto the tileLayer events, such as loading and load.

http://leafletjs.com/reference.html#tilelayer-load

Or is this implemented yet, if so can you point me to the documentation for this?

**Comment by saidheerajg** [comment]
Hi, Is this implemented yet. I really need these events for tilelayers.

**Comment by nmccready** [comment]
Searching tile.js reveals no events. So no it has not been done. The event architecture is in several directives. If you want it done fast please contribute and PR it back. Closing this ticket since it is stale.
