### ISSUE TITLE
Programmatically open marker popups (ie. access L.marker methods in markers array)

### ISSUE THREAD

**Issue by gwendall** [tombatossals/angular-leaflet-directive#252]
I have an array of markers bound to a map.

```html
<leaflet markers="markers"></leaflet>
```

I would like for example to trigger an openPopup() event on a marker programmatically but it does not work since the marker objects in the "markers" array are not leaflet L.markers objects. 
For example, from a given controller:

```javascript
$scope.markers = {
  example_marker: {
     lat : 51.5,
     lng : 0,
     title : "Marker",
     message : "example message"
  }
}
```

Calling this does not work (returns "object has no method openPopup"):

```javascript
$scope.markers['example_marker'].openPopup();
```

Hence my question: how do I access the L.marker methods (openPopup() in this case) on the leaflet-angular marker objects ("example_marker" here)?

**Comment by nmccready** [comment]
Stale issue closing.
