### ISSUE TITLE
Leaflet awesome markers support

### ISSUE THREAD

**Issue by zolotyx** [tombatossals/angular-leaflet-directive#258]
Leaflet awesome markers do not work, even in given example.
http://tombatossals.github.io/angular-leaflet-directive/examples/markers-update-example.html

In this example many other features do not work (popup message, draggable can not be turned off)

**Comment by nweis** [comment]
We still have an issue displaying font-awesome icons. It seems to me that the className and prefix is not set by the icon type in the angular-leaflet-directive. I've modified leaflet.awesome-markes.js to use 'fa' as default prefix instead of 'glyphicon' to make it work.

**Comment by kpennell** [comment]
@nweis Can you please share how you did this?  I'm getting a class not found error and pretty sure it's tied to this.

**Comment by nweis** [comment]
Sure - I've modified leaflet.awesome-markers.js as follows:

    L.AwesomeMarkers.Icon = L.Icon.extend({
        options: {
            iconSize: [35, 45],
            iconAnchor: [17, 42],
            popupAnchor: [1, -32],
            shadowAnchor: [10, 12],
            shadowSize: [36, 16],
            className: 'awesome-marker',
            prefix: 'fa', // changed from 'glyphicon' to 'fa' by nweis
            spinClass: 'fa-spin',
            extraClasses: '',
            icon: 'home',
            markerColor: 'blue',
            iconColor: 'white'
        },

**Comment by kpennell** [comment]
Thanks!

**Comment by nweis** [comment]
Glad to help. :)

**Comment by orenww** [comment]
Which color format should I use? 
I try to set the value "#00ff00" and it doesn't work
but when I set the value "green" it work well.

I get the color value from the server and I don't have the color name so I can't to set the color.
any solution?

let marker = {
                    lat: lat,
                    lng:lon,
                    message:msg,
                    icon: {
                        type: 'awesomeMarker',
                        prefix:'fa',
                        icon: iconName,
                        markerColor: iconColor
                    }
                }

**Comment by tombatossals** [comment]
Take a look at the new icons example:
http://tombatossals.github.io/angular-leaflet-directive/examples/0503-markers-icons-example.html

**Comment by fdlk** [comment]
@tombatossals I think you need to add the prefix fa or else it'll depend on and use bootstrap glyphicons.

**Comment by axelgunn** [comment]
I'm having difficulties resizing the marker. This is the code I have. Any idea.. someone
            var map = L.map('map',
                    {
                        crs: customCRS,
                        zoomSnap: 0,
                        zoomDelta: 0.5,
                        wheelPxPerZoomLevel: 100
                }),
                realtime = L.realtime(undefined, {
                    //getFeatureId: function (f) { return f.properties.id; },
                    start: false,
                    pointToLayer: function (feature, latlng) {
                        **var smallIcon = new L.AwesomeMarkers.Icon({
                            icon: feature.properties.icon,
                            prefix: "fa",
                            markerColor: feature.properties.color
                        });**
                        return L.marker(latlng,
                            {
                                icon: smallIcon                   
                            });
                    },
                    onEachFeature: onEachFeature
                }).addTo(map);
