### ISSUE TITLE
run demo as file not working

### ISSUE THREAD

**Issue by vanderleisp** [tombatossals/angular-leaflet-directive#262]
Hi David,
I've been trying to learn angular since weeks ago, and also saw Leaflet maybe 2 or 3 months ago, so your code is quite interesting merging both.

Basically I'm a 90% hardware guy since maybe 20 years ago, and last few months I got back to software (I used to do assembler code for microcontrollers loooong time ago...) so it has been a funny challenge to learn JS, HTML, CSS, frameworks, etc... but seems the right direction to go.

I was trying to run your "http://tombatossals.github.io/angular-leaflet-directive/#!/examples/simple-map" page as a local file, so I copied the source code and included it on same folder as all other files (examples, src) and then also "generated" the missing bower components on same folder, but then nothing shows up on such screen. One test I did was to take out the ng-cloak option, and then it only shows the upper area of page where you have the map plus some text, but all the example options plus the selected example itself don't show up.

I'm running the index.html as a file and not via a local HTTP server, so don't know if this could be the problem.

Maybe it's really something simple, but it's driving me nuts.
When I test each of the examples then it works perfectly, but trying to make this page work has been a funny exercise for me.

Later for the mobile device I'm using Titanium as to package the HTML5 app, so seems that having the demo running on a browser would be easier to also run inside Titanium.

**Comment by tombatossals** [comment]
Hi, I'm closing this as old, please reopen if needed
