### ISSUE TITLE
Yeoman with Angular directive gives 'angular-leaflet-directive was not injected in your file.'

### ISSUE THREAD

**Issue by petka535** [tombatossals/angular-leaflet-directive#264]
I would like to use the angular-leaflet directive as a dependency on my project that I use Yeoman to setup. I give the following commands in an empty directory:

$ yo angular
(answer "No" when asked about whether to install Sass with Compass, answer Yes when asked about installing Bootstrap, go with the defaults for the final question)

$ bower install angular-leaflet-directive --save
(I get "Unable to find a suitable version for angular, please choose one:" so I select alternative 3 which on my machine corresponds to "angular#1.2.x which resolved to 1.2.11-build.2192+sha.e2173f9 and has angular-leaflet-directive#0.7.3 as dependants" and prefix the choice with a "!" to persist it

Also, I get "Unable to find a suitable version for jquery, please choose one:" and here I choose 2) "jquery#2.0.x which resolved to 2.0.3 and has angular-leaflet-directive#0.7.3 as dependants", again prefixed with "!")

$ grunt serve

This starts OK but I get the following output:

Running "serve" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "bower-install:app" (bower-install) task

angular-leaflet-directive was not injected in your file.
Please go take a look in "app/bower_components/angular-leaflet-directive" for the file you need, then manually include it in your file.

-----------
Thus, it seems that the dependency on angular-leaflet-directive is not picked up properly for some reason. When I look in my bower.json file, the dependency seems to be there:

"dependencies": {
    "angular": "1.2.6",
    "json3": "~3.2.6",
    "es5-shim": "~2.1.0",
    "jquery": "~1.10.2",
    "bootstrap": "~3.0.3",
    "angular-resource": "1.2.6",
    "angular-cookies": "1.2.6",
    "angular-sanitize": "1.2.6",
    "angular-route": "1.2.6",
    "angular-leaflet-directive": "~0.7.3" }

I would expect the above commands to pick up the dependency and that seems to work for the angular-leaflet-directive. However, I would also expect that the leafletjs files would be present as dependencies as well. Also, the required JS file from the angular-leaflet-directive should now be present in the app/index.html file (along with the standard leafletjs JS and CSS file). 

Am I doing something wrong here? Missing a step? Doing something stupid or misunderstanding the whole concept?

**Comment by tombatossals** [comment]
I'm closing this as old, lot of things have changed. Please reopen if needed
