### ISSUE TITLE
Event handling question for multiple maps

### ISSUE THREAD

**Issue by uygardonduran** [tombatossals/angular-leaflet-directive#265]
Hi,
I have two maps on DOM, and the events triggered from the second is also handled by the first. So I have to control if the event triggered and handled with the same map as follows in my controller.
```
  var map = null;
  $scope.$on('leafletDirectiveMap.load', function (event, args) 
      {
        leafletData.getMap(args.leafletEvent.target._container.id)
        .then(function (m)     {
			if (!map) { 
				map = m;
			        //do something
			}			
		});
	});


   $scope.$on('leafletDirectiveMap.moveend', function (event,args) {
		if (map && map._container.id == args.leafletEvent.target._container.id) {
			//do something
		}		
	});
```
Is this the correct way of doing this ? Thanks.

**Comment by nmccready** [comment]
On master I have tacked mapId into the directive scope. So you can now check it.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/events/leafletMapEvents.js#L61-L63

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L42

Example of using the id:
https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/805-markers-updates.html#L127

**Comment by nmccready** [comment]
As @facultymatt stated broadcast appears to be hardcoded. 
https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L127

I'll look into fixing this unless someone else wants to. This should be dead easy. Also this will allow me to remove the comment in leafletMapEvents.

**Comment by nmccready** [comment]
I am working on this right now.

**Comment by nmccready** [comment]
This will be on 0.9.X

**Comment by nmccready** [comment]
https://github.com/tombatossals/angular-leaflet-directive/pull/987

**Comment by nmccready** [comment]
Resolved on master
