### ISSUE TITLE
Adding geojson data after initialization does not work

### ISSUE THREAD

**Issue by mchambaud** [tombatossals/angular-leaflet-directive#267]
Hey, 

Adding GeoJSON data only works before map load.

    var myGeoJson = "...";
    $scope.geojson = myGeoJson; // shows data on map

    Scope.add = function() {
        $scope.geojson = myGeoJson; // does not show data on map
    }

am I missing something?

**Comment by tombatossals** [comment]
Lot of code changes to GeoJSON in the last months. That will work for sure now, please reopen if needed
