### ISSUE TITLE
Remove Markers Question

### ISSUE THREAD

**Issue by davidkwong** [tombatossals/angular-leaflet-directive#276]
I have been looking for a proper way to remove marker and  I might not understand how this isolated scope works.

Basically I populate the markers from my database and add a stationid property of to each marker. I am hopeless....

1. I want to add a "delete" button inside each marker popup and the delete button is able to delete that particular marker when it's clicked and send a request back to my database to delete my station by the station id . 

Do I need to pass a button to the message property ? It's been a week now I still don't get it. ><

  myservice.getAllStations().$promise.then(function (item) {
            var matchedItems = new Array();
            angular.forEach(item, function (data) {
                var eachstation = {
                    lat: data.lat,
                    lng: data.lng,
                    message: data.message,
                    stationId: data.stationId
                };
                matchedItems.push(eachstation);         
            });
            $scope.markers = matchedItems;
        });

2. If I have a button in a different controller, how to use that button to add a marker to the map ? Is it something to do it broadcasting event ?

I hope you guys genius can help me out....=(

**Comment by tombatossals** [comment]
Hi, a lot of things has changed in the markers logic in the last months. Please reopen if needed.
