### ISSUE TITLE
Second trailing slash redirect hangs the application

### ISSUE THREAD

**Issue by masimakopoulos** [tombatossals/angular-leaflet-directive#286]
I came across a peculiar bug. 
I have a route that takes parameters and has an angular-leaflet directive. Something like /world/:continent/:country
If I go to #/world/europe/germany/ (note the trailing slash) I get redirected to #/world/europe/germany as per default angular behaviour. If I enter a trailing slash again in the url and press enter the App goes into a redirect loop.
Chrome restarts the SPA, IE burns and crashes (exception is thrown inside safeApply method line 2483 $scope.$apply(fn)). Other pages not containing the angular leaflet directive do not even fire a redirect event when placing the trailing slash for the second time.

**Comment by tombatossals** [comment]
Closing this as old, please reopen if needed
