### ISSUE TITLE
Google Maps panning after clicking zoom does not pan.

### ISSUE THREAD

**Issue by amyhua** [tombatossals/angular-leaflet-directive#287]
On the example: http://tombatossals.github.io/angular-leaflet-directive/examples/googlemaps-example.html

Both panning and zooming break if you use the +/- buttons to zoom immediately after loading. Panning and Zooming otherwise tend to work if you do not click on the +/- right after the map loads. SCROLLING to zoom right after map load does not encounter this problem; only clicking does.

**Comment by tombatossals** [comment]
This must be related with the Google Maps integration of https://github.com/shramov/leaflet-plugins.

I'm closing this, please reopen if you think this has to be revised.
