### ISSUE TITLE
Dynamic updates to markers only apply on mouse move

### ISSUE THREAD

**Issue by ghost** [tombatossals/angular-leaflet-directive#288]
In the web app I'm writing, I am connecting to a web socket to get real time data about object positions. I create a marker for an object whose position I'm tracking and then on ever new socket message, I update the marker position. I was having trouble getting it working until I noticed that the marker would move when I moused over the map. Here is a jsfiddle example demonstrating the problem. If you wiggle the mouse over the map, you should see the marker move, but it stops when you stop, even though it's position should still be changing.

http://jsfiddle.net/4PhzC/20/

**Comment by caioiglesias** [comment]
@nandokun If you're connecting to web sockets inside a service you should read this:
http://stackoverflow.com/questions/21658490/angular-websocket-and-rootscope-apply
