### ISSUE TITLE
Map jumps to new center position when double-clicked

### ISSUE THREAD

**Issue by perqa** [tombatossals/angular-leaflet-directive#292]
In the left-hand example (bicycle map, etc) on http://tombatossals.github.io/angular-leaflet-directive/#!/, if I double-click a point int the map, it will zoom, as expected, but it will also jump to a new location - outside the original map frame (usually north, it seems).

**Comment by tombatossals** [comment]
Can't notice this behaviour now, it must has been solved in a previous commit. Please reopen if needed. Thanks
