### ISSUE TITLE
Bounds incorrect after centre change

### ISSUE THREAD

**Issue by set321go** [tombatossals/angular-leaflet-directive#300]
I update the map with new centre coordinates (not sure if this is the correct way of doing it), and the map recenters on the new location. When getBounds is called it still contains the old map bounds. 

       if($scope.querylocation.trim() !== ''){
          geolookup.lookupAddress($scope.querylocation).then(function(data){
            $log.debug('Address response :' + data);
            $scope.center.lat = parseFloat(data[0].lat);
            $scope.center.lng = parseFloat(data[0].lon);
          });
        }
        leafletData.getMap().then(function(map){
            var bounds = map.getBounds();
            //do some bounds stuff
          });

**Comment by nmccready** [comment]
This is old and probably outdated. Closing unless someone chimes in.
