### ISSUE TITLE
IE8 - Paths - Invalid data passed to the polyline path

### ISSUE THREAD

**Issue by thetom88** [tombatossals/angular-leaflet-directive#304]
Hello everyone!
I'm having a problem in working with paths in IE8. I'm creating the path object this way:
```
$scope.paths = {}; // at controller start
//later when i get markers:
            _.each(steps, function (step) {
                p1.latlngs.push({ lat: step.Destination.Latitude, lng: step.Destination.Longitude });
            });
            $scope.paths.p1 = p1;
```
In chrome and firefox is working without problem, but in IE it's not working. I did some debugging and i found out that i don't pass the test:_isValidPolyline
Here's my p1 obj:
```
{
  "color": "#efa800",
  "weight": 8,
  "latlngs": [
    {
      "lat": 40.714,
      "lng": -74.006
    },
    {
      "lat": 25.788969,
      "lng": -80.22644
    }
  ]
}
```
Is my path obj correct?
What can I do to fix it?

**Comment by nmccready** [comment]
Was this ever figured out. Closing since it is stale.
