### ISSUE TITLE
Dynamically updating popup marker content doesn't work if moving center

### ISSUE THREAD

**Issue by kbdaitch** [tombatossals/angular-leaflet-directive#307]
Thanks for the great plugin. I have been using it recently for a project and found that updating a marker's message has weird behavior on the map.

For example, I start with a center of NYC (40.67, -73.94) and a marker at the same coordinates with a popup message: "msg 1". That works fine.

Next, in event of a resource URL fetch, I try to update the popup message to "msg 2" as well as the marker and center coordinates, and my map snaps to a center of older marker - as well as removes the marker visually. If I comment out this message change, changing other things such as center and marker's coordinates is working fine.

I have found the offending [line](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletMarkersHelpers.js#L262), however, cannot figure out why its giving such results from debugging in the underlying Leaflet library.

Let me know if you need any more context to track this down.

**Comment by nmccready** [comment]
Might be related #254

**Comment by nmccready** [comment]
Still valid.

**Comment by nmccready** [comment]
Actually the fiddle appears to work with 0.8.4, and 0.8.5. The map moves as well as the marker.
