### ISSUE TITLE
Path $on click, stops working post pan

### ISSUE THREAD

**Issue by xamelion** [tombatossals/angular-leaflet-directive#313]
when you move the map click stops working on paths

**Comment by eczajk1** [comment]
I have experienced the same problem.  :disappointed:

**Comment by tombatossals** [comment]
Could anyone post a jsfiddle with this behaviour?

**Comment by eczajk1** [comment]
This fiddle should illustrate it.  In summary, click events work fine on paths until the user pans the map.  At that point, click events appear to no longer fire.

http://jsfiddle.net/eczajk1/9pb1Lons/

**Comment by tombatossals** [comment]
@nmccready, I was just investigating this issue, it seems that in the default event propagation behaviour, where all the path events are propagated, when the map is panned the events stop propagating.

But if you specify which events must be propagated, it's working ok. I have created an example, based on @eczajk1 jsfiddle, to illustrate it, I'm sending a PR.

**Comment by nmccready** [comment]
thanks I'll take a look

**Comment by eczajk1** [comment]
I wasn't privy to events broadcast directive, but I suppose it solves my issue, fyi.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#7

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
