### ISSUE TITLE
Layer Bounds

### ISSUE THREAD

**Issue by JaumeFigueras** [tombatossals/angular-leaflet-directive#329]
Hi again,
I've seen that a layer have a bounds param, but can I use it to get the bounds? For example in a layer with markers get the extent of them.
Thanks.

**Comment by tombatossals** [comment]
Hi @JaumeFigueras, lot ot time passed from that issue, sorry for not responding.

You can't call a leaflet function without access the Leaflet object, you already know that for sure.

I'm closing this issue, please reopen if needed.
