### ISSUE TITLE
Cannot use leaflet directive multiple time at once.

### ISSUE THREAD

**Issue by wayofspark** [tombatossals/angular-leaflet-directive#331]
Hello,

The _leafletMap directive variable singleton in the root directive cause leaflet to crash in various way if more than one map is used at the same time in the application. ( all maps use the variable, causing previous maps to loose reference to their own map at one point )

Fix should be easy using a scope variable instead of directive singleton to store the map promise.

**Comment by kuanb** [comment]
Wondering if anyone has any insight on the following TypeError (seems to likely be related to this issue). I have two maps, `map_left` and `map_right`. When adding new layers, using `leafletData.getMap('map_xxx').then(function(map) { ... }` works great but whichever map I attempt to `var.addTo(map)` second (after one map has already been interacted with), results in the following `TypeError`: 

```
o.LineUtil._getBitCode	@	leaflet.js:8
o.LineUtil.clipSegment	@	leaflet.js:8
o.Polyline.o.Path.extend._clipPoints	@	leaflet.js:8
o.Polyline.o.Path.extend._updatePath	@	leaflet.js:8
o.Mixin.Events.fireEvent	@	leaflet.js:6
o.Util.bind	@	leaflet.js:6
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#11

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by tfendt** [comment]
This is still not working or me. Multiple maps each is updating it center when moving the other. Causes tiles to not load as well. I have different ID's for the maps and different controllers.
