### ISSUE TITLE
Leaflet sub-directives should be prefixed

### ISSUE THREAD

**Issue by wayofspark** [tombatossals/angular-leaflet-directive#332]
leaflet subdirective should be prefixed to avoid directive collision with other libs. Most dangerous directive is the 'legend' directive which require "^leaflet". Common directive names should be prefixed ( aka leafletLegend, lfLegend or any prefix ).

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#12

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
