### ISSUE TITLE
Adding the same file twice in bower.json -> 'main' property

### ISSUE THREAD

**Issue by rvanbaalen** [tombatossals/angular-leaflet-directive#333]
You've set the same file twice in the bower.json 'main' property (regular and minified). Just a reference to the regular file is enough.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#13

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
