### ISSUE TITLE
Getting center point from a factory

### ISSUE THREAD

**Issue by doronsever** [tombatossals/angular-leaflet-directive#334]
I'm trying to set the map's center via a factory service.
The factory returns lat/long via a promise.

I put the angular.extend inside the success function of the promise but the map doesn't show the center.
Its like it doesn't get affected by it.
Here is my controller(look that even with hardcoded params it doesn't work)

      .controller('TCtrl', function($scope, $stateParams, LocationService) {
             LocationService.getLatLong().then(
                function(latLong) {
                   angular.extend($scope, {
  
                    center: {
                        lat: 32.0791801,
                        lng: 34.7731258,
                        zoom: 17
                    },
                    defaults: {
                        scrollWheelZoom: false
                    }
                });
            },

            function(error) {
                alert(error);
            }
        );

});

How can i get this to work?

**Comment by tombatossals** [comment]
Closing as old, please reopen if needed
