### ISSUE TITLE
Title property for markers in markercluster group after filtering

### ISSUE THREAD

**Issue by mukhtyar** [tombatossals/angular-leaflet-directive#337]
I am trying to find a marker within a markerclustergroup overlay by using the following code:

```
$timeout(function(){    
          leafletData.getLayers().then(function(layers) {
              $scope.markerClusterGrp = layers.overlays.locations;
              var clusters = $scope.markerClusterGrp.getLayers();
              for (var i in clusters){
                if (marker.title == clusters[i].options.title) {
                  childMarker = clusters[i];
                  break;
                } 
             }
          });       
},1000);
```
I'm assuming that the options.title property in the clusters object is same as the marker.title property that I initially defined while creating the markers. However once I apply a filter to the markers, the options.title property in the clusters object does not match up. To illustrate this I have created a fiddle:  

http://jsfiddle.net/mukhtyar/pHeKJ/

If you open up the console and play around with the filter you will see a log of the $scope.marker titles and clusters options.titles. 

I am not sure if my assumption about .title is incorrect or if this is a bug. Is there a better way to find a marker within a markerclustergroup? My eventual objective is to find the parent cluster of this marker and highlight it on a mouseover event. I am using latest v. of this directive, and angular 1.2.8. Thanks!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#14

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
