### ISSUE TITLE
Markers and Zoom in / Out buttons don't work on Cordova/Phonegap

### ISSUE THREAD

**Issue by doronsever** [tombatossals/angular-leaflet-directive#338]
I've successfully placed the angular-leafet-directive in my phonegap(3.4) application.
Everything works great, but, i have few markers on my map with some message on each of them. The first maker, which i put it as focus:true is indeed showing the message, but i cannot see the other messages when i click on the other markers. Nor use the zoom in/out buttons.

Everything works great on my desktop browser

**Comment by wedgybo** [comment]
Did you ever get this working? I'm having difficulty with taps on mobile in the cordova environment. Double taps and pinch work great. Just appears to be problems with single taps.

**Comment by jonshutt** [comment]
I have same issue - appears that the map layer is in front of the markers and controls. i can see them when they load up, but the map comes in front...

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#15

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
