### ISSUE TITLE
bounds is not set after initial map load

### ISSUE THREAD

**Issue by jasadams** [tombatossals/angular-leaflet-directive#340]
I know the way bounds and center was reworked recently. One side effect of this improvement is that after the inital load of my map, the bounds are not set. It is not until I pan or zoom the map that the bounds are set.
I did a little initial investigation and it seems that the listener for the "boundsChanged" event in the bounds directive is not set up in time for the initial broadcast of this event when the center is set in the center directive. The listener is inside a Map.whenReady promise and the map is not ready when the initial center is set.

**Comment by joeystandrew** [comment]
I am actually having this same issue, to fix it inside my Ionic application I check for missing bounds on map moveEnd and re-set it.

```javascript
            var trueBounds = map.getBounds();
            var trueNE = trueBounds.getNorthEast();
            var trueSW = trueBounds.getSouthWest();

            $scope.map.bounds = {
                northEast: {
                    lat: trueNE.lat,
                    lng: trueNE.lng
                },
                southWest: {
                    lat: trueSW.lat,
                    lng: trueSW.lng
                }
            };
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#16

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
