### ISSUE TITLE
$scope.center won'T update after drag anymore

### ISSUE THREAD

**Issue by Calamari** [tombatossals/angular-leaflet-directive#346]
Hello!

I have the following setup:
scope that defines a center attribute and the directive accepting the directive via `center="center"`. If I set and reset the center  attribute multiple times it works like a charm. But when I drag the map a bit in between then every further update of the center attribute will not change the position in the map anymore. 

Do I do something wrong? In my opinion that should work, right?

**Comment by nmccready** [comment]
This is old and probably outdated. Closing unless someone chimes in.
