### ISSUE TITLE
Two (or multiple) GeoJSON Layers

### ISSUE THREAD

**Issue by shaunakv1** [tombatossals/angular-leaflet-directive#355]
First up, thanks for writing an awesome ng wrapper for leaflet! 

My question is what is the right way to add two or more GeoJson Layers to the map. I am able to draw features from one service (poly lines) using 'geojson' directive. But I have another GeoJson web service (circles) that I need to draw on the map in the same way I did the first one. Can you guide me please? 

Is there an example for this? I looked but couldn't fine.. 

Thanks!

**Comment by newmanw** [comment]
+1 for something in layers def.  Maybe a 'vectors' object to go along with baselayers and overlays.

**Comment by Mike-Loffland** [comment]
+1

**Comment by kuanb** [comment]
Any update on a solution here?

**Comment by nmccready** [comment]
Yes this is done. See geojson-nested in examples. I implemented this a few weeks back.

**Comment by nmccready** [comment]
https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0125-basic-geojson-nested-example.html

**Comment by gaiagilder** [comment]
is possible to get it working after an event is occurred? thanks

**Comment by nmccready** [comment]
@gaiagilder not sure what you mean. This should already work.

**Comment by gaiagilder** [comment]
sorry for the bad explanation, when I reached a certain zoom level, I make a request to a server that returns me two separate geojson in an array, at this point I'm trying to display the data but without success, I try to make Plunker
