### ISSUE TITLE
Example dragging on  "dynamic update marker properties"

### ISSUE THREAD

**Issue by samcfc** [tombatossals/angular-leaflet-directive#356]
Hi there, just a little thing to point out.

On the "Dynamic update marker properties" example, 
first the marker is not draggable but if I set it to draggable and then back to not draggable again, it keeps being draggable.

Thanks a lot for your work, have a good day and enjoy sunny days being back :)

**Comment by tombatossals** [comment]
Sorry I couldn't take a look at this, now the example has been splitted and it seems to work as expected: 

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/popup-example
