### ISSUE TITLE
Leaflet draw/layer events not firing upon ng-if being false and then true

### ISSUE THREAD

**Issue by nickponline** [tombatossals/angular-leaflet-directive#357]
I have map 
```html
<leaflet id="mycustom"  center="center" controls="controls"> </leaflet>
```
and a controller containing:
```javascript
function myCtrl($log, leafletData) {

    $scope.center = {lat : 36.215884,  lng : -119.289269, zoom: 15};
    $scope.editableLayers = new L.FeatureGroup();
    $scope.controls =  {
        position: 'bottomleft',
        draw: {
            polygon: false,
            marker: false,
            circle: false,
            rectangle: false,
            polyline: {
                shapeOptions: {
                    color: '#3498db',
                    opacity: 0.9
                }
            },
        },
        edit: {
            featureGroup: $scope.editableLayers,
            remove: false
        }
    };  
    leafletData.getMap('mymap').then(function(map) {
            $log.info('Adding events ...');
            map.on('draw:drawstart', function (e) {
                $log.info('Starting draw');
            });
    });
}
```

The first time I load the page with the map and draw something the ```draw:drawstart``` events fires but if I navigate to another URL in my app and then back to this page the event does not fire if I draw something. Any way I can debug this or provide more useful information?

**Comment by punknroll** [comment]
I have the same problem!

**Comment by nmccready** [comment]
When you navigate back and forth is this via a angular router? Seems like the map has been detached. One issue that is common in google maps is it must be resized once it is hidden (like ng-hide or a router). It could be the map has lost its bounds. Anyways, this is all guessing can you create an example and either PR it to examples , plnkr or jsfiddle it? Make sure to reference dependencies via rawgit so you have the latest code.

**Comment by nmccready** [comment]
Here is a starting point to fork. http://jsfiddle.net/nmccready/ua82epxd/

**Comment by grimace** [comment]
I am having the same issue. Is there any more info for this? I have created a simple page that allows toggling between divs :
```
<!DOCTYPE html>
<html ng-app="drawtestapp">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../bower_components/angular/angular.min.js"></script>
    <script src="../bower_components/leaflet/dist/leaflet.js"></script>
    <script src="../bower_components/angular-simple-logger/dist/index.js"></script>
    <script src="../dist/angular-leaflet-directive.min.js"></script>
    <script src="../bower_components/leaflet.draw/dist/leaflet.draw.js"></script>
    <link rel="stylesheet" href="../bower_components/leaflet/dist/leaflet.css" />
    <link rel="stylesheet" href="../bower_components/leaflet.draw/dist/leaflet.draw.css" />
    <script>
        var app = angular.module("drawtestapp", ["leaflet-directive"]);
        app.controller("ControlsDrawController", [ "$scope", "leafletData", function($scope, leafletData) {
            $scope.showMap = true;
            
            $scope.switchPanel = function() {
                $scope.showMap = !$scope.showMap;
            };
 
            angular.extend($scope, {
                london: {
                    lat: 51.505,
                    lng: -0.09,
                    zoom: 4
                },
                controls: {
                    draw: {}
                },
                layers: {
                    baselayers: {
                        mapbox_light: {
                            name: 'Mapbox Light',
                            url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
                            type: 'xyz',
                            layerOptions: {
                                apikey: 'pk.eyJ1IjoiYnVmYW51dm9scyIsImEiOiJLSURpX0pnIn0.2_9NrLz1U9bpwMQBhVk97Q',
                                mapid: 'bufanuvols.lia22g09'
                            },
                            layerParams: {
                                showOnSelector: false
                            }
                        }
                    },
                    overlays: {
                        draw: {
                            name: 'draw',
                            type: 'group',
                            visible: true,
                            layerParams: {
                                showOnSelector: false
                            }
                        }
                    }
                }
           });

           leafletData.getMap().then(function(map) {
               leafletData.getLayers().then(function(baselayers) {
                  var drawnItems = baselayers.overlays.draw;
                  map.on('draw:created', function (e) {
                    console.log('adding layer to drawnItems');
                    var layer = e.layer;
                    drawnItems.addLayer(layer);
                    console.log(JSON.stringify(layer.toGeoJSON()));
                  });
               });
           });
       }]);
    </script>
    <style>
        input {
            width: 120px;
            margin-right: 10px;
        }
    </style>
  </head>
  <body ng-controller="ControlsDrawController">
    <div ng-if="showMap">
        <leaflet lf-center="london" controls="controls" layers="layers" width="100%" height="400"></leaflet>
        <h1>Draw control example</h1>
        <p>Draw a shape and a geoJSON data structure will be shown on the console.log.</p>
    </div>
    <div ng-if="!showMap">
        <center>
            <p>This is something else entirely.</p>
        </center>
    </div>
    <button ng-click="switchPanel();">
        Toggle Map
    </button>
  </body>
</html>



```

**Comment by grimace** [comment]
I've also tried 
`
map.invalidateSize()
`
which doesn't work either.  Is that what you were thinking for resize()?

**Comment by nmccready** [comment]
Have you tried `ng-show` yet? That will just hide it and not detach it from the dom. That might work for a workaround. The other possible issue on getMap is it is returning the original map from the original dom element (which is gone). So it sounds like the promise list which getMap is returning from needs to be reset or cleaned out for that map instance.

**Comment by nmccready** [comment]
Try calling [unresolveMap](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletData.js#L30) from that service when your state hides the map. This will unresolve the map.

**Comment by grimace** [comment]
ng-show works perfect, and exactly the type of thing I want because I want to preserve the state when switching from one panel to the other and back,  (i.e. keep whatever is drawn on the screen )
 
I tried 
`
leafletData.unresolveMap() 
`
with no change.  The thing that is confusing to me is that the map comes back with the same pan and zoom but the other layers don't.

**Comment by nmccready** [comment]
@grimace cool that is a good lead that layers is the possible problem. We can keep digging into this.

**Comment by grimace** [comment]
it turns out that the ng-show only works if I show the map initially.  In my particular use case, I start out NOT showing the map and then toggle it in.  In this case ng-show behaves somewhat similar to the ng-if so it's not really a workaround IMHO.

**Comment by nmccready** [comment]
What about using the resize / invalidate?

**Comment by grimace** [comment]
I actually mis-spoke earlier, I got it working with ng-show.  My test worked fine so I tracked down that I had different versions in my real work.  You were right to say that ng-if causes some kind of detachment but ng-show works well.  Thx.

**Comment by nmccready** [comment]
So do you think this is good enough of a workaround that we can close this issue?

**Comment by grimace** [comment]
Yes, definitely working for me to use ng-show rather than ng-if

**Comment by rchacon01** [comment]
Is there support for ng-if in the latest release?

**Comment by AppDevGuy** [comment]
Any fix on the way for this? I have three leaflet maps and if I have a layer on more than one, then marker clusters do not fire events off because whatever the third map layer to load is takes precedence over all others in the `leafletData().getLayers().then(function(layers))` function. 

The map events are not being fired with ng-if to load markers based on map events and ng-show prevents marker cluster events from firing. 

My hope was to us ng-if in order to determine which map should contain the layer in order to receieve the correct layer. 

I am using id's in the HTML but that makes no difference and markerCluster is dependent on a layer not a specific object like a marker.
