### ISSUE TITLE
osm building support

### ISSUE THREAD

**Issue by goldalworming** [tombatossals/angular-leaflet-directive#361]
please add support for osmbuilding

http://osmbuildings.org/examples/Leaflet.php?lat=52.51913&lon=13.42438&zoom=17

**Comment by josesolano** [comment]
Yes, I'm sure that could be awesome!

**Comment by tombatossals** [comment]
I have tried to integrate osmbuilding into angular-leaflet-directive, but it's not an easy task, the initiation code from that project would need to be changed, so it could return a new osmb layer and added to the map in a subsequent sentence.

I close this task for now, maybe it could be reopened in the future.

**Comment by nerdfiles** [comment]
I've had success integrating OSMBuildings with angular-leaflet-directive while building [lovestamp.io](https://lovestamp.io), but it's true that it is not easy. I think $rootScope was involved. Ouch.
