### ISSUE TITLE
Scopes and 'The "center" property is not defined in the main scope'

### ISSUE THREAD

**Issue by wilhelmberg** [tombatossals/angular-leaflet-directive#362]
I'm using the [AngularJS SPA Template](http://visualstudiogallery.msdn.microsoft.com/5af151b2-9ed2-4809-bfe8-27566bfe7d83) with Visual Studio 2013 and the above mentioned error message occurs.

Somehow it seems, that two scopes for the leaflet-directive get created.
First one is completely empty and causes the error:
![scope-003](https://cloud.githubusercontent.com/assets/4549888/2903376/6ad9e5f2-d5f0-11e3-8278-eab702d6b6a7.png)

The second one contains all the information I set in the controller:
![scope-00h](https://cloud.githubusercontent.com/assets/4549888/2903380/6e9fe22c-d5f0-11e3-8685-f3793fc7bd54.png)
![layers](https://cloud.githubusercontent.com/assets/4549888/2903538/11377e90-d5f2-11e3-834b-e6c8fe434656.png)

Setting and getting the center seems to work from there on, but other angular bindings on the page are not executed.

Any hint on how to provide more useful information about my problem (or even a solution) would be highly appreciated.

Another error that pops up is `[AngularJS - Leaflet] At least one baselayer has to be defined`, but that one doesn't seem to cause any side effects: everything concerning layers seems to work just fine.

**Comment by lf94** [comment]
Where is the solution documented? Last Friday I tried setting up custom layers and I was getting the same "baselayers undefined" issue, but this fixed it. Having it in the documentation would save some time. How would I add it myself?
