### ISSUE TITLE
Dynamic Legend

### ISSUE THREAD

**Issue by dmoulton** [tombatossals/angular-leaflet-directive#369]
I am creating charts that get data from a service before they are built. That is also true of the data that builds the legend. I can't seem to create a legend unless I use static data at the top of my controller, before the service is called that gets the data. I also tried creating an empty legend and then populating it with the received data, but the legend remains blank. Am I going about this wrong?

**Comment by tombatossals** [comment]
The legend functionality can be greatly improved, I agree. Don't have time now for this, but we accept PR.
