### ISSUE TITLE
Latency using markercluster with 15K points

### ISSUE THREAD

**Issue by vadvv** [tombatossals/angular-leaflet-directive#371]
I'm having a problem clustering a large number of points (my current set is 40K+ points, but I've even gone down to about 15K points). It takes very long to cluster, and then when zooming in/out it takes similar time for the layer to render. Most of the time the browser (in my case Chrome) asks to kill the tab.

I should add that to overcome this, I had decided to show the data as a heat map until a zoom level is reached, after which I thought I could show the cluster, but that didn't seem to help either and resulted in the same delay.

These are my layerOptions:
layerOptions: {
		                    "chunkedLoading": true,
		                    "showCoverageOnHover": false,
		                    "removeOutsideVisibleBounds": true,
		                    "chunkProgress": updateProgressBar
		                }

I see that there's a leafletjs example that clusters 50K points pretty gracefully:
http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html

Here's a fiddle demonstrating the behavior:
http://jsfiddle.net/redgis/BLW4p/

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#19

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
