### ISSUE TITLE
Make marker message/label clickable?

### ISSUE THREAD

**Issue by wootwoot1234** [tombatossals/angular-leaflet-directive#372]
I'm trying to make my marker popups clickable.  When I use html in the marker popup the html is rendered correctly but ng-click doesn't work.  Here's what I have.  

     $scope.map.markers.push({
        lat: lat,
        lng: lng,
        message: '<span ng-click="openView()">' + data.results[i].locationName + '</span>',
        draggable: false
    });

Anyone know what I'm doing wrong or know how to call a function when the marker popup is clicked?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#20

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by tuncagurkan** [comment]
I think this is easiest way:  http://stackoverflow.com/a/27935131/2742162
