### ISSUE TITLE
Compressed Code in Examples

### ISSUE THREAD

**Issue by robotnic** [tombatossals/angular-leaflet-directive#379]
The examples are not really readable because of compressed javascript code.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#21

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
