### ISSUE TITLE
Is there a way to set active base layer ?

### ISSUE THREAD

**Issue by uygardonduran** [tombatossals/angular-leaflet-directive#384]
Hi,
I'm using the layers attribute for my fixed baselayers. I want to store and load the user's base layer selection in the localstorage so I need to set the base layer at start up.
With introducing an eg. activeLayer option and making a small change in the angular-leaflet code I could do it. Or I tried to use setting top = true for the active layer at start up, but that also ruins the order of the options in the layer control UI, making the active layer on top. ( I don't want this. ) Anyway maybe there is a simpler way to do this without changing the code. That's what I want to know.

Thanks.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#22

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
