### ISSUE TITLE
The "center" variable can't use a "-" on his key name

### ISSUE THREAD

**Issue by moretti** [tombatossals/angular-leaflet-directive#385]
What is the reason behind this check?

    if (attrs.center.search('-') !== -1) {
      $log.error('The "center" variable can\'t use a "-" on his key name: "' + attrs.center + '".');

It breaks a configuration like this one:

    <leaflet center="{'lat': 51.508515, 'lng':-0.1254872, 'zoom':12}"><leaflet>

**Comment by nmccready** [comment]
I did see this in the code base and thought it was interesting as well. @tombatossals thoughts?

**Comment by simison** [comment]
PS. A good reminder to comment code better. ;-)

**Comment by nmccready** [comment]
Or better yet use a function with proper naming that explains what it does.

**Comment by simison** [comment]
Totally. :+1:

**Comment by nmccready** [comment]
Bumping this to 0.9.1

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#23

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
