### ISSUE TITLE
maxzoom doesn't work over 18

### ISSUE THREAD

**Issue by kinhunt** [tombatossals/angular-leaflet-directive#387]
eg, maxzoom set to 20. it doesn't load tiles over 18. try it with this:

http://weburner.com/lab/qinhuangdao/tiles/{z}/{x}/{y}.jpg

**Comment by nielk** [comment]
I have the same issue, it's annoying… Is there a way to increase the max-zoom over 18 ? It works with leaflet (maxZoom > 18) but doesn't work with angular-leaflet-directive.

**Comment by rerezz** [comment]
I had the same issue. After setting max and min zoom in the options the zoom worked for me:

In my controller:
```javascript
var tiles = { tiles: {
  url: "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
  options: {
    attribution: "",
    minZoom: 10,
    maxZoom: 21
}}};
angular.extend(this.$scope, tiles);
```
in my view:
`<leaflet tiles="tiles" ></leaflet>`

Without this leaflet will use the default value of 18 for maxZoom. See the documentation: http://leafletjs.com/reference.html#tilelayer

This post helped me to solve it: (https://gist.github.com/atogle/06760453b057ec34248f#file-shareabouts-layer-maxzoom-yml) Thanks!

**Comment by nmccready** [comment]
@rerezz thanks a bunch big help

**Comment by nmccready** [comment]
FYI the same works in the layers directive except the options are `layerOptions`.

```
 layerOptions: {
    attribution: "",
    minZoom: 10,
    maxZoom: 21
}
```
