### ISSUE TITLE
doco - path events

### ISSUE THREAD

**Issue by porjo** [tombatossals/angular-leaflet-directive#389]
It would be great if the doco could be updated to indicate that events can be bound to markers and paths aswell as the map itself.

I have path events working now after reading issue #246 and digging through the code.

For the benefit of others, define `path` event:

```JS
...
events: {
  path: {
    enable: ['click'],
    logic: 'emit'
  }
},
...
```

and bind listener for `leafletDirectivePath`

```JS
$scope.$on('leafletDirectivePath.click', function(event,args) {
  console.log("click", event, args);
});
```

**Comment by nmccready** [comment]
#313
