### ISSUE TITLE
Should the directive to be defined within ng-view or outside when the map is only to be shown in a route

### ISSUE THREAD

**Issue by gotaheads** [tombatossals/angular-leaflet-directive#390]
Hi,

I've used leafletjs with Angular without this directive, which I've reused a map without recreating it to prevent the memory leak. 

My experience is if you create a map within the ng-view and discard when navigating away, the leafetmap has many orphaned divs in DOM.

My question: is this directive designed to be used within the ng-view or there should be only one directive created in app?

Thanks in advance.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#24

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
