### ISSUE TITLE
Change coordinate reference system (CRS) dynamically

### ISSUE THREAD

**Issue by muenchdo** [tombatossals/angular-leaflet-directive#401]
Is it possible to change the coordinate reference system (CRS) dynamically?

I have managed to initialize the map with different CRS by passing a Leaflet CRS object (e.g. `L.CRS.EPSG3857`) into `defaults`, but when I change this object the change is not reflected on the map.

There is a [fiddle](http://jsfiddle.net/GpG4G/7/) which does this with regular Leaflet.js, where this also requires to redraw the layer. I thought I could maybe do this by setting the `baselayers` object to `{}` and then adding my baselayers back in, but that also doesn't work.

Would be great if someone could help out!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#25

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
