### ISSUE TITLE
trouble drawing polyline

### ISSUE THREAD

**Issue by cleechtech** [tombatossals/angular-leaflet-directive#403]
I am trying to draw a polyline on my map to connect points. This object gets attached to `$scope.allPaths` on click.

```
{
  "path70601000211": {
    "color": '#008000',
    "weight": 8,
    "latlngs": [
      {
        "lat": "-1.29048",
        "lng": "36.827999"
      },
      {
        "lat": "-1.291455",
        "lng": "35.828468"
      },
     {
        "lat": "-1.290858",
        "lng": "37.828182"
      }
    ]
  }
}
```

This is the map directive
```
<leaflet center="nairobi" 
    paths="allPaths"
    height="480px" 
    class="col-md-12"></leaflet>
```

When I click the above object attaches to the scope but the polyline does not draw. How can I draw the line on my map?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#27

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
