### ISSUE TITLE
controller scope values don't change

### ISSUE THREAD

**Issue by pglotov** [tombatossals/angular-leaflet-directive#405]
Sorry if this has been discussed. I'm looking at an example
http://tombatossals.github.io/angular-leaflet-directive/examples/center-example.html

When I drag the map both center input fields change alright. But in AngularJS batarang plugin in chrome when I look at the scope of the controller, the numbers in 'london' field stay the same. In leaflet directive scope they change, as well as in input fields, but not in the controller. Shouldn't they all have the same value? 
EDIT: it seem it was a problem with batarang plugin, when reading from console values were consistent.

**Comment by tombatossals** [comment]
Closing this. Thanks for updating the issue.
