### ISSUE TITLE
Overlay visibility attribute always false

### ISSUE THREAD

**Issue by bubblepixel** [tombatossals/angular-leaflet-directive#408]
I have two overlays which are both groups. I set both to have no visibility initially:

overlays: {
                    jobs: {
                        name: 'Allocated Jobs',
                        type: 'group',
                        visible: false
                    },
                    completed: {
                        name: 'Completed Jobs',
                        type: 'group',
                        visible: false
                    },

I can select either of them in the Layer Controller and they display correctly, however even if the overlay is visible on screen;  $scope.layers.overlays.jobs.visible is always false.

**Comment by antoinegiret** [comment]
This issue seem to be doesn't solved...

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#28

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
