### ISSUE TITLE
get value geojson layer 

### ISSUE THREAD

**Issue by goldalworming** [tombatossals/angular-leaflet-directive#410]
hi, from this example 
http://tombatossals.github.io/angular-leaflet-directive/examples/geojson-layers-example.html

how to get value of each object from geojson property?

**Comment by tombatossals** [comment]
Please take a look at the new nested and non-nested GeoJON. Reopen if needed:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/geojson-non-nested-example
