### ISSUE TITLE
Usage with browserify and NPM?

### ISSUE THREAD

**Issue by wobblydeveloper** [tombatossals/angular-leaflet-directive#412]
I see this is an NPM module. I can't seem to figure out how to include it using browserify. Including it like so after the usual `npm install --save angular-leaflet-directive`....

```
var angular_leaflet_directive = require('angular-leaflet-directive');
```

... fails with...

```
Cannot find module 'angular-leaflet-directive'
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#29

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
