### ISSUE TITLE
Clustering GeoJson Points

### ISSUE THREAD

**Issue by vipervf1** [tombatossals/angular-leaflet-directive#415]
Is there an easy way to use the clustering plugin when using geojson points instead of markers?

**Comment by briankostar** [comment]
this saved me some time! thanks

**Comment by nmccready** [comment]
:+1:

**Comment by nmccready** [comment]
Someone want to work on flushing this out into the geojson directive?

**Comment by briankostar** [comment]
I'm still learning, but I'll take a crack at it this weekend.

**Comment by buunguyen** [comment]
I'm new to this, can anyone show me how to incorporate this code into a page? For example, what directives to use and what scope properties to set? Thank you.

**Comment by mahmoudmy** [comment]
Very useful, thanks!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#30

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
