### ISSUE TITLE
default popupOptions for markers

### ISSUE THREAD

**Issue by boustanihani** [tombatossals/angular-leaflet-directive#416]
Hi, is there a way to set default popupOptions for markers ??
I wasn't able to find any infos about this in the docs...

Something like => ???

```javascript
$scope.defaults = {
        markers: {
            popupOptions: {
                closeButton: false
            }
        }
    };
```

**Comment by tombatossals** [comment]
Hi, this was not implemented, but it could be, please send a PR if you think it must be added to the actual code.
