### ISSUE TITLE
Listen markercluster click event

### ISSUE THREAD

**Issue by markitosgv** [tombatossals/angular-leaflet-directive#421]
Its possible to acces clusterclick, without overlays??

My initial map:

```javascript

//map initial
    angular.extend($scope, {
        center: {
            autoDiscover: true
        },
        defaults: {
            scrollWheelZoom: false
        },
        layers: {
            baselayers: {
                osm: {
                    name: 'OpenStreetMap',
                    url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    type: 'xyz'
                }
            }
        }
    });

```

And then i call my own service to fecth markers data:

```javascript
    //on load map
    $scope.$on('leafletDirectiveMap.load', function(event){

       api.getMarkersByProximity(function(data){
             $scope.markers.push(data);
        });

       });

```

Now i have a map with markers and clusters.
With this event i can listen when a marker is clicked, but not a cluster:

```javascript
$scope.$on("leafletDirectiveMarkersClick", function(event, args){
        console.log($scope.markers[args]);
    });
```

Its possible to do?? thanks
I don´t want when cluster marker is clicked to expand child markers... i want to get child markers data to do another thing.

On official Leaflet.markercluster docs says:

```javascript
markers.on('clusterclick', function (a) {
    console.log('cluster ' + a.layer.getAllChildMarkers().length);
});
```
Is any event directive to listen?

**Comment by joeljeske** [comment]
@markitosgv, have you found a way to listen for cluster events?

**Comment by rasmi** [comment]
Has anyone found any ways to listen besides dipping down into pure Leaflet (like @joeljeske did in #648)?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#31

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
