### ISSUE TITLE
Popups for geoJSON

### ISSUE THREAD

**Issue by g8d3** [tombatossals/angular-leaflet-directive#423]
How could I do this?

What I tried is to convert the geoJSON data into markers with messages:

``` javascript
    var geoJsonToMarkers = function(geoJson){

      var features = geoJson.features;
      var out      = {};
      for(key in features){
        var feature = features[key];
        out[feature.properties.id] = {
                lat: feature.geometry.coordinates[1],
                lng: feature.geometry.coordinates[0],
                message: feature.properties.description,
                focus: true,
                draggable: false
            };
      }
      // out = {marker1: {...}, marker2: {...}}
      return out;
    };
```

And then use the markers after the AJAX call that makes the geoJSON  data available:

```
    // here I have more config options

    $http.get(myURL).success(function(data, status) {

        var markers = geoJsonToMarkers(data);
        $scope.markers = markers;
   });

```

I get an error saying that some keys in $scope are not defined, so I suppose this problem is due to the time AJAX request takes to define keys in $scope.

And the HTML I am using is just `<leaftet markers="markers"....>` mapping each config option and the markers attribute.

When I use [geoJSON](http://jsbin.com/fohiki/2/edit) only, it's rendering correctly the markers.

**Comment by GianlucaBobbio** [comment]
Great work juanpastas!
