### ISSUE TITLE
Can't access leafletData.getMap() without a delay if <leaflet> has an ID

### ISSUE THREAD

**Issue by mfc-julius** [tombatossals/angular-leaflet-directive#424]
If ID is set on a `<leaflet>` and `leafletData.getMap()` is evaluated straight away on the controller, a promise is not working at all without displaying any error. Although it runs fine if evaluating later, e.g. inside some function.

**Comment by 1337** [comment]
:+1:

**Comment by nmccready** [comment]
If it has an id then you are supposed to pass the id in to the function getMap.

`<leaflet id="someid"></leaflet>`

```
leafletData.getMap('someid')
```

**Comment by nmccready** [comment]
Otherwise it uses a default of main. Which is not the map you want as it does not exist. Not sure if this is documented but I just read the code.

**Comment by nmccready** [comment]
BTW this goes for any use in leafletData, where getWhatever('someId'). The syntatic sugar of having empty arguments only applies if there is not identifier on the leaflet dom element.

**Comment by jackvial** [comment]
Thanks @nmccready
