### ISSUE TITLE
Custom Tile Layers (the come back)

### ISSUE THREAD

**Issue by romgar** [tombatossals/angular-leaflet-directive#425]
Hi,

I was seeking for adding custom layer to leaflet, and have seen closed #12 issue.
There are lot of layers defined in leafletLayerHelpers, but I don't see how to use a newly created layer type (which extends TileLayer).
Somebody has some explanations to help me, do I have missed something ?

**Comment by tombatossals** [comment]
Hi @romgar, you better take a look at the source code, there are a lot of implemented custom layers, it's really easy to add a new one.

Closing this as old, please reopen if needed.
