### ISSUE TITLE
How to style markers that come from geojson?

### ISSUE THREAD

**Issue by kpennell** [tombatossals/angular-leaflet-directive#428]
I'm adapting the examples that Tombatossals was kind enough to make.  I'm using markers from geojson to make my map points.  I can't figure out how to change the default colors or styles of the markers.

I'm using the setup he had:

`angular.extend($scope, {
            geojson: {
                data: data,
                style: style
            }
        });
`

style is something like:
`
function style(feature) {
                return {
                    color: 'red'
                };
            }
`
It doesn't seem to do anything.

The examples seem setup more for the polygons and other Leaflet layer types. How does one access the marker/icon styles while using the geojson way of getting the data in?

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
