### ISSUE TITLE
Marker Cluster group

### ISSUE THREAD

**Issue by jacobharasimo** [tombatossals/angular-leaflet-directive#432]
I find my items are clustering to much... i know in the original marker cluster for leaflet you can set the cluster 'radius'

is there a way to set that using this wrapper?

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
