### ISSUE TITLE
Markers disappears after changing template

### ISSUE THREAD

**Issue by ws-anashkin** [tombatossals/angular-leaflet-directive#434]
Very critical for me issue!

When i load template first time, map and markers are showing correctly, but then after changing template and going back, all markers disappears!!

Found this is Google - http://jsfiddle.net/kb4df/
Click "Go to map", then "Go back". You will see, that markers will disappear.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
