### ISSUE TITLE
Getting markerData (model) on marker events

### ISSUE THREAD

**Issue by Marsup** [tombatossals/angular-leaflet-directive#435]
Bottom line: (modified by nmccready)

The events across the api should be consistent and always pass a leafletObject and model (markerData, geometry (feature), and or whatever else). Currently markers must be looked up by the markerName which can be an array index and or object field. However this is not really helpful in the case there is any marker nesting. Also why force the user of the api to look up the markerData when it is already there to pass on.

The problem code is here: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletEvents.js#L45-L78

Original Issue:

> Hello,

> Getting the `name` (which seems to be the index) of the marker on marker click event is not very useful, > since when you remove that marker from the array, all the names will be messed up.
> Would it be possible to pass the `markerData` on https://github.com/tombatossals/angular-leaflet-directive/blob/dab1c1e1b7d0ea3c8fab6d5d94096e5ed4d6aaed/src/services/leafletEvents.js#L34
> Unless I've missed a way to get the original data somehow, the name doesn't seem very reliable.

**Comment by nmccready** [comment]
@Marsup I plan on modifying this behavior to return the actual markerData (model).  Also the event should also include the layerName. The layerName should be included now as a way to get back to the actual markers location in the structure quickly if it is nested.

IE: if `<leaflet markers-nested='true' />` the following is now (master) possible :

```
markers :{
    cars: {
        1: { lat:_lng:_}
        2: ...
   }
}
```

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
