### ISSUE TITLE
unique marker.

### ISSUE THREAD

**Issue by jacobharasimo** [tombatossals/angular-leaflet-directive#441]
markers need a unique id. Currently save the title property on MarkerOptions there is no way to detect a unique maker, and title is not always unique enough. Easy solution is line 2372 of angular-leaflet-directive.js needs to have id: isDefined(markerData.id) ? markerData.id : '', so that we can pass in a unique id for the markers to allow us to easily find a specific maker easily.

```javascript
var clusters = $scope.markerClusterGrp.getLayers();
for (var i in clusters) {
    if (mapMarker.id == clusters[i].options.id) {
        marker = clusters[i];
        break;
    }
}
```

anyone else know a better way to do this? the use case is that i have a list of items beside the map and when i hover on a list item i want the map marker to 'grow' or unspider.

**Comment by tombatossals** [comment]
The @NOtherDev response is perfect. Closing this.
