### ISSUE TITLE
Multiple directives [leaflet, markers] asking for...

### ISSUE THREAD

**Issue by bonbonpiment** [tombatossals/angular-leaflet-directive#443]
Hi 

Found your script ! Damned, pretty awesome ! Nice work dude ! 
don't know if i can call it an issue but something drive me nuts till early this day : i'm trying to hack my code in multiples ways but no success  !
Notice : I'm using the ionic framework...
I m trying the simple example you provide 
my html : 
< leaflet center="london" markers="markers" ></ leaflet >

my JS (controller):
app.controller('Cartographie',function($scope){
    angular.extend($scope, {
         london: {
            lat: 49.118225,
            lng: 6.174605,
            zoom: 16
        }, 
        markers: {
            main_marker: {
                lat: 49.118225,
				lng: 6.174605,
                focus: true,
                //message: "Hey, drag me if you want",
                title: "Marker",
                draggable: true,
             }
        }
    });
})

and nothing works , still got this error message : 
Error: [$compile:multidir] Multiple directives [leaflet, markers] asking for new/isolated scope 

If i just delete the markers attribute , that's ok but definitely useless for my purpose ... 

Any idea of what 's going wrong ? I appreciate your help , i'm lost in space ;)

**Comment by deliriousrhino** [comment]
I believe there is an issue with Ionic. 
I have created a simple code pen here http://codepen.io/anon/pen/vOYKXM

**Comment by tombatossals** [comment]
Closing this as old. Please reopen if needed.

**Comment by bonbonpiment** [comment]
Sorry i simply forgot to close !! Thanks ! Have a nice day


2015-06-23 14:21 GMT+02:00 David Rubert <notifications@github.com>:
