### ISSUE TITLE
Update marker using input with ng-model

### ISSUE THREAD

**Issue by jopereyral** [tombatossals/angular-leaflet-directive#446]
Hi!

I'm triying to modify an input  and give this error: 

"There are problems with lat-lng data, please verify your marker model".

There is a jsfiddle to explain the problem http://jsfiddle.net/4PhzC/119/

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by jopereyral** [comment]
Thanks, no problem.
