### ISSUE TITLE
Marker with message changes position on click in Clusters

### ISSUE THREAD

**Issue by ws-fegon** [tombatossals/angular-leaflet-directive#450]
Hi

Marker with message changes its position on click in Clusters while it is spiderfied
Check out this:
http://jsfiddle.net/kb4df/4/

Try to click on markers

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
