### ISSUE TITLE
Focus/blur events on markers

### ISSUE THREAD

**Issue by vincentbernat** [tombatossals/angular-leaflet-directive#459]
Hi!

I am trying to do something like this:

```js
events: {
        markers: {
          enable: ['blur', 'focus'],
          logic: 'emit'
        }
},
```

```js
$scope.$on('leafletDirectiveMarker.focus', function(event, args) {
  console.log('hello');
});
$scope.$on('leafletDirectiveMarker.blur', function(event, args) {
  console.log('bye');
});
```

But this doesn't seem to work. If I replace `focus` by `click`, I get the event triggered as expected. However, I am setting the `focus` property of the marker in some other part of the code and want the event to be triggered at this moment.

**Comment by tombatossals** [comment]
Sorry, that funcionality is not provided at the markers events, at this moment.
