### ISSUE TITLE
How to fire on click event

### ISSUE THREAD

**Issue by sposnjak** [tombatossals/angular-leaflet-directive#461]
I use angular-leaflet-directive to display a map populated with multiple markers and I have a table from where the user can choose one of the markers. I know how to center (to show on map) the one marker which was clicked in the table, but I would like to open the popup message of the marker. I know that I need to fire an 'click' event on the map - i can find multiple leafleatjs examples, but I do not understand how to do it in a "angular way". Any advice would be deeply appreciated. Thank you.

**Comment by tombatossals** [comment]
Please take a look at the new examples showcase, there are some example that could help you:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html
