### ISSUE TITLE
How to draw circles in 0.7.8v?

### ISSUE THREAD

**Issue by dpocheketa** [tombatossals/angular-leaflet-directive#465]
Hi guys, I spend a lot of time to understand, what is wrong, but I`m not resolve my problem yet. I need to draw some areas(circles) on a map.
<pre>
<code>
$scope.targets = [];
        var point = {
                lat: 51.50,
                lng: -0.082
            };
        var mapDefaults = {
            weight: 2,
            colorOutside: '#ff612f',
            type: 'circle',
            color: '#72C456'
        };
        var map = {
                center: {
                    lat: 48,
                    lng: 4,
                    zoom: 6
                },
                markers: {
                },
                paths: {
                    p1: {
                        weight: mapDefaults.weight,
                        color: mapDefaults.color,
                        latlngs: point,
                        radius: 1000000,
                        type: mapDefaults.type
                    },
                },
                defaults: {
                    scrollWheelZoom: false
                }
            };
        angular.extend($scope, map);
        resourcesService
            .Map.list().then(function(data){

                $scope.targets = data;
console.log(data);
                var bounds = [];

                _.each($scope.targets, function(target){
                    var curTarget = {
                        'lat': target.lat,
                        'lng': target.lng
                    };
                    var curBound = [target.lat, target.lng];
                    bounds.push(curBound);
                    var curPath = {
                        weight: mapDefaults.weight,
                        color: target.inside ? mapDefaults.color : mapDefaults.colorOutside,
                        type: mapDefaults.type,
                        latlngs: curTarget,
                        radius: target.radius
                    };
                    map.markers[target.name] = curTarget;
                    map.paths[target.name] = curPath;
                });
                leafletData.getMap().then(function(map){
                    map.fitBounds(bounds);
                });
        });
</code>
</pre>

it works in 0.7.6 but in 0.7.8. is not. Now only p1 are drawn (static data). Dinamic data from resourseService are not drawen. In console.log all is ok.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
