### ISSUE TITLE
pointToLayer + layerGroup

### ISSUE THREAD

**Issue by ljelinek** [tombatossals/angular-leaflet-directive#467]
One undocumented yet powerful possible feature is to return layerGroup (group of markers) instead of just one marker while calling pointToLayer during processing of GeoJSON.

There are some specific scenarios in which this can be very handy, f.e. labeling in the middle of circle marker (using f.e.: divIcon) without usage special plugins, etc..

But angular leaflet directive fails in this case if onEachFeature is not defined.

It is because line 447 in last tag. Calling layer.on({}) is not possible on layerGroup.

**Comment by tombatossals** [comment]
Seems an interesting suggestion, but please send a PR
