### ISSUE TITLE
unshift marker array - moving wrong marker

### ISSUE THREAD

**Issue by robotnic** [tombatossals/angular-leaflet-directive#468]
Hi all

I'm using markers in an array (not object) like this:

$scope.markers=[
    {lat:10,lng:10,draggable:true},
    {lat:20,lng:20,draggable:true}
]

That works fine

If I add a new marker at first position like this

$scope.markers.unshift({lat:50,lng:50,draggable:true})

The marker appears but if I move it, the marker at 10,10 is also moved.

---------------------

Possible fix, delete all markers if array length is changed - but it's not very good fix:

  leafletScope.$watch('markers', function (newMarkers,oldMarkers) {
                var refreshAllMarkers=false;
                  if(angular.isArray(newMarkers) && angular.isArray(oldMarkers)){
                        if(newMarkers.length != oldMarkers.length){
                            var refreshAllMarkers=true;
                        }
                  }
                // Delete markers from the array
                for (var name in leafletMarkers) {
                  if (!isDefined(newMarkers) || !isDefined(newMarkers[name]) || refreshAllMarkers) {
                    deleteMarker(leafletMarkers[name], map, layers);
                    delete leafletMarkers[name];
                  }
                }

**Comment by tombatossals** [comment]
Hi guys, there has been a lot of code changes at the markers functionality in the last weeks, please reopen this if needed
