### ISSUE TITLE
How can one access the rest of the Leaflet API that is not implemented in the directive?

### ISSUE THREAD

**Issue by gausie** [tombatossals/angular-leaflet-directive#47]
I try to use `angular.element("div#map").scope().leaflet;` from the Controller but due to the page loading order, the scope does not exist when I try to do this. I am fairly new to Angular, so may be missing something basic.

**Comment by esetnik** [comment]
FYI the link provided by @houqp is broken. Do we have another example?

**Comment by tulsidaskhatri** [comment]
@houqp link is broken. @esetnik did you find any solution?

**Comment by tulsidaskhatri** [comment]
@esetnik if you are still looking for solution:
http://stackoverflow.com/questions/29993114/how-to-call-fitbounds-on-leaflet-angular
this works.

**Comment by williamknn** [comment]
@tulsidaskhatri this solution doesn't work if you're using AwesomeMarkers. I tried and got this error:
![screenshot from 2016-06-08 11 56 32](https://cloud.githubusercontent.com/assets/3988151/15898867/3aa48336-2d70-11e6-9856-1f4be9e80272.png)
