### ISSUE TITLE
Filter in markers throw exception

### ISSUE THREAD

**Issue by A13xs** [tombatossals/angular-leaflet-directive#475]
Hi,

If you add a filter in markers work, but throw exception in console.

Example with two markers and a filter to show just one: http://jsfiddle.net/3zvthhbb/1/

The same issue with paths.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
