### ISSUE TITLE
Allow hiding of layer control.

### ISSUE THREAD

**Issue by johntyree** [tombatossals/angular-leaflet-directive#477]
It should be possible to avoid showing the layer control on the map, particularly when there's only one baselayer being used.

In my case, I can't just use tiles and markers because I am using marker cluster, which forces me to use `layers` which forces me to include a `baselayer` which forces the layer control to be visible, even though there's nothing useful a user could do with it.

**Comment by sureshvsvb** [comment]
@tombatossals - Hi I am using your directive in one application. I struck up on one issue. Here is the scenario.

I am getting geoJson data with set of points, polygons. Each feature will have information specific to that point. For example if a feature is completed or not. I would like to implement this as overlays on the map. So when user clicks "Complete" on the layer control, it should show the completed geoJson data/vectors.

I dont have URL to pass to the layer/layer control for individual cases geoJson data. Entire geoJson data is available once the page is loaded. How could i implement this scenario ?

<leaflet width="100%" height="500" center="center" layers="layers" geojson="geojson" bounds="bounds">
    <layercontrol order="normal"></layercontrol>
</leaflet>

**Comment by tombatossals** [comment]
Hi, I'm closing the original issue because it's already implemented, take a look at this example which shows how to hide a layer from the baselayers. If no visible layers, the layers controls will not be shown:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/hide-baselayer-on-selector-example

Code example:

```
                layers: {
                    baselayers: {
                      mapbox_light: {
                          name: 'Mapbox Light',
                          url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
                          type: 'xyz',
                          layerOptions: {
                              apikey: 'pk.eyJ1IjoiYnVmYW51dm9scyIsImEiOiJLSURpX0pnIn0.2_9NrLz1U9bpwMQBhVk97Q',
                              mapid: 'bufanuvols.lia22g09',
                              "showOnSelector": false
                          }
                      }
                    }
                }
```

Please reopen again or with a new issue if there's something missing.

**Comment by luxigo** [comment]
layerOptions.showOnSelector does not work for hiding overlays,  use layerParams.showOnSelector instead.
