### ISSUE TITLE
Marker Name when Passed as Array

### ISSUE THREAD

**Issue by justinwp** [tombatossals/angular-leaflet-directive#478]
I'm running into an issue with removing and deleting markers when passing them as an array of objects instead of an object with each marker as a key. In this situation, the index of the array is used as the name, but when I delete some of the markers, there is a mismatch of names. 

For example, I have 10000 markers in an array. I remove all but 10. Unfortunately those 10 still show the original 10 markers on the map with names 0...9. I am using crossfilter.js with anywhere from 5000 to 30000 markers if that makes any difference.

I will put up a minimum example.

**Comment by mguentner** [comment]
Have you found a solution for that issue?

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by chagen19** [comment]
If anyone is still looking for a solution to this, I resolved the issue by adding the following to the **_updateMarker** function.

``` javascript
if (oldMarkerData.title !== markerData.title) {
     if (marker._icon) {
          marker._icon.title = markerData.title;
      }
      marker.options.title = markerData.title;
}
```
