### ISSUE TITLE
Force layer to bottom after selecting in layer control

### ISSUE THREAD

**Issue by cscrum** [tombatossals/angular-leaflet-directive#481]
Is there a way to always keep a layer on the bottom? For instance, if I add a layer dynamically, it gets added to the layer control and I can make it the bottom layer when I add it, but if I turn it off in layer control and back on, it is now the top layer. I want it to always be on bottom.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
