### ISSUE TITLE
Slow performance when calling getMap().then(function(){}); but not getMap();

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#483]
I'm tracking down a performance critter. I use `$interval` to constantly center the map. Seems that `getMap().then(function() {})` causes a performance hit while `getMap()` does not. The code is below. 

```
function centerOnTrip(data, mapName) {
      if(!data) {
        return;
      };
      leafletData.getMap(mapName).then(function doCenter(map) {
        console.timeEnd('get map');
      });
}
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#167

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
