### ISSUE TITLE
Draw example does not appear to work with Leaflet 0.7.3

### ISSUE THREAD

**Issue by christophermiles** [tombatossals/angular-leaflet-directive#484]
Following the example code at https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/control-draw-example.html does not work if referencing the latest version of the Leaflet library.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
