### ISSUE TITLE
Using radio button to select draw tool

### ISSUE THREAD

**Issue by rowanwins** [tombatossals/angular-leaflet-directive#485]
Hi there,

Im a newb to angular so I'm hoping someone can help me.

I've got my mapController working with leaflet.draw and have managed to turn off certain drawing tools eg (circle)
```
angular.extend($scope, {
	    controls: {
	        draw: {position: 'topright',draw:{
	            	circle:false,
	            	rectangle:false
	            }}
	        }
	    });  
```

What Im wondering is though is how I can use a radio button to turn the chosen draw tool to 'true'. So by default they should all be turned to false, but if someone choses the polygon radio button the leaflet.draw polygon tool becomes available to them.

At the moment I have created my radio buttons in the same controller however Im not sure how to best pass the form data to make it do what I want...

Any tips would be appreciated.
Thanks,
Rowan

**Comment by tombatossals** [comment]
Sorry, you have to look at the leaflet.draw project for this. Closing it
