### ISSUE TITLE
Why does leafletData.getMap return a promise?

### ISSUE THREAD

**Issue by bjorm** [tombatossals/angular-leaflet-directive#486]
As far as I can see it only looks up the given mapId (if any) in the maps object and if no mapId is given but there are multiple maps, it throws an error. If mapId is not present in the maps object, it creates some sort of dummy object containing an unresolved $q.defer.

I fail to see why this needs to be modeled with a promise as there is no asynchronous process involved.

What I would expect:
1) if getMap is called without args, then it should return the 'main' map or throw an error if it does not exist
2) if getMap is called with a mapId, it should get the respective map from the maps object or throw an error if it does not exist

**Comment by nmccready** [comment]
Promises are good and there are a million ways to skin a cat. Keep this to one way is probably better for now.
