### ISSUE TITLE
Trigger redraw of map when geojson style changes

### ISSUE THREAD

**Issue by michaelryancaputo** [tombatossals/angular-leaflet-directive#489]
I'm using this directive to show data that is returned from an api. There are a number of possible outputs, and I would like the user to be able to toggle between them, so that when trigger an event, the map would redraw with the same boundaries, however the style of the geojson would change accordingly.

I can't seem to find a way to add a trigger to cause the map to redraw. I see that there is a 'viewreset' event, but I don't know how to trigger that event.

**Comment by alakiikonen** [comment]
I have similar problem. The properties within the features change, and these properties are used to calculate the style for the shape. Now, when the geojson changes, and the properties within its features, the style is not reset.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
