### ISSUE TITLE
Having issue where tiles aren't loaded when used in a bootstrap tab until window is resized/refreshed

### ISSUE THREAD

**Issue by sstorie** [tombatossals/angular-leaflet-directive#49]
I'm relatively new to Angular, and I have the leaflet directive doing what I want except for a small issue. I have a leaflet map embedded in a tab that is created via AnuglarUI's bootstrap module. When my page is first loaded the leaflet map is shown, but doesn't display all the tiles properly (one is sometimes shown but the rest are just gray). The moment the browser window is re-sized or refreshed the map displays everything correctly. Here's a stackoverflow question discussing the exact issue I'm having (along with a jsfiddle that demonstrates it):

http://stackoverflow.com/q/10762984/571237
http://jsfiddle.net/C7Rp8/4/

In doing some research it seems that adding a call to invalidateSize() on the map object can trick leaflet into redrawing itself, but I'm not sure how to update this directive to use that technique. I've tried embedding some js code into the directive itself to call invalidateSize() but I'm not having any luck on getting it to work.

Has anyone else ran into this?

**Comment by rozzwalla** [comment]
I cannot seem to make this work I already used invalidateSize() when transferring to my tab using the same code in 
https://github.com/tombatossals/angular-leaflet-directive/issues/168#issuecomment-29127691

**Comment by p0wdrdotcom** [comment]
in your directive do this...   

$timeout(function () {
                  map.invalidateSize();
                });

$timeout without a delay seems to invoke the callback after the directive is rendered.

**Comment by mjoyce91** [comment]
`invalidateSize()` works well for me, just need to re-run my mapBounds function at the same time. Adding on from the demo code:

```
$scope.$watch("mapView", function(value) {
        console.log($scope.mapView);
        if (value === true) {
            leafletData.getMap().then(function(map) {
              $timeout(function() {
                map.invalidateSize();
                //create bounds
                leafletData.getMap().then(function (map) {
                    if ($scope.mapBounds.length < 1){$scope.mapBounds.push([$scope.location.coords.longitude,$scope.location.coords.latitude])}
                    var bbox = L.latLngBounds($scope.mapBounds);
                    $scope.maxBounds.southWest = bbox.getSouthWest();
                    $scope.maxBounds.northEast = bbox.getNorthEast();
                    map.fitBounds(bbox);
                });
              }, 300);
            });
        }
    });
```
