### ISSUE TITLE
Allow options to be passed to MarkerClusterGroup when not using overlays

### ISSUE THREAD

**Issue by cleversprocket** [tombatossals/angular-leaflet-directive#491]
Problem: when using marker clustering there is no way to pass options to the markerGroup if the markerGroup isn't being used as a Overlay Layer. When defining the Marker it is expecting the group property to be a string. 

Hack: I've hacked a solution to allow the group property on the marker to also be an Obj: 
```javascript
{
    name: 'groupName',
    options: {
        // L.MarkerClusterGroup options go here.
    {
}
```

Here's the entire solution in leafletMarkersHelpers factory:
```javascript
addMarkerToGroup: function(marker, groupName, groupOptions, map) {
            if (!isString(groupName)) {
                if (Object.prototype.toString.call(groupName) === "[object Object]") {
                    if (groupName.hasOwnProperty('name')) {
                        groupOptions = (groupName.options) ? groupName.options : null;
                        groupName = groupName.name;
                    }
                    else {
                        $log.error('[AngularJS - Leaflet] The marker group you have specified is invalid.');
                        return;
                    }
                }
                else {
                    $log.error('[AngularJS - Leaflet] The marker group you have specified is invalid.');
                    return;
                }
            }
    ...
```

Does this look like a good solution?

**Comment by tombatossals** [comment]
Hi @cleversprocket, I'm sorry for the late response.

Your solution looks good, but I can't imagine the case of use you are trying to solve. Lot of things have changed in the markers and layers funcitonality, so please, if you are interested in adding this to the main code, take a look at the actual source code and generate a Pull Request, it will be revised and accepted shortly.

Thanks, I'm closing this issue.
