### ISSUE TITLE
getting distance between 2 markers

### ISSUE THREAD

**Issue by Danny-weebo** [tombatossals/angular-leaflet-directive#503]
Hey, I'd like to get the distance between 2 marks but not as a direct line, more as a real path like it goes in this plugin -
https://github.com/perliedman/leaflet-routing-machine

I didn't find anything about using this plugin in this directive, 
if someone can guide how to make it done, it would be very appreciated :)

thanks!

**Comment by fbruno93** [comment]
Hey ! 
I'im same issue ! 
I want to use this plugin in a cordova project and as like you i've any idea to use it.

Please Help :) 

Thx!

**Comment by tombatossals** [comment]
Hi guys, very interesting leaflet plugin. I have added it to the directive, it will be in trunk shortly if approved by the rest of the developers.

This would be an example of how to use it:
http://tombatossals.github.io/angular-leaflet-directive/examples/0405-controls-routing-machine-example.html

**Comment by jasmo2** [comment]
Hello, the example does not show the routing plugin behaviour

**Comment by jasmo2** [comment]
the StandAlone version show the next error:
[AngularJS - Leaflet]  [Controls]  Invalid control type: routingMachine.

**Comment by julioleitao** [comment]
I have the same issue. The example show the error:
[AngularJS - Leaflet]  [Controls]  Invalid control type: routingMachine.

**Comment by nmccready** [comment]
@elesdoar ? or anyone this is probably a simple fix.

**Comment by nmccready** [comment]
More likely the example itself.

**Comment by elesdoar** [comment]
Routing machine feature is not merged in master branch, therefore, it is not in the current build for our examples.

https://github.com/tombatossals/angular-leaflet-directive/compare/routing-machine-feature-503

**Comment by doubl3p** [comment]
@elesdoar @tombatossals is it now merged in master?
