### ISSUE TITLE
'Error: L is not defined' ?   

### ISSUE THREAD

**Issue by markmcdonald51** [tombatossals/angular-leaflet-directive#504]
Hi,

New to leaflet and this module. Just cloned it and put it into my app andi am getting this in the console:

Error: L is not defined
_getDefaults@http://localhost/assets/angular-leaflet-directive/dist/angular-leaflet-directive.js?body=1:1667:13
.setDefaults@http://localhost/assets/angular-leaflet-directive/dist/angular-leaflet-directive.js?body=1:1740:31

This is the latest version. Something i am doing incorrectly?

Thanks for the cool mod!

cheers. --mark

**Comment by tombatossals** [comment]
You must load leaflet library first. Closing.
