### ISSUE TITLE
Cannot read property 'getMap' of undefined

### ISSUE THREAD

**Issue by aaonline** [tombatossals/angular-leaflet-directive#508]
Using Fiddle JS

Code:-

//--- CODE --------------------------
(function (angular) {
    // Create module
    var myApp = angular.module('myApp', ['leaflet-directive']);

    // Controller which counts changes to its "name" member    
    myApp.controller('TestCtrl', ['$scope', 'leafletData', '$log', function TestCtrl($scope, leafletData, $log) {
        $scope.name = 'MapApp';
        $log.info("Start...");
	    leafletData.getMap().then(function(map) {
		var southWest = L.latLng(-90, -180),
	    northEast = L.latLng(90, 180),
	    bounds = L.latLngBounds(southWest, northEast);
		mapObj.setMaxBounds(bounds);
		mapObj.options.maxZoom = 19;
		mapObj.options.minZoom = 1;
		$scope.map=map;
		$scope.featureGroup = L.featureGroup().addTo($scope.map);
	});        
    }]);

})(angular);

// ---SPECS-------------------------

describe('TestCtrl', function () {
        var scope,leafletData, compile;
        beforeEach(function () {
            module('myApp');
        });

        beforeEach(inject(function ($rootScope, $controller,$compile,leafletData) {
            scope = $rootScope.$new();
            compile = $compile
            controller = $controller('TestCtrl', {
                '$scope': scope,
                'leafletData' : leafletData
            });
        }));
      
       it("Map Function", function() {
               //expect(undefined).not.toBeNull();
				var element = angular.element('<leaflet center="center" controls="mapControls"></leaflet>');
				element = compile(element)(scope);
				//expect(leafletData).toBeUndefined();
                
				leafletData.getMap().then(function(map) {
					scope.map = map;
				});
				$rootScope.$digest();
				expect(scope.map.getZoom()).toEqual(1);
				expect(scope.map.getCenter().lat).toEqual(0);
				expect(scope.map.getCenter().lng).toEqual(0);
               
			});
        
    });

// --- Runner -------------------------
(function () {
    var jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;

    var htmlReporter = new jasmine.HtmlReporter();

    jasmineEnv.addReporter(htmlReporter);

    jasmineEnv.specFilter = function (spec) {
        return htmlReporter.specFilter(spec);
    };

    var currentWindowOnload = window.onload;

    window.onload = function () {
        if (currentWindowOnload) {
            currentWindowOnload();
        }
        execJasmine();
    };

    function execJasmine() {
        jasmineEnv.execute();
    }

})();

I get error as:-

TestCtrl Map Function.
TypeError: Cannot read property 'getMap' of undefined
TypeError: Cannot read property 'getMap' of undefined
    at null.<anonymous> (http://fiddle.jshell.net/_display/:111:16)
    at jasmine.Block.execute (http://jasmine.github.io/1.3/lib/jasmine.js:1064:17)
    at jasmine.Queue.next_ (http://jasmine.github.io/1.3/lib/jasmine.js:2096:31)
    at http://jasmine.github.io/1.3/lib/jasmine.js:2086:18

**Comment by tombatossals** [comment]
Closing this as old. Please reopen if you think it's necessary.

**Comment by vviikk** [comment]
This was probably due to the map not being initialized on time.

I used this to make sure that map was initialized. Perhaps the promise being returned from getMap() might need to be tweaked.

``` javascript

  $scope.$on('leafletDirectiveMap.load', (event) => {
    $scope.isLoaded = true;
  });

$scope.fitBounds = function(bounds) {
    if (!$scope.isLoaded) return;  // this line prevents the 'map' object from being defined.
    leafletData.getMap()
      .then(function(map) {
        map.fitBounds(bounds, {
          maxZoom: 12,
        });

      });
  };
```
