### ISSUE TITLE
How do I use `detectRetina`?

### ISSUE THREAD

**Issue by callmeStriking** [tombatossals/angular-leaflet-directive#509]
https://www.mapbox.com/mapbox.js/api/v1.6.0/retina/ and http://leafletjs.com/2012/07/30/leaflet-0-4-released.html#performance-and-usability-improvements imply that I can pass a `detectRetina` parameter to the tile layer to make it work nicely on Retina devices such as my iPhone 4S.

Is there a way to set this in angular-leaflet-directive?

Currently, it looks like this: ![map is very pixellated, text is smooth](http://res.cloudinary.com/chapp/image/upload/c_limit,h_1024,w_1024/gzwsgut2kgaom9jdh6nc)

**Comment by esetnik** [comment]
+1 I was wondering the same thing.

**Comment by esetnik** [comment]
It looks like this was also asked in #373 which is also open.

**Comment by esetnik** [comment]
I figured it out. You need to use the `detectRetina` option [from leaflet](http://leafletjs.com/reference.html#tilelayer-detectretina). Add it to your `tileLayerOptions` like this:

```
 defaults: {
  tileLayerOptions: {
    detectRetina: true
  }
}
```

**Comment by tombatossals** [comment]
Thanks for the contribution @esetnik, I'm going to close the issue
