### ISSUE TITLE
Add/Remove Layers, Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by wilhelmberg** [tombatossals/angular-leaflet-directive#511]
I get the same error as with this example: [This is a map with dynamic addition and deletion of layers](http://tombatossals.github.io/angular-leaflet-directive/examples/layers-example.html)

![add-remove-layers](https://cloud.githubusercontent.com/assets/4549888/4832363/60a421e4-5f9b-11e4-8181-a605a0fe57f4.png)

I tried to mimic [`This is a map with dynamic addition and deletion of Overlays`](http://tombatossals.github.io/angular-leaflet-directive/examples/layer-control-example.html) and [`Dynamic addition/removal of layers`](http://tombatossals.github.io/angular-leaflet-directive/examples/layers-add-remove.html), which work, but was unable to find the difference.

Any ideas?

**Comment by carrbrpoa** [comment]
Hey @BergWerkGIS, I'm having the same problem but didn't get your solution. I have a custom controller with injected ```$scope```, as always, in which I "append" the layers options. How could it be wrong?
