### ISSUE TITLE
Popup wrong in markers filtered

### ISSUE THREAD

**Issue by A13xs** [tombatossals/angular-leaflet-directive#512]
If you have filtered results and you change the items displayed, the popup messages shown on the popup are incorrect.

To reproduce the error go to this example http://jsfiddle.net/d8gouyjd/2/ and follow next steps:
1)uncheck up
2)unckeck middle
3)unckeck down
4)check down
5)check middle
6)check up

If you click on up marker, show popup down.

I think issues #276, #478 and #468 are related.

**Comment by F1LT3R** [comment]
:+1: 

Is there any cleaner work-around?

**Comment by F1LT3R** [comment]
This is probably a terrible way to do things, (and after digging into the dist/angular-leatlet-directive.js and realizing I was not going to get to the bottom of things in a couple of hours), but here's what I'm doing to work around the problem right now:
 
```javascript
var app = angular.module('myApp', ['ui.highlight', 'leaflet-directive']);  

function MyController($scope, $http, leafletData) {
  leafletData.getMap().then(function(map) {

    leafletData.getMarkers().then(function(markers){      
      for (var index in markers) {
        var marker = markers[index];

        (function(index){
          marker._leaflet_events.click[0].action = function(e){
            
            var theRealMarker = $scope.markers[index];
              
            L.popup()
              .setLatLng([ theRealMarker.lat, theRealMarker.lng ])
              .setContent('My index is: ' + index)
              .openOn(map)
              ;   
          }
        })(index);

      }
    });
  
  });
});
```

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by mhiemstrapodiumtv** [comment]
I am using v0.10.0 and this bug has not been resolved. 

I store my markers in an array and each marker has a property id which is the database id. 

I have registered the marker onclick using this code:
`$scope.$on('leafletDirectiveMarker.map.click', function (event, data)`
When I click on a marker I get the right data (The correct marker id)

When I add a marker using javascript and then reload the data (I reload the markers array) the leafletDirectiveMarker.map.click returns the wrond data. The id is completly wrong!
