### ISSUE TITLE
Panning map to new center when current location received asynchronously

### ISSUE THREAD

**Issue by skibohemen** [tombatossals/angular-leaflet-directive#517]
This may be slightly related to the scenario in #318, but it is the center, not a GeoJSON object I want to update. I try to get the user's current location by using the HTML5 API for this. This works by using a service called from the controller and with a callback back to the controller for the map view. Problem is of course that this happens asynchronously to the initial display of the view with the Leaflet map. So in this initial display  I provide a default center on the $scope, and update the center when the location comes in. But the map does not update. The leaflet directive is used like this in the view
````html
<leaflet center="here" layers="layers" height="500"></leaflet>
````
where **$scope.here** is the lat/lng object that is set to a default initial value and updated when the current position comes in. Controller code looks like this:
````javascript
app.controller("MainController", [ '$scope', 'myLocation', function($scope,myLocation) {
  myLocation.getLoc(function (pos){
    $scope.here = pos; console.log ($scope.here.lat + "," + $scope.here.lng); // reports correct pos
  });
  angular.extend($scope, {
      mapshow: true,
      here: {lat: 60.01, lng:10.62, zoom:16},
        layers: {
            baselayers: {
  .....
````

Would I need to do **$scope.$watch** "manually" ? But in that case, the listener function would need to talk to leaflet, and there is nothing exposed to do this?
I am fairly new to Angular, and may have designed my app in a wrong way. I know Leaflet well though, and was happy to find this directive to work with Leaflet in Angular. Any help would be appreciated.

**Comment by nmccready** [comment]
This is old and probably outdated. Closing unless someone chimes in.
