### ISSUE TITLE
Two controllers listening to the same map click event

### ISSUE THREAD

**Issue by gkatsanos** [tombatossals/angular-leaflet-directive#521]
I have two controllers, let's assume one is a child of the other, and I'm trying to find an efficient to get the lat and lng in both controllers when a click event is triggered. The only way that worked so far is using the $rootScope but in my understanding that can cause performance problems and so on.. I attempted $emit but without access. 
I think that's not really a specific question for this directive but I was wondering if there's any example related to that. it's rather advanced I guess.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
