### ISSUE TITLE
How can I load KML files?

### ISSUE THREAD

**Issue by sosoriov** [tombatossals/angular-leaflet-directive#522]
How can I add KML layers to my maps, or how can I use omnivore plugin 

https://github.com/mapbox/leaflet-omnivore to get the leaflet standard format

**Comment by yukk1** [comment]
leafletData.getMap().then(function(map) {
           var kmlLayer = omnivore.kml("myFile.kml")
                .addTo(map);
          });

You have to include leafletData in the controller.
This is a working demo.
http://plnkr.co/edit/cx2pY4p6rVE2K2aUKf84?p=info

**Comment by tombatossals** [comment]
Really interesting @yukk1 , we could think about integrating omnivore as a kind of layer of angular-leaflet, so it would be easy to load a KML or TopoJSON file.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
