### ISSUE TITLE
Leaflet.draw controls don't disable

### ISSUE THREAD

**Issue by nolandubeau** [tombatossals/angular-leaflet-directive#523]
Hello,

I tried customizing the controls config (as per the docs here: https://github.com/Leaflet/Leaflet.draw#drawoptions)  to try disabling some of the drawing options:

angular.extend($scope, {
        center: {
            lat: 43.6464666,
            lng: -79.3999922,
            zoom: 18
        },
        controls: {
            draw: {
                polyline: false,
                polygon: {
                    allowIntersection: false, // Restricts shapes to simple polygons
                    drawError: {
                        color: '#e1e100', // Color the shape will turn when intersects
                        message: '<strong>Oh snap!<strong> you can\'t draw that!' // Message that will show when intersect
                    },
                    shapeOptions: {
                        color: '#bada55'
                    }
                },
                rectangle: false
            }
        }
   });

No errors are thrown, however all drawing options are still active.  

Thank you.

**Comment by sofivsofi** [comment]
@nolandubeau I know it's been a long time and I don't know if you managed to over come this issue but what seemed to work for me is this: 

angular.extend($scope, {
	                controls: {
	                    draw: {
	                    	draw: {
	                    	             polyline:false,
                                             circle:false,
                                             rectangle:false
                                          },
	                    },
	                }
                  });

The fact that I am using draw twice is not an error.
Hope this helps someone!

**Comment by rpoisel** [comment]
@sofivsofi wrote
> Hope this helps someone!

Yes, it did. :-) Thanks a lot!

**Comment by sofivsofi** [comment]
@rpoisel I'm glad it helped you!
