### ISSUE TITLE
Overlays not update from inside event

### ISSUE THREAD

**Issue by kozer** [tombatossals/angular-leaflet-directive#529]
I want to drag a marker and to readd a layer (i pass data on server so i want to reload it if marker pos change), but nothing happens. I tried inside draggend marker callback to:
make layers visible= false and true again.
reassign the layer object.

In both cases it fails. I can remove the layer and add it through leaflet data getMap() with remove and add these overlays, but its not the proper way i guess... 

Any suggestions?

**Comment by tombatossals** [comment]
Please, we need an example, try to reproduce the problem in a jsfiddle an post it here.

Anyway, there has been a lot of changes in the markers functionality later, so you problem could be fixed with the current trunk.

I'm closing it, please reopen if needed.
