### ISSUE TITLE
Marker Cluster Slow

### ISSUE THREAD

**Issue by scottlepp** [tombatossals/angular-leaflet-directive#530]
Marker clustering is pretty slow.  The example for 10000 marker cluster is slow to pan and zoom.  This doesn't seem to be an issue when using just leaflet and the marker cluster plugin.  Even with only 1000 items performance degrades pretty bad.

**Comment by tombatossals** [comment]
Hi, the markers performance has been improved lastly. Take a look at this example:
http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/clustering-10000-markers-example

Please reopen if needed
