### ISSUE TITLE
Load distinct array markers for diferent maps.

### ISSUE THREAD

**Issue by mvsouza** [tombatossals/angular-leaflet-directive#532]
I was having problems to open a new map with different markers on the same page, after hard word I solved it locally. 
Today I was willing to share, so I downloaded the code and added some tests to see if the bug was still happening. 
Because the tests have failed, I added my fixes. 
How should I proceed to contribute?

**Comment by tombatossals** [comment]
Sorry for the late response @mvsouza, you can contribute to the project with Pull Requests, they are revised and added to the main project.

Lot of things changed with the markers funcionality. I'm closing this, please reopen if needed
