### ISSUE TITLE
Pass parameters in overlay url (eg xyz layer)

### ISSUE THREAD

**Issue by kozer** [tombatossals/angular-leaflet-directive#534]
i want to do something like this

          greecepng: {
            name: 'utfGreecePng',
            type: 'xyz',
            url: '/api/maps/{z}/{x}/{y}.png?param1={param1}&param2={param2}&param3={param3}',
            visible: true,
            layerOptions: {
              param1: '',
              param2: '',
              param3: '',
            }
          },

In leaflet documentation it says that this is possible , but whatever i do i cant accomplish that.
I tried on moveend event of map to :
remove the layer from map to force directive to readdit
update the layer object with the parameters.
but whatever i do parameters dont pass in the query in my server.
Is there any solution to that?

**Comment by tombatossals** [comment]
Please, we need an example documenting the issue:
https://github.com/tombatossals/angular-leaflet-directive/wiki/MCVE

I'm closing this as it's old and lot of things changed lately. Please reopen if needed
