### ISSUE TITLE
Bug in custom marker icon example

### ISSUE THREAD

**Issue by wylieconlon** [tombatossals/angular-leaflet-directive#538]
I discovered a bug in this example: http://tombatossals.github.io/angular-leaflet-directive/#!/examples/customized-markers

The steps to reproduce are:

1. Click 'leaf_icon'
2. Click 'default_icon'
3. The default marker is now stretched vertically, like this: 
![screenshot 2014-11-18 13 04 56](https://cloud.githubusercontent.com/assets/666475/5093187/a3d5e884-6f23-11e4-8b84-12968980770c.png)

I couldn't find any open issues or pull requests about this, sorry if this is known/a duplicate

**Comment by seadour** [comment]
Hi @wylieconlon,

I'm unable to reproduce this. Since this is an older issue, can you check the web site again to see if it's still happening? Also, which browser(s) does it occur in?

**Comment by wylieconlon** [comment]
This appears to have been fixed.

**Comment by seadour** [comment]
Thanks for checking.
