### ISSUE TITLE
CRS Simple?

### ISSUE THREAD

**Issue by agostinocinelli** [tombatossals/angular-leaflet-directive#542]
Hi,
i'm having a trouble with CRS Simple.
i changed the CRS as suggested in issue 
https://github.com/tombatossals/angular-leaflet-directive/issues/401
and the tiles load correctly, but as i try to pan/zoom the map, the tiles go away :(

http://jsfiddle.net/agostino_cinelli/ah041yxv/ (wait a few seconds for the server to wake up)
Am I missing something?

Thanks in advance.

**Comment by octavioamu** [comment]
Same problem here, could you fix it @agostinocinelli ?

**Comment by agostinocinelli** [comment]
Hi @octavioamu 
sorry,I've been very busy lately :/
i really think we should move to @tombatossals 's angular-openlayers-directive. i'm trying it right now and it seems to manage CRS simple.
Unless you found a solution with leaflet :)

**Comment by agostinocinelli** [comment]
I have good news: i removed the 
map._initialTopLeftPoint = map._getNewTopLeftPoint(map.getCenter());
line... and it seems to work now.
Check http://jsfiddle.net/agostino_cinelli/g3hh08xh/
Did you found another solution @octavioamu ?

**Comment by octavioamu** [comment]
No, I just jumped out of the ready directives and make my own adaptation of leaflet.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
