### ISSUE TITLE
Problems changing markers.

### ISSUE THREAD

**Issue by jonny75904** [tombatossals/angular-leaflet-directive#543]
I am having problems getting the map to respond to programmatic changes, and there just is not a lot of info available.  

Whereas most of the examples use UI elements, I am having no luck programmatically changing marker icons etc.I am using the draw tools successfully.  When I place a marker, I want all markers to turn pink.  

I can draw a marker.  I can turn it pink.  I can add it to the map.
When I go to edit markers by iterating leafletData.getMarkers(), the changes do not reflect on the map.

    leafletData.getMap().then(function(map) {
      var drawnItems = $scope.controls.draw.edit.featureGroup;
     
      map.on('draw:created', function(e) {
        if (e.layerType != 'marker') return;
        var marker = e.layer;
        
        //THIS WORKS for the marker drawn
        marker.options.icon = pinkIcon;
        drawnItems.addLayer(marker);
        
        //Now I'm going to try to set all other marker icons to pink icons
        leafletData.getMarkers().then(function(markers) {
          angular.forEach(markers, function(m, i) {
            
            //Neither of these work, but it worked for the drawn marker.  I also tried with/without adding to drawnItems

            m.icon = pinkIcon;
            drawnItems.addLayer(m);
            m.options.icon = pinkIcon;
            drawnItems.addLayer(m);

          });
        });
      });
    });

//Pink Icon stuff 
var metroMarkerOptions = {
  icon: blueIcon,
  iconAnchor: [25, 50],
  iconSize: [50, 50],
  popupAnchor: [0, -50],
  riseOnHover: true,
  blueIconURL: 'https://cdn1.iconfinder.com/data/icons/Map-Markers-Icons-Demo-PNG/256/Map-Marker-Marker-Outside-Azure.png',
  pinkIconURL: 'https://cdn1.iconfinder.com/data/icons/Map-Markers-Icons-Demo-PNG/256/Map-Marker-Marker-Outside-Pink.png',
  greenIconURL: 'https://cdn2.iconfinder.com/data/icons/IconsLandVistaMapMarkersIconsDemo/128/MapMarker_Marker_Outside_Chartreuse.png',
  grayBlueIconURL: 'https://cdn2.iconfinder.com/data/icons/IconsLandVistaMapMarkersIconsDemo/128/MapMarker_Marker_Inside_Azure.png',
  grayGreenIconURL: 'https://cdn2.iconfinder.com/data/icons/IconsLandVistaMapMarkersIconsDemo/128/MapMarker_Marker_Inside_Chartreuse.png',
  grayPinkIconURL: 'https://cdn1.iconfinder.com/data/icons/Map-Markers-Icons-Demo-PNG/128/Map-Marker-Marker-Inside-Pink.png'
};
var pinkIcon = L.icon({

  iconUrl: metroMarkerOptions.pinkIconURL,
  iconSize: metroMarkerOptions.iconSize, // size of the icon
  iconAnchor: metroMarkerOptions.iconAnchor, // point of the icon which will correspond to marker's location
  popupAnchor: metroMarkerOptions.popupAnchor // point from which the popup should open relative to the iconAnchor

});

**Comment by seadour** [comment]
Hi @jonny75904, 

Are you still having this problem? I have encountered a similar issue.

Are you getting an error in the browser's console when you try to change the icon? I am getting 'iconUrl not set in options'.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
