### ISSUE TITLE
Accessing prototype functions

### ISSUE THREAD

**Issue by mfc-julius** [tombatossals/angular-leaflet-directive#545]
Is there a way of accessing a prototype function of Leaflet? E.g. I would like to add padding on fitBounds and panTo as a standard padding (so that plugins using those functions would get padding also).

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
