### ISSUE TITLE
Google maps and Overlays out of sync while zooming

### ISSUE THREAD

**Issue by robotnic** [tombatossals/angular-leaflet-directive#552]
When the map is zoomed first the Overlay animation appears and after that the google maps animation starts. 

Openlayers has a nicer zoom animation I think - no idea how they do it.
http://openlayers.org/en/v3.0.0/examples/google-map.html

But it's also not in sync.

**Comment by dud3** [comment]
Same here.

**Comment by dud3** [comment]
@tombatossals Any new over here ?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#168

**Comment by nmccready** [comment]
@dud3 is this still a problem see https://github.com/angular-ui/ui-leaflet/issues/168 if it is. If I don't here back soon on this I will close it there.

**Comment by dud3** [comment]
@nmccready I was checking for an example at: http://tombatossals.github.io/angular-leaflet-directive/
but it seems to be something wrong with the page: <a href="https://docs.angularjs.org/error/$injector/modulerr?p0=mainPage&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.4.7%2F$injector%2Fmodulerr%3Fp0%3Dleaflet-directive%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.4.7%252F%2524injector%252Fmodulerr%253Fp0%253DnemLogging%2526p1%253DError%25253A%252520%25255B%252524injector%25253Anomod%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.4.7%25252F%252524injector%25252Fnomod%25253Fp0%25253DnemLogging%25250A%252520%252520%252520%252520at%252520Error%252520(native)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A6%25253A416%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A24%25253A186%25250A%252520%252520%252520%252520at%252520a%252520(http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A23%25253A252)%25250A%252520%252520%252520%252520at%252520P.bootstrap%252520(http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A23%25253A495)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A37%25253A497%25250A%252520%252520%252520%252520at%252520m%252520(http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A7%25253A322)%25250A%252520%252520%252520%252520at%252520h%252520(http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A37%25253A275)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A37%25253A444%25250A%252520%252520%252520%252520at%252520m%252520(http%25253A%25252F%25252Ftombatossals.github.io%25252Fangular-leaflet-directive%25252Fbower_components%25252Fangular%25252Fangular.min.js%25253A7%25253A322)%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A6%253A416%250A%2520%2520%2520%2520at%2520http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A38%253A184%250A%2520%2520%2520%2520at%2520m%2520(http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A7%253A322)%250A%2520%2520%2520%2520at%2520h%2520(http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A37%253A275)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A37%253A444%250A%2520%2520%2520%2520at%2520m%2520(http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A7%253A322)%250A%2520%2520%2520%2520at%2520h%2520(http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A37%253A275)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A37%253A444%250A%2520%2520%2520%2520at%2520m%2520(http%253A%252F%252Ftombatossals.github.io%252Fangular-leaflet-directive%252Fbower_components%252Fangular%252Fangular.min.js%253A7%253A322)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:6:416%0A%20%20%20%20at%20http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:38:184%0A%20%20%20%20at%20m%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:7:322)%0A%20%20%20%20at%20h%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:37:275)%0A%20%20%20%20at%20http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:37:444%0A%20%20%20%20at%20m%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:7:322)%0A%20%20%20%20at%20h%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:37:275)%0A%20%20%20%20at%20fb%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:41:35)%0A%20%20%20%20at%20d%20(http:%2F%2Ftombatossals.github.io%2Fangular-leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js:19:463">Error message</a>.

**Comment by nmccready** [comment]
Again I am not fixing angular-leaflet-directive any more. go here http://angular-ui.github.io/ui-leaflet/#!/

**Comment by dud3** [comment]
Oops, sorry, google suggested me: http://tombatossals.github.io/angular-leaflet-directive/

**Comment by dud3** [comment]
Alright I'll continue from: https://github.com/angular-ui/ui-leaflet/issues/168

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
