### ISSUE TITLE
Path popup message change not reflected

### ISSUE THREAD

**Issue by charlesbedrosian** [tombatossals/angular-leaflet-directive#554]
When adding adding a Path to the map, then alter changing the value of the message, it does not reflect in the map. Other options for the Path do show, such as color changes.

The reason is that it binds only when creating the Path on the map and even if a change is detected via the watch, the Path is not *new* so it does not re-bind the popup.

This is a problem that should be addressed.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
