### ISSUE TITLE
Google maps styling

### ISSUE THREAD

**Issue by robotnic** [tombatossals/angular-leaflet-directive#555]
It is possible to style the google tiles
http://gmaps-samples-v3.googlecode.com/svn/trunk/styledmaps/wizard/index.html

I have a ready to use style in json format, but I don't know how to use it with leaflet-directive.

I tried this:

....
    "googleRoadmap": {
        "name": "Google Streets",
        "layerType": "ROADMAP",
        "type": "google",
        "layerOptions": {
            "styles": [{
                    "featureType": "poi",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
...

But no success.

What's the correct syntax?

**Comment by durga-telsiz** [comment]
Robotnic, I am having the same issue. I added my styles array like you mentioned above layerOptions:{mapOptions:{styles:[{featureType:'administrative', stylers:[{visibility:'off'}]},{}]}} but I dont see any impact on the map. Could you clarify what all you had to change to get this working?

**Comment by robotnic** [comment]
I don't see the bug. Do yo have a complete example?

**Comment by gtramontina** [comment]
@durga-telsiz, I believe @robotnic 's example has a typo: isn't `styles` supposed to be `stylers` (notice the `r`)?

By the way, where did you find the correct syntax, @robotnic ? It is very annoying to not have (that I know of) a centralized place for which options we can provide and how.

**Comment by surbhiverma88** [comment]
This is not working for me, can someone help?
I tried the following piece of code.
layerOptions: {
                        mapOptions: {
                            styles: [
                            { featureType: "poi",
                            elementType: "labels",
                            stylers: [{ visibility: 'off' }]
                            }
                            , {}
                            ]
                        }
                    }

**Comment by shahinlotfi** [comment]
This works for me. The trick is to get the hierarchy right.

```googleRoadmap: {
                        name: 'Google Streets',
                        layerType: 'ROADMAP',
                        type: 'google',
                        layerOptions: {
                            mapOptions: {
                                styles: [
                                    {
                                        featureType: "administrative",
                                        elementType: "labels",
                                        stylers: [
                                        { visibility: "off" }
                                        ]
                                    },{
                                        featureType: "poi",
                                        elementType: "labels",
                                        stylers: [
                                        { visibility: "off" }
                                        ]
                                    },{
                                        featureType: "water",
                                        elementType: "labels",
                                        stylers: [
                                        { visibility: "off" }
                                        ]
                                    },{
                                        featureType: "road",
                                        elementType: "labels",
                                        stylers: [
                                        { visibility: "off" }
                                        ]
                                    }
                                ]
                            }
                        }
                    }
                }
