### ISSUE TITLE
Redraw map after width change by div

### ISSUE THREAD

**Issue by JoergPf** [tombatossals/angular-leaflet-directive#556]
Hi, I have a map in a bootstrap div:
```
<div class="col-xs-10 col-xs-offset-1" id="kartencol">
          <leaflet defaults="defaults" center="center" paths="meinePfade" bounds="bounds"     decorations="decorations" width="100%" height="480px" markers="markers"></leaflet>
</div>
```
Then I use jquery and css animation to change the width of the col div and put a form next to it.

    $('#kartencol').toggleClass('col-xs-10 col-xs-7')
    $('#formcol').toggleClass('col-xs-0 col-xs-3')

It works great, but when I now do something with the map like setting bounds, angular still thinks I have the old map width. 

How do I do a redraw or anything else with the map, to let angular know about the new width?

Best
Joerg

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#32

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
