### ISSUE TITLE
Add the ability to change the watch options on paths

### ISSUE THREAD

**Issue by cgat** [tombatossals/angular-leaflet-directive#559]
I'm building a map that displays realtime path data to the user using polling. On each poll interval, I update the paths property with a new updated path object, which contains a latlng array that can amass up to 4000 coordinates.

With the way the paths directive has been implemented, there is a 'deep watch' (ie scope.watch("", fn, true) on both the paths scope variable, but also on each individual path object. With big paths, thats some head dirty checking overhead on each digest loop.

By changing the paths $watch to a $watchCollection and removing the 'deep watch' true parameter from the individual path watches, I achieved huge performance gains.

So my questions are:
1) Should this be the default behaviour? The downside is that this would be a breaking change.
2) If not default, how would you like the api for modifying the watch options for paths to be implemented?

I can make a pull request, but I thought I would get your input before moving ahead.

**Comment by tombatossals** [comment]
Hi @cgat, sorry I didn't read your issue before. You're totatlly right "$watchCollections" is the way to go.

I'm going to apply the same solution to the markers watchers.

Thanks so much!

**Comment by cgat** [comment]
Thanks for the response @tombatossals. Were these changes supposed to be made in the commit you made for issue #590? It looks like only paths were changed to used "$watchCollections".

I should point out that if you do use this solution for marker watchers as well, it will introduce breaking changes. At the moment, if you hold a reference to a marker that is watched, you can change the internal state of the marker and the map marker will get updated (a good example of this is change the 'focus' property to true). If we change to "$watchCollection", you'd have to replace the marker with an updated version of the object to get it to work. Personally, I think this is the better solution given the performance improvements, however, I could see this upsetting people.

I was thinking that it might be nice to have one `watcherOptions` directive, which allows the users to configure how each element type is watched. For example, the input to the directive could be something like:

    {
      markers: "collection", //--> use $watchCollections
      paths: true, //--> use $watch(...., true),
      
      .... any other map element
    }

This would be opposed to having a watch directive for each element type (watch-markers, watch-paths, etc).

Thoughts?

**Comment by tombatossals** [comment]
Hi @cgat, thanks for your ideas. I finally didn't change to "watchCollection" on markers, but changhed the "geojson" object to it. I have to take a look closely on changing the markers because what you say, it could break old code.

I'm thinking about reworking this directive when leaflet-0.8 goes out and solve some of the functionality that could be improved, for example listen to only the markers you are interested, not everyone.

I would like to research the possibility to take out the marker as a dom tag, so it could be customized easily, and not to have big objects linked to the main "leaflet" tag. I have coded something similar in the "angular-openlayers-directive" and it works pretty well. Take a the code of this example:

http://tombatossals.github.io/angular-openlayers-directive/#/markers/marker-no-javascript

What do you think about it?

**Comment by cgat** [comment]
Yes! I think that would be a great solution. This will give lots of control over performance to the developer using angular-leaflet and make your code base easier to reason with. How far off do you think this reason would be? If I can help out (update examples, etc), let me know.

**Comment by tombatossals** [comment]
I'm doing this in my spare time, but I'm searching for some time and rework all the code. All the experience of these years could make this directive evolve.

It would be great if you could help, you know the code, you have good ideas, and you're great programming angular.

I have almost finished coding the angular-openlayers-directive, so maybe in a few weeks I could start refactoring this library. If you want to get involved just tell me and we could open a trello board for this new version.

**Comment by cgat** [comment]
I realize you do this on your spare time, so forgive me if I came across a bit too eager in my previous message. 

I'm definitely interested in helping out. Contact me in a few weeks and we'll get the ball rolling.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#33

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
