### ISSUE TITLE
Changing marker opacity does change on the map

### ISSUE THREAD

**Issue by JLLeitschuh** [tombatossals/angular-leaflet-directive#563]
If you give a marker an opacity level and then attempt to change it using the scope it does not update to the map.

I added the following code [here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/dist/angular-leaflet-directive.js#L3377) which solved the problem.
```
if (isNumber(markerData.opacity) && isNumber(oldMarkerData.opacity) && markerData.opacity !== oldMarkerData.opacity) {
    // There was a different opacity so we update it
    marker.setOpacity(markerData.opacity);
}
```

**Comment by davinov** [comment]
:+1:

**Comment by tombatossals** [comment]
Hi @JLLeitschuh, I have added your code and a new example that you can see here:

http://tombatossals.github.io/angular-leaflet-directive/examples/markers-change-opacity-example.html
