### ISSUE TITLE
custom layers

### ISSUE THREAD

**Issue by robotnic** [tombatossals/angular-leaflet-directive#564]
I wan't to use 2 special layers

https://github.com/glenrobertson/leaflet-tilelayer-geojson
and
https://github.com/afsuarez/mapsforge-cordova-plugin

I have seen "custom" layer in the source code, but I don't know how to use that.

**Comment by porjo** [comment]
Have you looked at the examples here: http://tombatossals.github.io/angular-leaflet-directive

**Comment by ageblade** [comment]
Hi, this is the way you can use custom layers (This example use leaflet IIP plugin)
```
$scope.layers.overlays["iip"] = {
    name: 'iip',
    type: 'custom',
    visible: true,
    layer: L.tileLayer.iip(url, options)
};
```
Just initialize your custom layer into the layer property and set a name, visible and type = 'custom'.

Good luck,

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#34

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
