### ISSUE TITLE
change map tileLayer

### ISSUE THREAD

**Issue by JoergPf** [tombatossals/angular-leaflet-directive#566]
Hi,

how do I change the tileLayer after the first init?

I tried 

    $scope.defaults.tileLayer = "http://tile.stamen.com/#toner/{z}/{x}/{y}.png";

and

    L.tileLayer('http://tile.stamen.com/#toner/{z}/{x}/{y}.png');

and also both with a 

    $scope.$apply(function(){
                   $scope.defaults.tileLayer = "http://tile.stamen.com/#toner/{z}/{x}/{y}.png";
                    //L.tileLayer('http://tile.stamen.com/#toner/{z}/{x}/{y}.png');
                });

How does this work?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#35

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
