### ISSUE TITLE
Bug in 'center' directive causes center to lose binding with $scope.center on 'moveend'

### ISSUE THREAD

**Issue by pieterjandesmedt** [tombatossals/angular-leaflet-directive#569]
Sometimes when scrolling the map, the center directive seems to lose its binding.
In `angular-leaflet-directive.js` around line 315:

```javascript
scope.center = {
    lat: map.getCenter().lat,
    lng: map.getCenter().lng,
    zoom: map.getZoom(),
    autoDiscover: false
};

```
should be
```javascript
angular.extend(scope.center,{
   lat: map.getCenter().lat,
   lng: map.getCenter().lng,
   zoom: map.getZoom(),
   autoDiscover: false
});

```

**Comment by MartinWeb** [comment]
This piece of code should be used every time scope.center is set.
I had the same issue for setting center in a promise. The binding was lost and use angular.extend in the angular leaflet file fix the issue.

**Comment by nmccready** [comment]
I think this is resolved. Please reply so I can close this.

**Comment by pieterjandesmedt** [comment]
It is :-)
