### ISSUE TITLE
Make compilation of markers & labels optional

### ISSUE THREAD

**Issue by r0b-** [tombatossals/angular-leaflet-directive#577]
It would be nice to make the compilation call optional (option-flag?).
In my usecase I want/need to use some custom compilation and with current behaviour each marker/label directive is compiled twice and things get totally messed up...

Additionally if autopan is enabled and the compiled directive changes the popup's height, the pan animation is no longer correct....

For the popup I also had the problem, that the compilation (=manageOpenPopup()) was never called on first open...

Thanks!

**Comment by davidovich** [comment]
hi @r0b- and @tombatossals,

I have something cooking. 

I have added two attributes to the markerData object:

markerData:
   getMessageScope: function () {}
   compileMessage: boolean

which will allow:
1) setting scope on which the message should be compiled.
2) compile or not the message

I still need to write tests, documentation and make the PR.

Will post back when it is ready, probably tomorrow.

**Comment by r0b-** [comment]
Cool - keep up the good work!
But what about the labels? Is it possible to have some similar options for that?

Thanks!

**Comment by davidovich** [comment]
@r0b- Since the labels are just an extension, the compileMessage flag will be taken into account also. In other words, it's an all or nothing for labels and popups.
