### ISSUE TITLE
static labels not working with leaflet labels and markercluster

### ISSUE THREAD

**Issue by muuuub** [tombatossals/angular-leaflet-directive#581]
Static labels won't show up in angular-leaflet-directive using markercluster.

Here is my marker:

    m1: {
        lat: 51.5,
        lng: 0,
        focus: true,
        draggable: false,
        group: "my_cluster_group",
        label: {
            message: "Hi there",
            options: {
                noHide: true
            }
        }
    }

If `noHide: false` then the label will show up if you over over the marker, but it won't be a static label.

There was an issue filed on the leaflet.label github related to this:
https://github.com/Leaflet/Leaflet.label/issues/35

However the issue was marked as fixed (for desktop), so I think this problem might be something to do with angular-leaflet-directive.

I'm using:

leaflet.label 0.2.1
markercluster 0.4.0
leaflet 0.7.3
angular-leaflet-directive 0.7.9

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#36

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
