### ISSUE TITLE
Extending markers

### ISSUE THREAD

**Issue by rtp-calpoly** [tombatossals/angular-leaflet-directive#583]
I am currently using both angular-leaflet-directive and some "fancy" markers called MovingMarkers that you can find in the following repository:

    https://github.com/ewoken/Leaflet.MovingMarker

Right now, I think that angular-leaflet has no support for them (please correct me if I am wrong); so I was thinking on trying to extend angular-leaflet so that I can handle them as a regular marker and not apart. Could somebody help me with the following basic questions?

1. Is there any guide/example that I can use as a base for extending angular-leaflet in order to support this type of markers?
2. MovingMarker has not been registered in Bower yet, so I was wondering if doing that first would be appropriate for integrating them better later in angular-leaflet.

Thanks in advance for the help.

**Comment by jar04h** [comment]
Hi ya'll. What is the status on this? I saw a commit to a branch named movingmarkers (afce4c5) but nowhere could I find the documentation on how to use the MovingMarker plugin with the ng-leaflet directive.

Sincerely,

**Comment by rtp-calpoly** [comment]
Hi all,

I actually stopped working on this issue since I found it a bit complicated for the amount of time that I can potentially spend on it.

Best, Ricardo.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#37

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
