### ISSUE TITLE
Paths data problem with layers

### ISSUE THREAD

**Issue by ValentinH** [tombatossals/angular-leaflet-directive#584]
I have noticed a behaviour that seems to be a bug when using path along with layers. However, I'm not sure if it is a problem on leaflet side or on this directive side.

When displaying paths in a group layer, and modifying the paths data, if I hide and show again the layer, the displayed paths are incorrect.

Here is a fiddle: http://jsfiddle.net/7au1sy91/.

To reproduce:
- Click the "Change Paths" button (it replaces the black path by a yellow one)
- Hide the "Test" layer and show it again (both the yellow and the black paths are displayed instead of only the yellow one).

**Comment by AleRob90** [comment]
Hello.
I have a problem with layer too.
When i click on a path i want to change layer of that path. I use leafletDirectivePath.click and a function looking like this
function(e, args){
path = $scope.paths[args.pathName];
path.layer = 'Other layer';
}
this is not working at all. Also path.clickable = true/false not working.

Working: 
path.width = n;
path.fillOacity = n;
path.AnyOtherStyleOption = n;

I want this to work for leaflet draw. I click on a path. That path will be hidden and a new path for draw will gonna rise. If i console.log(path) after i change layer it says it's 'Other layer', but is not affecting my map.

**Comment by ValentinH** [comment]
Please provide a fiddle showing your problem. And this is an issue tracker so could you post this message on stackoverflow instead?
