### ISSUE TITLE
How to override directive and service?

### ISSUE THREAD

**Issue by samcfc** [tombatossals/angular-leaflet-directive#586]
Hi there not a bug but a concern that I got.

I can't reach to override layers directive and leafletLayerHelpers service.

I have been trying for days and angular still complainning.

 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module leaflet-directive due to:
Error: [$injector:pget] Provider 'leafletLayerHelpers' must define $get factory method.

Does some one have a jsfiddle with surch a usecase? 
Decorators are the good way to go to achieve this type of overidding righrt??

Thanks for your contribution, 
I am right now stuck with custom code in those 2 which prevent automatic bower update :-/.

**Comment by tombatossals** [comment]
Sorry I don't understand why you are overriding layers directive adn leafletLayerHelpers, seems an angular related problem.

Please reopen with a jsfiddle example with the error if you think this needs to be revised.
