### ISSUE TITLE
watch Path function performance issues

### ISSUE THREAD

**Issue by skoslitz** [tombatossals/angular-leaflet-directive#590]
I am currently using angular-leaflet-directive for displaying response objects from an api request.
The objects are implemented as leaflet path objects. The map is set up with an Angular watcher on zoom level. For a higher zoom level the maps path object holds round 3000 items (drawn as circles).
Unfortunately the panning performance of the map with 3000 items is unsatisfactory
 (FramesPerSecond: far below 30).
During reading the directives source code I came up against the 'watchPathfunction' on line 1006.
This implements a watcher on all added paths.
As this feature is possibly causing my performance issues, I wanted to ask if it's on your plan to implement a disabling the path watcher feature.

**Comment by tombatossals** [comment]
Hi @skoslitz, it could be implemented, seems interesting.

Could you please provide an example (jsfiddle) where we can see the low performance? It could be a good starting point to start working this feature.

**Comment by skoslitz** [comment]
Here is a simplified [example](http://jsfiddle.net/skoslitz/cwg01qrq/)

At zoom level 3 the map is rendering 125 path objects.
At zoom level 4 the map is rendering 3065 path objects. 
With 3000+ items, map is panning at low frames per second (Hint: Use chrome://flags/ FPS counter)

Pure leaflet (without Angular) is rendering 3000 items properly.

**Comment by cgat** [comment]
I ran into a similar performance issue. The directive does a deep watch on paths, which seems to significantly slow down the app with large path objects. See issue #559 . Here's your fiddle example using my fork: http://jsfiddle.net/quhmbkpv/1/ .

Full disclosure: my fork will break some features in this directive (all test don't pass), so it's probably worth it to do a diff (very few changes) and understand the changes.

**Comment by skoslitz** [comment]
Thanks @cgat!
Based on the fact that this is not a one-time problem it should be worse to implement it officially.
So I'm not closing this issue until @tombatossals expresses something.

**Comment by tombatossals** [comment]
Great example @skoslitz , I'm going to take a loot at it.
Thanks for your reply @cgat, I'm going to take a look at your fork so your changes could be added to the main code.

Would you mind if I add your code example as a performance example in the repository?

**Comment by tombatossals** [comment]
Hi, I have used the @cgat solution, adding the possibility to disable marker watching (bi-directional update), so better performance is accomplished.

```
<leaflet paths="paths" watch-paths="false"><leaflet>
```
I have added your example to the repository @skoslitz , please tell me if this seems good to you.

This is the example with the new code, I think better performance is accomplished:

http://tombatossals.github.io/angular-leaflet-directive/examples/path-3000-items.html

**Comment by skoslitz** [comment]
Thanks a lot @tombatossals for the implementation of this useful feature and @cgat for contributing to this issue.
I am fully supporting the usage of my example.
