### ISSUE TITLE
Pins not showing when map is re-instantiated

### ISSUE THREAD

**Issue by martinchristov** [tombatossals/angular-leaflet-directive#591]
Hey there,
I've got a map with some pins that get populated via xhr when the controller function is executed.
When the view is instantiated the first time everything's great.
However when the user goes to another view and then comes back, the pins are not showing, although the xhr loads the same data correctly. Any following attempt to populate the pins object doesn't give any results.

Any ideas?

**Comment by martinchristov** [comment]
I removed the XHR and the pins are now static. Same result :/

**Comment by martinchristov** [comment]
Detected the source of the issue and found a workaround.
The issue was happening when the pins are under the same group.
Now I am generating a random group name string when the controller is hit and this fixes it.

I would say that this is a bug in the directive so I'm not closing the issue here.

**Comment by tombatossals** [comment]
Yes, it seems a bug. Could you provide a jsfiddle to reproduce the behaviour?

**Comment by Getz85** [comment]
I've exactly the same issue using a map into a bootstrap modal.

Indeed, generating a random group name works fine, thanks @martinchristov .

I've made a fiddle with my particular issue with bootstrap modal: http://jsfiddle.net/ext618u8/9/

**Comment by davidovich** [comment]
I have experienced this also in the markers example. 

Some preliminary debugging points to watches not being fired. I'm not sure as to why through.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
