### ISSUE TITLE
controls is undefined

### ISSUE THREAD

**Issue by lksv** [tombatossals/angular-leaflet-directive#593]
This is similar issue as #348 (and 449).

When I use production version of code (minimize/uglify), then it stops work with error message:

     Error: controls is undefined .link/<@http://localhost:9000/bower_components/angular-leaflet-directive/dist/angular-leaflet-directive.js:1081:1

In html I use:
       <leaflet id="map"
         controls="controls"
         defaults="defaults"
         geojson="geojson"
         center="center"
         layers="layers"
         markers="markers"
         paths="paths"
         url-hash-center="yes"
         class="sidebar-map">
       </leaflet>
    </div>

The problem is that even if I correctly set `$scope.controls = ..whatevet...` in my controller the `controls` variable is still undefined. I simply put `console.log` to angular-leaflet-directive.js line above. The other setting of leaflet scope is set correctly.

Personally I do not thing that problem is in minification (I use standard yeoman-generator generated grunt file).

**Comment by tombatossals** [comment]
Hi @lksv , I haven't been able to replicate this issue, could you provide a jsffiddle, or a stand-alone example where we can see it?

**Comment by lksv** [comment]
I am going to close this issue. I found this is duplicate of #348. 
Unfortunately the workaround described in #348 do not work for me. The only way (I know) make it working is change the `controls` name directly in source.
