### ISSUE TITLE
Deep watching geojson causes performance issues and circular reference errors

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#595]
Currently the geojson preforms a deep watch, as you can [see here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/geojson.js#L70) by the true value. 

This causes performance issues with large complex objects. 

It causes maximum stack errors on object that have circular references.

Is it possible to remove the deep watch, and still get the desired behavior?

**Comment by tombatossals** [comment]
Yes, you're totally right. I'm going to change the  deep $watch by the $watchCollection shallow watcher.

Thanks for reporting.

**Comment by facultymatt** [comment]
Thanks so much! Any word on a release date for this change?

On Tuesday, January 13, 2015, David Rubert <notifications@github.com> wrote:

> Closed #595
> <https://github.com/tombatossals/angular-leaflet-directive/issues/595>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tombatossals/angular-leaflet-directive/issues/595#event-217928836>
> .
>


-- 
Matt Miller


Web Master
609-335-4417
matt@superpedestrian.com
https://www.superpedestrian.com/
<https://www.google.com/url?q=https%3A%2F%2Fwww.superpedestrian.com%2F&sa=D&sntz=1&usg=AFQjCNHLEDFaMLgggeXL8rh4gGlNfN0WSA>
________________
Superpedestrian Inc.
84 Hamilton St.
Cambridge, MA 02139

*This message is intended only for the addressee named above.  If you are
not the intended recipient of this message, you are hereby notified that
you must not use, disseminate, or copy it in any form or take any action in
reliance upon it.  If you have received this message in error, please
delete it and any copies of it from your email system and reply immediately
to the sender at the address shown above.  This message may contain
confidential and/or proprietary information.  Neither confidentiality, nor
any proprietary rights are intended to be waived or lost by any error in
transmission.*

**Comment by tombatossals** [comment]
I'm merging some pending changes and solving some issues, I suppose we can increment the versión number by the end of the week.
