### ISSUE TITLE
multiple maps with marker groups

### ISSUE THREAD

**Issue by tarqe39** [tombatossals/angular-leaflet-directive#596]
there seems to be a problem with marker groups and multiple maps. the problem is in function:
 ```javascript
addMarkerToGroup: function(marker, groupName, groupOptions, map) 
```

it seems to me that when you switch views leaflet gets destroyed and the marker cluster group is left dangling around

```javascript
groups[groupName] = new L.MarkerClusterGroup(groupOptions);
map.addLayer(groups[groupName]);
```

so if you switch back to the first view, marker get loaded into group that is not attached to map
you should probably also check if map has that layer and reattach it if necessary, or destroy layers on $destroy event

**Comment by tombatossals** [comment]
Hi @tarqe39, you are probably right, could you explain a little more the behaviour? It would be great if you could provide a jsffidle demonstrating it. I have this jsfiddle as a starting point:

**Comment by tarqe39** [comment]
hi, im currently at work so i will try to explain. i can fix up some fiddle as soon as i get home.

so, i am using angular-ui-router to switch between two views. i presume that this is not that important in the story.
i have a view A that has marker groups on a leaflet map, and a view B that has single marker used to set some location.
so if i start at view A, switch to view B and then return to view A - no markers are rendered. my guess is that, when i switch to view B, the A's scope gets destroyed, leaving marker group unattached. switching back to view A finds the marker group, adds the markers into the group but its not attached to the map.
i have quick-fixed it in my map controller in the way that i call ```resetMarkerGroups()``` helper at startup so it clears the list of marker groups before the leaflet directive gets initialized and tries to add markers to the group.

**Comment by tombatossals** [comment]
Closed as old, please reopen if needed
