### ISSUE TITLE
MultiMaps controll error

### ISSUE THREAD

**Issue by starikan** [tombatossals/angular-leaflet-directive#598]
Hi.

http://jsfiddle.net/rm7r1jbz/8/ - When I click on map, then hide the layer with markers.

Error in console: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

If you comment out this line then the error disappears - https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/layers.js#L163

I think this error similar with this issue - https://github.com/Leaflet/Leaflet/issues/2877

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#39

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
