### ISSUE TITLE
Support for passing varibles to Popups if the message is built from template

### ISSUE THREAD

**Issue by TheCodeDestroyer** [tombatossals/angular-leaflet-directive#600]
Hey I've been messing around with templating of the popup message,
and since my case is that I need to dynamically populate markers and the popup message I would really need a solution for it.
I came up with a something and if you think its OK would really appreciate if you could put this in.

So what I have done in the `_manageOpenPopup` function I replaced this code:
```javascript
$compile(popup._contentNode)($rootScope);
````
with:

```javascript
var scope = $rootScope;
if (markerData.popupOptions.scope) {
    scope = $rootScope.$new();
    angular.extend(scope, markerData.popupOptions.scope);
}
            
$compile(popup._contentNode)(scope);
````
And then the usage would be like this:
````javascript
var marker = {
    lat: lat,
    lng: lng,
    message: '<div ng-include="<template url>"></div>',
    popupOptions: {
        scope: {
            variable1: value1,
            variable2: value2
        }
    }
};
````

Do you find this OK?
If you want I can also create a pull request, just wanted to ask before doing it...

**Comment by davidovich** [comment]
Hi @TheCodeDestroyer , 

@tombatossals just merged a PR implementing just this. See the new getMessageScope property of the marker:

https://github.com/tombatossals/angular-leaflet-directive/blob/master/doc/markers-attribute.md#marker-attributes

**Comment by TheCodeDestroyer** [comment]
@davidovich Awesomesauce!

I presume its this  `getMessageScope `, right?

**Comment by TheCodeDestroyer** [comment]
Hey @tombatossals one more question when will you tag this for bower?

**Comment by tombatossals** [comment]
Hi @TheCodeDestroyer, I need some more time to solve some a few issues, but I think by the end of the week we can close a new version on bower.

Cheers

**Comment by Quagh** [comment]
Is this included in 0.7.11 or master? I just can't get this to work, even when using the example code.

```js
$scope.test = 'hello';

getMessageScope: function () { return $scope; },
message: "<p>{{ test }}</p>",
compileMessage: true
```

It doesn't parse angular code.

**Comment by davidovich** [comment]
@Quagh of course you are adding these properties to a marker array or object ?

See the examples page, it does exactly what you want:

http://tombatossals.github.io/angular-leaflet-directive/examples/markers-angular-template-example.html

See the popup with angular interpolated message ? this is exactly your use case.

**Comment by Quagh** [comment]
I just found the culprit. Adding `watch-markers="yes"` to the HTML prevents it from parsing. Any thoughts?

**Comment by davidovich** [comment]
The watch-markers attribute works with true/false. Any other value will disable watching.
Currently, angular compilation relies on activated marker watching. This may change in the future.

**Comment by davidovich** [comment]
@Quagh you can monitor #614, it is a pull request that enables compilation of non-watched markers.

**Comment by Quagh** [comment]
Hm, weird it was using `yes` in my code then.

Anyway, the weirdest thing is happening. I have multiple markers and inside the message there is an `ng-click` that links to a `$scope` method. All is working fine, until I click it more than once. It just stops working after one use. Ditto for the other `ng-click`s inside the message.

Now I think I have found the issue (ng-click calls a scope method that throws an error because it receives `undefined` as parameter), which leads me to my question: what happens when there's an error in the compilation or execution of the message? Does it get silently ignored?

**Comment by Quagh** [comment]
Found it.

Consider the following example: https://tombatossals.github.io/angular-leaflet-directive/examples/markers-angular-template-example.html

Same code, but overriding `$scope.data.markers` by assigning a __new__ object screws it up (I'm just calling `$scope.addMarkers()` for a second time here, nothing more):

```js
var app = angular.module("demoapp", ["leaflet-directive"]);
        
        app.controller('DemoController', ['$scope', '$timeout', function ($scope, $timeout) {
            angular.extend($scope, {
                london: {
                    lat: 51.505,
                    lng: -0.09,
                    zoom: 8
                },
                data: {markers: {}}
            });
            
            $scope.addMarkers = function () {
                $scope.data.markers = {};
                angular.extend($scope.data, {angularInterpolatedMessage: "Angular interpolated message!"});
                angular.extend($scope.data, {
                    markers: {
                        m1: {
                            lat: 51.505,
                            lng: -0.09,
                            compileMessage: false,
                            message: "I'm a static marker"
                        },
                        m3: {
                            lat: 51,
                            lng: -1,
                            getMessageScope: function () {
                                return $scope;
                            },
                            message: "<p>{{data.angularInterpolatedMessage}}</p>",
                            compileMessage: true
                        }
                    }
                });
            };
            
            $scope.removeMarkers = function () {
                $scope.data.markers = {};
            };
            
            $scope.addMarkers();
            
            $timeout(function () {
                
                console.log('timeout!');
                
                
                $scope.addMarkers();
            }, 4000);
            
        }]);
```

Notice how it does work if you put the markers in a predefined variable:

```js
            var mrkrs = {
                m1: {
                    lat: 51.505,
                    lng: -0.09,
                    compileMessage: false,
                    message: "I'm a static marker"
                },
                m3: {
                    lat: 51,
                    lng: -1,
                    getMessageScope: function () {
                        return $scope;
                    },
                    message: "<p>{{data.angularInterpolatedMessage}}</p>",
                    compileMessage: true
                }
            };

            $scope.addMarkers = function () {
                $scope.data.markers = {};
                angular.extend($scope.data, {angularInterpolatedMessage: "Angular interpolated message!"});
                angular.extend($scope.data, {
                    markers: mrkrs
                });
            };
```

**Comment by davidovich** [comment]
@Quagh You should open a formal issue describing the problem, because the current one is closed.

**Comment by Quagh** [comment]
I managed to debug and fix it, but some other glitch appeared so we're trying to smooth that out. Will do once it works or we need help :)

To quickly situate the problem: the directive checks for existing entries, but when passing a completely new object with the same name, the `$watch(marker[name])` stays put on the old object and the new one never gets watched. That means no message compiling, popup triggers, etc.

**Comment by slrubinstein** [comment]
@Quagh hey thanks for detailing all your troubleshooting. I am having the same problem. I have a group of markers with popups and each popup links to a details page. If I hit the back button the markers are re-rendered but the one that was clicked no longer works. I see this issue is closed. Is there a solution or good workaround? Thanks.

**Comment by Quagh** [comment]
I think the key solution —besides fixing it— was to use lodash's or underscore's `_.defer()` and reset the markers before setting yours. Don't know if that would work for your situation, as we needed to convert the markers from our API's JSON format to the directive's.

```javascript
var refreshMap = function () {
    $log.debug('Refreshing map');
    
    // Reset the linked markers
    $scope.markers = {};
    
    // Fix for leaflet bug where assigning a NEW object with the same
    // keys would not render AngularJS code in the popup again
    _.defer(function () {
        
        // Assign your markers here (we just convert them from JSON Data)
        $scope.markers = officesToMarkers($scope.visibleOffices);
        
    });
};
```

**Comment by slrubinstein** [comment]
@Quagh We had something similar but weren't using defer. That seems to have fixed the problem. I appreciate you writing out the code. Thanks again!

**Comment by vksvicky** [comment]
I am having a problem with dynamic message, the problem being I am trying to invoke an AJAX call. So my code looks something like:

```
markers.push({
                                    id: 'abc_' + j,
                                    lat: abcLatLonOptions[j][0],
                                    lng: abcLatLonOptions[j][1],
                                    layer: 'abc',
                                    icon: {
                                        iconUrl: icons['abc'].icon,
                                        iconSize: [16, 16],
                                        popupAnchor: [0, 0],
                                    },
                                    message: complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed)
}
```
And 

```
 function  complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed) {
    var tide_level = 7.5;

    var tideWindowRequest = $.ajax({
                type: "GET",
                async: false,
                url: "https://api.sealevelresearch.com/1/predictions/tide-windows/liverpool-gladstone-dock/?start=" + startTime+ "Z&end=" + eta+ "Z&tide_level=" + tide_level,
                contentType: "application/json; charset=utf-8"
            });

return tideWindowRequest;
    }
```

I have tried to change  message to a function like

```
message: function(){
    complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed);
}
```

I get an error
```
TypeError: Argument 1 of Node.appendChild does not implement interface Node.
```

I have tried to play around without any success, any help would be appreciated. The reason I want it to be called inside a function is because the moment the marker is added to map, the complieAbcMessage function is called if I directly assign to message, which I don't want to do as I have over 1000 markers and that slow's the browser's response.
