### ISSUE TITLE
Failed to load resource (file://...) for map tile on mobile device

### ISSUE THREAD

**Issue by mbmerrill** [tombatossals/angular-leaflet-directive#602]
I'm writing a mobile application using the Ionic framework and Leaflet.

If I use "base" Leaflet, I get my map on both the desktop browser (dev env) and on my mobile device when I deploy to it.

If I use this directive, I get my map on the desktop browser, but when I deploy to my mobile device I get (for example) "Failed to load resource file://a.tile.openstreetmap.org/1/0/0.png"

So it seems to me this indicates that somehow this directive is telling Leaflet to look for a local file instead of grabbing it from the openstreetmap site.

That's a useful feature (and one I will be using eventually), but I need to be able to fetch from the openstreetmap site too!  I tried setting the tiles.url in my angular.extend statement explicitly, which did not change the behavior.

What am I missing?

Thanks for your time.

**Comment by tombatossals** [comment]
Hi @mbmerrill , sorry I haven't used Ionic framework, but I can assure you this problem is not related with this directive, there's no configuration to look for local files.

Seems some problem with Ionic framework, if you post some example (jsfiddle) I can take a look at it.

**Comment by pmusaraj** [comment]
I'm currently using this directive with Ionic, and I haven't run into this issue. The map loads the base layer from the web, same as on a browser, on the mobile device, not from a file:// call. You should try to find out why it's trying to load from a file...

**Comment by bwasnie1** [comment]
@mbmerrill It's because all urls in the directive are called like '//..' without. I mentioned this aswell as I updated the directive to the latest version.

But I don't know yet, why ionic behaves like that.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#40

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by BakhtiyorRuziev** [comment]
What about issue its fixed or no? In my case problem like that. url protocol changed to file:// How I can solve this?

**Comment by ansarikhurshid786** [comment]
I think this is whitelist issue in ionic. By default ionic not allow many thing in app. So check out whitelist.

**Comment by ansarikhurshid786** [comment]
Check this link : http://stackoverflow.com/questions/30124099/ionic-leaflet-cant-get-tiles-404-not-found-from-cache
