### ISSUE TITLE
How to do routing?

### ISSUE THREAD

**Issue by rozzwalla** [tombatossals/angular-leaflet-directive#604]
I tried to check the libraries but not sure If I missed something but how can I do routing using this directive and plot it onto the map?

**Comment by porjo** [comment]
@rozzwalla this lib is only useful for drawing the route. To generate the actual route data, you will need a routing engine. You can use Google's Directions API for this or checkout [ORSM API](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api) which uses Openstreetmap data (this is what I currently use).

**Comment by rozzwalla** [comment]
@porjo yeah made it work using OSRM API had the time today to work on it.

**Comment by marcelobaez** [comment]
@rozzwalla  How do you acomplished that? I can't find any examples. This directive includes leaflet.routing?
