### ISSUE TITLE
When drawing GeoJson layer, the ends connect sometimes. 

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#605]
I have a map with a GeoJson layer using the `geojson` directive. Here is generally what happens: 

- I set `geojson = LineString1`, it draws normally. 
- Then I set `geojson = {}` to "clear" the layer, 
- Then I set `geojson = LineString2`.
- It draws, but the end points of the LineString are connected! 

Any thoughts? Am I not clearing properly?

**Comment by tombatossals** [comment]
Hi @facultymatt, can you provide a jsfiddle showing this behaviour?

**Comment by facultymatt** [comment]
I was not able to successfully isolate this issue in jsFiddle. Here is my attempt: http://jsfiddle.net/mL6s2wdb/3/, but as you see the drawing works fine.

Closing for now - I will reopen if things change.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#41

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
