### ISSUE TITLE
Mapbox Markers

### ISSUE THREAD

**Issue by cyprusglobe** [tombatossals/angular-leaflet-directive#606]
is it possible to use map box markers in here?

**Comment by tombatossals** [comment]
Hi @cyprusglobe, can you provide me a link to the map box markers you are referring to?

**Comment by cyprusglobe** [comment]
here is the link for geojson

https://a.tiles.mapbox.com/v4/cyprusglobe.kfnme1k8/features.json?access_token=pk.eyJ1IjoiY3lwcnVzZ2xvYmUiLCJhIjoiejg3TndqVSJ9.YHXl8rm_IcgqrvJ-b0p8LQ

**Comment by aguilarm** [comment]
@cyprusglobe ever get the markers imported to this?  Pretty sure you can do it by parsing the geojson and adding them as markers using leaflet but if you found a painless way to do it I'm trying to do this as well.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#42

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
