### ISSUE TITLE
Marker not displayed correctly when using empty object as icon: icon: {}

### ISSUE THREAD

**Issue by Jespersm75** [tombatossals/angular-leaflet-directive#607]
Hi

The example below, does not display the marker correctly at start up. The marker also moves when  zooming.

http://tombatossals.github.io/angular-leaflet-directive/examples/markers-update-example.html

Regards Jesper

**Comment by tombatossals** [comment]
You're totally right @Jespersm75,  it seems that having another icons with different sizes breaks the default marker location. I have to take a deeper look at this.

Thanks for reporting

**Comment by tombatossals** [comment]
Finally solved, thanks for reporting @Jespersm75.
