### ISSUE TITLE
Convert marker objet to L.marker

### ISSUE THREAD

**Issue by thco** [tombatossals/angular-leaflet-directive#608]
Hi.

For now, if I don't misunderstanding, angular-leaflet markers attribute is just an array of objects, native objects. But I need to retrieve them back as L.marker, not object. Is that possible (without converting one by one scope objects markers I mean) ?

Here is my javascript & html

```javascript
angular.forEach(stops, function(stop, key) {
  var marker = {
    lat: stop.lat,
    lng: stop.lng,
    message: stop.name,
    label: {
      message: stop.name,
      options: {
        direction: 'auto'
      }
    },
    icon: icon
  };

  // Set the marker ID
  marker.id = stop.id;

  marks.push(marker);
});
```
```html
<leaflet center="center"
         defaults="defaults"
         tiles="tiles"
         markers="marks"></leaflet>
```

Is there a way to call something like map.getMarkers() or else ?

I hope you'll understand what I need ... Thanks !

**Comment by davidovich** [comment]
You can inject the leafletData service and call getMarkers:

leaftletData.getMarkers().then(function() { ...});

see https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletData.js#L49

**Comment by thco** [comment]
Oh, seems what I want !

I'll try that, great thanks.
