### ISSUE TITLE
Memory leaks in leaflet.

### ISSUE THREAD

**Issue by artgryn** [tombatossals/angular-leaflet-directive#611]
Description:
There is a clear memory leak in my Angular app wherever I use this leaflet directive.
Note that the directive works fine, however the memory footprint continues growing as I leave and return to any view using the directive.
http://stackoverflow.com/questions/23144386/angularjs-leaflet-memory-leak

Steps:
1) Go to view with leaflet map.
2) Go to any other view
3) Return to the view with leaflet map.

Result: during rendering view after frizzed for some time.

Related to: 
http://stackoverflow.com/questions/23144386/angularjs-leaflet-memory-leak
https://github.com/tombatossals/angular-leaflet-directive/issues/573#event-209533017

**Comment by nmccready** [comment]
@tombatossals any ideas on this?

**Comment by nmccready** [comment]
This should be read and possibly done.

http://stackoverflow.com/questions/11252780/whats-the-correct-way-to-communicate-between-controllers-in-angularjs

We use the decorator pattern at work to deal with this memory issue in angular for work. I am only bringing this up as it may be related. This is because broadcast and emit are used heavily in this project.

**Comment by epelc** [comment]
+1 This is a major issue with google maps as well.  It was part of the reason why we switched.

**Comment by nmccready** [comment]
Well according to angularjs $onRootScope is no longer needed so memory leaks are else where. So are the leaks here or leaflet itself. If you have any suggestions on where to start looking.. that would help a ton.

**Comment by ValentinH** [comment]
I have noticed that this code creates a leak, even if there is no map on my view:
```js
leafletData.getMap().then(function(map) {
    map.invalidateSize()
});
```

If I comment it, I don't have leak anymore.

Moreover, I tried to display the simplest map possible:
```html
<leaflet id="test"></leaflet>
```
and my application is still leaking. If I remove this tag completely, the leak is gone.

**Comment by nmccready** [comment]
So that code is in your controller, but how many times were you calling it to prove that it is the leak? leafletData itself is used similarly in most of the directives but I guess the leak could be there.

**Comment by ValentinH** [comment]
I just submit a PR that might fixes some problems. All the problems that I mentioned above are fixed with it.

**Comment by nmccready** [comment]
Yes commented on it.

**Comment by nmccready** [comment]
There is definitely many map.on event listeners that are never cleaned up. I will dig into these.

**Comment by ValentinH** [comment]
I think `map.on` listeners don't need to be cleaned as they are attached to the directive's element. Therefore, when the directive will be destroy, its scope will be deleted and its element (and all its children) will be deleted and their listeners destroyed as well.

Actually, I had forgotten to close this issue after my PR was closed but I don't have leaks problems anymore. I can't assure that there are no leaks at all in this directive (cause it's quite huge -thanks again for that btw) but I used several of the sub-directives (paths, markers, events, etc.) and don't have leaks in my application.

**Comment by nmccready** [comment]
Is this documented anywhere? Of can you give me leaflet line number to   read?

**Comment by nmccready** [comment]
Thanks for the info BTW.

**Comment by ValentinH** [comment]
I learnt it from there: http://stackoverflow.com/a/27016855/1713469. I think this seems to be pretty relevant information...

Then about Leaflet, I don't know but I just guess that when you do:
```js
var map = new L.Map(element[0], leafletMapDefaults.getMapCreationDefaults(attrs.id));
```
Leaflet attaches everything on element and so it will be handle by Angular on directive destruction.

**Comment by nmccready** [comment]
That stackoverflow leak notes are about $scope events . `map.on` is specific to leaflet. Why would they have the off function if it is cleaned up automatically? http://leafletjs.com/reference.html#events

**Comment by nmccready** [comment]
@ValentinH also when I was referring to leaflet line numbers i was referring to leaflet.js no our codebase.

Something like this. https://github.com/Leaflet/Leaflet/blob/v0.7.3/src/core/Events.js#L11

**Comment by ValentinH** [comment]
The stackoverflow answer also mentions element.on() which are the DOM bindings. I presume that internally, map.on() just attached DOM listeners so it should be OK.

Anyway, just found that: http://leafletjs.com/reference.html#map-remove
Since it is called here: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L143 we are good ;)

**Comment by nmccready** [comment]
@ValentinH awesome. I'll remove my additions then.
