### ISSUE TITLE
Scale control support?

### ISSUE THREAD

**Issue by dts** [tombatossals/angular-leaflet-directive#612]
I jimmied support for the scale control with this directive:

     angular.module("leaflet-directive").directive(
       'scalecontrol',
       function($log,$q) {
         return {
           restrict: 'A',
           scope: false,
           replace : false,
           require: 'leaflet',
           link: function(scope,element,attrs,controller) {
             controller.getMap().then(
               function(map) {
                 L.control.scale().addTo(map);
               }
             );
           }
         }
       }
     );

If you guys prefer, I can fork/patch/pull-request this, but it just seemed too simple.

**Comment by tombatossals** [comment]
Hi @dts, thanks so much for your example.

Your solution is pefect, I have coded it in the library in other way, grouping all the controls inside the "controls" object. I have added an example here:

http://tombatossals.github.io/angular-leaflet-directive/examples/control-scale-example.html

**Comment by dts** [comment]
Great!  Thanks!
