### ISSUE TITLE
path not being displayed in map

### ISSUE THREAD

**Issue by zebarahman** [tombatossals/angular-leaflet-directive#617]
hi, im using angularjs + ionic framework + leaflet.js. i want to show paths, i followed the paths example code, but the path is just not showing up. i added the modules in the same order as in the example ...the map centers to the given location and also shows markers if i specify there but the paths don't appear, what am i doing wrong?

**Comment by MarkAPhillips** [comment]
if you are using promises ensure the following - I had this issue today that was driving me nuts e.g.
```
$scope.paths = {};
$promise.then(function() {

       angular.extend($scope, {
                    paths: {
                        c1: {
                            weight: 2,
                            color: "#ff612f",
                            latlngs: { lat: 1, lng: -2 },
                            radius: 50,
                            type: "circleMarker"
                        }
                    }
                });        
 }
```

if you exclude the initialisation paths will not be shown - I think this also the case for markers - please can this be documented - thanks

**Comment by michaelkrog** [comment]
+1

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#44

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
