### ISSUE TITLE
Can't remove one marker

### ISSUE THREAD

**Issue by Jean-FrancoisTrevien** [tombatossals/angular-leaflet-directive#619]
Hello,

I'm trying to remove one marker an i have done this:
$scope.markers[nm]=null;
delete $scope.markers[nm];
But the marker remain visible, the leaflet countepart seem to be still there.
You have an example for removing all markers, but i just want to remove one.
Any idea?

**Comment by justinwp** [comment]
Probably related to #478

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#45

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
