### ISSUE TITLE
How to remove a layer, changing layer settings does not update layer.

### ISSUE THREAD

**Issue by SjRNMzU** [tombatossals/angular-leaflet-directive#620]
I'm registering a callback into leaflet zoom event to change part of my my map.layers.overlays.heatmap object however leaflet does not redraw the layer. I've tried setting the layers.overlays.heatmap to null and deleting it but nothing works.

**Comment by tombatossals** [comment]
Please, can you provide a working example and I will take a look?

https://github.com/tombatossals/angular-leaflet-directive/wiki/MCVE

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#46

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
