### ISSUE TITLE
Integrate Nominating

### ISSUE THREAD

**Issue by stefan-niedermann** [tombatossals/angular-leaflet-directive#622]
Is a Integration of OSM Nominating Service planned?

http://wiki.openstreetmap.org/wiki/Nominatim

As a User i want to be able to pass e.g. a city name instead of coordinates to display a marker.

**Comment by tombatossals** [comment]
Hi @stefan-niedermann , that's a really interesting feature, I'm going to take a look at integrate it.

How is your idea of using it? We could, for example, define the nominatim server as a default (overridable)

```
defaults: {
    ...
    nominatim: {
        server: ' http://nominatim.openstreetmap.org/reverse'
}
```

And the center attribute of the directive could take care of "name" instead of lat/lng parameters:

```
    center: {
        name: "221B Baker Street, London, UK"
    }
```

Does this seems acceptable to you? Do you have another idea?

**Comment by stefan-niedermann** [comment]
> And the center attribute of the directive could take care of "name" instead of lat/lng parameters

sounds great!
What i imagined: Use search api (https://nominatim.openstreetmap.org/search?<params>) to get lat and lng. eg a user could define a marker or center map like this:

center: {
	address: {
		street: <housenumber> <streetname>
		city: <city>
		county: <county>
		state: <state>
		country: <country>
		postalcode: <postalcode>
	}
}

so give the user more alternatives:
1.) lat / lng
2.) name (query a string in a unknown format using reverse api)
3.) address (query an address by detailed information using search api)

*but* what if a user puts multiple of these solutions which are in conflict to each other?

**Comment by razvansr** [comment]
Hi guys,
Is this feature still planned for a future release?

**Comment by tombatossals** [comment]
Hi, I have integrated the Nominatim with the "bounds" property. This will be merged soon if the rest of developers consider it interesting. We could think about adding this feature with the "center" property too.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#47

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
