### ISSUE TITLE
Confusion around tileLayerOptions and layerOptions

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#625]
The use cases for `tileLayerOptions` and `layerOptions` are unclear in the examples and documentation. 

For example here:

https://github.com/tombatossals/angular-leaflet-directive/blob/9cc9fd1426161b496dfc1e385c3255077c966986/examples/custom-parameters-example.html#L20-L24

and here:
 
https://github.com/tombatossals/angular-leaflet-directive/blob/dab1c1e1b7d0ea3c8fab6d5d94096e5ed4d6aaed/test/unit/leafletDirectiveSpec.js#L100-L103

However in practice I have found that to get detectRetina to work, you need to put it inside `layerOptions` and not `tileLayerOptions` as suggested. 

The two above links should be corrected, or the documentation clarified to remove confusion here.

**Comment by seadour** [comment]
+1 on this. Documentation and examples are unclear on when to use `layerOptions` and when to use `tileLayerOptions`.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#48

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
