### ISSUE TITLE
IE Utf Grid Click does not update until after mouse move

### ISSUE THREAD

**Issue by eczajk1** [tombatossals/angular-leaflet-directive#627]
In IE (and Safari, I think), I've noticed an issue where the results from a utf grid click do not post to the view until you move the mouse.

My guess is that this is somehow an Angular $digest issue.

http://jsfiddle.net/eczajk1/teczuxh4/

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#50

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
