### ISSUE TITLE
Google Maps max zoom?

### ISSUE THREAD

**Issue by nolandubeau** [tombatossals/angular-leaflet-directive#628]
Hi,

I was comparing the angular-leaflet google maps example with some of the other angular google maps directives (http://angular-ui.github.io/angular-google-maps/#!/demo) and it appears that the angular-leaflet directive doesn't allow you to zoom in to the same max zoom level as the other directive providers.  Is this a setting that is configurable or is this a restriction?

Thanks.

**Comment by tombatossals** [comment]
Hi @nolandubeau, that's because the Google Maps tiles have a restricted use outside its own javascript library of maps.

This is the leaflet plugin project which integrates the Google Maps Tiles inside leaflet:
https://github.com/shramov/leaflet-plugins

**Comment by nolandubeau** [comment]
Hi, so are you saying if the plugins are added then it removes the zoom
restrictions?  If so, is there an example that shows how to integrate the
plugins?  Thanks very much.

On Wed, Feb 11, 2015 at 3:05 AM, David Rubert <notifications@github.com>
wrote:

> Hi @nolandubeau <https://github.com/nolandubeau>, that's because the
> Google Maps tiles have a restricted use outside its own javascript library
> of maps.
>
> This is the leaflet plugin project which integrates the Google Maps Tiles
> inside leaflet:
> https://github.com/shramov/leaflet-plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tombatossals/angular-leaflet-directive/issues/628#issuecomment-73845362>
> .
>



-- 

*Nolan Dubeau*VP, Engineering, Guardly Corp.
Online: https://www.guardly.com
LinkedIn: http://www.linkedin.com/in/nolandubeau
20 Maud Street, Suite 307, Toronto, ON M5V 2M5
CA (416) 434-8029  |  US (650) 262-3599  |  Skype: nolandubeau
Please consider the environment before printing this email.

**Comment by tombatossals** [comment]
Not really, the problem is that the Google Licensing doesn't allow an intensive use of their tiles in an external library. If you need to use Google Maps Tiles I would recommend you to use the Angular Google Maps library:

http://angular-ui.github.io/angular-google-maps/#!/
