### ISSUE TITLE
Dynamically draw circles from AJAX?

### ISSUE THREAD

**Issue by israelidanny** [tombatossals/angular-leaflet-directive#629]
@danny-Weebo and I are trying to load data from an API, and based on that data show circles around markers on a map.

I can't seem to get it working. Any pointers?

**Comment by eczajk1** [comment]
Check the [examples] (http://tombatossals.github.io/angular-leaflet-directive/#!/examples/simple-map).  This one shows one way to draw circles:  http://tombatossals.github.io/angular-leaflet-directive/examples/paths-example.html

This one demonstrates retrieving data: http://tombatossals.github.io/angular-leaflet-directive/examples/geojson-example.html

**Comment by Danny-weebo** [comment]
thanks buddy

**Comment by israelidanny** [comment]
thanks! that helped alot.
