### ISSUE TITLE
I need to position a number on top of a marker. Is there an easy way to do so?

### ISSUE THREAD

**Issue by Danny-weebo** [tombatossals/angular-leaflet-directive#630]
@israelidanny and I need to have markers that have numbers on top of them to allow some information to be read at a glance without having to click on each marker.

I'm thinking of 2 possible solutions. 

* Find a way to specify text that would be rendered on top of the marker icon?
* Position text on the map regardless of the marker, with the same Lat/Lng? (This one is more cumbersome, but I guess if there is no other way...)

Thanks :)

**Comment by israelidanny** [comment]
It would be very helpful if anybody has a clue on this one :)

**Comment by justinwp** [comment]
You will need to make a custom icon regardless of whether you are using this directive or not. See [this example](https://gist.github.com/comp615/2288108) for one way to have numbers over your marker. Then you can add this custom icon to the directive using [this example](http://tombatossals.github.io/angular-leaflet-directive/examples/markers-update-example.html).

**Comment by tombatossals** [comment]
Hi, as @justinwp says, this is more related to the icon marker plugins, take a looks at this example to show you a few ones that this directive use:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/icons-example

But I have been researching and none of them adds the ability to show numbers in the marker.

Take a look at this stackoverflow thread where there are some explanation and solutions.

http://stackoverflow.com/questions/22622393/leaflet-awesome-markers-adding-numbers
