### ISSUE TITLE
Supporting public methods from label plugin

### ISSUE THREAD

**Issue by fbrandel** [tombatossals/angular-leaflet-directive#632]
The Leaflet.label plugin seems to be supported when creating markers in the directive or even when the label message gets changed. So far so good. Now I wonder if/how it is possible to access the label with its public methods like `showLabel()` or `hideLabel()`. 

This does not seem to work, as once the marker is created, I do not have access to the 'real' L.Marker instance.

Do you have any advice on this?

Thanks.

**Comment by seadour** [comment]
Hi fbrandel,

Have you tried using the leafletData service to access the map object?

See related comment here: https://github.com/tombatossals/angular-leaflet-directive/issues/184#issuecomment-28553932

Inject the service into your controller, then try something like:

    leafletData.getMap().then(function(map) {
        map.Marker.showLabel();
    });

**Comment by ivanssa** [comment]
Hello everyone thanks for the feedback, the more I tried and have not managed to successfully get the error "TypeError: Unable to get property 'getMap' of undefined or null reference" I received a undefined for leafletData there so I created the variable with var leafletData ; and now I get error in GetMap I'm trying to put together the pruneCluster this leaflet that uses Git-directive with ionic "https://github.com/calendee/ionic-leafletjs-map-demo" I am grateful to be able to help me solve this problem in my project.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#51

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
