### ISSUE TITLE
Changes in the marker functionality

### ISSUE THREAD

**Issue by Danny-weebo** [tombatossals/angular-leaflet-directive#633]
Hey, 
I have 2 things Im trying to achive,

1. chaing the "popup" of the marker to be on `mouseHover` instand of `onClick`
2. to change the `onClick` on the marker to zoom-in to the marker location.

if anyone can give me any clue how can I make it'd be great.
thank you!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#52

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
