### ISSUE TITLE
Using canvas

### ISSUE THREAD

**Issue by iamsaint** [tombatossals/angular-leaflet-directive#634]
Hi. Could you tell me how to use canvas to draw map layer with your directive?

**Comment by nCore** [comment]
You have two possibilities:

1. Create your own canvas, above (z-index) the map like this:

```
#map {
    display: block;
    width: 100%;
    height: 100%;
    position: relative;
    z-index: 1;
}

#canvas {
    display: block:
    width: 100%;
    height: 100%;
    position: absolute;
    z-index: 2;
    pointer-events: none; /* this will allow you to scroll the map and pass-through all the events */
}
```
and then just simply get it in javascript and draw anything on it:

```
var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');

// drawing logic
```

2. You can use this plugin for Leaflet: https://github.com/CartoDB/Leaflet.CanvasLayer and use with mapObject given by leafletData.getMap() promise.

**Comment by simonpeters** [comment]
Doesn't leaflet support canvas out of the box?

**Comment by nmccready** [comment]
Look at the code and the examples.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletLayerHelpers.js

**Comment by nmccready** [comment]
If the functionality is missing then see if you can add it.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#53

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
