### ISSUE TITLE
different popus for different markers

### ISSUE THREAD

**Issue by Danny-weebo** [tombatossals/angular-leaflet-directive#637]
Hey, I'd like to set a different class name for each popup marker so I can have different styles of popups for different types of markers. Any advice on how it's done properly? I thought about attaching a class name to a popup depending on which type of marker was clicked, but I have no idea about how to approach the task.
@israelidanny

**Comment by Getz85** [comment]
The message property of marker's object can contain HTML.

You can check this example:

http://tombatossals.github.io/angular-leaflet-directive/examples/markers-angular-template-example.html

**Comment by DogKillerKing** [comment]
how pass params to template?

**Comment by mastermind1981** [comment]
In the continuity of this issue, one of my use case is to have a directive for marker's popup like this :
1.
```
                 message: '<info-box param1="param1" param="param2"></info-box>',
```
info-box is a directive with template and it's own scope.
2.
I have another case, where i create an array of makers and i want  to create the popup with parameters of the directive are passed when looping like this
```
          angular.forEach($scope.hits, function(hit){
               coords = hit._source.location.split(',');
              $scope.markers.push ({
                 title : hit._source.title,
                 lat: parseFloat(coords[0]),
                 lng: parseFloat(coords [1]),
                 getMessageScope: function () { return $scope; },
                 message: '<info-box title="hit._source.title"></info-box>',
                 compileMessage: true,
                   });
           });
```
Is it possible to make the point 1 and 2?

Thanks in advance,

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#56

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
