### ISSUE TITLE
Custom Control

### ISSUE THREAD

**Issue by AleRob90** [tombatossals/angular-leaflet-directive#639]
Hello,
I saw you made a pull about custom Control Button, but i can't make it work. I can't find any other example work. Neither issue 114 or pull 160 are working.
angular.controller('myCtrl', ['$scope', 'leafletData', function($scope, leafletData){
  var MyControl = L.control();
    MyControl.setPosition('bottomleft');
    MyControl.onAdd = function () {
        var className = 'leaflet-custom-control', 
             container = L.DomUtil.create('div', className + ' leaflet-bar');
        return container;
    }
  angular.extend($scope, $scope.directives); // My directives include controls.custom = []
  leafletData.getMap().then(function(map){
    map.controls.custom.push(MyControl); 
    // tried even $scope.controls.custom.push(MyControl) that don't trow error, but didn't do anything
  });
})

I got an undefined error cause map.controls doesn't exist. I really appreciate an answer cause i don't want to put a random button that float on the map.
Other documentation about this doesn't exist. I tried leaflet way and still not working.

**Comment by AleRob90** [comment]
I managed to solve it:d
This is my solution: 

angular.controller('myCtrl', ['$scope', 'leafletData', function($scope){
var MyControl = new L.control();
MyControl.setPosition('bottomleft');
MyControl.onAdd = function () {
var className = 'leaflet-custom-control', 
container = L.DomUtil.create('div', className + ' leaflet-bar');
return container;
}
directives = getMyDirectives(); //Get center controls markers layers etc...
directives.controls.custom.push(MyControl);
angular.extend($scope, directives); // My directives include controls.custom = []
})

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#143

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
