### ISSUE TITLE
marker - multiple mouseover events

### ISSUE THREAD

**Issue by porjo** [tombatossals/angular-leaflet-directive#642]
I have created a custom 'div' marker where the popover displays on `mouseover` and hides on `mouseout` - see Plunkr http://plnkr.co/edit/ftGP05yqENLHT05nvZpN?p=preview

I find that `mouseover` and `mouseout` fire multiple times when the mouse is moved between elements within the same marker causing the popover to flicker off and on. Is this a bug? If not, how would I avoid the event being fired multiple times?

**Comment by MoleHillRocker** [comment]
Did you find a solution for this? We have the same issue with the current version 0.8.6. We are using icons on the marker provided by https://github.com/lvoogdt/Leaflet.awesome-markers. I guess it has something to do with the icon being added as child element of the 'common' icon, which causes separate mouseover and mouseout events.

**Comment by nmccready** [comment]
A workaround for the time being would be to debounce your handlers for your events.

**Comment by nmccready** [comment]
Adjusted plunker for correctness on event handler.

http://plnkr.co/edit/ZfsCImBfODaerpwqTfuo?p=preview

Yes it looks like the events are firing too many times; but I am not sure if this is us or leaflet itself yet.

**Comment by nmccready** [comment]
Also the  behavior appears to be no different from 0.8.5 and 0.8.6 so that statement is invalid.

**Comment by MoleHillRocker** [comment]
I just mentioned v0.8.6 because it is the initial version we used in our project. Since it is a new project, we did not use any previous version of the angular-leaflet-directive. The wording might have been a bit misleading.

**Comment by nmccready** [comment]
@MoleHillRocker no worries just trying to be clear for other. I updated the plnker with debounces. I don't see anything wrong in angular leaflet except for bogus logs on [markers] destroy.

**Comment by nmccready** [comment]
My guess this is a leaflet issue. If someone wants to fork the plnkr and make a raw leaflet example doing the same thing without angular and proves me wrong then we can dig further.

**Comment by MoleHillRocker** [comment]
Okay, we'll try the debouncing. Thanks for your effort! :)

**Comment by MoleHillRocker** [comment]
I just visited Leaflets GitHub page and found this: https://github.com/Leaflet/Leaflet/issues/3708.
It seems that a vertical offset applied to the popup fixes the issue. We will try that on monday, because this  [JSFiddle](http://jsfiddle.net/fevwbrjq/2/) looks pretty promising.

**Comment by MoleHillRocker** [comment]
It seems that just applying an offset does the trick only if the popup opens on top of the marker and the mouse then points on the popup instead of the marker. In our case, the marker contains a separate HTML tag, which causes the issue (as shown in your [Plunkr](http://plnkr.co/edit/ZfsCImBfODaerpwqTfuo?p=preview)).

The reported issue Leaflet/Leaflet#3708 makes me think that this is desired behavior.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#144

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
