### ISSUE TITLE
Path Layer is not updating

### ISSUE THREAD

**Issue by AleRob90** [tombatossals/angular-leaflet-directive#643]
Hello.
I have a problem with path layers.
When i click on a path i want to change layer of that path. I use leafletDirectivePath.click and a function looking like this
```
function(e, args){
path = $scope.paths[args.pathName];
path.layer = 'Other layer';
}
```
this is not working at all. Also path.clickable = true/false not working.

Working: 
```
path.width = n;
path.fillOacity = n;
path.AnyOtherStyleOption = n;
```
I want this to work for leaflet draw. I click on a path. That path will be hidden and a new path for draw will gonna rise. If i console.log(path) after i change layer it says it's 'Other layer', but is not affecting my map.

For markers is working perfect.

**Comment by nmccready** [comment]
Probably related #313

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
