### ISSUE TITLE
how to add fullscreeen control into leaflet map

### ISSUE THREAD

**Issue by zzjustinzz** [tombatossals/angular-leaflet-directive#644]
I want to add fullscreen control into leaflet same as attached image map but i don't know how to add.
Please help me!!!
![s7tej](https://cloud.githubusercontent.com/assets/4983541/6387593/31e428b2-bdc0-11e4-8b91-b5e41fbf21b7.png)

**Comment by AleRob90** [comment]
I managed to add it a while ago, but i found out about F11:D:))
I have a post how to add Custom control button
https://github.com/tombatossals/angular-leaflet-directive/issues/639
Maybe from there you can make it work with an event
 L.DomEvent.addListener(container, 'click', function(e){goFullscreen/*or something like this/*});

Good luck

**Comment by Vitalik74** [comment]
I do this like that. Download this plugin - https://github.com/Leaflet/Leaflet.fullscreen. And change in `https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/Leaflet.fullscreen.min.js` this code `L.Map.mergeOptions({fullscreenControl:false});` to `L.Map.mergeOptions({fullscreenControl:true});`. And it is work - `https://yadi.sk/i/e1pl0a6Jextko`

**Comment by Vitalik74** [comment]
I find better solution. Download this plugin - https://github.com/Leaflet/Leaflet.fullscreen. And set:
```
angular.extend($scope, {
    defaults: {
        map: {
            fullscreenControl: true
        }
    }
});
```

**Comment by tombatossals** [comment]
Hi, thanks for all the information @vitalik74, @zzjustinzz.

I have finally integrated Leaflet.fullscreen plugin inside angular-leaflet-directive, so you can use it easily with the "controls" functionality. Nowadays, the last post of @vitalik74 is a great solution too.
