### ISSUE TITLE
markercluster events

### ISSUE THREAD

**Issue by azatoth** [tombatossals/angular-leaflet-directive#648]
markercluster adds "cluster" + eventName events to markers; afaik, possible events are hardcoded in leafletEvents.js.

Would it be possible to remedy this to some extent?

**Comment by joeljeske** [comment]
I got around this for now by doing this by get the layer directly. **Note** this code is in a directive, so `layersCtrl` is the injected controller into the `link` function when using the `require` options in the directive definition. 

```js
layersCtrl.getLayers()
	.then(function(layers) {
		var layer = layers.overlays[layerId];
		layer.on('clusterclick', function(e) {
			var map      = e.target._map,
				children = e.layer.getAllChildMarkers(),
				latlng   = e.latlng;

			if (map._zoom >= map._layersMaxZoom) {
				showPopup(map, children, latlng);
			}
		});
	});
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#146

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
