### ISSUE TITLE
Error in page example

### ISSUE THREAD

**Issue by PrimeByDesign** [tombatossals/angular-leaflet-directive#650]
http://tombatossals.github.io/angular-leaflet-directive/#!/examples/bounds

Notice that the leaflet html tag does not include the center attribute. This appears to be required. It's taken me ages to work out what the issue was!

**Comment by tombatossals** [comment]
Hi @PrimeByDesign, thanks for reporting, you're totally right. The "bounds" example is outdated, I haven't noticed it. Now the "bounds" property is a read-only attribute, it's not bi-directionally updated.

I have updated the example to be more realistic, but you can find the more updated examples here:
http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/first-example
