### ISSUE TITLE
Controller promises should use a scope context variable

### ISSUE THREAD

**Issue by joeljeske** [tombatossals/angular-leaflet-directive#654]
When the leaflet directive controller is `required` by a dependent directive, the directive can call `.getMap()`. The current implementation works fine when using only one map on a page but when using two, the wrong promise may be returned, depending on when the `.getMap()` call is made. 

The culprit is [this line][1]. It should be using a scoped deferred as seen in other controllers like in the [layers controller][2]. 

There are examples for multiple maps on a page that function properly but I think that due to the lifecycle of angular and when the `.getMap()` call is made, it happens to work. 

I believe this is true other directive controllers, as seen in the [`center` directive][3].

[1]: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L24
[2]: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/layers.js#L8
[3]: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/center.js#L23

**Comment by tombatossals** [comment]
Hi @joeljeske, sorry for the late response.

In theory, you can access the required map passing a parameter to the getMap call, the id of the leaflet object you created prevously.

I have an example illustrating this:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/double-map-access-map-object-example

Doest this solve your issue, or I haven't fully understand you?

**Comment by joeljeske** [comment]
No that is not quite what I was asking. I should have provided links to specific commits.

The issue has been fixed with [this commit](https://github.com/tombatossals/angular-leaflet-directive/commit/63061ad7b5dcafbce57166fa530c3131cb6946d8). The `_leafletMap` promise was a single variable instead of a reference on the controller or on the $scope.

**Comment by tombatossals** [comment]
Sorry, you're right, thtat's because not all the issues can be processed at the same time the code evolves. I know the problem you're refering now.

Thanks for your detailed information in any case
