### ISSUE TITLE
Wrong implementation in base layers

### ISSUE THREAD

**Issue by kozer** [tombatossals/angular-leaflet-directive#655]
Hello, and thanks for your amazing work!
As i see you have wrong logic in baselayers.
They meant to be mutually exclusive, but as i see with the top property,
i can have two of them showing in the same time.
This is not the case although.
I ll take a look if you dont have the time to fix it, and i ll post back.
Thanks again for this awesome library

**Comment by tombatossals** [comment]
Hi kozer, you can have more than one layer at time, but only the top one will be visible. Having more than one layer active shows a "layer selector" at the top-right (by default) cornet of the map. If you want to show more information inside a layer you must use overlays.

Any contribution is welcomed, please reopen if needed
