### ISSUE TITLE
Double click on path or geoJSON not working

### ISSUE THREAD

**Issue by sushantkr17** [tombatossals/angular-leaflet-directive#662]
When I am doing double click on Path or geoJSON layer then nothing happens. I want to set it default such that when I do the double click it will zoom(+) the map.
But its not working ? Is this a error ?

**Comment by tombatossals** [comment]
You need to listen for the click event on your controller and set your logic based on this event, for example:

```
     $scope.$on('leafletDirectivePath.click', function(event, link) {
         $scope.bounds = leafletBoundsHelpers.createBoundsFromArray(...);
     });
```

**Comment by nmccready** [comment]
@tombatossals is there a dblclick event to add into the geojson.js directive itself?

**Comment by nmccready** [comment]
Should be one http://leafletjs.com/reference.html#map-events

**Comment by nmccready** [comment]
just needs to be added here https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/geojson.js#L35-L53

**Comment by nmccready** [comment]
No one else huh? This is pretty darn easy.

**Comment by nmccready** [comment]
This has been added (here)[https://github.com/tombatossals/angular-leaflet-directive/commit/816a633f37d4c8c693d97266442afda068f1fe07].
