### ISSUE TITLE
font-awesome bower dependency

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#663]
https://github.com/tombatossals/angular-leaflet-directive/blob/master/bower.json#L16

Should this not be a devDependency?

**Comment by nmccready** [comment]
@tombatossals

**Comment by nmccready** [comment]
I'll dig into this

**Comment by nmccready** [comment]
@tombatossals @jessertaylor do u guys know why this is a dependency? Is it really or just a devDep?

**Comment by jessertaylor** [comment]
It's because of https://github.com/lvoogdt/Leaflet.awesome-markers

**Comment by nmccready** [comment]
Right but the plugin is optional, so it should be a devDep and not forced upon everyone. One of the problems is font-awesome appears to be in bower in a few different ways. Thus this causes duplicate downloads of font-awesome by needing this library.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#148

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
