### ISSUE TITLE
MapBox Website Examples Are Broken

### ISSUE THREAD

**Issue by esetnik** [tombatossals/angular-leaflet-directive#664]
On the main website there is a Getting Started section. When selecting either *Mapbox Terrain* or *Mapbox Night* I am getting a gray map and errors in the console:
```
http://api.tiles.mapbox.com/v4/examples.map-i86nkdio/3/5/3.png?access_token=pk.eyJ1IjoidG9tYmF0b3NzYWxzIiwiYSI6Imo3MWxyTHMifQ.TjXg_IV7ZYMHX6tqjMikPg Failed to load resource: the server responded with a status of 404 (Not Found)
```
It appears as if the format is correct, so it's most likely that either the map `i86nkdio` no longer exists or the token `pk.eyJ1IjoidG9tYmF0b3NzYWxzIiwiYSI6Imo3MWxyTHMifQ.TjXg_IV7ZYMHX6tqjMikPg` is invalid.

**Comment by tombatossals** [comment]
Hi @esetnik, you're totally right, thanks for noticing it. The maps used were removed, I have added new ones.

I'm going to update the examples too.

**Comment by esetnik** [comment]
:thumbsup:

**Comment by esetnik** [comment]
MapBox maps are broken in the examples [here](http://tombatossals.github.io/angular-leaflet-directive/examples/tiles-example.html]) as well.

**Comment by lukas-shawford** [comment]
Looks like some of the examples are broken again:
- [Custom layer with no javascript Example](http://tombatossals.github.io/angular-openlayers-directive/#/layers/layer-no-javascript)
- [Layers change tiles example](http://tombatossals.github.io/angular-openlayers-directive/#/layers/layer)
- [Layer Opacity example](http://tombatossals.github.io/angular-openlayers-directive/#/layers/layer-opacity)
