### ISSUE TITLE
MapBox Polygons do not display

### ISSUE THREAD

**Issue by feelcreative** [tombatossals/angular-leaflet-directive#670]
Hi there! Thanks so much for this module, its quite awesome. I'd like to find out how to set it up so that Polygons in MapBox are displayed in my app. I've created the polygons in MapBox, but when I point my app to those new tiles, they don't show the polygons?

![screen shot 2015-04-01 at 5 38 17 pm](https://cloud.githubusercontent.com/assets/227636/6935760/ef4816da-d895-11e4-9b9f-47a75a6faccb.png)

**Comment by nmccready** [comment]
You need to provide a lot more context with a small example in jsfiddle or plnkr

**Comment by feelcreative** [comment]
Thanks mate, good point. Here is a share of the map itself with all the polygons on it: https://a.tiles.mapbox.com/v4/feelcreative.llm8dpdk/page.html?access_token=pk.eyJ1IjoiZmVlbGNyZWF0aXZlIiwiYSI6Ik1Gak9FXzAifQ.9eB142zVCM4JMg7btDDaZQ#16/-33.8980/151.2304

And here is a JSFiddle that uses AngularJS Leaflet directive to display this map, but the polygons do not show up: http://jsfiddle.net/2h26u3t4/4/

**Comment by tombatossals** [comment]
Hi @feelcreative , you need to load the GeoJSON data in a subsequent call. I have made an example to illustrate, you can see it here:

http://tombatossals.github.io/angular-leaflet-directive/examples-reworked/0602-mixed-mapbox-tiles-geojson-example.html

**Comment by feelcreative** [comment]
Very nice @tombatossals thank you! I've integrated your solution into my jsfiddle and pulled in the styling from the features json as well via a style function. http://jsfiddle.net/2h26u3t4/26/

reference for style function: https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/geojson-example.html

Hope this helps others.

**Comment by nmccready** [comment]
@feelcreative can this be closed?

**Comment by feelcreative** [comment]
yes siree! Thanks @nmccready !

**Comment by feelcreative** [comment]
Quick question, how do we enable the bubbles on click of the polygons?

C

**Comment by nmccready** [comment]
Since we're using geojson http://leafletjs.com/reference.html#geojson there is not built in convenience of a popup. We currently don't have a standalone popup directive. I started one, but it is easy enough to do in a controller given some point.

**Comment by nmccready** [comment]
```

//creates a popup with the default close button off as it is closed on mouseout
angular('yourAppName').service('popupLoader', [
  '$templateCache', '$http', '$compile', function($templateCache, $http, $compile) {
    var _map;
    _map = null;
    return {
      load: function($scope, map, model, opts, templateUrl) {
        if (opts == null) {
          opts = {
            closeButton: false,
            offset: new L.Point(0, -5)
          };
        }
        _map = map;
        if ((model != null ? model.markerType : void 0) === 'cluster') {
          return;
        }
        return $http.get(templateUrl, {
          cache: $templateCache
        }).then(function(content) {
          var compiled, lObj, templateScope;
          angular.extend(opts, {
            closeButton: false
          });
          templateScope = $scope.$new();
          templateScope.model = model;
          compiled = $compile(content.data)(templateScope);
          lObj = new L.popup(opts).setLatLng({
            lat: model.coordinates[1],
            lng: model.coordinates[0]
          }).openOn(map);
          lObj.setContent(compiled[0]);
          return lObj;
        });
      },
      close: function() {
        if (!_map) {
          return;
        }
        return _map.closePopup();
      }
    };
  }
]);
```

**Comment by feelcreative** [comment]
Thanks @nmccready !
