### ISSUE TITLE
ES5 Strict Mode Problems

### ISSUE THREAD

**Issue by stefan-niedermann** [tombatossals/angular-leaflet-directive#671]
Compiling with Google Closure i get the following problem:

Apr 01, 2015 11:38:12 AM com.google.javascript.jscomp.LoggerErrorManager println
SCHWERWIEGEND: script.js:618: ERROR - "arguments.callee" cannot be used in ES5 strict mode

**Comment by nmccready** [comment]
Did you dig into the code base or give us more specifics of the offending line? We need people to make an effort.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#151

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
