### ISSUE TITLE
Google Closure Warning

### ISSUE THREAD

**Issue by stefan-niedermann** [tombatossals/angular-leaflet-directive#672]
WARNUNG: script.js:606: WARNING - Parse error. illegal use of unknown JSDoc tag "authors"; ignoring it
 * @authors https://github.com/tombatossals/angular-leaflet-directive/graphs/contributors
   ^

**Comment by nmccready** [comment]
Ok, then can you correct the tag which is created via grunt in concat.

**Comment by stefan-niedermann** [comment]
sorry, i don't know anything about grunt and have no idea where i should start... maybe you could fix this since you know best where to change things?
best regards

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#152

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
