### ISSUE TITLE
Tile load event

### ISSUE THREAD

**Issue by vargi** [tombatossals/angular-leaflet-directive#674]
How can i catch the tile load event, i need to set map center, after tile is loaded, 
is there a way to do that?

**Comment by vargi** [comment]
sorry i found the load event 

      scope.$on('leafletDirectiveMap.load', function(event){});

**Comment by kitab15** [comment]
Is this event fired? I can't catch it. However, the 'unload' event is fired like I expect.

**Comment by nmccready** [comment]
Try $rootScope

**Comment by kitab15** [comment]
Thanks for the answer! 
The problem persist, my code is: 

```
    $rootScope.$on('leafletDirectiveMap.load', function(event, args){
      $log.info('load');
    });

    $rootScope.$on('leafletDirectiveMap.unload', function(event, args){
      $log.info('unload');
    });
```
The unload event is fired.
I can't understand what is the problem with the load event! 

Thanks in advance!

**Comment by nmccready** [comment]
@kitab15 can u make a plnkr?

**Comment by seadour** [comment]
@kitab15 For `leafletDirectiveMap` events, you must explicitly declare them in your `$scope`, like so:

    angular.extend($scope, {
      events: {
        map: {
          enable: ['load','unload'],
          logic: 'emit'
        }
      },
      ...
    });

and make sure to also use the `event-broadcast` attribute in your view's `<leaflet>` tag, like so:

    <leaflet event-broadcast="events"></leaflet>

Other events such as `leafletDirectiveMarker` do not require this, which may be confusing.

Does this help in your situation?
