### ISSUE TITLE
Bower minified version seems behind

### ISSUE THREAD

**Issue by EdHubbell** [tombatossals/angular-leaflet-directive#683]
I installed via bower, and the version of angular-leaflet-directive.min.js seems to not match that which comes along in the bower config file. For example, I install and I see in bower.json
```
 "angular-leaflet-directive": "~0.7.11"
```
But the header in bower_components/angular-leaflet-directive/dist/angular-leaflet-directive.min.js doesn't match the header in the github dist folder. The one in github has 0.7.11 in the header, along with a very recent build date. For now, I've gone to using a local copy and including that in my repo. Just figured I'd pass this along in case someone else runs up against it.

And thanks for the excellent library, BTW.

**Comment by nmccready** [comment]
Is this off master, or an actual release?

**Comment by nmccready** [comment]
Well you said bower so I assume this is a release. Well I guess we're due for a new one ;)

**Comment by tombatossals** [comment]
Mmmm @EdHubbell , @nmccready you're right, last time we bumped a version the bower.json was not updated.

I use grunt-bump to make the release, but the bower.json version has to be updated by hand. Any suggestions to automate this?

To solve this issue, we could release a new version (with all the great changes added recently) and sync the bower version.

What do you think about this?

**Comment by jessertaylor** [comment]
:+1:

**Comment by nmccready** [comment]
I think I fixed this for. 712

**Comment by nmccready** [comment]
I added Bower to grunt bump.  It wasn't working before because it had no version to begin with.

**Comment by EdHubbell** [comment]
I think this is mostly fixed. When I do a bower install, I get this nice new version 

    bower install               angular-leaflet-directive#0.7.12

But when I look at the top of the minified file, I can see that the version is still set to 0.7.11. 

    angular-leaflet-directive 0.7.11 2015-04-13

It looks like there must be a problem in the build script; It certainly looks like the .min file is a new build, based on the 2015-04-13 date. The version number just doesn't match what bower says it is.

Thanks for rebuilding - I feel comfortable installing via bower again - Just figured I'd follow up. If I was comfortable at all with Grunt maybe I could assist. I'm not gruntled.

**Comment by nmccready** [comment]
hmm Ill try and figure this out.

**Comment by nmccready** [comment]
I think the issue is the order of how things are happening. bump is just bumping the code and not rebuilding the codebase to bump internal numbers. So what needs to happen is
`bump-only -> grunt ->  git commit -> git tag -> git push origin -> git push origin --tags`

**Comment by nmccready** [comment]
Fixed from sha f72dd3b  to 85b79b7

**Comment by nmccready** [comment]
See history.

**Comment by EdHubbell** [comment]
Many thanks, @nmccready - Looks great.
~Ed
