### ISSUE TITLE
geojson event setup and usage needs to be unified and consistent

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#684]
Currently this directive is not consistent with the rest of the api. It offends it in the following ways.
not the same:
- call back arguments
- event naming

Resolution make all names lowercased , 'click' not Click and try to pass up the same number of event arguments as markers.

**Comment by tombatossals** [comment]
:+1:

**Comment by nmccready** [comment]
I'm going to add dblclick and other events as well.

**Comment by nmccready** [comment]
#750
