### ISSUE TITLE
markers-update-example example cannot update marker position in 0.7.13 version

### ISSUE THREAD

**Issue by samuelpfchoi** [tombatossals/angular-leaflet-directive#685]
markers-update-example example cannot update marker position during dragging the marker in 0.7.13 version

**Comment by samuelpfchoi** [comment]
It seems that the change of lat & lng is updated to model object (_genDispatchMarkerEvent function).
is it intentional? and how can I sync the data back to original marker object or how can I get the model object. Thanks

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#153

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by CatchSandeepVaid** [comment]
I am facing the same issue and there is no workaround yet. Can someone please tell me a workaround for this?
