### ISSUE TITLE
Error on paths events

### ISSUE THREAD

**Issue by antoinegiret** [tombatossals/angular-leaflet-directive#689]
Hi,
I have an error when a path event is fired on my map, like a mouseeenter :
<p><b>ReferenceError: fire is not defined</b></p>

Any idea with this issue ?
Thanks.

**Comment by antoinegiret** [comment]
I have the code of <b>angular-leaflet-directive 0.7.13 2015-04-14</b>
I modified the following function :

angular.module("leaflet-directive").factory('leafletPathEvents', [..., <b>"leafletEventsHelpers"</b>, function (..., <b>leafletEventsHelpers</b>) {
&nbsp;&nbsp;&nbsp;var fire = leafletEventsHelpers.fire</b>;

        ...

}]);

**Comment by iamsortiz** [comment]
Same error with bower install done today.

Code on github already has the fix:
https://github.com/tombatossals/angular-leaflet-directive/blob/master/dist/angular-leaflet-directive.js#L4433

Using that fixed .js from github solved the issue.

I don't know much about bower, but maybe bower it's using an older unfixed code on install.

**Comment by nmccready** [comment]
Yes a new release needs to be cut.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#154

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
