### ISSUE TITLE
Marker type Point fails if properties lat lng provide the coordinates vs an array

### ISSUE THREAD

**Issue by bwmcin** [tombatossals/angular-leaflet-directive#691]
Using 0.7.13.  _validateCoords returns true if the coords.type = 'Point' and properties 'lat' and 'lng' exist and are numbers (see line 442).  But in _getCoords this condition is not recognized and type 'Point' is assumed to have an array for the coordinates, resulting in an exception (lines 455-456).

**Comment by nmccready** [comment]
Please copy the urls with the line numbers in them. It makes everyone's world easier.

**Comment by nmccready** [comment]
Also reference the source code line numbers and not the dist file.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#155

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
