### ISSUE TITLE
Do Markers have to be an object?

### ISSUE THREAD

**Issue by adamkarb** [tombatossals/angular-leaflet-directive#693]
I'm using the map in a way that a user can click on a location and a marker is added.  
My code looks a little like this: 

    $scope.markers = [ ];
    
    $scope.$on('leafletDirectiveMap.click', function(event, args){
    
        var leafEvent = args.leafletEvent.latlng;
        
        $scope.markers.push({
            lat: leafEvent.lat,
            lng: leafEvent.lng,
            message: 'New marker'
        });
        
    });

Although this code functions the way that I would like it to, the console is filling with errors like this:

    [AngularJS - Leaflet] The marker definition is not valid.
    angular.js:11655 [AngularJS - Leaflet]  Received invalid data on the marker $add.
    angular.js:11655 [AngularJS - Leaflet] The marker definition is not valid.
    angular.js:11655 [AngularJS - Leaflet]  Received invalid data on the marker $save.

Just wondering, is this because my $scope.markers is not an object?  What am I missing?

**Comment by jessertaylor** [comment]
Try
```
$scope.markers['newMarkerName'] = {
        lat: leafEvent.lat,
        lng: leafEvent.lng,
        message: 'New marker'
    });
```

**Comment by adamkarb** [comment]
Yea that did nothing, sorry.  Actually ruined the map.

**Comment by nmccready** [comment]
If markers are not nested by `markers-nested="true"` then they should be able to be a an array or object. If nested I am pretty sure it will handle arrays of arrays as well and object of arrays.

**Comment by nmccready** [comment]
Ok works fine as object http://jsfiddle.net/nmccready/ed5uLcv5/ . Forking it to try as array.

**Comment by nmccready** [comment]
There is an error which is easy enough to fix `marker.getPopup is not a function` which is null.

**Comment by nmccready** [comment]
Fine as array .. http://jsfiddle.net/nmccready/ua82epxd/
