### ISSUE TITLE
Can't get angular compiled templates in popups to work...

### ISSUE THREAD

**Issue by Maistho** [tombatossals/angular-leaflet-directive#708]
Hi!

I was going to create an issue regarding width of angular compiled templates (it's not set correctly), but I couldn't even get compiled templates to work in jsfiddle.
http://jsfiddle.net/qvebnk9b/1/
The code is almost directly copied from [this example](http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/angular-template-example), so it should work, right?

**Comment by subliminalvoice** [comment]
Hello Maistho,

the problem lies in the leaflet.js version you are using (0.6.4), which is missing the getPopup() function for markers. Update to the latest leaflet version (0.7.3) and then it should work...

Best regards,
Simon

**Comment by Maistho** [comment]
Ok thanks! I thought I had updated the libs, but must've missed leaflet.

You should probably update the jsfiddle linked to in [contributing](https://github.com/tombatossals/angular-leaflet-directive/blob/master/CONTRIBUTING.md) so that the libs there are the newest versions.

[The issue I was actually trying to show you](https://github.com/tombatossals/angular-leaflet-directive/issues/721)

**Comment by nmccready** [comment]
@Maistho PR an update to fix the example. You are just as capable as fixing things as we are. Looking forward to your PR.
