### ISSUE TITLE
not responsive?

### ISSUE THREAD

**Issue by JoergPf** [tombatossals/angular-leaflet-directive#709]
Hi, when I open the map on my Iphone6, all icons are very small. Even the examples from the README.md.

Isn't the angular leaflet directive responsive like leaflet is?

**Comment by nmccready** [comment]
Did you try running something with native leaflet? It could be CSS issues. I know font-awesome is included as well.

**Comment by tombatossals** [comment]
Hi @JoergPf, @nmccready  I think it's all related to the "viewport" meta, as @johntyree reported here:

https://github.com/tombatossals/angular-leaflet-directive/issues/473

I will add the viewport meta to the examples so they shows better in mobile devices.

Thanks for reporting.

**Comment by JoergPf** [comment]
Yes, that's it :-)

**Comment by jessertaylor** [comment]
This is fixed.
