### ISSUE TITLE
Regression fix for commit 6503ded52d7b5dc2e73a15dd4f4cfc09be36a128

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#712]
Layers are not removing / being hidden when they are supposed to be.

**Comment by nmccready** [comment]
See comments https://github.com/tombatossals/angular-leaflet-directive/commit/6503ded52d7b5dc2e73a15dd4f4cfc09be36a128

**Comment by nmccready** [comment]
#713

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#156

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
