### ISSUE TITLE
Layers Icon not showing on Build

### ISSUE THREAD

**Issue by adamkarb** [tombatossals/angular-leaflet-directive#717]
I'm using gulp to build my project, and serving locally the path to the image works fine, but after the build the path becomes different.  I've tried to trace it down, but can't seem to get anything going.  
If you'd like to witness it yourself, go to 

https://fowl-landing.firebaseapp.com/#/geo

And open the console to see that 404 error on the layers image that should be in the top-right.
I'd appreciate any insight.

**Comment by subliminalvoice** [comment]
Hello Adam,

leaflet's css is looking for the layers icon at: https://fowl-landing.firebaseapp.com/styles/images/layers.png. So you either have to make sure the layers.png is available there or you have to change the css declaration to point to a different location.

Best regards,
Simon

**Comment by nmccready** [comment]
If you use something like webpack it will fix the css urls for you if you import leaflet via require.

**Comment by adamkarb** [comment]
@subliminalvoice I don't know how to change the declaration because it is coming all from the external https link request.  What could I do in my own css to fix this?
