### ISSUE TITLE
Path add event never fires

### ISSUE THREAD

**Issue by subliminalvoice** [tombatossals/angular-leaflet-directive#720]
Hello everybody,

there seems to be an issue with the firing of an event, when a path gets added to the map (leafletDirectivePath.add event) 

[Plunker](http://plnkr.co/edit/Z3CyTQS9BHQWYNIq20Fu)

Best regards,
Simon

**Comment by nmccready** [comment]
Yes this is already solved thanks. It fixed on master and 0.7.14. However 0.7.14 has some markers bugs. So 0.7.15 would be ideal.

**Comment by subliminalvoice** [comment]
Hello,

I just checked with 0.7.15 but the issue isn't resolved. The problem is that the new element (in this case the path) gets added to the map before the events get bound (bindPathEvents method), so the 'add' event doesn't get listened on. 

I built a workaround by just moving the bindPathEvents in front of the "addLayer(newPath)" function calls, so far this works for me and there haven't been any issues resulting from this...

**Comment by nmccready** [comment]
Please submit a fix.

**Comment by subliminalvoice** [comment]
Karma's currently failing with my version, will have a look at it soon.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#157

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
