### ISSUE TITLE
document issues when minifying html or change name of control to something else

### ISSUE THREAD

**Issue by stev-0** [tombatossals/angular-leaflet-directive#726]
I have spent quite some time debugging an issue with angular-leaflet-directive. It turned out to be due to the html minification process. I had 

`<leaflet center="centre" controls="controls" layers="layers" width="1200px" height="800px"></leaflet>
`

And because controls="controls" is a standard html attribute, the minifier was reducing it to, 

`<leaflet center="centre" controls layers="layers" width="1200px" height="800px"></leaflet>
`

which I didn't pick up on for quite a while.

Might it be possible to change the name of `controls` to something like `leaflet-controls` to stop this happening in future? Or alternatively is there a manual, documentation or faq that I could add this too. If not happy to create one.

There is more info on the [stackoverflow question](http://stackoverflow.com/questions/29784544/angular-watch-for-angular-leaflet-directive/29794132#29794132)

**Comment by tombatossals** [comment]
You're totally right, we have this issue, but haven't changed it yet because of the broken compatibility it supposes.

@nmccready, @jessertaylor what do you think about this? Maybe we can rename the sub-directives names for the next release version, something like:

```
&lt;leaflet lg-center="center" lg-controls="controls">
```

What do you think about this

**Comment by nmccready** [comment]
while your at it you should also do leaflet to lg-leaflet, as it becomes less likely to collide with other directives.

**Comment by tombatossals** [comment]
That's right, we should rename all directives including the main one with a directive prefix. Maybe we could consider adding these changes when leaflet 0.8 is released, that would be less painful.

**Comment by tombatossals** [comment]
Related: https://github.com/tombatossals/angular-leaflet-directive/issues/726

**Comment by nmccready** [comment]
Sounds like a good idea.

**Comment by boeckMt** [comment]
i had the same issue...
maybe as workaround till the renaming is done, prefixing the attributes with "data-" works for me with minifying.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#158

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
