### ISSUE TITLE
watchCollection doesn't watch to deep enough into $scope.geojson

### ISSUE THREAD

**Issue by pieterjandesmedt** [tombatossals/angular-leaflet-directive#735]
In geojson.js, line 138, you're using _maybeWatchCollection instead of _maybeWatch:
```javascript
_maybeWatchCollection(leafletScope,'geojson', watchOptions, function(geojson){
```
Since a watchCollection only goes one level deep, it doesn't pick up changes in `$scope.geojson.data.features`, only in `$scope.geojson.options`.

I think it should be
```javascript
_maybeWatch(leafletScope,'geojson', watchOptions, function(geojson){
```
like it is in markers.js

**Comment by nmccready** [comment]
This is heavier weight, which is what the original creator probably intended. We can disable the watch via watch options so it is probably fine. But assuming that watch deep is a good thing is not really the case for everything.

**Comment by nmccready** [comment]
@tombatossals what is your thought accept the PR ?

**Comment by pieterjandesmedt** [comment]
I agree it's heavy, but a watchCollection on `$scope.geojson` is just not deep enough. Adding a feature to `$scope.geojson.data.features` currently does nothing... You would expect the feature to show up, right?

Maybe a $watchCollection on `$scope.geojson.data`? It probably wouldn't catch coordinate updates of individual features though...

**Comment by nmccready** [comment]
Valid point.
