### ISSUE TITLE
markercluster click event on Marker

### ISSUE THREAD

**Issue by JoergPf** [tombatossals/angular-leaflet-directive#738]
Hi, as soon as I change my overlay type: from 'group' to 'markercluster' I cant get the click event for the single maker anymore.

Do I have to set some options?

**Comment by jessertaylor** [comment]
We currently don't have a wrapper for the cluster events - this could be added - you can do it natively at the moment listening via the clusterclick event

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#159

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
