### ISSUE TITLE
Document the api

### ISSUE THREAD

**Issue by epelc** [tombatossals/angular-leaflet-directive#739]
It would be really nice if the api was documented. Right now it seems there's a bunch of examples. But if you want to get more in depth or find out what does what you need to look at the source. Also there is little information on how this can be used along with the leaflet api.

**Comment by nmccready** [comment]
Feel free to contribute to the website.

**Comment by tombatossals** [comment]
There's a lot of documentation missing, but please consider  contributing the project, any help is welcomed.
