### ISSUE TITLE
Setting tms to true

### ISSUE THREAD

**Issue by hanleyhansen** [tombatossals/angular-leaflet-directive#740]
Using the directive, how can I set tms to true as described here:

http://leafletjs.com/reference.html#tilelayer-tms

This is what my obj looks like:

```javascript
{
    url: '/api/tiles/' + a.id + '/{z}/{x}/{y}.png',
    defaults: {
        tileLayerOptions: {
            noWrap: true,
            tms: true
        },
        maxZoom: 6,
        minZoom: 0
    },
    noWrap: true,   
    continuousWorld: false
};
```

Seems like tms is getting ignored

**Comment by tombatossals** [comment]
Hi, you don't need to pass the tms property in the defaults object, that's the default tiles object which only applies when the user doesn't define any layer. It's better to declare the custom layer properties it in the main layer "layerOptions". For example:

```
baselayers: {
    mylayer: {
        name: 'My Layer',
        url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        type: 'xyz'
        layerOptions: {
            tms: true
        }       
    }
}
```
