### ISSUE TITLE
marker click event does not work mobile

### ISSUE THREAD

**Issue by JasperDS** [tombatossals/angular-leaflet-directive#743]
Click event on a marker does not work on mobile devices. 

    $scope.$on('leafletDirectiveMarker.click', function(event, args){
        console.log("Leaflet Click");
    });

Is it supported?

**Comment by thegreatmichael** [comment]
try the change i made in https://github.com/tombatossals/angular-leaflet-directive/compare/master...thegreatmichael:patch-1 and then updating your code above to be as follows:

    // keep this so it works on mouse-having devices
    $scope.$on('leafletDirectiveMarker.click', function(event, args){
        console.log("Leaflet Click");
    });

    //notice touchend (basically a tap/click on a touch device)
    $scope.$on('leafletDirectiveMarker.touchend', function(event, args){
        console.log("Leaflet Touch");
    });

(make sure also that you're either allowing all the events on the markers, or that you update what you allow to include the appropriate touch event)

    $scope.events = {
      markers: {
         enable: leafletEvents.getAvailableMarkerEvents(),
      }
    };

**Comment by kardanov** [comment]
@thegreatmichael 
Hi Michael, just tried what you suggested, but unfortunately doesn't work at all (marker click/touch not fired completely, tested on Google Nexus 5 + latest Android + Chrome).
Could you probably have a quick look into my source here: 
https://github.com/kardanov/kardanov.github.io/blob/master/src/js/controllers/travel-controller.js
Seems to be all correct, right?

**Comment by jewelcai** [comment]
I met with this issue too, and could someone help me with this? I have tried many ways while they don't solve the problem.

**Comment by kardanov** [comment]
@jewelcai 
just as a hint (in case you didn't solve it yet): 
could it be not angular-leaflet-directive who stealing your taps/clicks?
i had similar problem and finally found out that it was angular-material hijacking my taps/clicks on mobile devices. possible solution described here:
http://stackoverflow.com/questions/38618541/tap-click-marker-events-not-working-in-angular-leaflet-directive-on-mobile-devic
