### ISSUE TITLE
clustering geojson markers

### ISSUE THREAD

**Issue by jessertaylor** [tombatossals/angular-leaflet-directive#744]
Hi,

Cannot find an example of clustering geojson markers, is it possible in this directive? (I know how to do it using L.geoJson etc)

@nmccready - I know you use geojson a lot, have you done this?

Thanks

**Comment by nmccready** [comment]
I have not done clustering on it. But I am sure it is similar to this #294#issuecomment-99244119

**Comment by jessertaylor** [comment]
This is how I'm doing it at the moment, it is no different to doing it vanilla leaflet

```
    function addGeoJsonLayerWithClustering(data) {
        var markers = L.markerClusterGroup();
        var geoJsonLayer = L.geoJson(data, {
            onEachFeature: function (feature, layer) {
                layer.bindPopup(feature.properties.title);
            }
        });
        markers.addLayer(geoJsonLayer);
        leafletData.getMap().then(function(map) {
            map.addLayer(markers);
            map.fitBounds(markers.getBounds());
        });
    }
```

**Comment by nmccready** [comment]
I am actually in the middle of making some geojson directive changes to its event setup. I could try and get to this next. Can you out line a clean API (config side) that you'd like to see and we could try to implement it.

I am pretty busy with work right now so it might be a lil while till I get to this.

**Comment by jessertaylor** [comment]
Great - I was going to have a look myself but just using some work arounds at the moment.

I'm not sure, it only needs to be on or off at the moment so 

```
vm.geojson = {
data: data,
clustering: true
}
```

There could be more options for a geojson feature Point (and others) like there is for normal markers, eg getMessageScope, getLabelScope, compileMessage, message etc. 

Not quite sure how this would look though.

**Comment by kylebradshaw** [comment]
I am about to investigate utilizing geoJSON in a markerCluster. I had previously built a solution with Mapbox but I'm wondering how far you were able to get @jessertaylor ? 

Is it possible to use the angular directive with geoJSON data in a markercluster?

**Comment by jessertaylor** [comment]
It is, but only the native leaflet way like I posted - at the moment for me having pretty code that fits snugly into the directive isn't my main worry, but it would be nice to have it fully angulared.

**Comment by sajanojha** [comment]
I also have the same issue.
I am stuck clustering my GeoJson data. 
I tried the way @jessertaylor posted but still no luck.
Please do let me know a good solution.

**Comment by jessertaylor** [comment]
@sajanojha  I've got it working fine - post your code in a plunkr and i'll see if I can help.

**Comment by sajanojha** [comment]
Thanks,
I am still new to angular.
My code snippet is here. I can easily get icons on the map but still stuck how to cluster them.
http://plnkr.co/edit/pd1cAReTGhD5WhvdhBUN?p=preview
It still does not work here at Plunkr  (I have too many dependencies to include)
Thanks @jessertaylor

**Comment by jessertaylor** [comment]
Forget using the API to add the geojson.

It's like this

```
 $http.get("http://localhost:5000/ep/getEntities?conceptID=45697&pagesize=10&pageindex=1&partof=0&locale=it").success(function(data, status) {
addGeoJsonLayerWithClustering(data);
});
```

**Comment by sajanojha** [comment]
Thanks @jessertaylor, It works 
But this is completely out of Angular and Leaflet isn't it?
It will be nice if we had a standard solution :)
Thanks

**Comment by kylebradshaw** [comment]
@sajanojha I'm interested to see the plunkr w/ the working solution, is it updated?

**Comment by nmccready** [comment]
@kylebradshaw start the plunkr and I am sure @jessertaylor will jump in a clean it up.

**Comment by sajanojha** [comment]
@kylebradshaw  yes I have updated the Plunkr. But this does not work for Multipoint geoJson.
I have also pasted my multipoint geojson in the data.json file.
Thanks

**Comment by kylebradshaw** [comment]
I was referring to the plunkr previously created by @sajanojha

**Comment by nmccready** [comment]
Gotcha, I see it now :)

**Comment by sajanojha** [comment]
Yes updated !!! But I cannot load the get with $http.get
thats why I pasted my Json on data.json file.
Here is the screen shot :)
![screen shot 2015-06-02 at 16 14 13](https://cloud.githubusercontent.com/assets/2937894/7937901/d25e0790-0942-11e5-82ca-6e592614fff9.png)

**Comment by sajanojha** [comment]
Ok Now my GeoJSON is working perfectly fine,
Only issue is with MultiPoint GeoJson. Please help me to fix it.
http://plnkr.co/edit/pd1cAReTGhD5WhvdhBUN?p=preview
Thanks

**Comment by jessertaylor** [comment]
@kylebradshaw http://plnkr.co/edit/EGloZdeEO4CNN8uZDlLr?p=preview

**Comment by kylebradshaw** [comment]
great example thanks!

**Comment by sajanojha** [comment]
@kylebradshaw a nice example.
But what happens if you introduce a multipoint on it? 
Thanks!

**Comment by kylebradshaw** [comment]
@sajanojha I noticed that your geojson file was not properly formatted as json and that might be why it wasn't properly loading, try fixing that first!

**Comment by sajanojha** [comment]
@kylebradshaw yes, I have already fixed it. It was caused my Chrome's plugin. Now it works fine.
The only issue now is that the plugin is unable to cluster multipoint Geometry. 

http://plnkr.co/edit/pd1cAReTGhD5WhvdhBUN?p=preview

**Comment by kylebradshaw** [comment]
Wanted to share my progress might be useful for someone. Needed to add a tooltip to render an output based on geoJSON property data based on @jessertaylor plunk

http://plnkr.co/edit/pq0203gY6XEB77sAnC1s?p=preview

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#161

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
