### ISSUE TITLE
removeLayer is not a function

### ISSUE THREAD

**Issue by antoinegiret** [tombatossals/angular-leaflet-directive#747]
Hi, I have an error when I remove paths having a layer.

```
TypeError: overlay.removeLayer is not a function
```

Here is the definition of my layer and my path:

```js
angular.extend($scope, {
   layers: {
      baselayers: {
         ...
      },
      overlays: {
         test: {
            name: 'test',
            visible: false,
            type: 'group'
         }
      }
   },
   paths: {}
});

...

var test = function () {
   $scope.paths['test'] = {
      layer: "test",
      type: "polyline",
      latlngs: latlngs
   };
};
```

And how I remove it from my map:

```
$scope.paths = {}
```

Thanks

**Comment by antoinegiret** [comment]
No solutions ?

**Comment by nmccready** [comment]
I haven't had time to look into it. Have you dug into the directive yourself?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#162

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
