### ISSUE TITLE
Pass geoJson object instead of url in overlays

### ISSUE THREAD

**Issue by clluiz** [tombatossals/angular-leaflet-directive#751]
It's possible to pass a geoJson object directly to an overlay definition? Example, make this:

                   overlays: {
                        traffic: {
                            name: "Traffic Jams",
                            type: "geoJson",
                            geoJson: {
                                     // geojson definition
                             }
                        }
                    }

Instead of this:

                   overlays: {
                        traffic: {
                            name: "Traffic Jams",
                            type: "xyz",
                            url: "http://map.be-mobile.be/customer/mobileninja/nl/los/{z}/{x}/{y}.png"
                        }
                    }

**Comment by nmccready** [comment]
It doesnt look like it. If you want it, please add it. It would go in this file.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletLayerHelpers.js#L45-L53

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#164

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
