### ISSUE TITLE
Canvas tiles instead of img tiles

### ISSUE THREAD

**Issue by simonpeters** [tombatossals/angular-leaflet-directive#753]
Is it possible to use canvas tiles instead of img tiles?

I'm having bad performance on mobile because I have to many markers.

**Comment by nmccready** [comment]
@tombatossals

**Comment by tombatossals** [comment]
Mmm... there's a canvas layer in Leaflet, here documented:
http://leafletjs.com/reference.html#tilelayer-canvas

But this is a canvas where you are the responsible of drawing things, so you would need to manage your markers inside the canvas, I see it a little difficult.

Any hints?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#165

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
