### ISSUE TITLE
Publish v0.8 to NPM

### ISSUE THREAD

**Issue by rjmackay** [tombatossals/angular-leaflet-directive#757]
NPM is still showing v0.7.11 . Can we get the latest version published? https://www.npmjs.com/package/angular-leaflet-directive

**Comment by nmccready** [comment]
I tried, I don't have permissions @tombatossals has to do it I think.

**Comment by tombatossals** [comment]
Yess, just published, thanks for noticing it.

**Comment by smelyakov** [comment]
Can't see v0.8 in NPM. It's still 0.7.15. Could you bump it please?

**Comment by tombatossals** [comment]
Yes of couse, it's published now.

**Comment by smelyakov** [comment]
Thanks!
