### ISSUE TITLE
Layers control doesn't show after release 0.8.1

### ISSUE THREAD

**Issue by zivlevy** [tombatossals/angular-leaflet-directive#758]
Since the release of 0.8.1 the upper right corner layer control doesn't show any more.
Changing back to 0.7.15 and all is well.

**Comment by nmccready** [comment]
Its working fine for me. It is only a problem when my layer config is messed up. Please make an example.

**Comment by dreamworks** [comment]
Same issue here - with the following layer configuration
leaflet itself is still 0.7.3


  $scope.layer = {
      "baselayers": {
              "DE": {
                  "name": "OpenStreetMap DE",
                  "url":
                  "http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png",
                  "type": "xyz",
                  "layerParams": {},
                  "layerOptions": {
                      subdomains: ['a', 'b', 'c'],
                      attribution: '� <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',                      
                  }
              },
              "osm": {
                  "name": "OpenStreetMap int.",
                  "url":
                  "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  "type": "xyz",
                  "layerParams": {},
                  "layerOptions": {
                      subdomains: ['a', 'b', 'c'],
                      attribution: '� <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',                      
                  }
              },              
              "cycle": {
                  name: 'OpenCycleMap',
                  type: 'xyz',
                  url: 'http://{s}.tile.opencyclemap.org/cycle/{z}/{x}/{y}.png',
                  layerOptions: {
                      subdomains: ['a', 'b', 'c'],
                      attribution: '� OpenCycleMap contributors - � OpenStreetMap contributors',                      
                  }
              }
          },
      };

**Comment by nmccready** [comment]
This must be some kind of race condition I very rarely see this (if it is the api). When I have seen it happen locally I thought it was something I was doing.

**Comment by chriseyhorn** [comment]
I am also experiencing the same issue with the layers control not showing after updating to 0.8.1.

**Comment by ghaefele** [comment]
I have the same problem after updating to 0.8.1. Going back to 0.7.15 and the layer control is here again. The issue can be reproduced with the "Baselayers with overlays" example.

**Comment by acemir** [comment]
Well! I think it was this commit that caused the issue: 5e51314b134f946a72e06f2e6bc8c9306ce7baec
More specifically, the line:

    if(angular.equals(newBaseLayers, oldBaseLayers)) return;

**Comment by MarkAPhillips** [comment]
Definitely not a race condition - as soon as I updated the version to 0.8.x the control disappeared.

Not to digress but it may be an idea to add some basic protractor e2e tests to cover these use cases so that these issues are picked up prior to a release being pushed - I am sure this might be useful and can be set up on travis ci  if required - so its part of the build process.

**Comment by nmccready** [comment]
This is confirmed it happens on an off for me. I will look into it.

**Comment by jessertaylor** [comment]
@nmccready It's been reported as a bug in our app too - thanks for looking into it :+1:

**Comment by Diones** [comment]
The same problem here.

I believe that @acemir is correct:

> @acemir commented 11 days ago

> Well! I think it was this commit that caused the issue: 5e51314
More specifically, the line:

> `if(angular.equals(newBaseLayers, oldBaseLayers)) return;`

**Comment by jessertaylor** [comment]
I have created a pull request #780 which fixes this. Not sure if it's exactly the right way to fix it, but if we're going to return early if the layers have not changed it seems we still need to run the function to show the layers control. @nmccready

**Comment by nmccready** [comment]
Thanks @jessertaylor
