### ISSUE TITLE
Marker z-index

### ISSUE THREAD

**Issue by simonpeters** [tombatossals/angular-leaflet-directive#759]
Hi,

Is there a way to define which marker goes on top of another marker when they overlap?

I can't find anything about it in the documentation.

Thanks in advance

**Comment by SjRNMzU** [comment]
Try using 'zIndexOffset' : 1000 in your marker object.

**Comment by simonpeters** [comment]
@SjRNMzU that worked! Thanks!

**Comment by tombatossals** [comment]
Closing this issue
