### ISSUE TITLE
Path with cluster

### ISSUE THREAD

**Issue by levipadre** [tombatossals/angular-leaflet-directive#761]
Hi,

Thanks for the great directive!
I have a question about path. I already managed to create a "network" between markers using multiPolyline. But there are a lot of markers, so I started to use cluster. The problem that I can't reduce the number of the paths. When I have 30 markers within a cluster, I got 30 paths.
Is there a way to check, how many cluster do I have and what's the position?

Thanks!

**Comment by levipadre** [comment]
Does anybody know can I solve that problem?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#57

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
