### ISSUE TITLE
extra params on defaults

### ISSUE THREAD

**Issue by kamalhg** [tombatossals/angular-leaflet-directive#762]
Hi,

in leaflet, some user defined controls have the capability to add and initialize the control in the options object while creating the map. but in leaflet-directive you are restricting the parameters passed in the defaults object. is there any way to pass any other user defined parameter to the map.

Best Regards,
Kamal

**Comment by tombatossals** [comment]
Hi, the "defaults" object is used only to override the most common attributes, so creating a new map with common options is easier. If you think there are useful options that need to be managed in the defaults options just propose it, I added only those which I use more.

If you could be more specific about these options, or provide an example, I can add them. Better if you send a PR by yourself, of course.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#58

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
