### ISSUE TITLE
Nested markerCluster in Layer

### ISSUE THREAD

**Issue by gsimenel** [tombatossals/angular-leaflet-directive#764]
Hi,
I'm trying to have 2 layers each with its own list of markers, the first is a simple marker list, the second should be a markerCluster. I get the following error message : 

[AngularJS - Leaflet]  A marker can only be added to a layer of type "group"

Can you please let me know if this is possible ? I'm using v0.7.15 

Thanks
G

**Comment by ws-perelyaynen** [comment]
//markersParams
markerObj = {
	//.....//
	layer: 'clusterGroup'
};


//mapParams
angular.extend($scope, {
    //params//
    markers: $scope.markers,
    layers: {
        //yourBaseLayer
        overlays: {
            clusterGroup: {
                name: 'cluster Group',
                type: 'markercluster',
                visible: true,
                layerOptions: {
                    showCoverageOnHover: false
                }
            }
        }
    }
});

see https://github.com/tombatossals/angular-leaflet-directive/blob/master/doc/markers-attribute.md#marker-clustering-with-overlays

**Comment by gsimenel** [comment]
Thanks a lot it works. I had 2 things wrong : I used 'markerCluster' instead of 'markercluster', plus I didn't use the property layer in my marker creations.
