### ISSUE TITLE
Creating custom layers control

### ISSUE THREAD

**Issue by chriseyhorn** [tombatossals/angular-leaflet-directive#765]
What is the best approach to build a custom layers control for base layers and a separate custom layers control for overlays?  I have looked at the <layercontrol order="normal"></layercontrol> but this just seems to pull from the existing list to display both base layers and overlay layers.

Any guidance is much appreciated!

**Comment by elesdoar** [comment]
I am working in a layer control, see an example [here](http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/controls/custom-layer-control-example) :smile: 

Soon it will have several enhancements.

**Comment by nicho90** [comment]
@elesdoar: Hi there, I have a little problem and just saw that you worked on the layer-control. Maybe you can help with my little question about changing base-layers, pls have a look about it ([#925](https://github.com/tombatossals/angular-leaflet-directive/issues/925)), if you have time, that would be awesome :)

Best, Nicho

**Comment by nicho90** [comment]
@elesdoar: Thank you for your quick reply :+1:

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#59

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
