### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by ws-perelyaynen** [tombatossals/angular-leaflet-directive#766]
seems that markers not fully clean
cluster's number permanently grow
problem not in clusters plugin, i think, because markers are still exists after filtering
in version 0.7.11 this worked fine.  
0.7.15  and 0.8.1 - not work
http://plnkr.co/edit/AXxuIiLbZ51S1MlieByH?p=preview 
click Filter Back couple times

**Comment by nmccready** [comment]
I can dig into this eventually but a spec added to check this would be ideal. That way it would have not happened to begin with.

**Comment by nmccready** [comment]
@ws-perelyaynen to help narrow it down did anything between 0.7.11-0.7.15 work?

**Comment by nmccready** [comment]
Also on rawgit instead of using sha# use:

`//cdn.rawgit.com/tombatossals/angular-leaflet-directive/v0.8.1/dist/angular-leaflet-directive.js`

**Comment by MarkAPhillips** [comment]
I had this problem also but thought it was an issue with my code - so refactored it to behave as expected (not the directive but my underlying js code). Thanks for spotting this @ws-perelyaynen.

**Comment by nmccready** [comment]
I found the issue I think. The _destroy code does not delete models that have not changed. However, the create code creates existing models. The _addMarkers code needs that same check. Basically it is creating dupes and keeps growing.

**Comment by nmccready** [comment]
Missing code logic (invert) for _addMarkers.
https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/markers.js#L128-L140

**Comment by Getz85** [comment]
Same problem here with 0.7.11 and 0.8.2.

I don't really understand how we can fix that when you say:

> the fix is simple .. copy the logic from _destroy

I tried to adapt the lines you indicate but completely fail...

Any help please?

**Comment by nmccready** [comment]
I might have some time this weekend. I'll try and look at it.

**Comment by nmccready** [comment]
Started working no this here https://github.com/realtymaps/angular-leaflet-directive/commit/74e80f554ce170b5f999153f8b1d14b03c3da50d

**Comment by nmccready** [comment]
I finished this mostly but I am having trouble getting the spec to pass. However the plunkr example is working.

**Comment by nmccready** [comment]
@Getz85 @MarkAPhillips @ws-perelyaynen see #796
