### ISSUE TITLE
Add layer to overlay layer

### ISSUE THREAD

**Issue by chriseyhorn** [tombatossals/angular-leaflet-directive#767]
I have created an overlay layer:
```
layers: {
      overlays: {
          myOverlayLayer: {
            name: 'Overlay Layer',
            type: 'featureGroup',
          },
```
When I try:

`$scope.layers.overlays.myOverlayLayer.addLayer(newLayer);`

I get an error that 'addLayer' is undefined.  

Ideally I want to setup some overlay layers that I can add other layers to dynamically and then have the user hide/show them using the layers control.

Thanks in advance!

Best Regards,
Chris

**Comment by vool** [comment]
Hi Chris,

You can add the overlays like this 

```
 layers: {
      overlays: {},
 ```

and then later 
```
var olays = { cars: {
                        name: 'Cars',
                        type: 'group',
                        visible: true
                    },
                    bikes: {
                        name: 'Bicycles',
                        type: 'group',
                        visible: false
                    }
};

 angular.extend($scope.layers['overlays'], olays);
```

**Comment by nmccready** [comment]
@vool is correct

**Comment by chriseyhorn** [comment]
What is the proper way to access the added layers later on so I can add to them and show/hide?

**Comment by nmccready** [comment]
Use your scope definition.

`layers.overlays.layer1.visible = false`

**Comment by nmccready** [comment]
This is in the exampels

**Comment by chriseyhorn** [comment]
Thank you.
