### ISSUE TITLE
Support fitBounds options

### ISSUE THREAD

**Issue by ValentinH** [tombatossals/angular-leaflet-directive#770]
In Leaflet, the fitBounds is defined like this:
```js
fitBounds( <LatLngBounds> bounds, <fitBounds options> options? )
```
http://leafletjs.com/reference.html#map-fitboundsoptions
but in this directive, there is no way (AFAIK) to specify these options.

Do you think it would be a good idea to support this? I can try to make a pull request.

**Comment by nmccready** [comment]
There is a way, use leafletData to get the map instance and then set fitBounds. There might not be a current angular way to do it.

**Comment by ValentinH** [comment]
The goal is to declare it like this in my controller:
```js
{
   markers: {}
   bounds: {
      northEast: {},
      southWest: {},
      options: {
          padding: [50, 50]
      }
   }
}
```

**Comment by nmccready** [comment]
Ok, feel free to look at the leaflet.js directive and add it in and make a PR.

**Comment by ValentinH** [comment]
Ok I'm doing it
