### ISSUE TITLE
[leafletMapDefaults] Setting {trackResize: false} does not work

### ISSUE THREAD

**Issue by adgoncal** [tombatossals/angular-leaflet-directive#772]
I noticed that if I set {trackResize: false} on map defaults, map.options.trackResize is still true and the resize event is still triggered.

Example:

```javaScript
angular.module('SomeModule', []);
angular.module('SomeModule').controller('SomeController', someController);

function someController($scope, leafletData) {
    angular.extend($scope, {
        defaults: {
            trackResize: false
        },
        center: {
            lat: 0,
            lng: 0,
            zoom: 1
        },
        layers: {
            baselayers: { ... }
        }
    });

    leafletData.getMap('mapID').then(function(map) {
        console.log(map.options.trackResize);
    });
}
```

Looking at the source code, it is clear that only a subset of the possible options are actually used on leafletMapDefaults.setDefaults. Wouldn't it be better to use angular.extend on the defaults that angular-leaflet-directive creates and the options that the user passes to the defaults object?

Something like this:
```javaScript
// ...
setDefaults: function (userDefaults, scopeId) {
    var newDefaults = _getDefaults();

    // Extend the defaults with userDefaults
    newDefaults = angular.extend({}, newDefaults, userDefaults);

    var mapId = obtainEffectiveMapId(defaults, scopeId);
    defaults[mapId] = newDefaults;
    return newDefaults;
}
// ...
```

**Comment by jancel** [comment]
+1

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#62

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
