### ISSUE TITLE
loading a ng-repeat

### ISSUE THREAD

**Issue by nourissam** [tombatossals/angular-leaflet-directive#776]
Error: [$compile:ctreq] http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=leaflet&p1=markers
R/<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:6:417
L@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:56:127
L/<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:56:193
r@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:7:300
L@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:56:170
B@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:59:293
g@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:51:335
B@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:59:199
g@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:51:335
B@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:59:199
g@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:51:335
D/<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:50:444
P/<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:52:322
k@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:56:322
ne</<.compile/</<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:234:428
Pe/this.$get</n.prototype.$watchCollection/<@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:122:281
Pe/this.$get</n.prototype.$digest@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:123:354
Pe/this.$get</n.prototype.$apply@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:126:291
l@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:81:238
M@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:85:342
wf/</F.onload@https://localhost:1443/apps/front-app/lib/angular/angular.min.js:86:367

https://localhost:1443/apps/front-app/lib/angular/angular.min.js
Line 102

**Comment by tombatossals** [comment]
Please, we need an example which provides information about a bug of the directive. Take a look at this document:
https://github.com/tombatossals/angular-leaflet-directive/wiki/MCVE

Reopen the issue if needed, thanks.
