### ISSUE TITLE
Run the example site on the latest version of angular-leaflet-directive

### ISSUE THREAD

**Issue by ValentinH** [tombatossals/angular-leaflet-directive#783]
The example site still runs on the 0.7.X version and it is confusing. 

For instance, I noticed the #758 on my application but I thought I was doing something wrong since the example was working fine. Running it in local, showed me it was a problem with the directive.

Is it possible to run the example website on the master version?

**Comment by tombatossals** [comment]
Yes of course, I have just updated the library version to the trunk.

Thanks for reporting.
