### ISSUE TITLE
Changes of marker model leads to duplicated markers on map

### ISSUE THREAD

**Issue by laz2** [tombatossals/angular-leaflet-directive#786]
Suppose we have 2 markers. If we will change label of first marker, then directive markers will duplicate second marker on map.

Problem inside function `_destroy` in `markers.js`. It doesn't clear argument `markerModels` from old markers and then `_create` calls `_addMarkers` with existent markers. Or `_addMarkers` should prevent duplicates.

**Comment by nmccready** [comment]
This is already know and planned to be fixed. see #766 . I believe this is the same exact problem.

**Comment by nmccready** [comment]
You're correct _addMarkers is the issue and I documented it in #766 the fix is simple .. copy the logic from _destroy
