### ISSUE TITLE
Heatmap options changing during run time

### ISSUE THREAD

**Issue by alexus37** [tombatossals/angular-leaflet-directive#792]
Hi, 
I am trying to change the the options of my heatmap overlay during the run time. Basically I am trying to 
adapted the layeroption size depending on the zoom level. 
```javascript
$scope.$watch("city.zoom", function(zoom) {
                var lowBound = 25;
                var fac = 18 - zoom;
                $scope.layers.overlays.heatmap.layerOptions.size = lowBound + (fac * 100);
            });
```

The problem is that the size is not changing. Could it be that the layeroptions are not watched? Is there any work around for that specific problem? Thanks for your help guys!!

**Comment by tombatossals** [comment]
You haven't attached how the heatmap layer is created. The layers object is watched deeply and must change with attribute changing, but maybe somethings wrong. Please, can you show this behaviour in a jsfiddle?

https://github.com/angular-ui/angular-google-maps/wiki/MCVE

You can start with this jsfiddle:
http://jsfiddle.net/maistho/9jymzymu/

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#64

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
