### ISSUE TITLE
Give markers another option to update the popup layout after loading compiled content without ngInclude

### ISSUE THREAD

**Issue by sibbl** [tombatossals/angular-leaflet-directive#793]
I do have the problem that after compiling the marker popup content, the size of the popup is not re-calculated. Afaik the popup size is only updated when the message includes the string "ngInclude".

In my eyes, that's not enough since I use a custom directive for the message (which of course does not have "ngInclude" in it), but loads a template anyway. Like:

      message: '<my-directive-that-includes-a-template param="' + param + '"></my-directive-that-includes-a-template>',

I'd love to be able to set "marker.watchForContentLoad = true" and have the angular leaflet directive also watch for the "$includeContentLoaded" event as well. Only looking for "ngInclude" in the message string looks promising, but is not enough.

**Comment by jessertaylor** [comment]
#800

**Comment by sibbl** [comment]
Thanks for fixing it! Just a small question: how long does it take to bower recognize the new version 0.8.4? Bower install still has 0.8.3. Hope you can give me a small hint. Thx :)

**Comment by sibbl** [comment]
Seems like the 0.8.4 tag is missing at the release commit. Has nothing to do with this issue, so will open another one. Thanks again :+1:

**Comment by jessertaylor** [comment]
you can specify master until a release is made.

**Comment by nmccready** [comment]
Its resolved.
