### ISSUE TITLE
Depend on leaflet-dist instead of leaflet for bower

### ISSUE THREAD

**Issue by flibbertigibbet** [tombatossals/angular-leaflet-directive#795]
The plugin dependencies, such as [leaflet.draw](https://github.com/Leaflet/Leaflet.draw/blob/master/bower.json), depend on `leaflet-dist` instead of `leaflet`.

**Comment by nmccready** [comment]
leaflet-dist isn't even up to date. It comes from here https://github.com/vperron/leaflet-dist and is on 0.7.2 and were using 0.7.3

**Comment by flibbertigibbet** [comment]
The plugins that depend on leaflet-dist have presumably only be tested against its version.

**Comment by nmccready** [comment]
Well, I can't please everyone. You can override deps in your bower.json.

**Comment by nmccready** [comment]
@tombatossals thoughts?

**Comment by flibbertigibbet** [comment]
Ok, I guess there's not really a good way around the proliferation of Leaflets.

On further investigation, it looks like several plugins use `leaflet` instead of `leaflet-dist`, and that the Leaflet plugin docs actually list `leaflet` as a dependency in their example.  On explicitly bower-installing some `leaflet-dist` dependent plugins, both versions of Leaflet were getting installed via bower, which meant having to add extra exclusion rules for `wiredep` to not go add them all, out of order.

**Comment by nmccready** [comment]
I'd bring this up with the plugin leaflet.draw
