### ISSUE TITLE
Leaflet.Minimap plugin 

### ISSUE THREAD

**Issue by nurseymybush** [tombatossals/angular-leaflet-directive#797]
I was wondering if someone knew how to get the leaflet minimap plugin to work in angular leaflet? right now i have 

```javascript
angular.extend($scope, {

controls: {
            MiniMap: {
                layer: 'osm2'
            }
        }
```
Thanks for your help

**Comment by elesdoar** [comment]
Hi, please see: https://github.com/elesdoar/angular-leaflet-directive/blob/master/examples/0404-controls-minimap-example.html

It's pending PR #798

**Comment by nurseymybush** [comment]
Thanks for your reply, i really appreciate it! Here is a fiddle that i was
using to test the minimap and I changed it to match the file you pointed me
to but it still doesnt work...
https://jsfiddle.net/cnurseyb/rt3bvfsq/170/
Thanks for all your help

**Comment by MarkAPhillips** [comment]
```
 leafletData.getMap().then(function(map) {
      var osm2 = new leaflet.TileLayer(leafletconfig.osm.url, { attribution: leafletconfig.osm.attrib, noWrap: true });
                var miniMap = new leaflet.Control.MiniMap(osm2, {..options...});
                miniMap.addTo(map);
});
```

leafletconfig is just constants I pass in... this works on my map - as the minimap did not really have to interact with angular in any way this suited my purpose, but adding it into the angular control pipeline might be a good option but not 100% convinced this is always the best option. The leafletData getMap() promise make  the directive very extensible for many use cases which I don't think should always be included in the core directive code base.
