### ISSUE TITLE
Adding markers with ng-repeat

### ISSUE THREAD

**Issue by mahmoudmy** [tombatossals/angular-leaflet-directive#802]
In angular-openlayers-directive, the marker directive uses a <code>restrict: 'E'</code> that allows using ng-repeat on it for easy manipulation on marker style and overlays. Why isn't that useful property here?

**Comment by cyrilchapon** [comment]
Already discussed [from here](https://github.com/tombatossals/angular-leaflet-directive/issues/548#issuecomment-94796849). The conclusion is [here](https://github.com/tombatossals/angular-leaflet-directive/issues/548#issuecomment-94809191). In resume, the strategy in *angular-leaflet-directive* was chosen as opposite of *angular-openlayers-directive*, for **performance** purpose, over **conciseness**.
