### ISSUE TITLE
Version 0.8.4 cannot be installed via bower

### ISSUE THREAD

**Issue by sibbl** [tombatossals/angular-leaflet-directive#803]
I cannot install v0.8.4 because I guess the tag is missing in the commit:

    > bower install angular-leaflet-directiv#0.8.4
    bower angular-leaflet-directive#0.8.4       not-cached git://github.com/tombatossals/angular-leaflet-directive.git#0.8.4
    bower angular-leaflet-directive#0.8.4          resolve git://github.com/tombatossals/angular-leaflet-directive.git#0.8.4
    bower angular-leaflet-directive#0.8.4     ENORESTARGET No tag found that was able to satisfy 0.8.4

    Additional error details:
    Available versions: 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.15, 0.7.14, 0.7.13, 0.7.12, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0..6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.0, 0.3.3, 0.3.2, 0.3.1

**Comment by MarkAPhillips** [comment]
same issue here - thanks

**Comment by nmccready** [comment]
Yes I forgot to push, its there now.
