### ISSUE TITLE
The MarkerCluster plugin is not loaded.

### ISSUE THREAD

**Issue by mastermind1981** [tombatossals/angular-leaflet-directive#804]
Hi,

Thanks for your great work on the module.

I'm testing the module specially, the marker cluster part and i'm getting The MarkerCluster plugin is not loaded error. I've installed the module via bower. Am i missing a dependency or something in my code?

Thanks,

**Comment by nmccready** [comment]
You need to load the dependency yourself, via browserify, webpack, html script.. etc.

**Comment by esetnik** [comment]
@mastermind1981 I found that there is no main entry in the latest stable release (0.4.0) of the leaflet.markercluster bower configuration.

```
bower info leaflet.markercluster
bower cached        git://github.com/Leaflet/Leaflet.markercluster.git#0.4.0
bower validate      0.4.0 against git://github.com/Leaflet/Leaflet.markercluster.git#*

{
  name: 'leaflet.markercluster',
  homepage: 'https://github.com/Leaflet/Leaflet.markercluster',
  version: '0.4.0'
}

Available versions:
  - 0.4.0
  - 0.4.0-hotfix.1
```

You need to use `0.4.0-hotfix.1`

See https://github.com/Leaflet/Leaflet.markercluster/commit/b66b9d72de0186735a620589667b9713c1b405cb
