### ISSUE TITLE
2 Markers layers with dynamic markers creation intersect

### ISSUE THREAD

**Issue by gsimenel** [tombatossals/angular-leaflet-directive#805]
Hi,
I want to have 2 markers layers, one static, the other one with markers that can be created by the user. I came up with the code in the Fiddle below, when you click on the map you can add a marker, when you right click it gets removed. 

The issue is that when you add markers, the markers from the other layer (the static one) disappear one after the other. When you remove the added markers, the static layer is restored progressively. 

http://jsfiddle.net/8yzu181e/

Thanks for your help.
G

**Comment by gsimenel** [comment]
Sorry the fiddle is : http://jsfiddle.net/8yzu181e/1/

**Comment by nmccready** [comment]
Yeah looks like a bug, ill check it out when I get a moment.

**Comment by gsimenel** [comment]
Thanks a lot.

**Comment by nmccready** [comment]
@gsimenel I think I see the problem. I forgot to handle the nesting in the clean routine, also leafletData needs to handle nesting as well.

**Comment by gsimenel** [comment]
Thanks a lot. Checked this in my app. Bye bye issue !
