### ISSUE TITLE
Access the map selector overlay checkboxes

### ISSUE THREAD

**Issue by jrosczyk** [tombatossals/angular-leaflet-directive#806]
Looking for a way to access the selector overlay checkboxes so I can have a custom (off map) checkbox reflect the selector's state. Any ideas?

Not working:
```
leafletData.getMap().then(function(map){
    $scope.layers.overlays['cars'].visible = map.hasLayer('cars');
});
```

**Comment by jrosczyk** [comment]
Basically, in the markers groups example instead of having a button that toggles I'm looking to use a checkbox. While the toggling works this way, the checkbox (outside the map) does not add/remove check when the overlay is controlled from the map selector.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0506-markers-groups-example.html

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#65

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
