### ISSUE TITLE
Dragging on mobile

### ISSUE THREAD

**Issue by yourilefers** [tombatossals/angular-leaflet-directive#807]
When we use the directive version 0.8.4 with leaflet version 0.7.3 or 0.8.x/1.0.x, it won't drag on mobile. Our application has a responsive design, so it must work either on the desktop and on a mobile device. On the desktop it works well, but mobile we cannot drag the map and or double tap to zoom.

Our config (markers are added manually):
```
$scope.map = {

        // Center
        city: {
            lat: 52.216667,
            lng: 6.883333,
            zoom: 13
        },

        // List of markers
        markers: {},

        // Default settings
        defaults: {
            scrollWheelZoom: true,
	        tileLayer: 'http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png',
	        tileLayerOptions: {
		        detectRetina: true,
		        reuseTiles: true
	        }
        }

    };
```

One of our markers:
```
{
    "id": "van_heekgarage",
    "title": "Van Heekgarage",
    "max": 1650,
    "free": 209,
    "lastUpdate": "1434619535220",
    "lat": 52.21714401245117,
    "lng": 6.898071765899658,
    "icon": {
        "iconUrl": "img/markers/parkinggarage.png",
        "iconSize": [
            32,
            37
        ],
        "iconAnchor": [
            16,
            37
        ],
        "popupAnchor": [
            0,
            -37
        ]
    },
    "message": "<h4>Van Heekgarage</h4>Aantal vrij: 209<br>Totaal: 1650"
}
```

Fyi; the markers are visible and clickable on the 0.7.3 version of leaflet. The 0.8.x/1.0.x version of leaflet doesn't work.

**Comment by nmccready** [comment]
I only see 0.7.3 as a valid release. If there are more versions where do you find them? https://github.com/Leaflet/Leaflet/releases

**Comment by yourilefers** [comment]
I've also tested with the dev release.
http://leafletjs.com/download.html

**Comment by anthonytison** [comment]
Any progress on this issue ??

**Comment by Wilzi** [comment]
It's works well for me.
Make sure you've set all the dragging settings true.

`dragging: true,
touchZoom: true,
scrollWheelZoom: true,
doubleClickZoom: true`

http://leafletjs.com/reference.html#map-dragging

Could you please provide a JSfiddle?

**Comment by dsifford** [comment]
I'm having this issue as well. Not able to pan the map using chrome devtools touch emulation. 

```js
  angular.extend($scope, {
        center: {
          autoDiscover: true,
          zoom: 6
        },
        layers: {
          baselayers: {
              base: {
                  name: 'Base',
                  url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
                  type: 'xyz',
                  layerOptions: {
                      apikey: 'xxxxxxxxxxxxxxxxxxx',
                      mapid: 'xxxxxxxxxxxx',
                      showOnSelector: false,
                  }
              }
          },
          overlays: {
            flightPaths: {
              name: 'Local Flight Area',
              type: 'group',
              visible: true,
              layerParams: {
                // showOnSelector: false, TODO: Add custom box for selectors
              }
            }
          }
      }
    });
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#66

**Comment by dsifford** [comment]
Hi @nmccready -- Sorry I didn't chime back on this. I managed to figure out what was going on a while ago but I'm forgetting exactly what it ended up being..

I want to say it had to do with touch events propagating up the DOM (but I could be wrong; I had a few issues with mobile touch events during the course of putting together my angular site).

**Comment by nmccready** [comment]
ok @dsifford well if more comes to mind to hesitate to respond on here.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
