### ISSUE TITLE
Bounds undefined

### ISSUE THREAD

**Issue by kripton69** [tombatossals/angular-leaflet-directive#808]
I have a L.layerGroup() and set layers in the group. The problems is, if I change the template and go back to the map I have a ERROR: bounds is undefined or ERROR: this._map._pathRoot is undefined. Any solution?

**Comment by nmccready** [comment]
Can you provide the example to test against? It saves the developers have the work.

**Comment by kripton69** [comment]
My web app is to much complex to make jsfiddler example. Basically I get via websocket coordinated for the new one and add it to layer. If I do not change model it shows fine. But when I change the template and return to the map errors occur. If I do clearLayers () and try addLayer () gives ERROR: bounds is undefined.

**Comment by kripton69** [comment]
What are these "bounds"?
If I make getBounds() he have bounds. But when I make map.addLayer() give me a ERROR: bounds is undefined.

**Comment by nmccready** [comment]
Please give me something to play with; https://github.com/angular-ui/angular-google-maps/wiki/MCVE .

**Comment by nmccready** [comment]
update?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#67

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
