### ISSUE TITLE
Grouped Layer Control

### ISSUE THREAD

**Issue by jrosczyk** [tombatossals/angular-leaflet-directive#810]
This would be a nice option to bring in:
https://github.com/ismyrnow/Leaflet.groupedlayercontrol

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
