### ISSUE TITLE
Updating markers doesn't appear to be possible

### ISSUE THREAD

**Issue by cgat** [tombatossals/angular-leaflet-directive#812]
Lots of change in this directive in the last couple months. I'm trying to play catch up and update a fork I had created a while ago.

My fork added the ability to use watchCollection on the markers object. That is, if a marker reference changed the markers directive's _create function would be called with the new and old markers. This really doesn't seem to be much different than using the new leafData.getDirectiveControls function to grab the controls for the markers and manually control the creation of markers (with the obviously difference that one is triggered by a watch and the other one is done manually).

After integrating 0.8.4 into my fork, the ability to update a marker seems to be lost. The same behaviour is exhibited by using the getDirectiveControls method, so I'll focus on that as an example since it is currently supported.

Let's start with this plunkr: http://plnkr.co/edit/uxCAVo0CItz7VmOYbYZC?p=preview

There are a couple things going wrong here, but I'll start with the marker update. The expected behaviour is the marker's position and attributes are updated. From the source, this is what I can figure out is happening:
1) call create on new and old
2) _clean gets called. which calls _destroy, which uses _seeWhatWeAlreadyHave to decide what to delete. _seeWhatWeAlreadyHave, in this case (when the isEqual arg is set to false) executes the callback on markers that no longer exists in the new markers list. So in our example, nothing gets deleted (marker1 still exists). Sidenote: this will log a debug statement  "[AngularJS -Leaflet] [markers] destroy:" to the console. Why? Nothing is getting deleted in this case.
3) _getNewModelsSkipp is called (note the spelling error). This uses _seeWhatWeAlreadyHave as well, but with isEqual set to true. It finds that the new marker1 and old marker1 are not equal, so it does not add it to the skips list.
4) _addMarkers is called. This loops through the markersToRender, but will skip stuff from step 3 (models that have not changed). Here's where I get confused. If the leaflet marker already exists, this function does nothing. The result is that the marker doesn't get updated. I don't fully understand this comment:

    //(nmccready) very important to not have model changes when lObject is changed
    //this might be desirable in some cases but it causes two-way binding to lObject which is not ideal
    //if it is left as the reference then all changes from oldModel vs newModel are ignored
    //see _destroy (where modelDiff becomes meaningless if we do not copy here)

so if you could elaborate I would appreciate it.

One thing I noticed is that addMarkerWatcher is leafletMarkersHelpers contains a lot of logic to handle the updating of a marker and clusters. This seems to be ignored in this workflow.

There other bug I noticed that you'll see in the plunker is that popups don't work. You'll see the error message "[AngularJS - Leaflet] Popup is invalid or does not have any content." in the console. I tried to figure this one out as well, but didn't get too far. When a leaflet marker initially issues a bindPopup(...), it gets the property _popup which contains some basic properties like _content, but no _contentNode. In the popupopen callback below, the marker does have _popup._contentNode. However, in other places (addMarkerWatcher is where I noticed), the marker object that gets closed over the function does not have _contentNode. Sorry if this doesn't make sense.

    listenMarkerEvents: function (marker, markerData, leafletScope, doWatch, map) {
            //these should be deregistered on destroy .. possible leake
            //handles should not be closures since they will need to be removed
            marker.on("popupopen", function (/* event */) {
                safeApply(leafletScope, function () {
                    if (isDefined(marker._popup) || isDefined(marker._popup._contentNode)) {
                        markerData.focus = true;
                        _manageOpenPopup(marker, markerData, map);//needed since markerData is now a copy
                    }
                });
            });
            marker.on("popupclose", function (/* event */) {
                safeApply(leafletScope, function () {
                    markerData.focus = false;
                });
            });
            marker.on("add", function (/* event */) {
                safeApply(leafletScope, function () {
                    if ('label' in markerData)
                        _manageOpenLabel(marker, markerData);
                });
            });
        },

**Comment by nmccready** [comment]
Probably related to #805 #789

**Comment by cgat** [comment]
Thanks. I've attempted to fix this: https://github.com/cgat/angular-leaflet-directive/tree/updating-markers (added comment to #789 as well).

In regards to the popup issue, I've dug into this a bit more. The general issue is that when bindPopup is used on a marker, it recreates the L.Popup object. This object is without the _contentNode property until it is added to the map. Specifically, when L.Popup's onAdd method gets executed. It's unclear to me where exactly this gets triggered, potentially in a leaflet callback. Anyway, the markers.js and leafletMarkersHelpers.js are littered with bindPopup's followed eventually followed by manageOpenPopup. This function relies on _contentNode to be able to compile, and logs an errors and returns when it's not present.

**Comment by jessertaylor** [comment]
@cgat I recently added the log message - it was just returning nothing before. Maybe it should not log an error there - but I do think that _manageOpenPopup should not be called until the popup has been added to the map - how can it open the popup when it's not even on the map? It seems by me adding the log message it has revealed that it is being called when it should not be.

**Comment by cgat** [comment]
@jessertaylor yes, I came to the same conclusion. As you pointed out, _manageOpenPopup only really works on the listen event.

I think I've found a solution. I've removed all occurrences of manageOpenPopup with the exception of the one in the popupopen listener and replaced them with marker.openPopup(). This way, the popup is still opened as requested, and the compilation occurs when the popup is opened. This seems to do the trick on my example, but I'm unsure about other scenarios (e.g. when the marker changes layer). I'm going to add my changes to the current PR that I'm building. Please let me know what you think.

**Comment by jessertaylor** [comment]
@cgat That actually makes sense, good job. I think the only case popups should be opened by the directive is when when focus is set to true, right?

**Comment by cgat** [comment]
@jessertaylor exactly. See the latest commit on my updating-markers2 branch https://github.com/cgat/angular-leaflet-directive/commit/360401243f3f6d645860355b2c0067db6c55218a

Pretty simple

**Comment by nmccready** [comment]
:+1:

**Comment by jessertaylor** [comment]
@cgat Well that should stop _manageOpenPopup running twice :ok_hand:

**Comment by nmccready** [comment]
So is this close to a PR, im curious if the other issues get resolved. I am kina waiting on this one before I dig into those if need be.

**Comment by jessertaylor** [comment]
@cgat thanks, your PR has been merged
