### ISSUE TITLE
Marker positions don't update when dragging them

### ISSUE THREAD

**Issue by timesqueezer** [tombatossals/angular-leaflet-directive#814]
I recently discovered that dragging markers would'nt update their longitude and latitude.
As it appears to be happening on the example pages too, I think it is a general bug.
http://tombatossals.github.io/angular-leaflet-directive/#!/examples/dragging-markers

**Comment by nmccready** [comment]
Confirmed.

**Comment by jessertaylor** [comment]
Is this a dupe of #690 ?

**Comment by nmccready** [comment]
Yes dupe, closing.
