### ISSUE TITLE
Map not refreshing after state change

### ISSUE THREAD

**Issue by itree** [tombatossals/angular-leaflet-directive#818]
Ok, I have being stuck on this for over 2 weeks now.  I am using the directive in Ionic.  However, at this point I am pretty certain that the problem is with the directive and how it refreshes it self.  I have a screen shot of the bug, but not sure how to fix it.  This happens when I create 2 states.  

1. with the angular-leaflet-directive
2. Just any state with a button that calls a modal.  

Go to state 1 the map is fine.  
Now go to state 2 and click the button and open the modal.  Close the window and in the menu go to the state 1 (the map). 

Now the map looks all screwed up.  See screenshot attached. 
![fr_3793_size880](https://cloud.githubusercontent.com/assets/370009/8321272/b675f252-19f2-11e5-809f-efe0ffd24a46.jpg)

(If I turn phone the orientation landscape <-> portrait. It fixes the problem.  But that will not be an option in production (as we will need to lock the screen orientation).  How can I get the map to just refresh and behave.  Any pointer appreciated. 

I have even created a repository of the bug that you can check out. 

https://github.com/itree/leaflet-refresh-issues

**Comment by nmccready** [comment]
@itree when you go to state 2 you need some scope boolean to track and turn it to true. Then 

```
<div ng-if="isState2">
<leaflet/>
</div>
```

This has been asked in many issues but ng-show or hide or hiding the map in anyway will always bork the map. You are better off using ng-if. Otherwise you need the map instance and tell it to resize or invalidate.

http://stackoverflow.com/questions/24412325/resizing-a-leaflet-map-on-container-resize

**Comment by producerism** [comment]
Any chance you could elaborate on the ng-if method?

This is the current map.html template I'm using, in case it helps:
    <ion-view view-title="Map">
    
      <ion-nav-buttons side="primary">        
        <button class="button icon ion-ios-arrow-back button-icon" ng-click="goBack()"></button>
      </ion-nav-buttons>
    
      <ion-nav-buttons side="secondary">        
        <button class="button icon ion-navicon-round" ng-click="goBack()"></button>
      </ion-nav-buttons>
    
      <ion-content data-tap-disabled="true">
    
        <leaflet defaults="map.defaults" center="map.center" markers="map.markers" layers="map.layers" ng-if="map"></leaflet>
    
      </ion-content>
    </ion-view>

I assume that you are saying that I would just add something like

    $scope.isMapState = true

into my MapController.js ... but I don't see how that would solve the problem. The leaflet directive is only in this map.html template, so each time it is displayed, it will always get $scope.isMapState = true. Since no other templates are using the directive, won't $scope.isMapState always be true (and only even checked when loading the map template anyways)?

**Comment by itree** [comment]
Hey guys, thanks for the response. I had to do some klug to make it work for now.  I'll check out your suggestion.  If you can 

What I found out is that if I call to close the modal 

        $scope.tagTypeModal.hide().then(function() {
            $ionicHistory.clearCache();
        });

Then the map will work again.  

@nmccready if you can elaborate a bit more on the ng-if state that would be great. Also FYI, I'm not showing or hiding the map specifically.  But rather using the state change.  Also just plain state change does NOT cause the problem. Only if state change in combination with a modal and closing of that modal, and then switch back to the map state, that will cause the map to be not responsive.

**Comment by nmccready** [comment]
Anyway you guys can produce an example that I can mess with?

**Comment by joeystandrew** [comment]
I am having this same issue in my Ionic application, I will try and post an example when I get some free time.

I am currently using the "ng-if" fix in my application and it seems to work, but feels kinda dirty to me, also changing orientation seems to fix the issue.

**Comment by itree** [comment]
Hey @nmccready, 

have you look at  https://github.com/itree/leaflet-refresh-issues ? 

You will need an android or iphone to test.  I believe this error only show up on smart phones.  It has something to do with the way the keyboards show up in a modal view on smart phones. 

There for the issue will not show up in browsers.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by itree** [comment]
Thanks @tombatossals.  I think THE MOST IMPORTANT function/feature is to have the leafletjs map work in different states and/or restore to previous state when hidden.  

Right now it works ok if it is in an hybrid/html5 app with only one page/state, but as soonest we introduce more than one page/state, the map gets messed up.

**Comment by 2msd** [comment]
In case anybody is interested in this, I solved my problem (map destroyed as above on showing ads on a view other than map...i know it sounds crazy;) like this:

``` javascript
$scope.$on('$ionicView.afterEnter', function(e) {
    // Prevent destroying of leaflet
    if($state.current.name == 'app.map') {
        ionic.trigger('resize');
    };
});
```

see driftyco/ionic#3233

**Comment by itree** [comment]
Thanks @2msd for the tip. I have taken a break from all these bloated frameworks like ionic/angluar and found a really nice/lightweight alternative http://mithril.js.org 

I'm going to try just plain leaftleat js in there and have total control of the hide and show/refresh of the map.

**Comment by MrHakala** [comment]
Any other suggestions for workarounds?

**Comment by ghost** [comment]
In my case, markers are added successfully even popup also works fine on click but map is not being displayed. any idea why this is happening.
Thank You

**Comment by ghost** [comment]
@2msd what did you mean by 'map destroyed as above on showing ads on a view other than map'? Does that mean that you did something else than the piece of code you put in that comment?

**Comment by 2msd** [comment]
@kennethvandenberghe sorry, I'll try to explain it better.

I have a mobile app with cordova and ionic.
I have a view with a list, and a view with the map.
I show Ads from time to time.

When Ads are shown on the list view, if you switch to the map view. then you see exactly the problem described here.

To prevent this, I use the stated code.

**Comment by Alkasih** [comment]
```
  `  $ionicHistory.clearCache();`
```

Solve it.
