### ISSUE TITLE
Version 0.8.4 marker focus=true not working

### ISSUE THREAD

**Issue by Diones** [tombatossals/angular-leaflet-directive#819]
When using 0.8.3 and marker `focus = true`, the popup shows up and I got no error on console. However, updating to 0.8.4, the same code shows `error    [AngularJS - Leaflet] Popup is invalid or does not have any content.` and popup marker initialize hidden on map.

http://jsfiddle.net/mzowsqzb/ - Check dev console

**Comment by cgat** [comment]
Fixed in master by this PR https://github.com/tombatossals/angular-leaflet-directive/pull/813

**Comment by Diones** [comment]
Test using master: OK!

Working again.

Thank you.

**Comment by nmccready** [comment]
I might cut a new release today but I still need to add cgats commit msg and bump the current milestone work.

**Comment by nmccready** [comment]
@jessertaylor just including you so u know what is going on.

**Comment by jessertaylor** [comment]
:+1:
