### ISSUE TITLE
Adding search control gives 'addTo is not a function'

### ISSUE THREAD

**Issue by pieterjandesmedt** [tombatossals/angular-leaflet-directive#822]
Hi,

I'm trying to add [stefanocudini's search control](https://github.com/stefanocudini/leaflet-search) to the controls with:
```javascript
var controls: {
	custom: [
		new L.Control.Search({
			url: 'http://nominatim.openstreetmap.org/search?format=json&q={s}',
			jsonpParam: 'json_callback',
			propertyName: 'display_name',
			propertyLoc: ['lat','lon']
		})
	]
}

angular.extend($scope, {
	controls: controls
}
```
but I get an error saying
```
TypeError: control.addTo is not a function at L.Map.include.addControl
```
The search control does have its function `addTo` defined though. What am I missing here?

**Comment by pieterjandesmedt** [comment]
When I extend the scope with just the search control parameters and add this in the `controls` directive (and the corresponding `isLoaded()` check in `LeafletHelpers`), it works though:
```javascript
if (isDefined(controls.search)) {
    if (leafletHelpers.SearchControlPlugin.isLoaded()) {
        var searchControl = new L.Control.Search(controls.search);
        map.addControl(searchControl);
    } else {
        $log.error(errorHeader + ' Search plugin is not loaded.');
    }
}
```
Does this mean the directive has to be changed every time someone needs to add a new kind of control? I thought the `controls.custom` part was meant to catch this...

**Comment by nmccready** [comment]
@pieterjandesmedt do you want to create another issue for controls.custom to handle it more dynamically? I will close this issue since your PR is through.

**Comment by pieterjandesmedt** [comment]
No it's ok. I'm going to investigate why custom plugins aren't created as expected and submit a PR when I find something.

**Comment by nmccready** [comment]
cool

**Comment by matt-bradley** [comment]
@pieterjandesmedt did you figure out what the issue was here with the custom controls? 

I am have the same issue with my own control and no so keen to start changing the controls directive if I don't have too.
