### ISSUE TITLE
"Single marker example" example not working?

### ISSUE THREAD

**Issue by pglotov** [tombatossals/angular-leaflet-directive#828]
While trying to debug an issue in my code I tried one of the examples

http://tombatossals.github.io/angular-leaflet-directive/examples/0500-markers-simple-example.html

and it doesn't seem to work, the marker can be dragged but its lat/lon value numbers in the bottom of the screen don't change. Is this by design?

**Comment by tombatossals** [comment]
Yess, the examples wasn't in sync with the last changes to the library. I have updated them.

The change is that now you can specify the events that you want to enable in the markers, for example:

```
events: {
    markers:{
        enable: [ 'dragend' ]
    }
}
```
