### ISSUE TITLE
stoppropagation and preventdefault on custom controls

### ISSUE THREAD

**Issue by HarelM** [tombatossals/angular-leaflet-directive#834]
Hi, first and foremost, great project! 
I'm not sure if this is an issue or I'm doing something wrong but I have created a custom control.
this control is generated from $compile with template and scope.
now I want to prevent the propagation of ng-click event but I can't seem to be able to do it.
the creation is done in onAdd:
```js
var container = L.DomUtil.create("div", "my-container");
var innerElement = L.DomUtil.create("div", "", container);
innerElement.setAttribute("ng-include", "'views/my.html'");
var newScope = $scope.$new();
... manipulate scope ...
$(".my-container").html($compile(innerElement)(newScope)));
return container;
```

now when using ng-click on the custom control I can't find a way to prevent the event from propagating...
any thoughts?

Thanks,
Harel M.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#80

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
