### ISSUE TITLE
create an editable path with hovering end

### ISSUE THREAD

**Issue by HarelM** [tombatossals/angular-leaflet-directive#835]
I'm trying to achieve with this directive the following: (ignore the routing)
http://brouter.de/brouter-web/
In order to do it I create two paths:
1. the path I add the points to when the user clicks.
2. the path that will be used to hover.
Creating the first path is easy and works great (using the click event)
When creating a path that changes every hover event the map stops behaving as expected and event are not propagated.
I'm not so good with fiddler, but if you can give me a base fiddler that works with this map I can change it hopefully to present the issue.
I think the issue is with the digest cycle because when I use the native map API I can achieve what I want...

Thanks,
Harel M.

**Comment by jessertaylor** [comment]
Fork this and produce a MCVE http://plnkr.co/edit/EGloZdeEO4CNN8uZDlLr?p=preview

**Comment by HarelM** [comment]
please loot at:
http://plnkr.co/edit/PrcZDUv6SALFsFN1jYTo?p=preview
I have left a comment where the event is not working:
```// this does not get called...```
It is clear enough?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#81

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
