### ISSUE TITLE
Website: links to standalone examples are broken

### ISSUE THREAD

**Issue by sknebel** [tombatossals/angular-leaflet-directive#836]
E.g. on [simple-map example](http://tombatossals.github.io/angular-leaflet-directive/#!/examples/simple-map) page at the bottom there is a link pointing to [here](http://tombatossals.github.io/angular-leaflet-directive/examples/simple-example.html), which is returns a 404.

**Comment by tombatossals** [comment]
I have updated all the broken links, thanks for reporting.
