### ISSUE TITLE
Marker clusters not updating on marker updates

### ISSUE THREAD

**Issue by ruben1** [tombatossals/angular-leaflet-directive#837]
I'm using leaflet.markerCluster for clustering markers. The problem is that clusters don't update when I update add/remove markers. The only thing that happens is that the number of markers add up. If I have initially 2 markers, then I remove and then I add them back. The number in the cluster will be 4. 

Is this a known problem and are there any solutions? Thanks.

**Comment by tombatossals** [comment]
Please, provide a jsfiddle where this behaviour can be reproduced.

https://github.com/tombatossals/angular-leaflet-directive/wiki/MCVE

http://jsfiddle.net/maistho/9jymzymu/
http://plnkr.co/edit/EGloZdeEO4CNN8uZDlLr?p=preview

**Comment by ruben1** [comment]
http://jsfiddle.net/maistho/9jymzymu/

All working. It must be my app then. Thanks.
