### ISSUE TITLE
Marker position binding is not updated when dragging a marker

### ISSUE THREAD

**Issue by HarelM** [tombatossals/angular-leaflet-directive#838]
Please see below plunker:
http://plnkr.co/edit/MyH7NOhKUCRftQKvGSQu?p=preview
When dragging the marker the position is not updated...

**Comment by tombatossals** [comment]
Hi, please take a look at this example:
http://tombatossals.github.io/angular-leaflet-directive/examples/0500-markers-simple-example.html

There's no direct binding between the markers properties and the scope for performance reasons, but you can listen to marker events to be able to get the new marker coordinates, and update its model if needed.

**Comment by HarelM** [comment]
Will it work if I change it the other way around? meaning I'll change the model behind, will it change the position on the map?

**Comment by tombatossals** [comment]
Yes, it will work if you change the lat/lng of the marker on the scope.

**Comment by HarelM** [comment]
Thanks, what field of args do I need to use when I want to update my scope while dragging, it seems that "model" is not defined - is it defined only in ```dragend```?

**Comment by ageblade** [comment]
What's the latest on this one ?
Is there any way to get the new marker position after 'dragend' ?
It looks like it is applied on a variable called 'model' however he is local and not part of the scope

**Comment by nmccready** [comment]
I don't think anyone is looking at it yet. This could be due to the model being cloned. But disabling the clone can cause update issues. So just removing cloning is not just the easy solution. Anyway feel free to dig in.

**Comment by ageblade** [comment]
For the record I was able to overcome this by listening to the ``` leafletDirectiveMarker.dragend ``` event which passes the leaflet object as an argument and has a ``` getLatLng() ``` method.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#82

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by HarelM** [comment]
Unfortunately, this directive was not adequate to my needs and I'm no longer using it.
