### ISSUE TITLE
Possible issue with Firefox  - marker._popup._contentNode.innerText is undefined

### ISSUE THREAD

**Issue by MarkAPhillips** [tombatossals/angular-leaflet-directive#841]
```
 if (marker._popup._contentNode.innerText.length < 1) {
            $timeout(function () {
                updatePopup(marker, markerScope, map);
            });
        }
```
line 2078

This is using the ng-include syntax to load a template in the popup for a marker. I have tested this on the latest version of Chrome and works as expected.

I know that Firefox did not support the innerText property and do not think it still does.

Can this check be reviewed - I assume we could also check for 'textContent'

Thanks

**Comment by jessertaylor** [comment]
If firefox uses textContent then add a check in for that.

**Comment by MarkAPhillips** [comment]
OK - code below should fix it will test locally.

I will check if innerText is being used anywhere else.

``` 
var innerText = marker._popup._contentNode.innerText || marker._popup._contentNode.textContent;
if (innerText && innerText.length < 1) {
            $timeout(function () {
                updatePopup(marker, markerScope, map);
            });
        }
```

**Comment by MarkAPhillips** [comment]
OK the above fixed the issue but the popUp content width is incorrect on FireFox also,  which is currently fixed at 51px whereas in Chrome its 235px 

```
<div class="leaflet-popup-content ng-scope" style="width: 51px;">
```

I will review and update this issue when I can,
