### ISSUE TITLE
DivIcon marker doesn't $compile the HTML inside itself

### ISSUE THREAD

**Issue by jec99** [tombatossals/angular-leaflet-directive#843]
If I am trying to create an icon from an HTML template in angular-leaflet, I use the syntax:

    icon: {
        type: 'div',
        className: 'marker-default',
        iconSize: null,
        html: '<div class="icon-container" ng-class="{icon_clicked: clicked}"></div>'
    }

where I declared `$scope.clicked` somewhere else. It seems expected behavior should be for angular-leaflet to compile the HTML inside the icon before displaying it, but it doesn't, for instance if I set `$scope.clicked = true`. Is this a bug or is this how angular-leaflet is supposed to work? If the latter perhaps it should be changed because as it is I need to `$compile` the HTML manually, which violates MVC.

**Comment by ValentinH** [comment]
I think this would be a really great feature because we would be able to display complex content inside markers! 

However, we need to find a way to provide the scope that the HTML has to be compiled with...

**Comment by woods9910** [comment]
Did you get this working with compile? If so, would you mind putting it up here? Struggling with the same thing right now.

**Comment by ValentinH** [comment]
Nope because I couldn't manage to pass the scope so far...

**Comment by woods9910** [comment]
Can anyone shed some light on this?

**Comment by ValentinH** [comment]
Managed to got a result by creating a small Leaflet plugin that works like DivIcon but take directly a dom element to be append to the marker. Then inside Angular Leaflet I add a special case to handle icon of domIcon type where I compile the template string with the scope provided through a getMarkerScope function. 

Here's the code:
> **Warning:** this is just a prototype, there seems to be some problems when updating a marker:

The Leaflet plugin:
```js
L.DomIcon = L.DivIcon.extend({
    options: {
        element: false
    },

    createIcon: function() {
        var div = this.options.element;

        this._setIconStyles(div, 'icon');

        return div;
    }

});

L.domIcon = function(options) {
    return new L.DomIcon(options);
};
```

Then inside [this block](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletMarkersHelpers.js#L31), I add the following code:
```js
if (isDefined(iconData) && isDefined(iconData.type) && isDefined(iconData.getMarkerScope) && iconData.type === 'dom') {
    var markerScope = iconData.getMarkerScope(),
        template = $compile(iconData.html)(markerScope);
    iconData.element = template[0];
    return new L.domIcon(iconData);
}
```

Then to use it inside your controller:
```js
$scope.your_variable = 'THIS WORKS';

//inside your map config object
markers: {
    osloMarker: {
        lat: 59.91,
        lng: 10.75,
        icon: {
            type: 'dom',
            iconSize: [20, 20],
            className: 'your-class',
            getMarkerScope: function() {
                return $scope
            },
            html: '<div>{{ your_variable }}</div>'
        }
    }
}
```

Any remarks are welcome. I'm still working on this to improve it and to be able to provide a templateUrl to be loaded inside the icon...

**Comment by ValentinH** [comment]
I will submit a dedicated PR tomorrow if people are interested by this feature. 

I think that this enables us to do many cool stuffs. I already tried crazy stuffs like input fields on the map or a slider for instance. I'm sure that people will find cool features to implement thanks to it.

**Comment by woods9910** [comment]
Yeah I actually switched over from google maps specifically for this feature thinking it would work. I think it would be quite useful to have interactive markers.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#83

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by ValentinH** [comment]
Actually, I submitted the PR I mentioned above and it was merged in master. It added a DomMarker plugin to handle this use case: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletMarkersHelpers.js#L70 . So this issue was already fixed I think.
