### ISSUE TITLE
[Layers directive] $watch does not handle certain changes to layer object

### ISSUE THREAD

**Issue by adgoncal** [tombatossals/angular-leaflet-directive#846]
Layer objects are watched for changes, but certain changes are not handled. 
Example: changing the url or bounds of an imageOverlay layer on the controller does not change the image src on the map.

http://plnkr.co/edit/UWrIEa9y30mDMuRtcDWN?p=preview

On the plnkr, click the button at the bottom of the page to swap image layers. It will change the layer object, which will trigger the watch on the layers directive, but will not set the url or the bounds of the image on the map. An alert box will say the angular-leaflet layer url (expected value) and the map layer url (what is actually displayed on the map).

The only way I can dynamically update the image src is using leaflet itself, which seems like a hack:
```javascript
$scope._leafletLayers.promise
          .then(function(layers) {
            layers.baselayers.image.setUrl('path-to-image');
            layers.baselayers.image._bounds = newBounds;
```

If this is not a bug, please mention it on the documentation and consider it a feature request.

**Comment by adgoncal** [comment]
I investigated the source code and found the <code>doRefresh</code> option. Setting it to <code>true</code> after the changes are made causes the layer to be removed and added back to the map. This solved my problem.

http://plnkr.co/edit/2OGVXLiHwjmCThJbgBgH?p=preview

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#84

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
