### ISSUE TITLE
Markers-watch applying to all maps

### ISSUE THREAD

**Issue by gsimenel** [tombatossals/angular-leaflet-directive#847]
Hi,
It seems that when you set markers-watch='false' to a given map it will apply to all maps on the page. See Fiddle here : http://jsfiddle.net/8yzu181e/4/ 
I've had the case where this happens across different pages (the two maps not shown at the same time but one after the other after a route change in ui-router). Using angular v1.3.15. 

Cheers.
G

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#85

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
