### ISSUE TITLE
Possible to getBounds of a layer without using leafletData.getLayers?

### ISSUE THREAD

**Issue by cly** [tombatossals/angular-leaflet-directive#848]
I have markers and paths on a map layer. Id'd like to find the bounds for this layer.

Currently, I'm resorting to using
```
leafletData.getLayers().then(function(layers) {
  var overlayLayers = layers.overlays[overlayId].getLayers()
  var bounds = new L.featureGroup(overlayLayers).getBounds();
  $scope.map.bounds = {...}
});
```

Is there a way to avoid using leafletData.getLayers to get the bounds of an overlay layer?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#86

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
