### ISSUE TITLE
routing-machine-feature-503 refresh map problem

### ISSUE THREAD

**Issue by matalaa** [tombatossals/angular-leaflet-directive#849]
Hi,

Thanks for your code on branch routing-machine-feature-503 I was able to trace a route on load 

However I have a button that should trigger the trace route on demand but its not refreshing the view, eventhough the scope contains the newly added points

in my controller I declare the mapControls
`$scope.mapControls = {
        routingMachine: {
           waypoints: []
         }
    };`

then I add the points on click event, or here on timeout event for the sake of the test

`$timeout(function() {
        $scope.mapControls.routingMachine.waypoints.push(L.latLng(-22.2682246, 166.4422263));
        $scope.mapControls.routingMachine.waypoints.push(L.latLng(-22.268562, 166.438407));
    }, 3000)`

but the map is not being refreshed

`<leaflet id="map" center="mapCenter" markers="markers" controls="mapControls" height="450px" width="100%"></leaflet>`

**Comment by tombatossals** [comment]
Hi,  I will take a look on it, but, can you provide a minimal example showing this behaviour?

https://github.com/tombatossals/angular-leaflet-directive/wiki/MCVE

http://jsfiddle.net/maistho/9jymzymu/
http://plnkr.co/edit/EGloZdeEO4CNN8uZDlLr?p=preview

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#87

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by marcelobaez** [comment]
Did anyone find a solution for this?
