### ISSUE TITLE
[Question] What is the difference between layerOptions and layerParams?

### ISSUE THREAD

**Issue by Maistho** [tombatossals/angular-leaflet-directive#852]
They seem to do the exact same thing, but depending on if it's a baselayer or an overlay. What is the reason behind them not having the same name?

**Comment by mikefedak** [comment]
I was just glancing at this code in the layer helpers service. layerOptions and layerParams are merged into the same 'options' object when the layer is created so from that point of view they are the same. However, if you look at the comments the author states that layerParams are meant to refer to the leaflet specific layer params. For example: http://leafletjs.com/reference.html#tilelayer-options you would pass as layerParams. I think layer options are library specific. So if you were using a dynamicMapLayer from esri-leaflet for instance, you would pass the library specific options in layerOptions (https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0208-layers-esri-dynamic-layer-example.html).

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
