### ISSUE TITLE
Cannot read property 'centerMapOnPosition' of undefined

### ISSUE THREAD

**Issue by VolvoOlympian** [tombatossals/angular-leaflet-directive#856]
I get "Cannot read property 'centerMapOnPosition' of undefined" with the following code on line `L.GeoIP.centerMapOnPosition(map, 15);`, am I missing something?

`.controller('CourseDetailsCtrl', ['$scope', 'leafletData',
    function($scope, leafletData) {
            leafletData.getMap('mymap').then(function(map) {
                L.GeoIP.centerMapOnPosition(map, 15);
            });
    }
])`

**Comment by sibbl** [comment]
Inject `$window` into your function and then use `$window.L` to access the leaflet namespace.

**Comment by VolvoOlympian** [comment]
Like this?
`.controller('CourseDetailsCtrl', ['$scope', 'leafletData', function($scope, $window, leafletData) { leafletData.getMap('mymap').then(function(map) { $window.L.GeoIP.centerMapOnPosition(map, 15); }); } ])`

But it does not work...sorry I am quite new to angular

**Comment by sibbl** [comment]
You need to add `'$window'` to the list before your function as well:

 `.controller('CourseDetailsCtrl', ['$scope', '$window', 'leafletData', function($scope, $window, leafletData) { leafletData.getMap('mymap').then(function(map) { $window.L.GeoIP.centerMapOnPosition(map, 15); }); } ])`

https://docs.angularjs.org/guide/di

**Comment by nmccready** [comment]
Is this resolved?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#91

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
