### ISSUE TITLE
Low tile resolution on mobile devices

### ISSUE THREAD

**Issue by VolvoOlympian** [tombatossals/angular-leaflet-directive#857]
The tile resolution is low on mobile devices(especially on Android). The words and shapes on the map are a bit pixelated. Is there a way to increase the default map tile resolution?

PS: I did not change the default tile source

**Comment by Wilzi** [comment]
Just use `detectRetina: true` in `layerOptions`
http://leafletjs.com/reference.html#tilelayer-detectretina

**Comment by VolvoOlympian** [comment]
Thanks, problem solved

**Comment by Wilzi** [comment]
You're welcome. Please close this issue then :)

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#92

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
