### ISSUE TITLE
Offline tiles usage

### ISSUE THREAD

**Issue by hoigo** [tombatossals/angular-leaflet-directive#858]
Is it possible to use locally saved tiles (for offline usage)? I tried to set the tile layer with a relative path, but it doesn't work.

E.g.:

	angular.extend($scope, {
		defaults : {
			tileLayer : "/tiles/{z}/{x}/{y}.png"
		}
	});

**Comment by Wilzi** [comment]
Any console error? The tile files are 404 not found in network panel?

**Comment by zachatrocity** [comment]
One option would be to create a Express.js server using [forever-monitor](https://github.com/foreverjs/forever-monitor) when you start your application that exposes the directory of your tiles on your local machine then you could set your tileLayer attribute to "http://localhost/tiles/{z}/{x}/{y}.png"

A sample express server would look something like this:
```
var express = require('express');
var app = express();

app.set('port', process.env.PORT || 1337);
//this is the location of the tiles on the local machine
app.use(express.static(__dirname + 'tiles');

var server = http.createServer(app);
server.listen(app.get('port'), function(){
    console.log("server listening on port  " + app.get('port'));
});
```

Then you could set your tileLayer attribute to "localhost/{z}/{x}/{y}.png" and you would be fetching tiles from the machine. If this interests you then i'll post a full scale example.

**Comment by hoigo** [comment]
I forgot to set the leaflet attribute "defaults" in my HTML file. Now it works.

Thx for your hints.

**Comment by ansarikhurshid786** [comment]
@hoigo Can you share your offline map code with me?
I want to make offline map in ionic using leaflet and angular-leaflet-directive.

**Comment by hoigo** [comment]
@ansarikhurshid786 no problem. if you would like to get the running demo it's about 55 MB.

**Comment by michelezan** [comment]
@hoigo Can you share offline code for angular-leaflet-directive? I had to build ad app that should be save map with navigation.

Thank you

**Comment by ansarikhurshid786** [comment]
@michelezan I have develop an offline ionic app with angular leaflet directive. If you want code I will share with you.

**Comment by michelezan** [comment]
@ansarikhurshid786 Would be great! Thank you

**Comment by adyngom** [comment]
hello @ansarikhurshid786 is that code available anywhere. I have a map within my ionic app and the client has insisted that everything is offline. It would be great if you could share that code. Thanks

**Comment by ansarikhurshid786** [comment]
Yes sure
