### ISSUE TITLE
[Question]: Is there a way to get all markers in an specific area?

### ISSUE THREAD

**Issue by StOrMiSH** [tombatossals/angular-leaflet-directive#863]
I need all markers in an area which I can draw manually. (like BoxZoom)

I found sth. like this, but dunno how I can archieve this with angular-leaflet-directive. Is there any feature for this?

map.on("boxzoomend", function(e) {
 for (var i = 0; i < markers.length; i++) {
      if (e.boxZoomBounds.contains(markers[i])) {
      console.log(markers[i]);
    }
  }
});

Thanks!

**Comment by Wilzi** [comment]
As i know there is no function for it but the solution is really simple.
Please check: http://stackoverflow.com/questions/18295825/determine-if-point-is-within-bounding-box

**Comment by Wilzi** [comment]
For a polygon you can use turf.js within or inside function
http://turfjs.org/static/docs/module-turf_within.html

**Comment by mikefedak** [comment]
Just to add to Wilzi's comments. You should be able to access the markers using   leafletData.getLayers(), see the layercontrol directive for an example: https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/layercontrol.js

**Comment by nmccready** [comment]
Why not focus doing this on the backend? It is simpler that way. IE constrict your bounds via the database.

**Comment by StOrMiSH** [comment]
Yes, i got this:

$scope.getKarte = function() {
            leafletData.getMap().then(function(map) {
                var latlngs = [];
                for (var i in $scope.geojson.data.features) {
                  latlngs.push(L.GeoJSON.coordsToLatLng($scope.geojson.data.features[i].geometry.coordinates));
                }
                map.on("boxzoomend", function(e) {
                  for (var i = 0; i < latlngs.length; i++) {
                    if (e.boxZoomBounds.contains(latlngs[i])) {
                    console.log(latlngs[i]);
                    }
                  }
                });
            });
        };

works fine i guess.

Thanks
