### ISSUE TITLE
Dynamic (ajax) message in pop-up

### ISSUE THREAD

**Issue by vksvicky** [tombatossals/angular-leaflet-directive#866]
Referring to ticket: https://github.com/tombatossals/angular-leaflet-directive/issues/600

I am having a problem with dynamic message, the problem being I am trying to invoke an AJAX call. So my code looks something like:

```
markers.push({
                                    id: 'abc_' + j,
                                    lat: abcLatLonOptions[j][0],
                                    lng: abcLatLonOptions[j][1],
                                    layer: 'abc',
                                    icon: {
                                        iconUrl: icons['abc'].icon,
                                        iconSize: [16, 16],
                                        popupAnchor: [0, 0],
                                    },
                                    message: complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed)
}
```
And 

```
 function  complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed) {
    var tide_level = 7.5;

    var tideWindowRequest = $.ajax({
                type: "GET",
                async: false,
                url: "https://api.sealevelresearch.com/1/predictions/tide-windows/liverpool-gladstone-dock/?start=" + startTime+ "Z&end=" + eta+ "Z&tide_level=" + tide_level,
                contentType: "application/json; charset=utf-8"
            });

return tideWindowRequest;
    }
```

I have tried to change  message to a function like

```
message: function(){
    complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed);
}
```

I get an error
```
TypeError: Argument 1 of Node.appendChild does not implement interface Node.
```

I have tried to play around without any success, any help would be appreciated. The reason I want it to be called inside a function is because the moment the marker is added to map, the complieAbcMessage function is called if I directly assign to message, which I don't want to do as I have over 1000 markers and that slow's the browser's response.

**Comment by MarkAPhillips** [comment]
Just a note - why are you using $.ajax - which is a jQuery wrapper- I suggest you use $resource or $http services to make the ajax request if you are build an angular app (which I assume you are if using this directive..)

**Comment by vksvicky** [comment]
@MarkAPhillips, thanks for the note, I shall look up and make the necessary change, but don't think that will solve the problem, would it?

**Comment by mikefedak** [comment]
So you are trying to get a tide table as a json? 

A leaflet popup requires that the content it displays is either html or string. If you do things the way you are, you are returning a promise and leaflet does not know how to deal with this. 

You should resolve you promise first and then populate your popup content. 

Just an idea- In the past when I had to populate async popup content I would write a directive and then pass the directive html element as the message. That way I could handle any logic/promises within the directive.

**Comment by vksvicky** [comment]
Can you direct me to an example, its completely new to me. Also my return from the function call is like:
```
<b>Name:</b> ABC<br><b>Latitude: </b> xxx.xxx<br><b>Longitude: </b> xxx.xxx<br><b>Tide window: </b>: ... <br><b>Speed:</b> 22 kn
```

**Comment by Wilzi** [comment]
Here is a working solution: http://jsfiddle.net/d2p19vn4/3/

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#94

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
