### ISSUE TITLE
Angular-Leaflet-Directive + JSON markers

### ISSUE THREAD

**Issue by kingstakh** [tombatossals/angular-leaflet-directive#869]
Try create Leaflet Map with clustering markers in my app. Using for this Angular Leaflet Directive plugin. It's work with example controller and JSON data, but I have other JSON with other data format and have problem with get lattitude and longitude parameters for creating markers array on my map.

In example JSON data ([-37.8839, 175.3745188667, "571"]) we got lat/lng like ap[0], ap[1]. 

            var addressPointsToMarkers = function(points) {
              return points.map(function(ap) {
                return {
                  layer: 'realworld',
                    lat: ap[0],
                    lng: ap[1]          
                };
              });
            };

But how get  lat/lng if JSON data looks like:
            {
    "posts": [
        {
            "ID": "1",
            "title": "Title",
            "tag": "tag1",
            "lat": "53.11691211703813",
            "lng": "26.03631556034088",
            "thumb": "getImage-24-100x100.jpg",
            "fullimg": "getImage-24.jpg",
            "imgs": [
                {
                    "imgurl": "getImage-24-300x200.jpg"
                }
            ],
            "place": "Place",
            "type": "Photo",
            "period": "War",
            "year": "1985",
            "url": "site.com",
            "author": "author"
        }
}

  

Try ap.posts[0].lat, but markers not show

            var addressPointsToMarkers = function(points) {
              return points.map(function(ap) {
                return {
                  layer: 'realworld',
                    lat: ap.posts[0].lat,
                    lng: ap.posts[0].lng        
                };
              });
            };

**Comment by Wilzi** [comment]
You must define an overlay layer for each marker for eg.: `"layer": "markers"` and the lat & lng values must be float type! use `parseFloat()` function on them, or return JSON from server side without double quotes.
