### ISSUE TITLE
error parameter args for event leafletDirectiveMarker.click

### ISSUE THREAD

**Issue by dienlh** [tombatossals/angular-leaflet-directive#870]
i had 2 marker with 2 different address. when create map with 1 marker the first, event map return modelName =1 , address: marker1. 
when i remove marker1 and add marker2 on map, event map return modelName =1 , address:marker 1. 
i don't know why?? with modelName the same but they don't show the time 

$scope.$on("leafletDirectiveMarker.click", function(event, args){
            //$scope.selectItem(args.model);
            console.log("modelName"+args.modelName);
            console.log("Address"+args.model.item.address[0]);
});

click marker 1:
modelName7
mapsleftlet.js:100 AddressPhố Lý Thường Kiệt, Quận 10, Hồ Chí Minh

remove marker 1 and add marker 2: $scope.markers=[marker2]

when click marker 2:
modelName7
mapsleftlet.js:100 Address Phố Lý Thường Kiệt, Quận 10, Hồ Chí Minh

remember:geocode marker1 # marker 2

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#95

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
