### ISSUE TITLE
releasing for angular 1.4 compliance

### ISSUE THREAD

**Issue by nschloe** [tombatossals/angular-leaflet-directive#871]
The latest release still depends on Angular 1.3, with Angular 1.4 being out now for a while. Thankfully, master has already moved to `>=1.3`. Since the angular-leaflet-directive is the one asset that keeps us from moving to Angular 1.4, I'd like to encourage the devs to reconsider if the fixes for the [three blocking bugs](https://github.com/tombatossals/angular-leaflet-directive/milestones/0.8.6) can be delayed until 0.8.7.

**Comment by nmccready** [comment]
You mean 0.8.6 correct?

**Comment by nschloe** [comment]
Well, I meant to inquire if 0.8.6 can be released not too far in the future (and the fixes delayed until 0.8.7 then).

**Comment by nmccready** [comment]
Ahh sure.

**Comment by nmccready** [comment]
Done I think; https://github.com/tombatossals/angular-leaflet-directive/releases/tag/v0.8.6

**Comment by nschloe** [comment]
Thanks!
