### ISSUE TITLE
[Question]: Markers doesn't change on filtering geojsondata

### ISSUE THREAD

**Issue by StOrMiSH** [tombatossals/angular-leaflet-directive#872]
Hello, I'm very new to Angular and Leaflet. Sorry for my second question :)

I followed the example of iH8 from this question at Stackoverflow: how make ng-model="search" have influence on leaflet directive?

If this event is fired

function receiveMessage(event){
$scope.geojson.data = $filter('filter')($scope.data, 'name', 'some Value');
}

from another tab or frame with postMessage:

receiver.postMessage('value', 'URL')

the view changes and everything works fine. If I call this function locally or any other function with

$scope.geojson.data = $filter('filter')($scope.data, 'name', 'some Value');

nothing changes. Can someone explain me why?

Thanks in advance!

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#96

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
