### ISSUE TITLE
Attach an event handler to Tile events?

### ISSUE THREAD

**Issue by paambaati** [tombatossals/angular-leaflet-directive#873]
Is there a way to subscribe to Tile events? I'm trying to show a loader till all tiles finish loading. Looking at https://github.com/Leaflet/Leaflet/issues/177, it looks like they have `load` and `loading` events.

**Comment by BAByrne** [comment]
I'm trying to do the exact same thing. I've been playing around with this for the last couple of days (0.9.0) and I've noticed if you check out leafletMapEvents.getAvailableMapEvents(), you'll see "load" in the list, but I'm not sure it's the same as leaflet's load event. Leaflet's load event will fire when all layers are done loading and if a new layer is added, it will fire again once that layer is done. I'm only getting the load event to fire once when the page loads.

One more thing to note is that you MUST have center set on your map to get the 'load' to work even if it's just that once at the beginning.

**Comment by BAByrne** [comment]
Here's a Plunkr that adds an overlay after 5 seconds. As you'll see, the "load" event is only fired once before the "layeradd" event even shows up. Open console for list of fired events.

http://plnkr.co/O1d3ZGfCbLox3aqqfrJr

**Comment by BAByrne** [comment]
Now that I look at it again, it looks like @hyzhak added the load event correctly. I guess my/our (anyone that wants to add a loading indicator to their map) issue is getting at and listening for those layer events.

**Comment by paambaati** [comment]
@BAByrne Haven't tried your code yet, but doesn't it fire on ever layer's `load`?

**Comment by BAByrne** [comment]
I just got it to work! Updated the [**plunkr**](http://plnkr.co/O1d3ZGfCbLox3aqqfrJr).

My problem was knowing when to check for the load event. Once I wrapped it with a check for the 'layeradd' event, they started showing up. Now, all I have to do is make sure the layer that's sending the load event is the target layer and not some underlying baselayer.

**Comment by paambaati** [comment]
You da MVP!
