### ISSUE TITLE
Are there any build instructions?

### ISSUE THREAD

**Issue by stev-0** [tombatossals/angular-leaflet-directive#877]
I have tried to build the project on Windows and on Linux and have come across issues. On Windows I had to compile some code and install old versions of Visual Studio (no thanks) so swiftly switched to Linux, where I had a problem with the node 'inherits' module not being available (could it be in package.json), and then a problem with `node_modules/esprima/esprima.js:2764
});
 ^
SyntaxError: Unexpected token )`

Is there anywhere with some tips? Happy to start one somewhere, assuming I make any headway. Alternatively, it could be a temporary problem with one of the dependencies.

**Comment by tombatossals** [comment]
Hi @stev-0, you have install instructions here:

http://tombatossals.github.io/angular-leaflet-directive/#!/howto-extend

I'm not sure about the problem you are reporting with the "esprima" module, we're not using it, maybe is a dependency of another module we're using, but I can compile the project without problem with Linux.

You have some more compilation instructions here:

https://github.com/tombatossals/angular-leaflet-directive/blob/master/CONTRIBUTING.md

**Comment by nmccready** [comment]
Also if you try running `grunt graph` you will need to install graphviz `brew install graphviz`

**Comment by stev-0** [comment]
OK, thanks. Bit wierd - works on my shink new Fedora 22, but not on my venerable Debian 7 (Node 0.12.7 and npm 2.13.3. On the latter I just get a load of unmet dependency warnings and then the error message above. Assume this is a problem with my setup or the node on debian setup.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#97

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
