### ISSUE TITLE
Vector Layers integration

### ISSUE THREAD

**Issue by dkuzhanov** [tombatossals/angular-leaflet-directive#879]
Hi Guys, 
Firstly - thank you for creating this great tool! 
I'm using angular-lefleat directive in my app - it works like a charm. However, I was thinking about adding some big custom vector layers on top of the regular OSM raster tiles. For this purpose geojson-vt seems like a perfect fit. I managed to find this:
http://bl.ocks.org/Sumbera/raw/c67e5551b21c68dc8299/
example of using geojson-vt with leaflet and canvas.  It looks pretty impressive, but I for some reason can't make it work with AngLeafDir. spent 2 days trying to make it. 

Does anyone have a working example of AngLeafDir working with geojson-vt?
thanks  in advance!

PS:I honestly believe that vector tile technology is the future of web maps and BIG guys (Goodle maps, apple maps) already use it. This example should significantly contribute to the library.

**Comment by nmccready** [comment]
Did a PR resolve this? Or did you figure this out?

**Comment by dkuzhanov** [comment]
Hi @nmccready,
I did figure this out, thanks for asking!
It took awhile but the result works great and allows displaying multiply heavy geojsons by cutting them on the fly. 
If anyone  interested I can try posting my example or even pushing my example into the examples branch.

Cheers

**Comment by nmccready** [comment]
Yeah please add an example; that would be awesome. Thanks

**Comment by dkuzhanov** [comment]
Thanks, man, I appreciate that! 
I'd love to get involved and help if I can. Will do that over the weekend. 
thanks!
