### ISSUE TITLE
Getting 'The 'Center' not defined error

### ISSUE THREAD

**Issue by patb23** [tombatossals/angular-leaflet-directive#880]
I am setting bounds, geojson and center on $http response. It is only complaining about 'center'. [referred this issue in github](https://github.com/tombatossals/angular-leaflet-directive/issues/100)

    var s = $scope;
    $http.get('/cat/activeFire').success(function (result) {
      console.log('got result');
      s.center = {lat: 37.27, lng: -119.27, zoom: 16};
      s.bounds = {
        southWest: {lat: 32.53429, lng: -124.409622},
        northEast: {lat: 42.00946, lng: -114.130836}
      };
      s.polygons = {
        data: result,
        style: {
          fillColor: "red",
          weight: 2,
          opacity: 1,
          color: 'white',
          dashArray: '3',
          fillOpacity: 0.7
        }
      };
    
    });

    <leaflet bounds="bounds" center="center" geojson="polygons" url-hash-center="yes" width="640" height="400"></leaflet>

When the page is rendered, the map zooms to the bounds (CA state)but ignores'center'. Also, the layer is getting rendered when I zoom into CA state. Could I get help on what is wrong here? Thanks

**Comment by patb23** [comment]
Missed reading a line :-). After initializing  the 'center' in the scope,got it working

**Comment by jeansymolanza** [comment]
I am having a similar issue. How did you initialise the `center` in the scope?
