### ISSUE TITLE
The marker definition is not valid

### ISSUE THREAD

**Issue by patb23** [tombatossals/angular-leaflet-directive#881]
Hi,
I am getting this error while adding the markers. The screenshot is attached and verified that the lat/long is valid. Please let me know, if any additional detail is required.
Thanks 

![image](https://cloud.githubusercontent.com/assets/1138859/9126739/5f994754-3c7f-11e5-93c2-194715b32d54.png)

**Comment by nmccready** [comment]
Walk through validateCoords and see why validateCoords is returning false.

**Comment by sofivsofi** [comment]
I think that the problem is **lon** which supposed to be **lng**

`markerData = Object {layer: "baselayers", lat: 34.019783, lng: -118.790482}`

**Comment by patb23** [comment]
sofivsofi - thank you so much for spotting the mistake. Itworked

**Comment by sofivsofi** [comment]
u r welcome! :-D

**Comment by chidg** [comment]
Any future googlers dealing with a similar issue, I was getting this very frustrating error for a while before I realised that I was passing strings instead of floats for the lat and long values when trying to instantiate a marker. Make sure you're giving the marker coordinate values that are actually numerics.

**Comment by nmccready** [comment]
Yes it is strict on numerics, @chidg good comment.

**Comment by nmccready** [comment]
@chidg honestly I do not know why it is this strict. Does this same restriction exist in leaflet itself?
@tombatossals

**Comment by christianbm1** [comment]
I'm getting this same error, however the markers are still plotting correctly, and everything seems to be working. Not sure what's up.

Errors: "The marker definition is not valid" and also: "received invalid data on marker 1"

**Comment by thulioph** [comment]
I'm getting the same error of @christianbm1

**Comment by Steckelfisch** [comment]
@chidg: thanks, did the trick.
