### ISSUE TITLE
Invalid logging of markers destroy

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#882]
The following lines should be moved to ~180.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/markers.js#L155-L158

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#98

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
