### ISSUE TITLE
Zoom in/out - map freeze issue

### ISSUE THREAD

**Issue by dud3** [tombatossals/angular-leaflet-directive#883]
## Specifications 
Browser: Firefox 39.0
Leaflet: 0.7.3
Leaflet-draw: 0.2.3
Angular: 1.3.15

## Problem space
JSON call to the coordinates and zoom property like:
```
$scope.center = {
    lng: parseFloat(location.longitude),
    lat: parseFloat(location.latitude),
    zoom: parseInt(data.data.result.zoom_level)
}
```
In zoom out the map freezes.

## Code
```js

// Get the location(marker).
spotLocationsSvc.get({ spot_id: window.__G__server_data_spot_id }).then(function(data) {

    $scope.submission.spot.location_name = data.data.result[0].location_name;

    // Since we have multiple markers, we should push them all.
    angular.forEach(data.data.result, function(location) {

        leafletData.getMap().then(function(map) {

            var drawnItems = $scope.controls.edit.featureGroup;
            var coordinates = {lat: location.latitude, lng: location.longitude};

            var layer = new L.Marker(coordinates);
            drawnItems.addLayer(layer);

            var _push_layer = coordinates;

                // Push the leaflet_id first, so later on we
                // can easily remove it from the map.
                _push_layer.id = layer._leaflet_id;

                // Push location id as well, so we can distinguish
                // if the marker already existed or not, and make a call
                // to the back-end to remove/modify the entity on the db.
                _push_layer.location_id = location.id;

                // And finally the spot_id, just in case.
                _push_layer.spot_id = location.spot_id;

            $scope.submission.spot.coordinates['marker'].push(_push_layer);

            // Spot projection, zoom level and such...
            spotProjectionSvc.get({ spot_id: window.__G__server_data_spot_id })
                .then(function(data) {

                // Fix for maps on hidden elements.
                leafletData.getMap().then(function(map) {
                    map.invalidateSize(false);
                });

                $scope.center = {
                    lng: parseFloat(location.longitude),
                    lat: parseFloat(location.latitude),
                    zoom: parseInt(data.data.result.zoom_level)
                }
...
```

## Example
* Video: https://drive.google.com/file/d/0B5C6s30Pt8vJeFhmVk1obzg4Tk0/view?usp=sharing
* In action: http://app.yachtingsbest.com/spot/edit?string_id=Kenmore_Air4
 * email: test@gmail.com
 *  pwd: 123123123

**Comment by nmccready** [comment]
Can you set this up as a plnkr?

**Comment by dud3** [comment]
@nmccready I apologize for my late answer I think I never got notified for this post, could you maybe mention me as @dud3 when you post a comment, thanks :D.

I unfortunately can't set up a plnkr, but I can show the the bug happening in action:
* http://app.yachtingsbest.com/spot/edit?string_id=Kenmore_Air4
 *  email: test@gmail.com
 * pwd: 123123123

The code: http://app.yachtingsbest.com/src/app/controllers/submissionCtrl.js?v=1442881068
Searching for: `data.data.result.zoom_level` should bring you to the right line.

One thing I've noticed is that: `it happens with google maps` if we switch to `OSM satellite` everything works.

**Comment by nmccready** [comment]
Ahh.. well I have some workaround with google maps as I try to throttle the plug in way down. I throttle it down as the google maps plugin w/ leaflet hammers the heck out of the API. So by throttling I debounce the events coming from leaflet when using google maps.

**Comment by nmccready** [comment]
Here is some code I use personally.

inside some baseMapCtrl code
```coffee
_pingPass = ->
        _now = new Date()
        diff = _now.getTime() - _last.getTime()
        if diff > redrawDebounceMilliSeconds
          _last = _now
          return diff
        false

_maybeDraw = _.debounce (leafletDirectiveEvent, leaflet) =>
    #_pingPass ans debounce are all things to mimick map "idle" event
    leafletEvent = leaflet?.leafletEvent or undefined

    _maybePingTime = _pingPass()

    if leafletEvent?.type == 'zoomend'
      self.clearBurdenLayers()
      $log.debug "zoom: #{@scope.map?.center?.zoom}"

    $log.debug "redraw delay (small/false bad): #{_maybePingTime}"
    $log.debug "map event: #{leafletEvent.type}" if leafletEvent?.type?
    self.draw? 'idle'
 , redrawDebounceMilliSeconds

$timeout =>
  @map.invalidateSize()#map's bounds is not valid until after this call
   leafletPreNamespace = 'leafletDirectiveMap.'
   mapEvents.forEach (eventName) =>
     eventName =  leafletPreNamespace + eventName
     return @scope.$on eventName, _maybeDraw
   _maybeDraw()
```

Also there are some smooth dragging issues which I deal with as well http://stackoverflow.com/questions/16645766/google-maps-api-v3-no-smooth-dragging .

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#99

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
