### ISSUE TITLE
$http.get to get markers

### ISSUE THREAD

**Issue by srini-raju** [tombatossals/angular-leaflet-directive#885]
Hi,
Thanks for creating the directive. Great work. I am trying to use multiple markers on the map and all the lat/long and popup details will need to come from a url. There is nothing static in the page. Can someone point me to a sample that can set markers dynamically?

Thanks in advance for any help.

Thanks,
Srini

**Comment by kitab15** [comment]
Hi, 
I think I have something like what you want
My backend gives me the markers as a geoJSON structure, then I iterate over this data and for each element I create a marker, then, I add this marker to a markers object which is passed to the map as a directive's parameter

```
// Get data from server
$http.get('your_markers_url').success(function (data) {

// For each element create a marker
for (var i=0;i<data.features.length;i++){
    var marker = {
                    title: data.features[i].properties.name,
                    lat: data.features[i].geometry.coordinates[1],
                    lng: data.features[i].geometry.coordinates[0],
                    focus: true,
                    label: {
                              message: data.features[i].properties.name,
                              options: {
                                    noHide: true
                               }
                            }
                   };

// Add marker to the markers object
$scope.markers[data.features[i].id] = marker;
})

// Add markers to the map
<leaflet markers="markers"></leaflet>
```

**Comment by srini-raju** [comment]
Thanks for the response. Is very helpful. I also solved it differently, though not sure if this is right way.
$http.get("mps1.json").success(function(data, status) {
            angular.extend($scope, {
                geojson: {
                    data: data,
                    style: {
                        fillColor: "green",
                        weight: 2,
                        opacity: 1,
                        color: 'white',
                        dashArray: '3',
                        fillOpacity: 0.7
                    },
                    
            onEachFeature: function (feature, layer) {
        layer.bindPopup(feature.properties.popupContent); } ,
                    events: {}
                }
            });
        });
