### ISSUE TITLE
Support defaults.infoControl

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#886]
In the example: http://bl.ocks.org/lxbarth/9921260 we see a small info window for attribution. 

This is not possible with this library because only certain defaults are passed to the map. Specifically `attributionControl` is supported, but `infoControl` is not. See https://github.com/tombatossals/angular-leaflet-directive/blob/d386b7f8f7bd201e1e3d467d5e61c67045a56570/doc/defaults-attribute.md

We should add `infoControl`. Is it possible to make this more flexible to allow setting any default even if they are not specifically defined here?

**Comment by facultymatt** [comment]
See https://github.com/tombatossals/angular-leaflet-directive/issues/87#issuecomment-22299962

**Comment by tombatossals** [comment]
That's a great suggestion, and it seems simple to support.

Will take a look at it if anybody code it before.

**Comment by tombatossals** [comment]
Hi @facultymatt, it seems that infocontrol is related to mapbox, I can't find this property in the leaflet API. :(
