### ISSUE TITLE
Map invalid size. When ng-hide and resize window.

### ISSUE THREAD

**Issue by dannesart** [tombatossals/angular-leaflet-directive#887]
Hi everybody,
I've faced an irritating issue.
I got a tab view with 3 tabs. The tab content is controlled by ng-show='tab=x'.
In the first tab I've the map and when I turn to tab 2 or 3. Nothing happens, which is nice.
This means that the map-view now has a ng-hide class.
And when I resize the window. 

The map bounds are now:
lat: 59.40473394955639, lng: 18.100318908691406
and
lat: 59.29096170715197, lng: 18.100318908691406
(Same LNG)

And the map is grey.

I tried to add "map.invalidateSize()" inside a 
```js
$scope.$on('leafletDirectiveMap.resize', function (e) {
var bounds = map.getBounds();
                console.log(bounds._northEast, bounds._southWest);
                if (
                    bounds._southWest.lng === bounds._northEast.lng  || 
                    bounds._southWest.lat === bounds._northEast.lat
                ) {
                    console.log("Yepp, map is broken", map);
                    map.invalidateSize(false);
                }
})
```
But doesn't seems to work.

```html
<p>&lt;ul class="tabs"&gt;<br />&lt;li data-ng-click="1"&gt;tab 1&lt;/li&gt;<br />...<br />&lt;/ul&gt;</p>
<p>&lt;div data-ng-show="tab == 1"&gt;<br />&lt;leaflet defaults="map.defaults" geojson="map.geojson" controls="map.controls" layers="map.layers" center="map.center" markers="map.markers" class="map-canvas"&gt;&lt;/leaflet&gt;<br />&lt;/div&gt;<br />&lt;div data-ng-show="tab == 2"&gt;<br />...<br />&lt;/div&gt;</p>
```
But if I use data-ng-if="tab == 1" instead of data-ng-show="tab == 1". It works.
But not markers and polygons. 

Any ideas?

**Comment by kuanb** [comment]
It would be easier to read your question if you format your code but here are some quick thoughts:

1. If you have multiple maps, could you be setting your listener on the wrong map?
2. Consider this issue: https://groups.google.com/forum/#!topic/leaflet-js/Jzs5Sd7lRx8 and wrap the size invalidator in a `setTimeout` such that: `setTimeout(function () { map.invalidateSize() });`

**Comment by dannesart** [comment]
Hi @kuanb, 
Thank you for your answer!
Sorry about the code parts. I don't know how to insert code in a nice code format here :)

But it seems to work now.. I don't know why. I did what you said with setTimeout. At first it didn't work. So I needed to add 100 miliseconds to it. setTimeout(function () { map.invalidateSize() }, 100);

And now it works like a charm.

Do you know why setTimeout is needed?

Once again Thank you!

**Comment by nmccready** [comment]
@dannesart since your in angular I'd advise using `$timeout` this will also cause an internal scope.$apply()
