### ISSUE TITLE
Add markers to a particular map id

### ISSUE THREAD

**Issue by VolvoOlympian** [tombatossals/angular-leaflet-directive#893]
How do I add markers to a specific map using 
`leafletData.getMap('mymap').then(function(map) {   })`

What are the functions available for the `map` variable?

**Comment by tombatossals** [comment]
The "map" object is the leaflet Map object, so you can interact with it directly if you want if you're coding something complicated this library can not manage.

But if you only need to add markers, maybe you don't need the map object. Take a look at this code, for example:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/two-maps-events-example

**Comment by VolvoOlympian** [comment]
Thanks for the info, but the number of maps and the markers in them is dynamic...

**Comment by nmccready** [comment]
@VolvoOlympian  then you need to come up with a mechanism to keep track of what is talking to what via a hashmap or something.
