### ISSUE TITLE
AngularJS double curly brackets not working on markers attribute

### ISSUE THREAD

**Issue by VolvoOlympian** [tombatossals/angular-leaflet-directive#894]
I am trying to print out the $index of ng-repeat, but it gives me: 

    Error: [$parse:syntax] Syntax Error: Token '{' is an unexpected token at column 8 of the expression [markers{{ $index }}] starting at [{{ $index }}].

This is my code: 

    <div ng-repeat="place in places">
             <leaflet id="map{{ $index }}" defaults="defaults" center="center" markers="markers{{ $index }}"></leaflet>
    </div>

But changing to this works:

    <div ng-repeat="place in places">
         <leaflet id="map{{ $index }}" defaults="defaults" center="center" markers="markers0"></leaflet>
</div>

This is very strange...why does that happen?

**Comment by nmccready** [comment]
google found: 
http://stackoverflow.com/questions/22129582/ng-repeat-in-custom-directive-syntax-error-token-index-is-unexpected

leaflet isolated scope definition:
https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L6-L22

Id is not in the isolated scope as it is used from the attribute only.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/leaflet.js#L42-L43

Lastly use isolated scope binding and keep it simple and do:
```
<div ng-repeat="place in places">
         <leaflet id="place.id" defaults="defaults" center="center" markers="place.markers"></leaflet>
</div>
```
