### ISSUE TITLE
Use shared angular template for sets of markers

### ISSUE THREAD

**Issue by joeljeske** [tombatossals/angular-leaflet-directive#896]
It would make sense to allow a set of markers to use the same angular templates (`marker.message` property) and the same scope factory (`marker.getMessageScope()` function). 

By definition, a template should be the generic html partial that gets compiled and made specific by Angular and its scope bindings. Each marker should not have its own copy of the angular template but shared at some higher level. 

## Possible API

**controller.js**
```js
$scope.markers = {
  m1: {
    lat: 51.505,
    lng: -0.09,
    popupGroup: "detail"
  },
  m2: {
    lat: 51,
    lng: 0,
    popupGroup: "detail"
  },
  m3: {
    lat: 51,
    lng: -1,
    popupGroup: "detail"
 };

$scope.markerOptions = {
  groups: {
    detail: {
      // template: "1 + 1 = {{ 1 + 1 }}",
      templateUrl: "popupTemplate.html",
      getScope: function(marker) {
          var scope = $scope.$new();
          scope.marker = marker;
          return scope;
      }
    }
  }
};
```

**index.html**
```html
<leaflet markers="markers" marker-options="markerOptions" ... ></leaflet>
```

**popup.html**
```html
<div>Location: {{marker.lat}} , {{marker.lng}}</div>
```

## Additional Notes

* The individual markers could override their group's template or scope
* The html partial would not be duplicated in memory 
* The template could be lazily `$compile`d and reused for performance
* This would bring a lot of familiarity to common Angular Developers. Similar examples
  * [ngRoute's $routeProvider](https://docs.angularjs.org/api/ngRoute/provider/$routeProvider)
  * [ui.router's $stateProvider](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider)
  * [ui.bootstrap's $modal](https://angular-ui.github.io/bootstrap/#/modal)

**Comment by gustavoaragon** [comment]
+1

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#100
