### ISSUE TITLE
marker.setIconAngle is not a function

### ISSUE THREAD

**Issue by adambarthelson** [tombatossals/angular-leaflet-directive#897]
I checked through the updated Leaflet source, as well as the updated source for this repo.  Where are you hiding this method that I so desire?

**Comment by ryanjadhav** [comment]
:+1: running into this as well, whats going on here?

**Comment by ryanjadhav** [comment]
found it, it lives in this js: 
```
<script src="../bower_components/leaflet-plugins/layer/Marker.Rotate.js"></script>
```

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#101

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
