### ISSUE TITLE
getMessageScope and message for paths

### ISSUE THREAD

**Issue by billxinli** [tombatossals/angular-leaflet-directive#898]
With markers, once can add `getMessageScope` and `message` to compile the message and/or include a template. 

However, is it possible to do this with paths as well?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#102

**Comment by billxinli** [comment]
Thanks for the pointer @nmccready.

Just wondering since angular ui forked this project, which org will be the "official" owner? And who is responsible for releasing to bower?

**Comment by nmccready** [comment]
The angular-ui version has been renamed to ui-leaflet.js  so it is more of a clean break from this. I do not plan on cutting any more releases on this lib. It is all @tombatossals  now.

**Comment by nmccready** [comment]
So to be clearer. Several admins from angular-ui will be able to cut releases for bower on ui-leaflet, along with npm. For angular-leaflet-directive @tombatossals will be handling for itself.

**Comment by billxinli** [comment]
Will the two forks be diverged significantly, or will the two projects pull from each other in terms of features?

Or will one eventually be deprecated? If not, which will have the "latest and greatest" in terms of updates, fixes and features?

**Comment by nmccready** [comment]
The two projects will probably diverge as I the fork is permanently broken from angular-ui. All the contributing devs are on angular-ui from this project except tombs as he wants this to be a personal project still. If @tombatossals wants he can come to angular-ui as well. But the org transfer would have made things significantly easier than what has happened.

**Comment by billxinli** [comment]
Fair enough! I will keep an eye open for when angular-ui starts to
release this as a stable library, and then switch over.

**Comment by nmccready** [comment]
It is released already as 1.0.0

**Comment by nmccready** [comment]
https://www.npmjs.com/package/ui-leaflet

**Comment by nmccready** [comment]
Only breaking change is the module naming.

**Comment by nmccready** [comment]
https://github.com/angular-ui/ui-leaflet/releases/tag/v1.0.0

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
