### ISSUE TITLE
Changing the base layer sometimes hides the active overlays (+ workaround)

### ISSUE THREAD

**Issue by pieterjandesmedt** [tombatossals/angular-leaflet-directive#904]
The problem - I think - is that the baselayers and overlays are watched by a different watch, and changing the baselayer involves adding it to the map. Then the newly added baselayer is on top of the overlays. 

[Example here](http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/dynamic-addition-example) - try playing with the base layers and notice the overlay gets hidden.

This is my workaround, but maybe the overlays should be redrawn if a base layers changes?

```javascript
	$rootScope.$on('leafletDirectiveMap.baselayerchange', function(ev,layer){
		console.log('base layer changed to %s',layer.leafletEvent.name);
		angular.forEach($scope.layers.overlays, function(overlay){
			if (overlay.visible) overlay.doRefresh = true;
		});
	});
```

**Comment by thatgirlcancode** [comment]
Hmmmm... I tried this workaround, but it didn't work for me. Here is my plunk, it has directions for reproducing... 

http://embed.plnkr.co/MNyxz5A8GbX1oM9c8ZPK/preview

**Comment by carrbrpoa** [comment]
@pieterjandesmedt, your code didn't work for me too, but acted as a good start point. I solved with this:
```javascript
$rootScope.$on('leafletDirectiveMap.baselayerchange', function (ev, layer) {
	leafletData.getLayers().then(function (l) {
		angular.forEach(l.baselayers, function (bl) {
			bl.setZIndex(-1);
		});
	});
});
```
Now, my overlays are **always** on top of any basemap/baselayer.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#103

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
