### ISSUE TITLE
leafletDirectiveMap.geojsonClick

### ISSUE THREAD

**Issue by futurityverb** [tombatossals/angular-leaflet-directive#905]
In 0.7, I was able to listen for the `leafletDirectiveMap.geojsonClick` event. In 0.8 this has stopped working, and I can't figure out how to listen for clicking on a geojson layer.

**Comment by ageblade** [comment]
You can do it like this by using the geojson directive and this code:

    vm.geojson = {
        data: myFeatureCollection,
        onEachFeature: function (feature, layer) {
            layer.on({
                click: onMouseClick
            });
        }
    };

**Comment by nmccready** [comment]
Its still there but the event follows camelCase conventions across the board now.

https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/events/leafletGeoJsonEvents.js#L9


Example:

https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0601-mixed-geojson-events-example.html#L72-L74

`leafletDirectiveGeoJson[whateverEvent] or leafletDirectiveGeoJson.whateverEvent`
