### ISSUE TITLE
Center: Allow user provided setView options

### ISSUE THREAD

**Issue by joeljeske** [tombatossals/angular-leaflet-directive#907]
In the bounds directive, [`$scope.bounds.options` is used][1] as the options for `map.fitBounds`. This is nice as the user can specify animation options and the like. Center should use a similar way to specify options to `map.setView` ([leaflet docs][2]). 

[1]: https://github.com/tombatossals/angular-leaflet-directive/blob/e3e93c2882c4606a763cbd440552b5614e8351b6/src/directives/bounds.js#L71
[2]: http://leafletjs.com/reference.html#map-setview

**Comment by nmccready** [comment]
Why not just use 
```js
leafletData.getMap().then(function(map){
  map.setView(whatever);
});
```
instead?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#104

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
