### ISSUE TITLE
Drag too sensitive on big screen, prevents marker popup from appearing on click.

### ISSUE THREAD

**Issue by feelcreative** [tombatossals/angular-leaflet-directive#908]
Hi guys, 

I'm creating a kiosk using a big windows touchscreen with the ionic app running in Chrome fullscreen. 

Works a treat except for the map touch sensitivity. When a touch registers on the screen it is registered as a small drag event, preventing the marker's popup from appearing. 

I am looking for a way to stop small drag events from occuring, or fire off a click event in the dragstart location if the dragend distance is less than 10. 

I have tried the following:
```
$scope.$on('leafletDirectiveMap.dragend', function(event, args){
                            if(args.leafletEvent.distance < 20) {
                              args.leafletEvent.target.fireEvent('click',
                                {
                                  latlng: args.leafletEvent.latlng, 
                                  layerPoint: args.leafletEvent.layerPoint,
                                  containerPoint: args.leafletEvent.containerPoint
//problem is latlng doesn't exist for dragend event, also I tried this with mousedown giving a valid latlng value and it did still nothing
                                }
                              );
                            }
                        });
```
Any advice?

C

**Comment by nmccready** [comment]
@feelcreative yes you need to add some debouncing. The leaflet events update way too often and too fast. I recommend debouncing the heck out of movend dragend ..etc.

**Comment by nmccready** [comment]
For instance with lodash

```js
var mapEvents = ['resize','moveend', 'zoomend'], //no need for dragend
  redrawDebounceMilliSeconds= 700,
  leafletPreNamespace = 'leafletDirectiveMap.';

var _maybeDraw = _.debounce(function(leafletDirectiveEvent, leaflet){
  //start doing stuff based off of the events defined above
},redrawDebounceMilliSeconds );

mapEvents.forEach(function(eventName){
  eventName =  leafletPreNamespace + eventName
  return @scope.$on eventName, _maybeDraw
});
```

**Comment by nmccready** [comment]
BTW this is also ten times worse when using the google maps plugin its events update insanely too much. This has nothing to do with angular but probably a buggy plugin. So debouncing is of utmost importance against that.

**Comment by feelcreative** [comment]
Thanks @nmccready 

It isn't an issue with debouncing, the events are not firing too many times, its just that the drag event is too sensitive, it picks up touches that should be clicks as drags. 

Is there a way of reducing the threshold of whats deemed a drag? e.g. if drag distance is less than 10 then treat the event as a click?

C

**Comment by feelcreative** [comment]
I've able to get the desired effect by setting draggable to true on each marker, now when you touch the marker it opens the popup even if a little drag is occuring, this comes with the unfortunate consequence that my markers are now draggable.

I have attempted to preventDefault and stopPropagation using: 
$scope.$on('leafletDirectiveMarker.dragstart', function (e, args) {
	e.preventDefault();
	e.stopPropagation();
});

and 

$scope.$on('leafletDirectiveMarker.dragstart', function (e, args) {
	L.DomEvent.stop(e);
});

But to no avail, the markers are still draggable. Any advice is much appreciated!

C

**Comment by feelcreative** [comment]
My temporary workaround is this in case anyone else is interested:

When building each marker object I add 2 more fields to hold the original latlng values, on dragend I am resetting the marker's latlng values back to the original ones. 

There is the undesired effect that the user can drag the marker, but the marker pops back to its original location on drag end.

C

**Comment by marcusasplund** [comment]
@feelcreative Any chance you could post an explanatory snippet of your workaround?
Me too is working on a Chrome Kiosk app on a windows pc with large samsung screens and some touch overlay. It sounds that we have the same issue; it works flawlessly in any other environment except the one above, where only gentle, precise taps on the markers triggers the click event. Producing a really bad ux. Tried all methods i can think of, to no avail.
Angular Material as background framework.

**Comment by marcusasplund** [comment]
I did it like this, set the markers with `draggable: true`, then :

`````` javascript
  var orgLatLng = {};
 $scope.$on('leafletDirectiveMarker.dragstart', function (e, args) {
    orgLatLng = args.leafletObject._latlng;
});
  $scope.$on('leafletDirectiveMarker.dragend', function (e, args) {
    args.leafletObject.setLatLng(orgLatLng);
}); ```
``````
