### ISSUE TITLE
Using Leaflet Draw and editing drawn items

### ISSUE THREAD

**Issue by MarkAPhillips** [tombatossals/angular-leaflet-directive#909]
Hi - after all the changes to the control functionality what is the recommended approach now to be able to edit draw items added to a map via the Leaflet Draw control.

I have reviewed many of the issues and had this working in 0.8.5. I have now updated to 0.8.7 and everything is working as expected except being able to edit the drawn items.

Can I suggest the example for using the control is extended to include the following:

1) Include the use of options as defined as follows:

```
    angular.extend($scope, {
                center: {},
                paths: {},
                controls: { draw: { draw: {   position: "topright",marker: false,rectangle: false} } },
                defaults: {},
            });
```

2) Include an example where the drawn items are editable as most use cases require this and would make it simpler to review rather than searching through all the issues which have varying examples, usually incomplete or possibly out of date.

Thanks!

**Comment by sebastibe** [comment]
I have the same issue, after updating to 0.8.8, I can't find how to enable edit controls again.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#105

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
