### ISSUE TITLE
last release build v0.8.8 breaks the app 

### ISSUE THREAD

**Issue by mravinale** [tombatossals/angular-leaflet-directive#918]
Version:
https://github.com/tombatossals/angular-leaflet-directive/releases/tag/v0.8.8

JsFidle:
 using the V0.8.8 http://jsfiddle.net/mravinale/rjnf0g78/

Error detail:
```
Error: [$injector:modulerr] Failed to instantiate module billboarderApp due to:
    Error: [$injector:modulerr] Failed to instantiate module leaflet-directive due to:
    Error: [$injector:modulerr] Failed to instantiate module nemLogging due to:
    Error: [$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by mravinale** [comment]
fixed using last version, be careful

**Comment by nmccready** [comment]
@mravinale look at the dependency list in bower the logger is now a dependency. If you use https://github.com/ck86/main-bower-files to load your deps you'll never have this problem

**Comment by nmccready** [comment]
also the error is flat out in there `Module 'nemLogging' is not available!`

**Comment by nmccready** [comment]
#829

**Comment by suprMax** [comment]
some people use npm over bower for simplicity's sake. can we fix this somehow?

**Comment by suprMax** [comment]
p.s. good god, angular-simple-logger depends on other modules as well, I wonder how long would I have to spend to load whole deps tree for this bugger
![screen shot 2015-10-02 at 5 27 51 pm](https://cloud.githubusercontent.com/assets/789031/10250407/ea159036-692a-11e5-8f12-41af3cb1458f.png)

**Comment by nmccready** [comment]
People make mistakes and I am fixing good god, you don't have to be an ass. You could also make a PR on the logger as well.

**Comment by elesdoar** [comment]
Sorry, you could fork the project and contribute, or only use a previous version, don't make things more complicated. It's open source, all we contribute, not demand.

**Comment by suprMax** [comment]
I mean no disrespect and appreciate the work you've done. No offense guys, just would be cool to have it working out of the box if it's published to npm, that's all.

**Comment by nmccready** [comment]
Thanks for the reply, and please remember tone is everything. I myself need to watch this from time to time. But when it is negative it is very very **demotivating** to continue working on these projects (when it is free).

There is actually a conversation going on now on leaflet 1.0 on becoming npm centric because leaflet itself wants out bower. Currently jspm, npm and keeping bower are on the table. #851

**Comment by nmccready** [comment]
Feel free to chime in and help out.
