### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by schmichri** [tombatossals/angular-leaflet-directive#919]
Below on this page http://tombatossals.github.io/angular-leaflet-directive/#!/ 

"Click on the buttons to change the active map layer. You can see a standalone example of this code **here**." points to http://tombatossals.github.io/angular-leaflet-directive/examples/layers-example.html which is dead.

**Comment by nmccready** [comment]
Your link is a 404 but how the heck are you getting there? Screen shots would help. Also if you'd like dig into the website code which is in the gh-pages branch.

**Comment by schmichri** [comment]
![screenshot_553](https://cloud.githubusercontent.com/assets/8415907/9700714/d620de50-540d-11e5-9cfa-b23412e59223.jpg)

**Comment by nmccready** [comment]
Thanks now that's clear as day. confirmed

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#106

**Comment by tombatossals** [comment]
Solved, thanks for reporting @schmichri
