### ISSUE TITLE
angular-leaflet-directive 0.8.8 requires nemLogging

### ISSUE THREAD

**Issue by rpadovani** [tombatossals/angular-leaflet-directive#920]
If I update the module to version 0.8.8 it fails to start with this error:

```
Error: [$injector:modulerr] Failed to instantiate module demoapp due to:
[$injector:modulerr] Failed to instantiate module leaflet-directive due to:
[$injector:modulerr] Failed to instantiate module nemLogging due to:
[$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.5/$injector/nomod?p0=nemLogging
minErr/<@file:///home/rpadovani/Archon/leaflet/bug-linestring/bower_components/angular/angular.js:68:12
module/<@file:///home/rpadovani/Archon/leaflet/bug-linestring/bower_components/angular/angular.js:1983:1
ensure@file:///home/rpadovani/Archon/leaflet/bug-linestring/bower_components/angular/angular.js:1907:38
module@file:///home/rpadovani/Archon/leaflet/bug-linestring/bower_components/angular/angular.js:1981:1
```

I've no idea what nemLogging is supposed to be.

**Comment by simison** [comment]
Dublicate #918

As per #829 you need to include angular-simple-logger into your project now.

**Comment by rpadovani** [comment]
I have `"angular-simple-logger": "~0.0.1",` in my bower.json, it doesn't work.

**Comment by nmccready** [comment]
You have to load the script prior. There are tools out there to do this for you or you need to move it or direct the html to the correct location.

**Comment by iammichiel** [comment]
Too bad, this library doesn't use semantic versionning... Introducing a BC break like this broke a lot of things and semver would have prevented breaking our builds.

**Comment by simison** [comment]
@iammichiel yup. #829

**Comment by jtroe** [comment]
It would probably be best if we update the `gh-pages` so the examples at http://tombatossals.github.io/angular-leaflet-directive reflect this.  The examples using 0.8.6 threw me off too.

**Comment by nmccready** [comment]
See #984 I will start digging into the gh-pages.
