### ISSUE TITLE
Issue or fix related ngRoute in v0.8.8 ?

### ISSUE THREAD

**Issue by iasinDev** [tombatossals/angular-leaflet-directive#921]
Hi, I only want to say what have happened to me cause I'm not sure at all if it's an issue of leaplet directive or how was used in my code..

The thing is, with v0.8.8 everything seemed ok... app start.. but in execution I got error: ($injector:modulerr).

After investigate what was broken... by setting v0.8.6 everything worked again

As I have said previous, I only advert this like info just in case if needed, thank you!

**Comment by nmccready** [comment]
Please research recently closed issues.  There is a new dependency. Feel free to add to the Readme.

**Comment by nmccready** [comment]
Please research recently closed issues.  There is a new dependency. Feel free to add to the Readme.
