### ISSUE TITLE
Question: How to switch baselayers by scope-function

### ISSUE THREAD

**Issue by nicho90** [tombatossals/angular-leaflet-directive#925]
Hi everyone, 

I have a (maybe) simple question, but I'm new in AngularJS and I'm currently develop my first application with it. So here is my problem: I want to build a public transport app and need a function to switch baselayers with a `$scope.function` in my controller. 
I have already 5 baselayers defined an I can select them in the control-field in the upper right corner on the map. But I want to switch them them automatically (e.g. time-related) or by own buttons, so I can provide a "day" view (this shows the day-busses on a light-map) and the night-busses on a dark-map but the user should also have the chance to change the baselayer by the control-field. 
I already looked into the `layers-directive` and `events-directive`, but I couldn't find out, which is responsible for changing the baselayer and how I can access them as a scope-function in my controller. Is there a solution for that? I hope anyone can help me :) Thank you guys!! 

Cheerio,
Nicho

**Comment by elesdoar** [comment]
Please, see 

* http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/dynamic-addition-example
* http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/basic/tiles-example 

I hope it helps

**Comment by nicho90** [comment]
Hi @elesdoar, 
thank you for your links!! :)
I already looked into the examples, but I don't want to remove the baselayers from the control like it happens in the examples. I only want to active the baselayer by an own scope-function, which can be triggered, e.g. when I press a button on the website, without deleting them on the control-list. I'm sure that I need to delete the current baselayer from the map and then add the new baselayer, but maybe there is already a function for that. I tried to remove all baselayers in the extended scope `$scope.layers.baselayer` and add all baselayers again to the scope, with the wanted baselayer as first item, but it couldn't solve the problem, because the map didn't refresh.

**Comment by nicho90** [comment]
Hi guys,

I found a solution for my problem, but I didn't used any functions from "Angular-Leaflet-Directive".
For those of you, who are interested what I did, I added a "Leaflet-Draw-Control-bar" with 3 buttons under the "Zoom-Control-Bar", like this: 

``` html
<leaflet id="map" markers="markers" center="center" layers="layers" paths="paths">
	<div class="leaflet-draw leaflet-control">
		<div class="leaflet-draw-section" style="position: relative; top: 80px; left: 10px;">
			<div class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top">
				<a href="" ng-click="changeBaselayer('default')"><i class="fa fa-map-o"></i></a>
				<a href="" ng-click="changeBaselayer('day')"><i class="fa fa-sun-o"></i></a>
				<a href="" ng-click="changeBaselayer('night')"><i class="fa fa-moon-o"></i></a>
			</div>
		</div>
	</div>
</leaflet>
```

As you can see I have 3 buttons and when one is clicked my own defined function `$scope.changeBaselayer` will be accessed and delete all baselayers and add only a day-baselayer or a night-baselayer or if it's `default` 3 baselayers from Mapbox.

Anyway, thank you @elesdoar for your helping :+1:  

Cheerio,
Nicho

**Comment by ivanssa** [comment]
I had the same problem after searching managed to find very few code snippet here and make my button that switches between the map layers and satellite with the following code

Function 

```
// Toggle Layer
$ Scope.layer = true;
$ Scope.change baselayer = function (key) {$ scope.layer = $ scope.layer!; leafletData.getMap () then (function (map) {leafletData.getLayers () then (function (layers) {_.each (layers.baselayers, function (layer) {map.removeLayer (layer);..}); map .addLayer (layers.baselayers [key]);});});
};

```

Html

```
<a ng-if="layer" ng-click="change BaseLayer('google Hybrid')" class="leaflet-control-layers-toggle radar" href="#" title="Layers"> </a>
<a ng-if="!layer" ng-click="changeBaseLayer('googleRoadmap')" class="leaflet-control-layers-toggle mapa" href="#" title="Layers"> </a>
```

Result: :-)

![result](https://cloud.githubusercontent.com/assets/3166174/12998515/411c9770-d123-11e5-80c5-416c59369615.jpg)
