### ISSUE TITLE
Toggling 'group' overlay visibility gives error

### ISSUE THREAD

**Issue by simison** [tombatossals/angular-leaflet-directive#926]
With version 0.8.8 I'm getting `TypeError: Cannot read property 'length' of undefined`

...from this line at compiled source: 
https://github.com/tombatossals/angular-leaflet-directive/blob/6a08769a6c926c0703d233e7c7b7ff5bf0a61568/dist/angular-leaflet-directive.js#L1592

...if I try to toggle visibility of an overlay:
```
overlays: {
  test: {
    name: 'test',
    type: 'group',
    visible: false
  }
}
```

...by doing:
```
$scope.$watch('center.zoom', function(newZoomValue) {
  vm.mapLayers.overlays.test.visible = newZoomValue >= 12;
});
```

Easy to re-produce by loading [0506-markers-groups-example.html](http://tombatossals.github.io/angular-leaflet-directive/examples/0506-markers-groups-example.html) with angular-leaflet 0.8.8. (Live example uses 0.8.6)

__I fixed this__ by changing layer type "group" to "featureGroup" but this was working before just fine and in any case that example should be updated.

Cheers! :-)

**Comment by elesdoar** [comment]
Sorry, it's my fault, I'll fix

**Comment by nmccready** [comment]
Thanks man
