### ISSUE TITLE
Question: Mapping of options to layers

### ISSUE THREAD

**Issue by sischnei** [tombatossals/angular-leaflet-directive#927]
I'm trying to map the following leaflet js code to the directive

    var basemapAT = L.tileLayer('http://maps{s}.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.{format}', {
            maxZoom: 19,
            attribution: 'Datenquelle: <a href="www.basemap.at">basemap.at</a>',
            subdomains: ["", "1", "2", "3", "4"],
            format: 'png',
            bounds: [[46.35877, 8.782379], [49.037872, 17.189532]]
        });
    basemapAT.addTo(map);

It works nicely with standard Leaflet and now I tried to map it to use the layers options but I can't seem to get it working correctly. I can get `attributions` to work by using `tileLayerOptions` in the `defaults` area and without any `layers` set, but then I can't have multiple layers. I didn't find any option on how to set subdomains like above. Can anybody point me in the right direction?

                layers: {
                    baselayers: {
                        basemap: {
                            name: 'Basemap',
                            type: 'xyz',
                            url: 'http://maps1.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png',
                            tileLayerOptions: {
                                attribution: 'Datenquelle: <a href="www.basemap.at">basemap.at</a>',
                            }
                        }

Works but doesn't use subdomains and the attribution is not shown at all...

**Comment by devourment77** [comment]
It looks like you can just use "layerOptions" instead of "tileLayerOptions" in this case (at least it worked for me on attribution).

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#107

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
