### ISSUE TITLE
minZoom and maxZoom not working for overlay layer

### ISSUE THREAD

**Issue by corymsmith** [tombatossals/angular-leaflet-directive#928]
I have a base layer and a bunch of overlays, each overlay has a min and max zoom but it doesn't appear to be working. Does this structure look correct?

```javascript
var overlay = {
  name: 'Elevation',
  url: base_url + tile_path,
  type: 'xyz',
  visible: false,
  layerOptions: {
    minZoom: 9,
    maxZoom: 18
  }
};
```

**Comment by florentplomb** [comment]
Hi,

Try with this : 
  layerParams: {
    minZoom: 9,
    maxZoom: 18
  }

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#108

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
