### ISSUE TITLE
Where is documentation, controls API?

### ISSUE THREAD

**Issue by vko-online** [tombatossals/angular-leaflet-directive#929]
I've been struggling with this repo for a long time, 0 docs
For now i want to add controls to map (this repo contains _fullscreen_, _minimap_, etc).
But how do we use it. The main problem is: Where do i look for controls, in leaflet repo or this repo? Also 0 demo about controls/custom-controls, indeed it's very important feature
And why API for this directive is so strange? `angular.extend($scope, {})` things look __very__ messy

**Comment by simison** [comment]
>`angular.extend($scope, {})` things look very messy
That's subjective: http://toddmotto.com/a-better-way-to-scope-angular-extend-no-more-vm-this/ ;-)

Although I got rid of it myself as well as I prefer `vm.` format.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#109

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
