### ISSUE TITLE
fit layer bounds

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [tombatossals/angular-leaflet-directive#932]
I'm trying to find a way to fit my map to a layer bounds. So basically what is the best strategy for this ?  
I know how to get bounds from a layer, ie `layer.getBounds()`, and how to fit map to bounds, ie `map.fitBounds()`; but if I know how to get the raw leaflet map with `leafletData.getMap().then()`, I have no clue how to retreive my raw leaflet layer (from name, maybe ? With an *angular-leaflet* helper ? With a raw `map.FUNCTION()` ?). Plus, isn't there a best (angularish) way to accomplish that ?

Same question for fitting multiple layers at the same time, I'd like to group my layers in a layergroup, and achieve the fitbounds on this layergroup.

Thanks =)

**Comment by nmccready** [comment]
```js
//getMap has one argument that is optional only if there is one map, it is required if there are multimaps

var _leafletMap = null;
var _leafletMarkers = null;
leafletData.getMap(maybeMapIDName).then(function(leafletMap){
//do whatever you want with the map
_leafletMap = leafletMap;
  leafletData.getMarkers(maybeMapIDName).then(function(leafletMarkers){
    //do whatever you want with the map
    _leafletMarkers = leafletMarkers;

     $scope.$watch('markers' , function (newVal, oldVal){
      // you already have or should have the leafletMap and Markers references
      //do your leaflet fit here
      // you have the markers which each object I think has the layer object in it. Otherwise convert it to LatLngBnds
// then us map like u stated above to fit
    });
```
});
});

**Comment by cyrilchaponeverysens** [comment]
Hey nmccready =)

Thanks for this answer. I'll give it a try.

But actually what if my layer is another type of layer ? (GeoJson, path)

**Comment by nmccready** [comment]
I'll have to get back to you.

**Comment by cyrilchaponeverysens** [comment]
I managed to accomplish that 

```
$q.all({
  map: leafletData.getMap(),
  layers: leafletData.getLayers()
}).then(function(mapItems) {
  var layerToFit = $scope.map.layers.overlays.things.name;
  var fitOptions = {
    padding: [50, 50]
  };
  mapItems.map.fitBounds(mapItems.layers.overlays[layerToFit.name].getBounds(), fitOptions);
});
```

**Comment by cyrilchaponeverysens** [comment]
Just need to find out how to fit multiple layers at the same time

**Comment by 9662** [comment]
> Just need to find out how to fit multiple layers at the same time

Use `getMarkers` instead of `getLayers`. E.g.:

``` javascript
leafletData.getMarkers().then(
    function (markers) {
        var bounds = null;
        function getBoundsRecursive(obj) {
            for (key in obj) {
                if (obj[key].getLatLng) {
                    if (bounds) {
                        bounds.extend(obj[key].getLatLng());
                    } else {
                        bounds = L.latLngBounds(obj[key].getLatLng(), obj[key].getLatLng());
                    }
                } else {
                    getBoundsRecursive(obj[key]);
                }
            }
        };
        getBoundsRecursive(markers);
        map.fitBounds(bounds, {padding: [ 50, 50 ]});
    }
)
```

The above code will fit the view to all loaded layers, visible or not. You can filter layers in the outermost `else` if need be.
