### ISSUE TITLE
GeoJSON mouse events throwing exceptions

### ISSUE THREAD

**Issue by ageblade** [tombatossals/angular-leaflet-directive#934]
Recently I bumped into some exceptions on console:

	Uncaught TypeError: Cannot read property 'mouseEventToContainerPoint' of null
		L.Path.L.Path.extend._fireMouseEvent @ leaflet-src.js:4746
		L.DomEvent.addListener.handler @ leaflet-src.js:6403

Trying to figure this out I have a theory:
The way geojson directive is implemented - it is cleaning and adding the data on every change made to the dataset (with a deep $watch).
If a change is made to the dataset in the course of an event (mouseover for example), the layer is removed and the leaflet path object is now map-less, so when it is time to execute the mouseout event, the map is not associated with the object and the exceptions occurs. To make it more confusing the object is still drawn on map because it is now added again by the $watch.

Any thoughts on how to fix this ?

**Comment by ageblade** [comment]
This is a leaflet issue, https://github.com/Leaflet/Leaflet/issues/3829 if anyone also has this.
Closing.

**Comment by nmccready** [comment]
Thanks for posting as I have seen this random error as well. Can u link the leaflet issue number to here?

**Comment by nmccready** [comment]
Edit nvm u already did :)
