### ISSUE TITLE
Using leafletData service inside another service, instead of inside controller

### ISSUE THREAD

**Issue by dpraimeyuu** [tombatossals/angular-leaflet-directive#935]
Hi,

I'm trying to use leafletData in a service to not pollute controller with a lot of code and keep it as thin as possible. I'm using simply leafletData.getMap() method and when I get map I try to add some markers on map depending on user's geolocation (I'm using map.locate() method).

Here problem appears - markers weren't properly added, locate() method didn't caused map to be zoomed to user position.

I am wondering what is the cause of such issue. When I'm doing all from above in controller, everything works smoothly. Do I need to keep everything in controller? I'd rather try to avoid that.

Thank you for help :-)

**Comment by nmccready** [comment]
No you should need one controller for scope binding but leafletData itself is a service. So you can get to leafletData from anywhere in the angular app domain. With regards to map.locate I am not sure and someone will need to dig in and investigate that. Can you make an example/plnkr?

**Comment by dpraimeyuu** [comment]
Problem solved. It was internal problem, so no worries :-)

Thanks for immediate response!
