### ISSUE TITLE
Attribution: How to disable "Leaflet" from showing up?

### ISSUE THREAD

**Issue by devourment77** [tombatossals/angular-leaflet-directive#939]
Here is the layers object I am using and the custom attribution is showing correctly, but it has a prefix "Leaflet" that I was not sure how to toggle?

```
$scope.map.layers = {
    baselayers: {
        mapbox_terrain: {
            name: 'Mapbox Terrain',
            url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
            type: 'xyz',
            layerOptions: {
                apikey: '...',
                mapid: 'mapbox.streets',
                attribution: '&copy; <a href="http://maponics.com" target="_blank">Maponics</a> &amp; <a href="" target="_blank">MapBox</a>'
            }
        }
    }
};
```

**Comment by simison** [comment]
I'm doing this by first setting `attributionControl: false` and then:

```javascript
    leafletData.getMap('map-canvas').then(function(map) {
      map.addControl(L.control.attribution({
        position: 'bottomright',
        prefix: ''
      }));
    });
```

...a bit cumbersome indeed.

A separate `attributionPrefix` option would suffice.

**Comment by seadour** [comment]
+1

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#110

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
