### ISSUE TITLE
Labels not coming back after markerclusterer hide() show()

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [tombatossals/angular-leaflet-directive#941]
When grouping **labelled** markers in a **markerclusterer** (this requires both [label](https://github.com/Leaflet/Leaflet.label) and [markerclusterer](https://github.com/Leaflet/Leaflet.markercluster) plugins), if one **hides** then **show** the holding `type: 'markerclusterer'` overlay layer (be with the layercontrol or programmatically with `visible` attribute), the label functionnality disapear.

This behavior is not observed when grouping markers with `type: 'group'`.

See [this fiddle](http://jsfiddle.net/4PhzC/422/). Reproduction :
- Hover the 2 markers, and notice the labels
- Go top right to the layercontrol, and uncheck then check both overlays layers
- Rehover the 2 markers, and notice only the label on the group reappears
- You can inspect code to notice that on hover the markerclustered marker, the label is not just "hidden", it's not added to the dom anymore

**Comment by kirimi** [comment]
+1
I also have same issue.

**Comment by thatgirlcancode** [comment]
+1

**Comment by nmccready** [comment]
I'll try and take a look when I get a chance. Looks to be valid.

**Comment by nmccready** [comment]
I you would like this resolved sooner.. please anyone dive in.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#111

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
