### ISSUE TITLE
Search Control not showing up

### ISSUE THREAD

**Issue by fabio-silva** [tombatossals/angular-leaflet-directive#948]
Hey there. I'm trying to implement the search control on the map, but it's not showing up.

My controller is like this: (after controller declaration)
       
        $scope.$on("$stateChangeSuccess", function() {

        $scope.locations = LocationsService.savedLocations;
        $scope.newLocation;

        if(!InstructionsService.instructions.newLocations.seen) {

          var instructionsPopup = $ionicPopup.alert({
            title: 'Add Locations',
            template: InstructionsService.instructions.newLocations.text
          });
          instructionsPopup.then(function(res) {
            InstructionsService.instructions.newLocations.seen = true;
            });

        }

        $scope.map = {
          defaults: {
            layers: {
              baselayers: {
                basemap: {
                  name: 'BaseMap',
                  url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                  type: 'xyz',
                  layerParams: {
                    showOnSelector: false
                  }
                }
              },
              overlays: {
                search: {
                  name: 'search',
                  type: 'group',
                  visible: true,
                  layerParams: {
                    showOnSelector: false
                  }
                }
              }
            },
            controls: {},
            maxZoom: 18,
            zoomControlPosition: 'bottomleft'
          },
          markers: {},
          center: {},
          events: {
            map: {
              enable: ['context'],
              logic: 'emit'
            }
          }
        };

        leafletData.getLayers().then(function(baselayers) {
          console.log(baselayers.overlays.search);
          $scope.map.defaults.controls = {
            search: {
              layer: baselayers.overlays.search
            }
          }
        });
        $scope.locate();

      });

I have no errors on the console. Also, the layers button is showing on the top right corner and flickering on hover, which is not supposed, following the example.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#112

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
