### ISSUE TITLE
CSS Flexbox With Leaflet Map

### ISSUE THREAD

**Issue by esetnik** [tombatossals/angular-leaflet-directive#950]
When using `display: flex` in conjunction with angular-leaflet-map I get issues with the tiles not loading. Even when scrolling around the map it seems like the plugin believes that the viewport is a different size.

Has anyone encountered this before?

<img width="644" alt="screen shot 2015-09-19 at 2 25 26 am" src="https://cloud.githubusercontent.com/assets/664434/9974913/d51d0336-5e75-11e5-80d2-2dc6b7a36c89.png">

**Comment by cgat** [comment]
This isn't an angular-leaflet-directive issue. I have the same problem. I've gotten around this by adding:

`leafletData.getMap().then(function (map) {
                map.invalidateSize();
            });`

in a $timeout (where the invalidateSize() call happens after your map has initially flexed to size)

**Comment by esetnik** [comment]
@cgat thanks that works!

**Comment by sdebionne** [comment]
I have the same problem as well. I run the $timeout from `run()`, but is it the right solution ?
```js
myApp.run(function($timeout, leafletData) {
    $timeout(function() {
      leafletData.getMap().then(function (map) { map.invalidateSize(); });
    });
```
Has this issue been reported to leaflet ? Shall we reopen https://github.com/Leaflet/Leaflet/issues/3072 ?

**Comment by nmccready** [comment]
@sdebionne good point I would report it.

**Comment by nmccready** [comment]
But a valid MCVE against raw leaflet is what they will want.

**Comment by adam-s** [comment]
@sdebionne The $timeout for the function call to `map.invalidateSize();` should be in the next tick after the promise is resolved. 

```
    .run(function($timeout, leafletData) {
        leafletData.getMap().then(function (map) {
            $timeout(function() {map.invalidateSize()});
        });
    });
```

**Comment by esetnik** [comment]
This isn't working for me. It seems that the timeout is occurring before the flex layout finishes. I can get it to work by increasing the timeout duration but obviously this isn't ideal because the layout duration is device dependent.
