### ISSUE TITLE
Close one popup and open another using focus

### ISSUE THREAD

**Issue by payros** [tombatossals/angular-leaflet-directive#951]
I have a collection of markers with focus false and one with focus true. I'm trying to close that popup setting all the markers to false, and open another one right after, by setting the focus to true:

    for(city in cities){
          cities[city].focus = false;
    }
    cities["New York"].focus = true;

Is that the right approach to this? Is this supported currently? (I'm using version 0.8.6)

Thanks :)

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#113

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Comment by 3ynm** [comment]
I'd like to know too, which is the proper way to programatically open/close popups?
