### ISSUE TITLE
Drag map through paths

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [tombatossals/angular-leaflet-directive#952]
In the [leaflet examples](http://leafletjs.com/examples/quick-start.html), if you **click & drag** a path, the map moves.

In the [angular-leaflet examples](http://tombatossals.github.io/angular-leaflet-directive/examples/0301-paths-types-example.html), this only works with `mutlipolygon` & `multipolyline` type.

I know I can disable pointer-events on my paths, setting clickable = false, but one really needs to move map through Polygons plus keeping the ability to have pointer events on it (including *label*, *popup*, *hover* features)

**Comment by vlavellauruit** [comment]
@cyrilchaponeverysens  facing the same issue... any idea about how can I achieve this?

**Comment by cgat** [comment]
I've been over the code a few times and can't figure this one out.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#114

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
