### ISSUE TITLE
ng-include inside path popup

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [tombatossals/angular-leaflet-directive#953]
When working with paths, the following doesn't work

```
var path = {
  [...],
  message: '<div ng-include src="views/partials/my-partial.html"/>',
  [...]
}
```

whereas same thing with markers does work.

Probably because [this clever kind of logic](https://github.com/tombatossals/angular-leaflet-directive/blob/b0dd8269c1c1e396c6cd594275a6c72db3a5971b/src/services/leafletMarkersHelpers.js#L145-L186) for markers is not applied when [binding path popup](https://github.com/tombatossals/angular-leaflet-directive/blob/b0dd8269c1c1e396c6cd594275a6c72db3a5971b/src/directives/paths.js#L88-L91)

**Comment by nmccready** [comment]
Care to PR the extra missing functionality?

**Comment by jessertaylor** [comment]
Seems like a copy and paste job to me, but would be better to make the whole thing a bit more generic so the code can be re-used for markers and paths.

**Comment by nmccready** [comment]
Agreed

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#115

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
