### ISSUE TITLE
Markers not correctly drawn after bounds update

### ISSUE THREAD

**Issue by michaelvaneck** [tombatossals/angular-leaflet-directive#955]
We are trying to dynamicly load the markers on the map. We do this everytime the bounds change and they are within zoom level 17.

But when dragging the map the markers get updated but not at the current bounds, it looks like it takes the previous bounds and not the new bounds.

    $scope.$watch('bounds', function (n, o)
         {
            console.log(n)
            if (n == o) return;
            $scope.newBounds = n;
            $scope.moved = true;
            redrawMap($scope.center.zoom);
        }, true);

    var redrawMap = function (zoom) {
            if (zoom >= 17) {
                if ($scope.markersDrawn == false || $scope.moved == true) {
                    drawBounds();
                    drawMarkers();
                    $scope.moved = false;
                }
            }
            else {
                if ($scope.markersDrawn == true) {
                    removeMarkers();
                }
            }
        }

$scope.newBounds is used to get the marker positions from the database.
this is done through a web call and retrieving a List of Markers

**Comment by nmccready** [comment]
Old issue that I haven't found the time to work on. I use the workaround exclusively as it is more performant anyways. #820
