### ISSUE TITLE
How to save map as an image?

### ISSUE THREAD

**Issue by Igor-Morozov** [tombatossals/angular-leaflet-directive#956]
Is there a way to save the map as an image? Or how can I use leaflet-image plugin https://github.com/mapbox/leaflet-image?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#116

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
