### ISSUE TITLE
Navionics - Overlay issue

### ISSUE THREAD

**Issue by dud3** [tombatossals/angular-leaflet-directive#958]
@tombatossals I'm trying to use the following service: http://webapiv2.navionics.com/examples/5000_LeafletSupport.html

Checking the examples, the overlays are added like the following:
```js
...    
            layers: {
                    overlays: {
                        wms: {
                            name: 'EEUU States (WMS)',
                            type: 'wms',
                            visible: true,
                            url: 'http://suite.opengeo.org/geoserver/usa/wms',
                            layerParams: {
                                layers: 'usa:states',
                                format: 'image/png',
                                transparent: true
                            }
                        }
                    }
            }
...
```

The example from the link above tells:
```js
var map = L.map('nautical-map-container');

var overlay=new JNC.Views.LeafletNavionicsOverlay({
    navKey: 'navionics_key',
    chartType: JNC.NAVIONICS_CHARTS.NAUTICAL,
    isTransparent: true,
    zIndex: 1
}));

overlay.addTo(map);
```

How would we add this overlay using `angular-leaflet` directive ?

Thanks.

**Comment by dud3** [comment]
cc: @nmccready

**Comment by dud3** [comment]
Anyone ?

**Comment by nmccready** [comment]
Sorry I don't have time to look at this until next week. I have family from out of town around. @elesdoar maybe?

**Comment by elesdoar** [comment]
Sorry, neither do I am so busy for this days, I could look at this until after next Wednesday. :cry:

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#117

**Comment by dud3** [comment]
I'm actually using leaflet without angular for this one, but it would be cool if we could through angular-leaflet as well.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
