### ISSUE TITLE
Removing control throws error - TypeError: map.hasControl is not a function

### ISSUE THREAD

**Issue by skray** [tombatossals/angular-leaflet-directive#962]
I ran into this trying to use the Leaflet.draw plugin and was able to recreate it in [this fiddle](http://jsfiddle.net/xkwgkyuL/) (click the 'Remove Controls' button to trigger the error).

If you have controls in your map and use the `controls` directive, like this:

```javascript
$scope.controls = { draw: {} };
``` 

and then remove the control from the controls object later, like this:

```javascript
$scope.controls = { };
```

This error is thrown:

![angular-leaflet-directive-error](https://cloud.githubusercontent.com/assets/3921751/10120964/bab5a15c-649b-11e5-8e63-915902129082.png)

It seems the culprit is [this line](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/controls.js#L29), where it tries to call `map.hasControl()`, but I cannot find the `hasControl` method defined in either the leaflet.js source or in this project.

If this is just me misunderstanding how to work with controls, I'd love to know what I'm doing wrong. If this is a bug, I'd be happy to try to put a pull request in to fix it.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#118

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
