### ISSUE TITLE
Tiles Not Loading on Mobie Device

### ISSUE THREAD

**Issue by mdridley** [tombatossals/angular-leaflet-directive#963]
Everything works fine until I try using this on a device, then I get everything but the map tiles and no error messages.

I tried whitelisting everything:
  $sceDelegateProvider.resourceUrlWhitelist([
      // Allow same origin resource loads.
      'self',
      'https://csi.gstatic.com/**',
      'http://a.tile.openstreetmap.org/**',
      'http://b.tile.openstreetmap.org/**',
      'http://c.tile.openstreetmap.org/**']);

And I added the iOS9 Transport security workaround.

No luck. Anything else that I might be missing?

Using iPhone 6, iOS9

**Comment by mdridley** [comment]
Had someone help me with the fix. Appears that if you specify the tiles source directly, the tiles will load correctly.

  angular.extend($scope, {
    center: {
      autoDiscover: true,
      zoom: 12
    },
    tiles: {
      url: "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    }
  });

**Comment by ManuelRauber** [comment]
You need to use a https:// endpoint for loading the tiles. You can try https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png for tiles.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#119

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
