### ISSUE TITLE
maintain map through routing

### ISSUE THREAD

**Issue by cscrum** [tombatossals/angular-leaflet-directive#964]
I've got a fairly complex application which uses routing to bring up differentt aspects of the application. Some of these other pieces can add data layers to a map, but a large part of the application is the map itself. The problem I'm having is maintaining the map after routing to a new module. I can certainly store the map center, zoom, layers, etc into a service, and then "redraw" everything when I route back to the map, but what I'd really like to do is keep the map throughout all the scopes. Since routing away from the view which has the map html on it effectively destroys the map, I can see no other way than to redraw it each time. The difficulty is that I can have dozens of layers, some with 100s of objects that I really don't want to have to redraw every time I switch back to the map. Can anyone provide some advice on how to accomplish something like this?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#120

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
