### ISSUE TITLE
fix specs on leaflet-1.X

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#966]
Specs are broken.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#122

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
