### ISSUE TITLE
fix examples to point to leaflet 1.0.0-beta ..

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#967]
So the old path

`<script src="../bower_components/leaflet/dist/leaflet.js"></script>` is now at

`<script src="../bower_components/leaflet/leaflet.js"></script>`

as well as the css.

`<link rel="stylesheet" href="../bower_components/leaflet/dist/leaflet.css" />`

`<link rel="stylesheet" href="../bower_components/leaflet/leaflet.css" />`

This might be reverted to dist depending on what leaflet does about the bower situation. See #851

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#123

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
