### ISSUE TITLE
possible require.js issue

### ISSUE THREAD

**Issue by cscrum** [tombatossals/angular-leaflet-directive#968]
I'm using require.js with my project. This is an intermittent problem, but occasionally I get the following error from Bing.js

Uncaught ReferenceError: L is not defined

when I first load my page. 
I've tried loading the library without using the dependencies, but it still happens. It happens about 40-50% of the time.

**Comment by nmccready** [comment]
see #965

**Comment by cscrum** [comment]
Yes I posted that one too, but that was a logger error. This was happening with Bing even before I started using the new version with logger.
