### ISSUE TITLE
How to build a map with the array of values using leaflet directive

### ISSUE THREAD

**Issue by balajijana** [tombatossals/angular-leaflet-directive#972]
Hi,

 I am a new beginner in learning the leaflet directive.I have latitude and longitude in an array for 4 locations. For each location i need to display a map with by passing the latitude and longitude. Below is my code:
```
angular.forEach($scope.activities, function (activities, index) {          
            if (activities._id) {
              actId.push(activities._id);
              latid = activities['attributes'].loc[0][0];
              longid = activities['attributes'].loc[0][1];
              txt = activities.text;
               // console.log(latid); 
                //console.log(longid);
               // console.log(txt);
               $scope.osloCenter = {
                  lat: latid,
                  lng: longid,
                  zoom: 22
                };
                $scope.markers = {
                  osloMarker: {
                    lat: latid,
                    lng: longid,
                    message: txt,
                    focus: true,
                    draggable: false
                  }
                };
            }           
          });
```
When i print the value in the console i am able to get the array values for 4 locations as an array. I need to know how to pass the array values to iterate it to display the map for each location. Also I am getting the following error: 

[AngularJS - Leaflet] The marker definition is not valid.
angular.js:11655 [AngularJS - Leaflet]  [AngularJS - Leaflet]  Received invalid data on the marker osloMarker.

Please help me out what is this error and how to rectify it or any other alternative solutions

**Comment by chidg** [comment]
Check that your `lat` and `lng` values passed to the marker are floats.

**Comment by nmccready** [comment]
#881

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#124

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
