### ISSUE TITLE
Overlay group visible bug.

### ISSUE THREAD

**Issue by kozer** [tombatossals/angular-leaflet-directive#973]
In version 0.8.7 everything was ok. But in 0.8.8 when i do visible = false, the inner layers, dont remove from map.

**Comment by nmccready** [comment]
@elesdoar , just pinging you as I know you have been in this area recently.

**Comment by elesdoar** [comment]
yeah, this was fixed at #926, but I think that 0.8.8 release contains this bug.

**Comment by elesdoar** [comment]
Duplicate #926

**Comment by nmccready** [comment]
@elesdoar thanks, @kozer  we are still in process of working on the next release
