### ISSUE TITLE
(grunt) getAvailPort is not cross-platform

### ISSUE THREAD

**Issue by jtroe** [tombatossals/angular-leaflet-directive#977]
https://github.com/tombatossals/angular-leaflet-directive/blob/master/grunt/utils/getAvailPort.js#L4 does not execute on Windows

```
'lsof' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by nmccready** [comment]
I suggest making a PR to make it compatible; I don't have time to 'fix' this. If you don't want to PR then I suggest a virtual machine or run inside of cygwin.
