### ISSUE TITLE
Events on overlay GeoJson

### ISSUE THREAD

**Issue by florentplomb** [tombatossals/angular-leaflet-directive#978]
Hello!
I try to listen events on overlays GeoJson. I used this exemple : https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0231-layers-overlay-geojson-example.html . But now I don't know how can I do for to listen a event (like click) on the GeoJson overlay? 

BR

**Comment by BAByrne** [comment]
I think you're looking for this:
https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0601-mixed-geojson-events-example-w-id.html

If you create a plunkr and describe what you're trying to do, we might be able to better solve the problem.

**Comment by yukk1** [comment]
By adding onEachFeature to layerOptions,

```javasscript
$http.get("countries.geo.json").success(function(data, status) {
        angular.extend($scope.layers.overlays, {
          countries: {
            name:'World Country Boundaries',
            type: 'geoJSONShape',
            data: data,
            visible: true,
            layerOptions: {
              style: {
                color: '#00D',
                fillColor: 'red',
                weight: 2.0,
                opacity: 0.6,
                fillOpacity: 0.2
              },
              onEachFeature: onEachFeature
            }

          }
        });

        function onEachFeature(feature, layer) {
          layer.on({
            click: function() {
              console.log(layer.feature.properties.name);
              $scope.country = layer.feature.properties.name;

            }
          })
        }
      });
```
This makes the country layers listen to click event.

[This is my plunker.] (http://embed.plnkr.co/M1y2yF5dT624umBGU0Wi/preview)

If you want to add more event listeners, [leaflet choropleth tutorial will help you](http://leafletjs.com/examples/choropleth.html).

**Comment by florentplomb** [comment]
Thanks for all the info @BAByrne , @yukk1 . It works perfectly
