### ISSUE TITLE
Using plugins and race-conditions (?)

### ISSUE THREAD

**Issue by kwisatz** [tombatossals/angular-leaflet-directive#981]
We're using this directive together with the [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine)  (LRM) which is not a directive, but a leaflet plugin, and it appears that we sometimes see race conditions on this.

When doing something like this:

```javascript
leafletData.getMap().then(function(map) {
    // Sometimes, L.Routing is not defined, sometimes even L is not defined
    self.routingControl = L.Routing.control({
        waypoints: self.waypoints
    }).addTo(map);
});
```

Then at times, we're getting errors saying that L.Routing is not defined (but L is), and sometimes even L is not defined.

I'm wondering whether the LRM plugins isn't perhaps trying to initialize before L is available and thus cannot extend it by adding the Routing object to it? (The plugin's code is evaluated, it runs, while the directive's code is only run when angular initializes the directives. By the time the angular app runs, all the code would have been initialized, but at the very beginning, the plugin had been enable to extend L.) But maybe I'm not yet understanding correctly how and when code is being executed.

A useful info in this context might be that we're bower for both the directive and the plugin, and then concatenating all our JS (vendor and app) to a single file, with the leaflet directive and plugins being loaded right after angular and the logger.

I was wondering whether anyone has had a similar experience?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#127

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
