### ISSUE TITLE
Google maps layer, language and key

### ISSUE THREAD

**Issue by pkarop** [tombatossals/angular-leaflet-directive#982]
Are there any params for Google maps layer, so I can set language and api key through Javascript?
I am trying something like this

                layers: {
                    baselayers: {
                        googleRoadmap: {
                            name: 'Google Streets',
                            layerType: 'ROADMAP',
                            type: 'google',
                            layerParams: {
                                key: key,
                                language: $scope.language
                            }                            
                        }
                     }                    
                }

**Comment by nmccready** [comment]
I dont think there is yet; but copying this service angular-google-maps would work.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#128

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
