### ISSUE TITLE
[Broken Demo?] GeoJSON Shape Layer and GeoJSON Awesome Marker Layer

### ISSUE THREAD

**Issue by that1guy** [tombatossals/angular-leaflet-directive#983]
http://tombatossals.github.io/angular-leaflet-directive/examples/0231-layers-overlay-geojson-example.html

I'm not seeing any heart markers or shape overlays in this example.  Trying to mimic what this example is trying to demonstrate.  Thanks for help.

**Comment by nmccready** [comment]
There have been a bunch of changes to layers recently and this example probably got broken. I or you can look at the recent pull requests accepted and we can try to fix this.

**Comment by nmccready** [comment]
Actually I just looked at this and the example is working fine. The visibility of the stuff is just off by default.

**Comment by nmccready** [comment]
![screen shot 2015-10-07 at 9 39 25 pm](https://cloud.githubusercontent.com/assets/583593/10355588/ebe6e166-6d3b-11e5-8776-360426742924.png)


![screen shot 2015-10-07 at 9 39 33 pm](https://cloud.githubusercontent.com/assets/583593/10355589/ee0c850e-6d3b-11e5-8a08-14703410158b.png)

**Comment by nmccready** [comment]
See here as I changed it to on `visible:true` in this PR.

https://github.com/tombatossals/angular-leaflet-directive/pull/984/files#diff-27ad7e2c9b26ede30e6b91a2e8fb9f4fR44

**Comment by that1guy** [comment]
@nmccready thanks man.
