### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by chughk1** [tombatossals/angular-leaflet-directive#985]
Are there any plans to convert angular-leaflet directive in typescript?

**Comment by nmccready** [comment]
For version 3 yes, but for 2.X no. Currently I have no time for version 3.

**Comment by nmccready** [comment]
Sorry I was responding w/ regards to angular-google-maps. Actually I don't know what is in-store for this library for languages. If it is going to go the angular2 route then I supposed it should. Personally I find more value in moving to babel and es6. Anyway I doubt this would happen until a version 2 of this library. As currently we are looking at version 1.X to be compat with leaflet 1.

**Comment by nmccready** [comment]
@tombatossals @elesdoar @simison @jessertaylor thoughts?

**Comment by simison** [comment]
Right now it seems that would cut down some potential contributors more than typescript would bring people in. A2 might change this, but that didn't happen yet and might even not happen at all.

Babel+ES6 on the other hand seems to be cutting a lot of reasons why to write in typescript/coffeescript/whatnot.

This is some good food for thought as well: https://github.com/SINTEF-9012/PruneCluster/issues/79

**Comment by nmccready** [comment]
I personally am not on the Angular 2 bandwagon yet as it is too beta and such a break from original angular. So I am hesitant to adopt typescript. 

This will probably not be a popular thought (and please lets discuss this as adults).:

I know people love their type checking but I think this is spawned from people used to a type checking world like java. The big issue I have with the types is the interfaces which lead to design restrictions and overly complicated code on checking types when at times a truthy and duck typing is plenty sufficient. From what I have seen on typescript thought is you can type check and use ducktyping as well. But my biggest problem with it is that it is not fully ES6 yet.

**Comment by simison** [comment]
Would be interesting to see examples of libs that moved to typescript and their reasoning/discussion behind the move.

**Comment by elesdoar** [comment]
For now I do not think we should change to typescript, we must focus in next version for Leaflet 1.x and after think about to give support for angular 2 and about how do it.

**Comment by nmccready** [comment]
agree with @elesdoar

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#129

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
