### ISSUE TITLE
"Defaults" keys

### ISSUE THREAD

**Issue by markovaljaots** [tombatossals/angular-leaflet-directive#986]
I want to use https://github.com/yohanboniface/Leaflet.Editable together with angular-leaflet-directive, but in order to do so it is necessary to create a map with following options: 
```javascript
angular.extend($scope, {defaults: {editable: true}});
```

Unfortunately all the "defaults" keys are hardcoded in angular-leaflet-directive.js and therefore "editable: true" is skipped. I managed to enable "editable" key by modifying angular-leflet-directive.js and making these adjustments:
```javascript
getMapCreationDefaults: function(scopeId) {

  ...

  if(isDefined(d.editable)) {
    mapDefaults.editable = d.editable;
  }

  ...

},

setDefaults: function(userDefaults, scopeId) {
  var newDefaults = _getDefaults();

  if (isDefined(userDefaults)) {

    ...

    if(isDefined(userDefaults.editable)) {
      newDefaults.editable = userDefaults.editable;
    }

  }

  ...

}

```

Now Leaflet.Editable works, but this solution is quite hacky. Are there any alternative ways to achieve this?

**Comment by skray** [comment]
I also was trying to use Leaflet.Editable, and ran into this same problem. Looking at [this line](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/services/leafletMapDefaults.js#L92) in LeafletMapDefaults, it looks like you can assign any non-standard default to the `map` field of the `defaults` object, and they will get carried over. So for your example @markovaljaots, I did this instead and it worked for me:

```
angular.extend($scope, { defaults: { map: { editable: true} } });
```

I'm not sure if this is the correct use of `defaults.map`, but it seems to do the trick.

**Comment by nmccready** [comment]
With leafletMapDefaults factory why doesn't someone PR changes to setDefaults to make them less restrictive.  IE remove all the isDefined and default checks and just merge / extend all the properties via `angular.extend({}. newDefaults, userDefaults)`

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#130

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
