### ISSUE TITLE
map loading incorrectly when not in dom

### ISSUE THREAD

**Issue by cscrum** [tombatossals/angular-leaflet-directive#988]
I've updated to the latest version of this directive, but still have issues with correct map loading when the map is not in the dom. Has this been resolved? Do I need to upgrade leaflet to the 1.0 beta? The map seems to be centered off the div which contains the map and many of my layers don't load. The map seems to recenter if I resize the screen, but the layers never load. Any suggestions?

**Comment by cscrum** [comment]
Also still can't get map to resize if it not in the main body even if it completely loads in the dom.

**Comment by nmccready** [comment]
Please make an example.

**Comment by nmccready** [comment]
Closing until that is done.
