### ISSUE TITLE
Publish 0.9.0 to npm

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#989]

**Comment by nmccready** [comment]
ping @tombatossals

**Comment by tombatossals** [comment]
Aggh, sorry for the delay @nmccready.

Just published, version 0.9.0:

https://www.npmjs.com/package/angular-leaflet-directive

**Comment by nmccready** [comment]
@tombatossals anyway I can be added to publishers so I can push to npm? Then I won't have to worry about pinging you.

**Comment by nmccready** [comment]
@tombatossals can you sign into slack when you get the chance?
