### ISSUE TITLE
Fix travis leaflet dependency for 1.0.0 leaflet

### ISSUE THREAD

**Issue by nmccready** [tombatossals/angular-leaflet-directive#991]
https://travis-ci.org/realtymaps/realtymaps/angular-leaflet-directive/builds/82999172

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#131

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
