### ISSUE TITLE
Tiles broken when using the option param

### ISSUE THREAD

**Issue by Onefox** [tombatossals/angular-leaflet-directive#992]
When i am using my own handled map container the tiles are where they should be, but when iam using the option param than the tiles are broken.

This is my working code in the controller (than i get only the error because the directive tries to put another map in there)
```javascript
var map = L.map('map').setView([0, 0], 2);
		L.tileLayer('altis2/{z}/{x}/{y}.png', {
			minZoom: 1,
			maxZoom: 7,
			attribution: 'ESO/INAF-VST/OmegaCAM',
			tms: true,
			noWrap: true
		}).addTo(map);
```

And this is the code with using the option param that is not working right.
```javascript
$scope.defaults ={
			tileLayer: 'altis2/{z}/{x}/{y}.png',
			minZoom: 0,
			maxZoom: 7,
			tms: true,
			noWrap: true
		};
		$scope.center = {
			lat: 0,
			lng: 0,
			zoom: 2
		};
```
Both are with
`<leaflet id="map" tiles="tiles" defaults="defaults" center="center" ></leaflet>`

And here are the screenshots of the broken parts:
http://imgur.com/a/DSlZo

So there must be a difference how the L.titleLayer is working and how the tileLayer option is working.
Cheers,

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#132

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
