### ISSUE TITLE
two seperate marker lists

### ISSUE THREAD

**Issue by michaelvaneck** [tombatossals/angular-leaflet-directive#995]
Hey! Is there any way to have 2 marker lists at the same time?

I'm running $scope.markers for my points but I need to add a seperate list of markers that are in NO way connected to the $scope.markers list.

**Comment by nmccready** [comment]
Yes use markers-nested attribute. Please see examples. Also be aware there is an existing race condition so it is recommended to disable watching via watchOptions and use directiveControls to update the markers. All of this exists in the examples directory [here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0605-mixed-overlays-markers-nested-no-watch-example.html).
