### ISSUE TITLE
Applying Mapbox CartoCSS styles to overlays

### ISSUE THREAD

**Issue by that1guy** [tombatossals/angular-leaflet-directive#996]
I have a custom build cartoCSS style that I've synced to my mapboxId in their cloud.

When I overlay polygons on my map, how do I make sure that style get's applied to that layer?

![mapbox](https://cloud.githubusercontent.com/assets/1218940/10525552/3511bc54-733a-11e5-9ae1-a36baffe8931.png)

![app](https://cloud.githubusercontent.com/assets/1218940/10525554/380ec9b0-733a-11e5-9276-0e5d8ca7db3c.png)

**Comment by nmccready** [comment]
So I actually use this myself. I do all my styling via cartodb api. So the styling is not being done by leaflet at all.

http://docs.cartodb.com/cartodb-platform/import-api.html

I use this btw to upload the data as well.

https://github.com/realtymaps/cartodb-api

Here is an example json style I upload to the import api .

```
{
  "version": "0.0.1",
  "name": "parcels",
  "auth": {
    "method": "open"
  },
  "layergroup": {
    "layers": [{
          "type": "cartodb",
          "options": {
            "cartocss_version": "2.1.1",
            "cartocss": "#layer {
              polygon-fill: transparent;
              polygon-opacity: 0.7;
              line-color: #1269D8;
              line-width: 1.5;
              line-opacity: 1;
            }",
        "sql": "select * from parcels"
      }
    }]
  }
}
```

Example:

Anonymous Map template: (see cartodb [MAP API](http://docs.cartodb.com/cartodb-platform/maps-api.html))

Example below all deals with the parcels template.

* CREATE
```
curl -X POST 'https://YOURNAME.cartodb.com/api/v1/map/named?api_key=SOME_KEY' -H 'Content-Type: application/json' -d @parcels.json
```

* GET
```
curl -X POST 'https://YOURNAME.cartodb.com/api/v1/map/named/parcels?api_key=SOME_KEY' -H 'Content-Type: application/json'
```

* UPDATE
```
curl -X PUT 'https://YOURNAME.cartodb.com/api/v1/map/named/parcels?api_key=SOME_KEY' -H 'Content-Type: application/json' -d @parcels.json
```

* DELETE
```
 'https://YOURNAME.cartodb.com/api/v1/map/named/parcels?api_key=SOME_KEY' -H 'Content-Type: application/json'
```


The curl commands are there for you to play with it manually to understand the API. But the node library above takes care of all this for you. Anyway when its done up loading you can verify the URL of where your tile is located.



Now this last part is where everything gets tied together.

On your backend config you use your ENV_VARS via process to fill out this code:

```coffee
CARTODB: do ->
    ret = _getAllConfigs('CARTODB', ['API_KEY', {name:'MAPS', isJson: true}, 'ACCOUNT', 'API_KEY_TO_US', 'TEMPLATE'])
    root = "//#{ret.ACCOUNT}.cartodb.com/api/v1"
    apiUrl = "api_key=#{ret.API_KEY}"

    _.extend ret,
      ROOT_URL: root
      API_URL: apiUrl
      TILE_URL: "#{root}/map/{mapid}/{z}/{x}/{y}.png?#{apiUrl}"
      WAKE_URLS: ret.MAPS.map (m) -> "#{root}/map/named/#{m.name}?#{apiUrl}"

```

Frontend CartoDb maps layer
```coffee
_cartodb.MAPS.forEach (map) ->
      _overlays[map.name] =
        visible: false
        name: map.name
        url: _cartodb.TILE_URL
        type: 'xyz'
        layerOptions:
          apikey: _cartodb.API_KEY
          account: _cartodb.ACCOUNT
          mapid: map.mapId
          attribution: ''
          maxZoom: 21
```

The wake URL above is something to hit somewhere as the CARTODB server will go to sleep. So you can poll it on heroku or whatever and ping it when the client fires up (client side). 

Now this being said is making it work without the official way using the cartodb.js client side app. But it does work well and it puts most if not all the brunt of the work on the backend.

**Comment by nmccready** [comment]
Sorry if this is out of context; but this is just my solution to using cartodb in angular-leaflet-directive . I am totally open to a better way.

**Comment by nmccready** [comment]
Also be aware every-time you update your template the root tile url will change.

**Comment by elesdoar** [comment]
Waooo @nmccready you works with cartodb api, great, I did the QGIS plugin, jejejeje

https://github.com/gkudos/qgis-cartodb

PD: Free ads.. :joy:

**Comment by that1guy** [comment]
Thanks for all the info @nmccready.  I'm still slightly confused though..  :P 

Setting aside the cartodb-api, I've believe I've already created and saved my cartoCSS style to my mapID.

Here's my cartoCSS style
````
#areas {
  line-color: black;
}
````

Here's my map defaults.
````
  factory.map = {
    defaults: {
      controls: {
        layers: {
          visible: false
        }
      }
    },
    center: {
      lat: 37.773972,
      lng: -122.431297,
      zoom: 12
    },
    markers: {},
    markerEvents: {
      enable: leafletEvents.getAvailableMarkerEvents()
    },
    layers: {
      baselayers: {
        mapbox_light: {
          name: 'Mapbox Light',
          url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
          type: 'xyz',
          layerOptions: {
            apikey: ENV.mapbox.apikey,
            mapid: ENV.mapbox.mapid
          }
        }
      },
      overlays: {
        clusterLayer: {
          name: "clusterLayer",
          type: "markercluster",
          visible: true,
          layerOptions: {
            showCoverageOnHover: false,
            maxClusterRadius: 55
          }
        }
      }
    }
  };
````

Then later on I do an AJAX request to my own server to fetch some geoJSON.
````
var getNeighborhoodBoundaries = function () {

    elasticsearch.client.search({
      q: 'properties.boundary.level:1 AND properties.mlsName:sfar',
      size: 300,
      type: 'area'
    }).then(function (body) {

      angular.extend(factory.map.layers.overlays, {
        areas:{
          name: 'areas',
          type: 'geoJSONShape',
          data: {
            "features":body.results,
            "type":"FeatureCollection"
          }
        }
      });
    }, function (error) {
      console.log(error);
    });
  };
  getNeighborhoodBoundaries();
````

How do I get that areas overlay to assume my #areas cartoCSS style?

**Comment by nmccready** [comment]
neat. BTW if anyone wants to make PR's to cartodb-api update docs .. etc that would be welcomed.

**Comment by nmccready** [comment]
So the cartodb-api's purpose is so you do not have to login into an application and make styles. Using the api I can push the geojson to our cartodb account at will and then push the template to style it several different ways. This can all be done on the backend without me needing to do anything to my leaflet app except add tile layers.

**Comment by that1guy** [comment]
We don't mind logging into the app to make some styles, and we have really settled into using our elasicsearch clusters to store our geoJSON.  Is there a way we can just add a new overlay to the map and tell that overlay to use that cartoCSS style?

Thanks again for all the info, just trying to find a quick solution if there is one.

**Comment by nmccready** [comment]
My interpretation of the purpose of cartodb is to not use clientside objects, IE your querying for geosjon objects an then forcing leaflet to iterate and render them all individually. What I suggested is to use the power of vector tiles and upload your data on a regular basis to carotdb or a cartodb implementation tile server. That way your layers load **BLAZZING FAST**, now if you do this you do lose client interaction like hovers.. and etc. So basically you pic and choose your battles on what you need. But if it is large tile data I suggest the backend way. Then when you want client interaction like when you zoom in, then use the geojson and iterate through way less data.

**Comment by nmccready** [comment]
Anyway back to your problem of the style not applying locally on client side data. I actually have not used the geoJSONShape plugin yet. I am using the [geojson](https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/geojson.js) attribute instead. The example for styling that can be found [here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0125-basic-geojson-nested-example.html).

**Comment by that1guy** [comment]
Okay, so we need to style within JS then to pull off quick and easy solution.. got it.  We were just curious if it was possible to apply the cartoCSS style in the cloud.  Sounds like these cartoCSS styles are used during vector tile generation only, which makes sense.

Thanks for confirmation.

**Comment by nmccready** [comment]
@that1guy yeah that was going to be my next question it seems your not using cartoCss at all here. So if your zoomed out far (LARGE DATA)  I suggest using the tile server.

**Comment by nmccready** [comment]
Anyways that was fun to talk about as I like cartodb :)

**Comment by that1guy** [comment]
Haha.. The convo was informative.. it's just tough to think about moving our geoJSON over to a cartodb implementation because that very same geoJSON data is also heavily used to conduct geospatial queries (i.e. return only the data that falls within this boundary).. that's no fun combining elasticsearch with SQL-like cartodb stuff.

**Comment by nmccready** [comment]
Yes I hear you we have the same problem. But cartodb is very very open source and you can host your own tile server with their tech. So if you want to cut out the cartodb-api convience of their server. Then you can stand up one of their servers and target your own in house data / db. But who knows how long that will take to steam roll.

**Comment by nmccready** [comment]
Thats why it costs money :) .

**Comment by nmccready** [comment]
Here is the server I think ; https://github.com/CartoDB/Windshaft-cartodb and

https://github.com/CartoDB/Windshaft

**Comment by that1guy** [comment]
Nice! Thanks @nmccready.  Cheers!
