### ISSUE TITLE
'The "center" property is not defined in the main scope'

### ISSUE THREAD

**Issue by toutpt** [tombatossals/angular-leaflet-directive#999]
I dont find a way to create a directive that embed leaflet directive.

I have created a plunker to isolate the problem:
http://plnkr.co/edit/zgnzG3fqHxJ13DoiNGy8?p=preview

console shows many errors:
* [AngularJS - Leaflet]  The "center" property is not defined in the main scope(anonymous function)
* [AngularJS - Leaflet] The 'tiles' definition doesn't have the 'url' property.

This seems different from #362

**Comment by yukk1** [comment]
Thank for forking my plunk.

I have updated [my plunk](http://plnkr.co/edit/fRylaHFllSR9HrTf2UCV?p=preview).
Please check it.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#135

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
